### PR TITLE
AKS - show subnets in virtual network dropdown

### LINKED ISSUE #10431: AKS: Virtual network field not showing Subnets to provision the cluster
**Setup**
Rancher version: `v2.9-4479597c19bb4f7a74c304aa621932d213a05532-head`
Browser type & version: Chrome latest

**Describe the bug**
AKS (Vue UI): Unable to provision cluster with Network policy & Network plugin as Azure CNI
The virtual network drop-down does not lists Subnet, on old UI it does as below:

image

**To Reproduce**
- Create downstream AKS cluster and select Network policy & Network plugin as Azure, under Networking
- Select existing vNet under Virtual network
- Fill all other necessary fields and create cluster

**Screenshots**
image

image

### PR DESCRIPTION
**Pull request by mantis-toboggan-md**
### Summary
Fixes #10431 

### Occurred changes and/or fixed issues
This PR updates the virtual networks dropdown to display subnets, grouped by network, and set the config.subnet field when one is selected (in addition to setting `config.virtualNetwork` and `config.virtualNetworkResourceGroup`, which it already does)

### Areas or cases that should be tested
1. selecting one of the subnet options should set virtualNetwork, virtualNetworkResourceGroup, and subnet
2. selecting a subnet then selecting again the default 'none' option and saving should not return errors

### Screenshot/Video
Screenshot 2024-05-21 at 9 56 24 AM

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: pkg/aks/components/CruAks.vue [hunk 1]
```diff
@@ -596,6 +596,60 @@ export default defineComponent({
...
 
+    // in the labeledselect, networks will be shown as 'groups' with their subnets as selectable options
+    // it is possible for a virtual network to have no subnets defined - they will be excluded from this list
+    virtualNetworkOptions() {
+      const out: {label: string, kind?: string, disabled?: boolean, value?: string, virtualNetwork?: any, key?: string}[] = [{ label: this.t('generic.none') }];
+
+      if (this.loadingVirtualNetworks) {
+        return out;
+      }
+      (this.allVirtualNetworks || []).forEach((network) => {
```
Comment (momesgin) [inline pkg/aks/components/CruAks.vue:607]: You probably don't need the fallback since you have a default value in the data block.

Comment (mantis-toboggan-md) [reply pkg/aks/components/CruAks.vue]: You're right: it's always defined. I've removed this fallback.

**Review by momesgin — APPROVED** [review]
Tested and worked as expected, lgtm
