### PR TITLE
Azuread custom endpoint radio option

### LINKED ISSUE #6428: Azure AD Edit Config always picks Standard endpoint in radio button
**Setup**
- Rancher version: v2.6-head near v2.6.7 release
- Browser type & version: Firefox 102

**Describe the bug**
This is relevant for existing setups of Azure AD. The Edit Config screen always selects the Standard endpoint as a value in the radio button, even if the set up has China as the endpoint, or Custom.

**To Reproduce**
This does not happen immediately after registering Azure AD - if you register and then navigate to the Edit Config screen, then everything works correctly, China is selected, if I had registered with a China endpoint and credentials.

But if I navigate away and come back, the issue appears.
1. Register Azure AD with a China endpoint.
2. Go to the local cluster, then back to the Edit Config screen in Auth Providers.

**Result**
The radio button selects the Standard value by default

**Expected Result**
The radio button should select China as the endpoint, since this is how I had configured Azure AD initially.

**Screenshots**

**Additional context**

**Detailed Description**
The same will happen with Custom endpoint configurations. I wonder if the UI could figure out which value to select by querying the auth config and inspecting the value of Graph Endpoint. We know which Standard and China endpoints are valid. If it's none of those, then assume it's Custom.

**Context**
This is not urgent for the v2.6.7 Azure AD changes, just a UI enhancement.

### PR DESCRIPTION
**Pull request by jordojordo**
### Summary
Fixes #6428 

### Occurred changes and/or fixed issues

This issue would arise regardless of upgrading prior to `v2.6.5` as we were checking _only_ for the `graphEndpoint`, not for the other endpoints.
Added a method to determine if the values for all of the endpoints match the values in the hard coded map. If they don't match, `custom` will be the type.

### Areas or cases that should be tested

- Steps to test are in the related issue
- A test environment can be given if needed

### CODE REVIEW

File: shell/edit/auth/azuread.vue [hunk 1]
```diff
@@ -190,6 +190,23 @@ export default {
...
+
+        if ( mappedValues === valuesToCheck ) {
+          out = key;
+        } else {
+          out = 'custom';
+        }
+      }
+
+      return out;
+    },
```
Comment (mantis-toboggan-md) [inline shell/edit/auth/azuread.vue:208]: Arrays can't be properly compared using `===` try lodash:
```
import isEqual from 'lodash/isEqual'

...

if(isEqual(mappedValues, valuesToCheck))

...

```

I think you also need to change where in this process you're setting `out = 'custom' `. As it is now, this loop is setting `out = 'custom'` for each region (standard, china, custom) that doesn't correspond to the current config. That is, if the first region checked is the one we want, out is gonna be re-set to 'custom' when the next region is iterated over. Try using 'custom' as the initial value for `out` rather than setting it within the loop.

This is, admittedly, nitpicky, but I find this loop hard to read: I think some more specific variable names would be helpful here.

**Review by mantis-toboggan-md — CHANGES_REQUESTED** [review]

File: shell/edit/auth/azuread.vue (hunk 1 above)
Comment (jordojordo) [reply shell/edit/auth/azuread.vue]: Great points, makes a lot of sense to set `out` as `custom` initially. Also changed the equality checking to use lodash and renamed a few of the variables.

Comment (mantis-toboggan-md) [reply shell/edit/auth/azuread.vue]: It's easier for me to read now, thank you :)

**Review by mantis-toboggan-md — APPROVED** [review]
LGTM

**Comment by nwmac** [comment]
Force merging as drone is stuck
