### PR TITLE
fix misc issues with codemirror and a11y

### LINKED ISSUE #13528: Fix misc issues with YAML editor
**Setup**
- Rancher version: `master`
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**

Fix a couple of issues with the `YAML editor` component:
**1:**
- Editor shouldn't allow focus while in `VIEW` mode

Image

**2:**
- `YAML editor` component doesn't take into account padding on the bottom to include the `press escape to blur` message

Image

**To Reproduce**

**1:**
go to any resource list view and select as a table row action, `view YAML`

**2:**
go to Fleet git repo - create - select `Git Authentication` as `create an SSH key secret` then click on `known hosts`, which should open a modal

**Result**

**Expected Result**

All issues fixed

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by aalves08**
### Summary
Fixes #13528 

### Occurred changes and/or fixed issues

- Fixes issue `1` by adding the `inert` HTML attribute when in view mode (disabled) https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inert so that element and it's children aren't focusable
- Fixes issue `2` by updating CSS on modal + adding padding to bottom of `CodeMirror` component so that it can fit the "escape to blur" message

### Technical notes summary
 
- @torchiaf regarding the issue with `escape` closing the modal and not leaving the code mirror focus trap, it will be fixed once https://github.com/rancher/dashboard/pull/13519 get's merged.

After that you'll only need to add to AppModal component inside of that modal the following: `:trigger-focus-trap="true"`.

This will make the modal a focus trap itself while it's open.

### Checklist
- [X] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [X] The PR has a Milestone 
- [X] The PR template has been filled out
- [X] The PR has been self reviewed 
- [X] The PR has a reviewer assigned
- [X] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [X] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: shell/components/CodeMirror.vue [hunk 1]
```diff
@@ -239,6 +239,7 @@ export default {
 <template>
   <div
     ref="codeMirrorContainer"
+    :inert="isDisabled ? true : false"
```
Comment (rak-phillip) [inline shell/components/CodeMirror.vue:242]: I wasn't aware of `inert`, this is a great attribute to add to our toolbox 🎉

**Review by rak-phillip — APPROVED** [review]
LGTM

**Review by torchiaf — APPROVED** [review]
I tested the Yaml editor in KnownHosts dialog, LGTM
