### PR TITLE
Last Project Member removal in Rancher Dashboard

### LINKED ISSUE #13167: Last Project Member removal in Rancher Dashboard
**SURE-9616**

**Setup**
- Rancher version: 2.10.1
- Rancher UI Extensions: /
- Browser type & version: any

**Describe the bug**
In Rancher 2.10.1 Project Member editing has a UI bug when removing a Project Member. Once the "Remove" button is clicked, UI removes the last added Member. 

**To Reproduce**
Remove Project Member with the "Remove" button

**Result**
The "Remove" button removes the last member in the view

**Expected Result**
The "Remove" button removes the correct member in the view

**Screenshots**

https://github.com/user-attachments/assets/a00212ba-bb49-422d-afb2-6491065261bf

**Additional context**

### LINKED ISSUE #13319: [BUG] UI Cluster Member Roles remove button deletes the last row
**Rancher Server Setup**
- Rancher version: 2.10.1, 2.10.2
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): EKS

**Information about the Cluster**
- Kubernetes version: 1.29, 1.30, 1.31
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): AWS EC2 RKE2

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

**Describe the bug**

In cluster management, select Edit config on a RKE2 cluster, scroll down to Member Roles. If the cluster has more than 1 member, if you click on Remove of any user user except for the last one, the last user at the bottom will be removed instead of the one you clicked Remove.

**To Reproduce**
See bug Description 

**Result**

**Expected Result**
The user you wanted to delete should be removed

**Screenshots**

Image

**Additional context**

### PR DESCRIPTION
**Pull request by cnotv**
### Summary
Fixes #13167
Fixes #13319

### Occurred changes and/or fixed issues

Made component Principal (the user card) to fetch again the member data on prop change (the ID passed in the array).

### Technical notes summary

- Moved `Principal` logic within a method and called on prop change
- Added Jest setup configuration to prevent Vue warns to spam the console while debugging
- Added unit tests
  - `ArrayList` 
     - Added case with more items
     - Update test to get correct emitters (the removed one is confusing) which require mocked timers
  - `MembershipEditor` ensured removing a member is still working correctly as in the component
  - `Principal` test to update fetched values on prop change

### Areas or cases that should be tested
As by issue

### Screenshot/Video

https://github.com/user-attachments/assets/f918b82d-a465-4e72-adaf-a0e42aeba31e

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: shell/components/auth/Principal.vue [hunk 1]
```diff
@@ -51,6 +35,34 @@ export default {
...
+      const principalId = escape(this.value).replace(/\//g, '%2F');
+
+      try {
+        this.principal = await this.$store.dispatch('rancher/find', {
+          type: NORMAN.PRINCIPAL,
+          id:   this.value,
+          opt:  { url: `/v3/principals/${ principalId }` }
+        });
+      } catch (e) {
+        console.error('Failed to fetch principal', this.value, principalId); // eslint-disable-line no-console
```
Comment (eva-vashkevich) [inline shell/components/auth/Principal.vue:56]: future todo: We should emit it for the parent to handle instead of printing to the console

**Review by eva-vashkevich — APPROVED** [review]
lgtm with a minor comment

File: shell/components/auth/Principal.vue (hunk 1 above)
Comment (cnotv) [reply shell/components/auth/Principal.vue:56]: Wait that's not my change 🤔
