### PR TITLE
Ensure refresh button correctly clears table selection

### LINKED ISSUE #14448: SSP: The table's selection state becomes corrupted after clicking Refresh button
**Setup**
- Rancher version: v2.12
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**
Clicking the Refresh button on a resource table causes selection issues:

1. After selecting items (individually or via Select all) and then clicking Refresh, the selection state becomes inconsistent.
2. The Select all button can still be clicked once and appears to deselect all rows visually — but the selection count does not update, indicating items are still selected.
3. After this, the Select all button becomes unresponsive and cannot be used to select/deselect items.
4. Attempting a bulk action, such as Delete, will trigger the PromptRemoval modal with all items still shown as selected.

**To Reproduce**
1. Enable SSP
2. Go to local cluster 
3. Go to Cluster > Nodes
4. Click `Select all`
5. Click the `Refresh` button
6. Attempt to deselect using Select all again — it appears to work visually but selection count remains unchanged
7. Perform a bulk action (e.g., Delete) — all nodes are still treated as selected

**Result**
The table's selection state becomes corrupted after a refresh. The UI and underlying data go out of sync, preventing proper deselection or accurate bulk actions.

**Expected Result**
Clicking Refresh should fully reset the selection state of the table, restoring proper UI and behavior for bulk actions.

**Screenshots**

https://github.com/user-attachments/assets/53225d36-1b1c-4228-b501-aedd11ef64f8

**Additional context**
Discovered while testing https://github.com/rancher/dashboard/issues/13043

### PR DESCRIPTION
**Pull request by richard-cox**
### Summary
Fixes #14448

### Occurred changes and/or fixed issues
- On manul refresh with vai on ensure that the table's selection state (row highlighting, checkbox, total count at top) is reset once the user has clicked refresh

### Technical notes summary
- need to understand how this should / will work when resource's are automatically updated

### Areas or cases that should be tested
- vai on, any list, make a few selections hit refresh

### Areas which could experience regressions
- projects/namespace list `move` namespace (though this looks already broken)

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes
- [x] The PR has been reviewed in terms of Accessibility

### CODE REVIEW

File: shell/components/SortableTable/selection.js [hunk 1]
```diff
@@ -531,7 +531,7 @@ export default {
     },
 
     clearSelection() {
-      this.update([], this.selectedRows);
+      this.update([], [...this.selectedRows]);
```
Comment (richard-cox) [inline shell/components/SortableTable/selection.js:534]: `update`s second param is `toRemove` and it's entries are removed from the selection rows i.e this.selectedRows. it runs through those and removes it's entries from this.selectedRows. Without spread it in affect removes entries from itself, so later on there's nothing in toRemove to remove (though it has been removed from this.selectedRows). by spreading it means items are still removed from this.selectedRows but still exist in toRemove
