### PR TITLE
Fix SSH Key missing fields

### LINKED ISSUE #13474: Secrets: SSH Key: Unable to create SSH Key due to missing fields on Create SSH Key form
**Setup**
- Rancher version: v2.11
- Rancher UI Extensions:
- Browser type & version: Chrome, FF

**Describe the bug**
User is unable to create SSH Key due to missing fields on Create SSH Key form.

**To Reproduce**
1. go to Cluster Dashboard -> Storage -> Secrets
2. click Create
3. select SSH Key

**Result**
User is unable to create SSH Key due to missing fields on Create SSH Key form.

**Expected Result**
User is able to create SSH Key. All expected tabs/fields are present on Create SSH Key form.

**Screenshots**
2.10.2

Image

2.11

Image

**Additional context**

### PR DESCRIPTION
**Pull request by torchiaf**
### Summary
Fixes #13474

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: shell/edit/secret/ssh.vue [hunk 1]
```diff
@@ -44,7 +44,10 @@ export default {
     update() {
       this.value.setData('ssh-publickey', this.username);
       this.value.setData('ssh-privatekey', this.password);
-      this.value.setData('known_hosts', this.knownHosts);
+
+      if (this.showKnownHosts) {
```
Comment (torchiaf) [inline shell/edit/secret/ssh.vue:48]: With this, the `known_hosts` field will be visible only when editing a secret that already has that value in `data`.
The other solution is enable it by default.

Comment (nwmac) [reply shell/edit/secret/ssh.vue:48]: I think this is fine

**Review by nwmac — APPROVED** [review]
