### PR TITLE
EKS: edit imported clusters, and clusters with exclusively self-managed nodes

### LINKED ISSUE #10335: Unable to edit imported EKS cluster having self-managed nodes
**Setup**
Rancher version: v2.8-d0a177f1745fe14a0b3de7483aa3ef895d1ab967-head
Rancher UI Extensions: None
Browser type & version: Chrome latest

**Describe the bug**
Unable to edit imported EKS cluster having self-managed nodes. Saving the changes after editing the cluster is not working.

**To Reproduce**
- Import EKS cluster having self-managed nodes
- Edit the cluster and upgrade k8s version or add cluster tags or enable logging, etc.

**Expected Result**
In https://github.com/rancher/eks-operator/issues/301, support is added for self-managed EKS nodes.
User must be able to edit and perform operations on imported EKS cluster having self-managed nodes

**Screenshots**
image

cc: @mjura @salasberryfin

### LINKED ISSUE #11100: [v2.9] EKS: Unable to edit imported cluster
**Setup**
Rancher version: `v2.9-3c48a195381ad55f9fef7e9bf32b1593d43368ca-head`
Browser type & version: Chrome latest

**Describe the bug**
AKS (Vue UI): Unable to manage and edit imported cluster. Error on UI: At least one of public or private access must be enabled.

**To Reproduce**
- Create EKS cluster and import it from Rancher UI
- Once cluster becomes Active, edit cluster and check the fields

**Screenshots**
image

**Additional Info**
Cluster spec after importing:
```
spec:
  agentImageOverride: ''
  answers: {}
  clusterSecrets: {}
  description: ''
  desiredAgentImage: ''
  desiredAuthImage: ''
  displayName: cpinjani-imp
  dockerRootDir: /var/lib/docker
  eksConfig:
    amazonCredentialSecret: cattle-global-data:cc-4v4rm
    displayName: cpinjani-imp
    ebsCSIDriver: null
    imported: true
    kmsKey: null
    kubernetesVersion: null
    loggingTypes: null
    nodeGroups: null
    privateAccess: null
    publicAccess: null
    publicAccessSources: null
    region: ca-central-1
    secretsEncryption: null
    securityGroups: null
    serviceRole: null
    subnets: null
    tags: null
  enableNetworkPolicy: false
  fleetWorkspaceName: fleet-default
  internal: false
  localClusterAuthEndpoint:
    enabled: false
  windowsPreferedCluster: false
```

### LINKED ISSUE #11104: [v2.9] EKS: Cluster details not displayed
**Setup**
Rancher version: `v2.9-3c48a195381ad55f9fef7e9bf32b1593d43368ca-head`
Browser type & version: Chrome latest

**Describe the bug**
AKS (Vue UI): Cluster details not displayed, Subnet and service role information is missing.

**To Reproduce**
- Create EKS cluster and import it from Rancher UI
- Once cluster becomes Active, edit cluster and check the fields

**Screenshots**
image

**Spec:**
```
eksConfig:
    amazonCredentialSecret: cattle-global-data:cc-4v4rm
    displayName: cpinjani-eks29
    ebsCSIDriver: null
    imported: false
    kmsKey: null
    kubernetesVersion: '1.28'
    loggingTypes: []
    nodeGroups:
      - arm: null
        desiredSize: 1
        diskSize: 20
        ec2SshKey: null
        gpu: false
        imageId: null
        instanceType: t3.medium
        labels: {}
        launchTemplate: null
        maxSize: 1
        minSize: 1
        nodeRole: >-
          arn:aws:iam::REDACTED:role/cpinjani-eks29-node-instance-role-REDACTED
        nodegroupName: group1
        requestSpotInstances: false
        resourceTags: {}
        spotInstanceTypes: null
        subnets:
          - subnet-08d04305e92081795
          - subnet-02b9ee3a4ea2fab0d
          - subnet-07e95c09365177dfd
        tags: {}
        userData: null
        version: '1.28'
    privateAccess: false
    publicAccess: true
    publicAccessSources:
      - 0.0.0.0/0
    region: us-west-2
    secretsEncryption: false
    securityGroups: []
    serviceRole: null
    subnets: []
    tags: {}
```

### LINKED ISSUE #11291: [v2.9] GKE: Unable to edit imported cluster
**Setup**
Rancher - v2.9-4dd0c38a2aab4f77271c07d2c887ecf5bbcea5e3-head
Dashboard- master e750be9
Browser type & version: Chrome latest

**Describe the bug**
GKE (Vue UI): Unable to manage and edit imported cluster. 'Save' button is disabled.

**To Reproduce**
- Create GKE cluster and import it from Rancher UI
- Once cluster becomes Active, edit cluster, enter project details and Authenticate.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by mantis-toboggan-md**
### Summary
Fixes #11100 
Fixes #11104 
Fixes #10335 
Fixes #11291 

### Occurred changes and/or fixed issues
This PR updates EKS provisioning to incorporate the same upstream syncing behavior as AKS - see https://github.com/rancher/dashboard/pull/11120 for some background on why this is needed. This PR adds some fixes to the syncing utility as well as unit tests around the problems I found while working on the PR. There are also some minor fixes around the EKS components to correct console errors shown when editing an imported cluster.

Special notes about EKS:
- imported clusters with no nodeGroups are valid (they may have self-managed nodes)
- After following aws instructions to create an EKS cluster with default values and importing it into Rancher, the subnet/virtual network configuration is indistinguishable from an EKS cluster provisioned in Rancher with the 'Create a new VPC and subnet automatically' option selected. The old UI just shows that option selected for imported clusters. 
- In this PR I updated the networking tab to use the subnets from the upstream status instead, so the user can see which VPC/subnets are in use by the current cluster.

### Areas or cases that should be tested
1. Edit an imported cluster with exclusively self-managed nodes (no node groups)
     - no console errors shown
     - user should be able to save the cluster without having added node groups
     - ~user should be able to add and remove node groups~
     EDIT: removing all node groups is causing issues due to backend validation, issue filed here https://github.com/rancher/dashboard/issues/11336
2. Edit an imported cluster with node groups
    - user should be able to make all the same changes as they can with a Rancher-provisioned EKS cluster
    - the networking tab should show a list of selected subnets

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: pkg/eks/components/CruEKS.vue [hunk 1]
```diff
@@ -409,6 +418,9 @@ export default defineComponent({
     },
 
     async actuallySave(): Promise<void> {
+      if (!this.isNewOrUnprovisioned && !this.nodeGroups.length) {
+        delete this.normanCluster.eksConfig.nodeGroups;
```
Comment (torchiaf) [inline pkg/eks/components/CruEKS.vue:422]: `this.normanCluster.eksConfig` is possibly undefined. We can include it in the if condition before delete.

**Comment by torchiaf** [comment]
I tired to add and remove some node groups. While the cluster is `updating` and I click on edit button, some fields are still enabled. Is it a wanted behavior ?

image

**Review by torchiaf — APPROVED** [review]
LGTM, just a comment about null checks.

**Review by torchiaf — CHANGES_REQUESTED** [review]
Just a comment to add the null check.

**Comment by mantis-toboggan-md** [comment]
Updated to include https://github.com/rancher/dashboard/issues/11291 - the same syncUpstreamConfig functionality needs to be added to GKE provisioning. No extra logic around node groups needed for GKE though.

**Comment by mantis-toboggan-md** [comment]
I hit an additional issue with this: due to pre-existing norman api validation it's not possible to add node groups then delete all node groups through the UI. I've separated that out into a different issue, as it needs backend work as well and the other fixes in this PR are required to reproduce the bug.

**Review by torchiaf — APPROVED** [review]
LGTM
