### PR TITLE
Fix gke import loading

### LINKED ISSUE #13686: GKE Import Cluster dropdown is missing a loading spinner
**Setup**
- Rancher version: v2.11-41098eee7331faf5d4a478dfcf66232867ed6a6f-head
- Rancher UI Extensions: n/a
- Browser type & version: ff

**Describe the bug**

**To Reproduce**

1. Create a gke cluster to import
2. In the Rancher UI, navigate to the cluster manament list view and click 'import existing'
3. Select GKE
4. Select the zone you created your cluster in in step 1
5. Check that the cluster dropdown is populated w/ your cluster
6. Select a different zone

**Result**
The stale cluster data stays in the dropdown for a moment.

**Expected Result**
A loading spinner should appear while new cluster data is being fetched

**Screenshots**

https://github.com/user-attachments/assets/0b49c347-09ae-4f90-bf79-009bfb79ae8c

**Additional context**

### LINKED ISSUE #13695: GKE Import page should not show 'Extra Zones'
**Setup**
- Rancher version:	v2.11-41098eee7331faf5d4a478dfcf66232867ed6a6f-head
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**
The GKE import cluster page should not allow users to set 'extra zones.'

**To Reproduce**
Navigate to the cluster management list view, click 'import existing', and select GKE
Enter project credentials and authenticate

**Result**
Zone, extra zones, and region/zone inputs are shown

**Expected Result**
The extra zones inputs shouldn't be shown when importing a GKE cluster

**Screenshots**
Old UI:

Image

**Additional context**

### LINKED ISSUE #13696: GKE import page: 'cluster to register' should be a required field
**Setup**
- Rancher version: v2.11-41098eee7331faf5d4a478dfcf66232867ed6a6f-head
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**

**To Reproduce**

1. Navigate to the cluster management list view, click 'import existing', and select GKE
2. Enter project credentials and authenticate
3. Enter a name and click 'create' without choosing a cluster to register

**Result**
The cluster is created and eventually enters an error state

**Expected Result**
Users should be prevented from saving if a cluster to register is not defined.

### LINKED ISSUE #13697: GKE Import - cluster to register text input is broken
**Setup**
- Rancher version:
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**
The GKE import page includes a dropdown of all GKE clusters available to import in the selected zone/region. If no clusters are found, a text input is shown in stead. The text input is currently broken.

**To Reproduce**
    In the Rancher UI, navigate to the cluster manament list view and click 'import existing'
    Select GKE
   If the default zone has clusters (a dropdown of cluster names is rendered) pick a different zone without clusters
  Type to type something in the input

**Result**
`[object InputEvent]` appears in the input

**Expected Result**
Typing in the input should set the `<normanCluster>.gkeConfig.clusterName` field

**Screenshots**
Image

### PR DESCRIPTION
**Pull request by mantis-toboggan-md**
### Summary
Fixes #13686 
Fixes #13695
Fixes #13696 
Fixes #13697 

### Occurred changes and/or fixed issues
- add a loading spinner to the cluster dropdown
- hide the 'extra zones' checkboxes when importing gke clusters
- validate that a cluster name is defined
- fix broken cluster name text input

### Areas or cases that should be tested
Importing GKE clusters, as described in the linked issues above

### Areas which could experience regressions
Create new GKE cluster - verify that the extra zones checkboxes are rendered, and that form validation is still working (nbo extra name validator)

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: pkg/gke/components/Import.vue [hunk 1]
```diff
@@ -111,7 +124,9 @@ export default defineComponent({
       } catch (err:any) {
         this.$emit('error', err);
```
Comment (eva-vashkevich) [inline pkg/gke/components/Import.vue:125]: should we set this.loadClusterFailed = false here too?

**Review by eva-vashkevich — DISMISSED** [review]
lgtm with a small comment

File: pkg/gke/components/Import.vue (hunk 1 above)
Comment (mantis-toboggan-md) [reply pkg/gke/components/Import.vue:118]: With the introduction of `loadingClusters` `loadClusterFailed` is redundant; I removed it to clean up the code a bit.

**Review by eva-vashkevich — APPROVED** [review]
lgtm
