### PR TITLE
Fixes an issue where we failed to render deployment pages when match expressions with multiple values are present

### LINKED ISSUE #15908: The deployment detail page isn't rendering when matchExpressions with multiple values are used
**Setup**
- Rancher version: 2.12

**Describe the bug**
[SURE-10938]

If you have a deployment which has match expression which contain multiple values the deployment detail page will fail to render.

Image

**To Reproduce**
You can use this deployment to reproduce.

[nginx.yaml](https://github.com/user-attachments/files/23464739/nginx.yaml)

**Result**
A blank deployment page

**Expected Result**
A fully rendered deployment page with the expected pods listed.

Image

**Additional context**
This is caused by this code which intentionally only supported single values:
https://github.com/rancher/dashboard/blob/master/shell/utils/selector-typed.ts#L202-L204

### PR DESCRIPTION
**Pull request by codyrancher**
### Summary
Fixes #15908

### Occurred changes and/or fixed issues
Added support for multi-value matchExpressions when retrieving pods related to a deployment.

### Technical notes summary
We didn't originally support match expressions with multiple values. This change adds the support.

### Areas or cases that should be tested
Multi-value matchExpressions when retrieving pods related to a deployment for both vai enabled and vai disabled.

### Areas which could experience regressions
Multi-value matchExpressions when retrieving pods related to a deployment for both vai enabled and vai disabled.

### Screenshot/Video

[Screencast_20251110_132831.webm](https://github.com/user-attachments/assets/98b1e812-1d44-445a-a30c-195a3b0c4323)

[Screencast_20251110_140037.webm](https://github.com/user-attachments/assets/ff77ad9e-b297-439d-ac86-9d677f09f1f6)

I want to make a note, when vai is enabled it seems that the results of filtered api requests can be cached  and won't change even if labels are removed/changed that are necessary for matching. This is a separate backend issue and I'll open a new issue once I confirm the problem.

[Screencast_20251110_140237.webm](https://github.com/user-attachments/assets/cb6f0d57-eb70-48ed-b158-712d1cbd5a4c)

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes
- [x] The PR has been reviewed in terms of Accessibility
- [x] The PR has considered, and if applicable tested with, the three Global Roles `Admin`, `Standard User` and `User Base`

### CODE REVIEW

File: shell/utils/selector-typed.ts [hunk 1]
```diff
@@ -199,8 +199,12 @@ export function labelSelectorToSelector(labelSelector?: KubeLabelSelector): stri
   });
 
   (labelSelector?.matchExpressions || []).forEach((value: KubeLabelSelectorExpression) => {
-    if (value.operator === 'In' && value.values?.length === 1) {
-      res.push(`${ value.key }=${ value.values[0] }`);
+    if (value.operator === 'In' && value.values !== undefined) {
+      if (value.values?.length === 1) {
+        res.push(`${ value.key }=${ value.values[0] }`);
```
Comment (codyrancher) [inline shell/utils/selector-typed.ts:204]: Maintains the existing behavior to reduce risk even though the second case should work for all values.

**Comment by catz** [comment]
Hello @codyrancher , small question, is it possible to edit matchExpressions via form or only in yaml ?

**Comment by codyrancher** [comment]
@catz I'm not aware of a way to do it via the form. I looked around the code and poked around the form and I didn't find anything.
