### PR TITLE
EKS - do not allow upgrades if any node groups would fall more than one minor version behind

### LINKED ISSUE #11460: v2.9 EKS - Disallow upgrading cluster version if Nodegroup is on lower version
**Setup**
Rancher - v2.9-81337b95660cba868629d6fe769bd7e8242b5aee-head
Dashboard - master 3da1205
Browser type & version: Chrome latest

**Describe the bug**
EKS (Vue UI): Validation for version upgrade to next minor version was added in https://github.com/rancher/dashboard/issues/11389
However we require to disallow upgrading cluster version to next version if Nodegroup is on lower version, similar check as of 2.8:

image

**To Reproduce**
- Create EKS cluster from Rancher UI with lowest supported version eg. v1.27
- Upgrade control plane to next version v1.28, Nodegroup is at v1.27
- Edit cluster and next version is shown for upgrade
image

### PR DESCRIPTION
**Pull request by mantis-toboggan-md**
### Summary
Fixes #11460 

### Occurred changes and/or fixed issues
This PR updates the EKS provisioning form to prevent users from upgrading the cluster (control plane) k8s version more than one minor version ahead of any node groups in the cluster.

### Areas or cases that should be tested
1. Create an EKS cluster with an older version eg 1.27, upgrade it & edit it again - the version input should be disabled with a warning about node groups
2. Check all nodegroup upgrade checkboxes - the cluster version dropdown should stay disabled
3. Save the cluster
4. Edit again - now that nodegroups are the same version as the cluster, you should be able to upgrade the cluster again

### Screenshot/Video
Screenshot 2024-07-18 at 12 47 31 PM
Screenshot 2024-07-18 at 12 47 48 PM
Screenshot 2024-07-18 at 12 47 55 PM

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: pkg/eks/components/Config.vue [hunk 1]
```diff
@@ -146,6 +157,23 @@ export default defineComponent({
...
 
+    // the control plane k8s version can't be more than one minor version ahead of any node pools
+    // verify that all nodepools are on the same version as the control plane before showing upgrade optiopns
+    canUpgrade(): boolean {
+      if (this.mode === _CREATE) {
+        return true;
+      }
+      const nodeGroups = this.config?.nodeGroups || [];
+
+      const needsUpgrade = nodeGroups.filter((group) => semver.gt(semver.coerce(this.originalVersion), semver.coerce(group.version)) || group._isUpgrading);
```
Comment (momesgin) [inline pkg/eks/components/Config.vue:168]: Out of curiosity, shouldn't we consider equal versions to be allowed and use `semver.gte`?

Comment (mantis-toboggan-md) [reply pkg/eks/components/Config.vue:168]: If the node group version is equal to the cluster version, the node group can't be upgraded further (yet). Users need to upgrade the cluster version, then come back and upgrade the node group version. In this context we just care that node groups are not behind the current cluster version: if they were, attempting to upgrade the cluster further would make them more than one minor release apart which is not permitted by EKS

Comment (momesgin) [reply pkg/eks/components/Config.vue:168]: Thanks for explaining

**Review by momesgin — APPROVED** [review]
Tested and it works as expected, lgtm
