### PR TITLE
Fix YAML 409 conflict errors

### LINKED ISSUE #11705: Intermittent error when editing Yaml in Continuous Delivery
**Setup**
- Rancher version: `v2.9-4a8d37af3fc1d570ea115f5654e897a33106ed78-head` (`rancher/fleet:v0.10.1`)
- Rancher UI Extensions: None
- Browser type & version: `Brave 1.69.153 Chromium 128.0.6613.52`

**Describe the bug**

Editing certain values from gitrepos like `disablePolling` or `paths` is not possible sometimes and an error is triggered

**To Reproduce**
- Deploy Rancher and some downstream clusters
- Go to Continuous Delivery > Gitrepo > (choose fleet-default) > Add Repository
- Add this repo:
```
URL: https://github.com/mmartin24/test-fleet
Branch: master
Paths: disable-polling
```
- Click `Next`
- Select in Target `All Clusters in the Workspace`
- Click `Create`
- Wait for repo to be deployed and things to settle
- Click on 3 dots > `Edit YAML`
- Add value `disablePolling` and set it to `true`

**Result**
Many times it errors with this message:
```
Operation cannot be fulfilled on gitrepos.fleet.cattle.io "disable-polling-test": the object has been modified; please apply your changes to the latest version and try again
```
Video: 

https://github.com/user-attachments/assets/980ba55a-a619-4174-887e-9fc1fbafe62b

If it does not happen, just try changing to `false` / `true` and eventually will occur.
Sometimes, this happens even if you try adding the parameter at gitrepo creation.

**Expected Result**
Error should not happen

**Screenshots**

image

**Additional context**
Occasionally, I have seen this error as well with `paths` value as previously mentioned.

### LINKED ISSUE #14703: Conflict error when editing YAML
**Setup**
- Rancher version: 2.12-head
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**

While editing resources and the UI receives a new version from the server, the UI is able to resolve PUT request's conflicts by merging background changes with user's changes and resend the request.

This mechanism is implemented in Edit forms https://github.com/rancher/dashboard/blob/f9aa1f38bb9c5bdae689d786eb4713ff700eea28/shell/plugins/dashboard-store/normalize.js#L23-L24

but not for YAML edit forms

**To Reproduce**

This can be easily reproduced in Fleet, the server sends new GitRepo images every 10 seconds by default, updating the `metadata.resourceVersion` field .

- Go to Fleet
- Edit a App Bundle -> GitRepo
- Click on 'Edit YAML'
- Wait 10 seconds
- Click Save

**Result**

https://github.com/user-attachments/assets/05307834-290b-4dc4-b4aa-ee6d35812186

**Expected Result**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by torchiaf**
### Summary
Fixes #14703
Fixes #11705

### Technical notes summary

We are applying the `handleConflict` method to `saveYaml` to handle 409 errors.
When the UI gets a 409 error, it should try to resolve the conflicts by merging background changes with user's changes, and re-send the PUT request.

### Areas or cases that should be tested

Fleet -> GitRepo YAML edit.

### Screenshot/Video

[Screencast from 2025-07-07 10-47-33.webm](https://github.com/user-attachments/assets/11c6bdca-f87d-4479-a49c-b1953a3f53c5)

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes
- [x] The PR has been reviewed in terms of Accessibility

### CODE REVIEW

**Review by richard-cox — CHANGES_REQUESTED** [review]
Marking this one as blocked on https://github.com/rancher/dashboard/pull/14431 (which is pending final review). it has lots of improvements including unit tests for handleConflicts

**Review by eva-vashkevich — DISMISSED** [review]
lgtm

**Review by eva-vashkevich — APPROVED** [review]
lgtm

File: shell/plugins/dashboard-store/normalize.js [hunk 1]
```diff
@@ -20,18 +20,18 @@ export function normalizeType(type) {
...
  * Detect and resolve conflicts from a 409 response.
  *
- * @param {*} initialValueJSON the initial value before changes
+ * @param {*} initialValue the initial value before changes
  * @param {*} userValue the value containing the local changes. this function will intentionally mutate this to contain changes made from the server
  * @param {*} serverValue the very latest value from the server
  * @returns If `value` has been successfully updated return a false-y value. Else they can't be resolved, return an array of errors to show the user.
  */
-export async function handleConflict(initialValueJSON, userValue, serverValue, rootGetters, store, storeNamespace) {
+export async function handleConflict(initialValue, userValue, serverValue, store, storeNamespace, toJSON = (x) => x.toJSON()) {
```
Comment (eva-vashkevich) [inline shell/plugins/dashboard-store/normalize.js:28]: I don't think we ever actually provide a different toJSON function, do we need it as a param?

File: shell/mixins/create-edit-view/impl.js [hunk 2]
```diff
@@ -117,7 +117,16 @@ export default {
...
-      return await handleConflict(this.initialValue.toJSON(), this.value, this.liveValue, this.$store.getters, this.$store, this.storeOverride || this.$store.getters['currentStore'](this.value.type));
+      return await handleConflict(
+        this.initialValue,
+        this.value,
+        this.liveValue,
+        {
+          dispatch: this.$store.dispatch,
+          getters:  this.$store.getters
+        },
+        this.storeOverride || this.$store.getters['currentStore'](this.value.type)
```
Comment (eva-vashkevich) [inline shell/mixins/create-edit-view/impl.js:128]: this.storeOverride here throws a warning in the console 'runtime-core.esm-bundler.js:51 [Vue warn]: Property "storeOverride" was accessed during render but is not defined on instance. "

Comment (eva-vashkevich) [inline shell/mixins/create-edit-view/impl.js:128]: when going to edit a Repository (catalog.cattle.io.clusterrepo) this.storeOverride gives a Vue warn in the console, because this.storeOVerride is not defined

**Review by eva-vashkevich — CHANGES_REQUESTED** [review]

File: shell/mixins/create-edit-view/impl.js (hunk 2 above)
Comment (torchiaf) [reply shell/mixins/create-edit-view/impl.js:128]: I found the `warning` but it's actually in `schema()` computed value so not a regression from current PR. I think it could be related to the recent Resource Details refactoring @codyrancher .
It doesn't seem to be a blocker though.

image

File: shell/plugins/dashboard-store/normalize.js (hunk 1 above)
Comment (torchiaf) [reply shell/plugins/dashboard-store/normalize.js:28]: The callback is a param here: 
https://github.com/rancher/dashboard/blob/5c95ca97b33e8747487bfa2a870214ca9470e2e7/shell/plugins/dashboard-store/resource-class.js#L1591-L1601
It's worth to have it as a param with a default value.
When used in `_saveYaml`, not every input values are Steve objects, so I need to specify a custom `toJSON` there.

**Comment by torchiaf** [comment]
Thanks @eva-vashkevich , I left some comments.

File: shell/mixins/create-edit-view/impl.js (hunk 2 above)
Comment (eva-vashkevich) [reply shell/mixins/create-edit-view/impl.js:128]: are you sure? I wasn't getting it when I removed this.storeOverride  from L128. but I might need to check it again

File: shell/edit/provisioning.cattle.io.cluster/rke2.vue [hunk 3]
```diff
@@ -1333,7 +1333,16 @@ export default {
 
         // if there's the initial machine pool config, we are in a good position to apply the handleConflict function
         // to deal with out-of-sync data between machinePools configs. This also mutates the data inside machinePool.config through object reference
-        const conflict = await handleConflict(initialMachinePoolValue.toJSON(), machinePool.config, latestConfig, this.$store.getters, this.$store, 'management');
+        const conflict = await handleConflict(
+          initialMachinePoolValue,
+          machinePool.config,
+          latestConfig,
+          {
```
Comment (aalves08) [inline shell/edit/provisioning.cattle.io.cluster/rke2.vue:1340]: You are changing the functions signature here (one less argument, now the toJSON is inside the actual function) which will cause problems with backwards compatibility IF there's an extension that uses `handleConflict`... I would say the chances of that are low (I only learned about this method a couple of months ago), but it's good to know the risks involved. FYI @richard-cox

File: shell/plugins/dashboard-store/__tests__/normalize.test.ts [hunk 4]
```diff
@@ -3,10 +3,199 @@ import { handleConflictUseCases } from '@shell/plugins/dashboard-store/__tests__
...
+
+    mockStore = {
+      dispatch: jest.fn((action, payload) => Promise.resolve(payload)),
+      getters:  { 'i18n/t': jest.fn((key, params) => `${ key } - ${ JSON.stringify(params) }`) },
+    };
+
+    mockToJSON = jest.fn((x) => x);
+  });
+
+  it('should resolve conflict and return false if no actual conflicts (integration)', async() => {
```
Comment (aalves08) [inline shell/plugins/dashboard-store/__tests__/normalize.test.ts:21]: why are you adding all of these individually when you can extend `handleConflictUseCases` and keep it all in an array?

**Review by aalves08 — COMMENTED** [review]
Left a couple of comments @richard-cox , but overall the unit tests are passing so I think that the code changes and the tests that I did are fine for the machine pools conflict handling

File: shell/plugins/dashboard-store/__tests__/normalize.test.ts (hunk 4 above)
Comment (torchiaf) [reply shell/plugins/dashboard-store/__tests__/normalize.test.ts:21]: That's because I added the unit tests before to rebase with your changes, so they remained in the same file .
As long as they succeed I would keep them as it is and maybe clean up the code in 2.13

File: shell/edit/provisioning.cattle.io.cluster/rke2.vue (hunk 3 above)
Comment (torchiaf) [reply shell/edit/provisioning.cattle.io.cluster/rke2.vue:1340]: Let's double check if that code is used in official extensions.
TBH I think we should be allowed to change and improve the code, if this causes compatibility issues we should fix the problem at root.
BTW, worst case scenario is that it'll fail in case of mismatch between shell in container app and extension's shell when running the extension in embedded mode, and so get an JS error instead of conflict errors like it currently does. I think the possible are close to zero, but It could happen...

Comment (torchiaf) [reply shell/edit/provisioning.cattle.io.cluster/rke2.vue:1340]: Harvester, Elemental, Kubewarden don't have references to `handleConflicts`,

File: shell/mixins/create-edit-view/impl.js (hunk 2 above)
Comment (torchiaf) [reply shell/mixins/create-edit-view/impl.js:128]: `this.storeOverride` removed from the code, I'm running the UI locally and I still get the errors:

image

File: shell/plugins/dashboard-store/__tests__/normalize.test.ts (hunk 4 above)
Comment (aalves08) [reply shell/plugins/dashboard-store/__tests__/normalize.test.ts:21]: I would say it's ok as long as you create an issue to track it so it won't get forgotten 🙏

**Comment by torchiaf** [comment]
Rebased to unlock the CI.
