### PR TITLE
aks node pools - allow 0 count when autoscaling is enabled

### LINKED ISSUE #11842: AKS: Allow 0 NodeCount for User mode pools
**Setup**
Rancher - v2.9-ac80dbd08dd92b65627b36e8658c87ea661c1baf-head
Dashboard - release-2.9 e791050

**Describe the bug**
On AKS portal, zero NodeCount is allowed for User mode pools in scale methods: Manual & Autoscale. The same to be allowed on Rancher UI.

**Screenshots**
_AKS:_

image
--------------------
image

_Rancher:_

image
--------------------------------
image

### PR DESCRIPTION
**Pull request by mantis-toboggan-md**
### Summary
Fixes #11842

### Occurred changes and/or fixed issues
This PR updates AKS validation to allow users to specify a min and max node counts of 0, and a node count of 0 if autoscaling is enabled. All 3 inputs allow a maximum of 1000. These limitations mirror the azure portal validation.

### Areas or cases that should be tested
1. Create new aks cluster without autoscaling in any pools: 'Node Count' should be validated to be >0
2. Create an AKS cluster with autoscaling enabled in a pool: 'Node Count' should be validated to be >=0, <=max count, and >= min count.
3. Max and min count should also be limited to 1000 

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

**Comment by mantis-toboggan-md** [comment]
Adding unit tests in 2.10 is blocked by https://github.com/rancher/dashboard/issues/11682

File: pkg/aks/util/validators.ts [hunk 1]
```diff
@@ -152,11 +152,11 @@ export const nodePoolNames = (ctx: any) => {
         const name = pool.name || '';
 
         if (!isValid(name)) {
-          ctx.$set(pool._validation, '_validName', false);
+          set(pool._validation, '_validName', false);
```
Comment (mantis-toboggan-md) [inline pkg/aks/util/validators.ts:155]: This fixes an error that prevented the AKS form from rendering.

File: pkg/aks/components/AksNodePool.vue [hunk 2]
```diff
@@ -334,24 +334,24 @@ export default defineComponent({
       <template v-if="pool.enableAutoScaling">
         <div class="col span-3">
           <LabeledInput
-            v-model.number="pool.minCount"
+            v-model:value.number="pool.minCount"
```
Comment (mantis-toboggan-md) [inline pkg/aks/components/AksNodePool.vue:337]: I think there are many more instances of this bug in the dashboard. I'm investigating and writing up an issue about it.

**Review by momesgin — APPROVED** [review]
Tested and it worked as expected, lgtm

File: pkg/aks/components/AksNodePool.vue (hunk 2 above)
Comment (mantis-toboggan-md) [reply pkg/aks/components/AksNodePool.vue:337]: https://github.com/rancher/dashboard/issues/11856
