### PR TITLE
workload create fixes

### LINKED ISSUE #971: Job - fail to create job because of wrong value of spec.template.spec.restartPolicy
rancher/rancher:`master-3411-head`

Steps:

- install rancher in HA mode
- go to the dashboard
- navigate to Job page
- create a Job 

Result:
- failed to create the job because of the following error 
```
Job.batch "test1" is invalid: spec.template.spec.restartPolicy: Unsupported value: "Always": supported values: "OnFailure", "Never"
```

image

- but there is no place in the creation workflow to set the value of restartPolicy

- here is the payload of the POST request 
Screen Shot 2020-08-05 at 5 51 00 PM

### PR DESCRIPTION
**Pull request by mantis-toboggan-md**
#971 
#943 
#937 
#948

### CODE REVIEW

File: components/ContainerResourceLimit.vue [hunk 1]
```diff
@@ -42,11 +42,11 @@ export default {
...
-      limitsCpu,
-      limitsMemory,
-      requestsCpu,
-      requestsMemory,
-      viewMode: _VIEW,
+      limitsCpu:      limitsCpu ? limitsCpu.replace(/([A-Z]|[a-z])/g, '') : null,
+      limitsMemory:   limitsMemory ? limitsMemory.replace(/([A-Z]|[a-z])/g, '') : null,
+      requestsCpu:    requestsCpu ? requestsCpu.replace(/([A-Z]|[a-z])/g, '') : null,
+      requestsMemory: requestsMemory ? requestsMemory.replace(/([A-Z]|[a-z])/g, '') : null,
+      viewMode:       _VIEW,
```
Comment (vincent99) [inline components/ContainerResourceLimit.vue:49]: These could be in any unit (bytes, megs, terabytes) if the container comes from kubectl/not us.  The value needs to be converted to the unit you're expecting . 
 utils/units parseSi() & formatSi({... minExponent: 2, maxExponent: 2, addSuffix: false, increment: /* 1000 for cpu, 1024 for memory */}) ).
