### PR TITLE
Custom chart UIs show PSP switch on Kubernetes v1.25 (merge fix)

### LINKED ISSUE #8528: [Backport v2.7] Custom chart UIs show PSP switch on Kubernetes v1.25
This is a backport issue for https://github.com/rancher/dashboard/issues/8434, automatically created via rancherbot by @cnotv

Original issue description:

**Setup**
- Rancher version: Rancher v2.7.2-rc5
- Browser type & version: Microsoft Edge v111.0.1661.41 (Official build) (arm64)

**Describe the bug**

When installing charts on a Kubernetes v1.25.6 cluster, the custom chart UIs still show the **Enable PodSecurityPolicies** checkbox, even though it is not possible to have PSPs in this version of Kubernetes and above.

**To Reproduce**

1. Create an RKE downstream cluster with Kubernetes v1.25.
2. Go to **Explore Cluster** and select the newly created v1.25 cluster.
3. In **Apps**/**Charts**, select one of the following charts:
    * Alerting Drivers
    * Epinio
    * Istio
    * Logging
    * Longhorn
    * Monitoring
    * NeuVector
    * OPA Gatekeeper
    * Prometheus Federator
5. Click **Install**.
6. Select any project then click **Next**.
7. Notice that the second page of configuration shows the **Enable Pod Security Policies** checkbox.

**Result**
A user can still select the checkbox to install PodSecurityPolicies even though these are not supported in Kubernetes v1.25 anymore.

**Expected Result**

A user cannot choose to install PSPs from the UI when the cluster is Kubernetes v1.25.

### PR DESCRIPTION
**Pull request by cnotv**
### Summary
Fixes #8528
Backport #8505

### CODE REVIEW

**Review by mantis-toboggan-md — APPROVED** [review]

File: shell/chart/gatekeeper.vue [hunk 1]
```diff
@@ -21,6 +22,8 @@ export default {
   },
 
   computed: {
+    ...mapGetters(['currentCluster']),
```
Comment (mantis-toboggan-md) [inline shell/chart/gatekeeper.vue:25]: I updated this component to fix a duplicated computed property; the PR was otherwise good.
