### PR TITLE
Fix yaml editor styling

### LINKED ISSUE #11701: Vue3: Yaml editor and other codemirror components' theme rendering is off
**To Reproduce**

1. Navigate to local cluster
2. View details of any given resource that doesn't have a custom detail view
  - For example:  `apiregistration.k8s.io.apiservice`

**Result**
Yaml editor shows strange theme rendering

**Expected Result**

Theme should render properly 

**Screenshots**

yaml

**Additional context**
Other areas with likely broken styling are:
- KeyValue when used in configmaps
- Workload storage detail view (volumes)
- Monitoring's alerting rule and recording rule edit components
- JSON annotation display

Error in console:
```console
resize nullpx nullpx codemirror-editor-vue3.js:405
```

### PR DESCRIPTION
**Pull request by mantis-toboggan-md**
### Summary
Fixes #11701 

### Occurred changes and/or fixed issues
This PR fixes Codemirror styling (used in yaml editor and a couple other places). There were two main issues: this new library introduced new styles, which can be overwritten via prop (added here). The new library also had a hardcoded font value the old did not. 

I also noticed some Codemirror elements are arranged differently. I left all this alone, I wouldn't consider it a bug and it looks better now anyway:
(old)
Screenshot 2024-09-03 at 9 20 51 AM
(new)
Screenshot 2024-09-03 at 9 20 46 AM

The resize nullpx nullpx message reported in #11701 is a known issue with the library https://github.com/rennzhang/codemirror-editor-vue3/issues/54

### Areas or cases that should be tested
'View as Yaml' and 'Edit as Yaml' pages
Create/edit a configmap with json values
Detail view of a resource with json annotations

### Screenshot/Video

(old)
Screenshot 2024-09-04 at 9 23 42 AM

(new)
Screenshot 2024-09-04 at 9 18 19 AM

(old)
Screenshot 2024-09-04 at 9 18 08 AM

(new)
Screenshot 2024-09-04 at 9 25 04 AM

(old)
Screenshot 2024-09-04 at 9 26 08 AM

(new)
Screenshot 2024-09-04 at 10 10 11 AM

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: shell/components/YamlEditor.vue [hunk 1]
```diff
@@ -103,7 +103,7 @@ export default {
         mode:            'yaml',
         lint:            !readOnly,
         lineNumbers:     !readOnly,
-        styleActiveLine: true,
```
Comment (mantis-toboggan-md) [inline shell/components/YamlEditor.vue:106]: Although we had this set to true previously, no styling was actually applied to active lines. So to keep parity with 2.9 styling, I disabled this prop

Comment (cnotv) [reply shell/components/YamlEditor.vue:106]: Crossed that as well, I'd set it as `false` but that's the default one looks like.

**Review by cnotv — APPROVED** [review]
LGTM

Screenshot 2024-09-18 at 14 55 37
Screenshot 2024-09-18 at 14 56 44
