### PR TITLE
Consolidate two project secret columns into one

### LINKED ISSUE #14892: Secrets list - visual bugs
**Setup**
- Rancher version:
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**

- Data should be the same for all namespaces, and there seems to be some outlier data types that go away after refreshing the page (maybe due to https://github.com/rancher/dashboard/issues/14791). 

- The kind column displays kubernetes.io for each secret, which seems unnecessary and brings visual pollution to the table.

- There's 2 columns: Created by Project Secret and Project Secret.  Project Secret column is empty for regular namespaces and is populated for the generated namespaces, which is a bug. See #14890. I suggest that we display the project name for each secret when they are created for a project or to remove the Project Secret column from the table. 

Image

Image

**To Reproduce**
1- Provision a cluster (any driver)
2- Access the downstream cluster after it's successfully created
3- Create a project under Cluster> Projects/Namespaces
2- Create 2 namespaces under this project
3- In the UI, go to Storage > Project Secrets
4- Add a Project-scoped secret (or more than 1) under this project
5- Go to the local cluster
6 - Also create Project Scoped Secrets, and add 2 namespaces for each project.
6- In the local cluster, Go to Storage > Secrets
7- Observe the bugs highlighted in this issue description

### PR DESCRIPTION
**Pull request by momesgin**
### Summary
Fixes #14892 

### Occurred changes and/or fixed issues
- Consolidated the "Created by Project Secret" and "Project Secret" columns in the Secrets list into a single "Origin" column.
- Added a new `SecretOrigin` formatter component to handle the display logic for the new column.
- The "Origin" column displays:
  - "Project Secret" for Project Scoped Secrets (with a tooltip showing the project and cluster).
  - "Via Project Secret" for secrets created by a Project Scoped Secret (with a tooltip showing the source secret and project).
- Added optional chaining to the project lookup in `shell/edit/secret/index.vue` to prevent potential runtime errors.

### Technical notes summary
- Replaced `SECRET_CLONE` and `SECRET_PROJECT_SCOPED` headers with `SECRET_ORIGIN` in `shell/config/table-headers.js` and `shell/list/secret.vue`.
- The new `SecretOrigin.vue` component handles fetching necessary project/cluster data for the tooltip if it's missing from the store.
- Removed the now unused `clusterAndProjectLabel` getter from `shell/models/secret.js`.
- Sorting for the new column is based on the `management.cattle.io/project-scoped-secret-copy` annotation.

### Areas or cases that should be tested
Make sure to enable this option "`Show dynamic Namespaces managed by Rancher (not intended for editing or deletion)`" in preferences to be able to see the PSS created from downstream clusters in the local's secrets list page.

- **Secrets List**:
  - Verify that standard secrets have an empty or dash indicator in the "Origin" column.
  - Verify that **Project Scoped Secrets** display "Project Secret" in the "Origin" column.
  - Verify that **Copied Secrets** (created by a Project Scoped Secret) display "Via Project Secret".
  - Hover over the values in the "Origin" column to ensure the tooltips display the correct project/cluster information.

### Areas which could experience regressions
- Secrets list table layout and sorting behaviour.
- Test sorting by the "Origin" column to ensure it behaves as before.
- Tooltip display for secrets with missing project/cluster metadata.

### Screenshot/Video

image

image

image

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes
- [x] The PR has been reviewed in terms of Accessibility
- [x] The PR has considered, and if applicable tested with, the three Global Roles `Admin`, `Standard User` and `User Base`

### CODE REVIEW

File: shell/list/secret.vue [hunk 1]
```diff
@@ -52,29 +50,37 @@ export default {
 
   async created() {
     this.canViewProjects = this.$store.getters[`${ STORE.MANAGEMENT }/schemaFor`](MANAGEMENT.PROJECT);
+
+    if (this.canViewProjects && this.currentCluster.isLocal) {
+      // this is needed to display the project name in the tooltip for project-scoped secrets
+      this.$store.dispatch(`${ STORE.MANAGEMENT }/findAll`, { type: MANAGEMENT.CLUSTER });
```
Comment (richard-cox) [inline shell/list/secret.vue]: This is a findAll, which we should avoid using for scaling reasons

File: shell/components/formatter/SecretName.vue [hunk 2]
```diff
@@ -0,0 +1,73 @@
...
+      type:    String,
+      default: ''
+    },
+    row: {
+      type:     Object,
+      required: true
+    },
+  },
+  computed: {
+    isProjectScoped() {
```
Comment (richard-cox) [inline shell/components/formatter/SecretName.vue]: isProjectScoped and isProjectSecretCopy are kinda pointless? they only save 4 chars and are each only used once

File: shell/list/secret.vue [hunk 3]
```diff
@@ -52,29 +50,37 @@ export default {
...
-      headers.push(SECRET_CLONE);
-      headersSSP.push(STEVE_SECRET_CLONE);
-      if (this.currentCluster.isLocal) {
-        // if the user is on the local cluster, add a column to let them know if it's a project scoped secret (from another cluster)
-        headers.push(SECRET_PROJECT_SCOPED);
-        headersSSP.push(SECRET_PROJECT_SCOPED);
+    const headers = this.$store.getters['type-map/headersFor'](this.schema, false) as TableColumn[];
+    const headersSSP = this.$store.getters['type-map/headersFor'](this.schema, true) as TableColumn[];
+
+    this.namespacedHeaders = headers.map((h) => {
```
Comment (richard-cox) [inline shell/list/secret.vue]: if this is always being added, it might as well replace the original name column

File: shell/models/secret.js [hunk 4]
```diff
@@ -550,23 +550,6 @@ export default class Secret extends SteveModel {
     return this.$rootGetters[`${ STORE.MANAGEMENT }/byId`](MANAGEMENT.PROJECT, `${ this.projectScopedClusterId }/${ this.projectScopedProjectId }`);
   }
 
-  get clusterAndProjectLabel() {
```
Comment (momesgin) [inline shell/models/secret.js:553]: this was not needed anymore

File: shell/config/pagination-table-headers.js [hunk 5]
```diff
@@ -89,7 +89,9 @@ export const STEVE_LIST_GROUPS = [{
   groupLabelKey: 'groupByLabel',
 }];
 
-export const STEVE_SECRET_CLONE = {
-  ...SECRET_CLONE,
+export const STEVE_SECRET_ORIGIN = {
+  ...SECRET_ORIGIN,
+  // We can't sort by the 'UI_PROJECT_SECRET' label (management.cattle.io/project-scoped-secret) due to backend limitations.
+  // So we sort by the 'UI_PROJECT_SECRET_COPY' annotation (management.cattle.io/project-scoped-secret-copy) which at least groups the copies.
   sort: `metadata.annotations[${ UI_PROJECT_SECRET_COPY }]`,
```
Comment (momesgin) [inline shell/config/pagination-table-headers.js]: I kept the previous sorting and added the comment above, I hope the comment makes sense.

File: shell/config/table-headers.js [hunk 6]
```diff
@@ -385,27 +385,19 @@ export const SECRET_DATA = {
...
+  tooltip:   'tableHeaders.secret.originTooltip',
+  formatter: 'SecretOrigin',
   // Cannot _sort_ upstream secrets by if they are cluster scoped
   // https://github.com/rancher/rancher/issues/51001
   // metadata.labels[management.cattle.io/project-scoped-secret] - covers both cluster scoped AND clones
   // metadata.annotations[management.cattle.io/project-scoped-secret-copy]
   // sort:     [`metadata.labels[${ UI_PROJECT_SECRET }]`, `metadata.annotations[${ UI_PROJECT_SECRET_COPY }]`],
-  search:   false,
+  // But we can sort by the 'UI_PROJECT_SECRET_COPY' annotation (management.cattle.io/project-scoped-secret-copy) which at least groups the copies.
+  sort:      `metadata.annotations."${ UI_PROJECT_SECRET_COPY }"`,
```
Comment (momesgin) [inline shell/config/table-headers.js]: I checked the sorting while having `ui-sql-cache` disabled, and it worked as before.

File: shell/assets/translations/en-us.yaml [hunk 7]
```diff
@@ -6968,10 +6975,8 @@ tableHeaders:
   selector: Selector
   secrets: Secrets
   secret:
-    project-clone: Created by Project Secret
-    project-clone-tooltip: Has a Project Scoped Secret created this Secret in this Namespace
-    project-scoped: Project Secret
-    project-scoped-tooltip: This Project Scoped Secret will create matching Secrets in the Namespaces it contains
+    origin: Origin
+    originTooltip: "Shows if a secret has been created or managed via another Project Scoped Secret. Read the documentation to learn more about this Rancher concept"
```
Comment (richard-cox) [inline shell/assets/translations/en-us.yaml]:
```suggestion
    originTooltip: "Shows if a secret has been created or managed via another Project Scoped Secret. Read the Project Scoped Secret documentation to learn more about this Rancher concept"
```

Comment (richard-cox) [reply shell/assets/translations/en-us.yaml]: I had wondered if we should use the vendor tag instead of `Rancher`, but we need to steer them at our docs

File: shell/config/pagination-table-headers.js (hunk 5 above)
Comment (richard-cox) [reply shell/config/pagination-table-headers.js]: ideally this would be both, but you're right we're blocked on the backend. they need to index the other field and i've made a request to do so (https://github.com/rancher/rancher/issues/53927).

this would then avoid

Image

it would be nice for the first click on sort to bring the rows to the top though, so for now would suggest...

```
export const STEVE_SECRET_ORIGIN = {
  ...SECRET_ORIGIN,
  sort: `metadata.annotations[${ UI_PROJECT_SECRET_COPY }]:desc`,
  // This should be updated to below once https://github.com/rancher/rancher/issues/53927 has been resolved
  // sort: [`metadata.annotations[${ UI_PROJECT_SECRET_COPY }]:desc`, `metadata.annotations[${ UI_PROJECT_SECRET }]`],
};
```

(note the `:desc` at the end of the column)

File: shell/config/table-headers.js (hunk 6 above)
Comment (richard-cox) [reply shell/config/table-headers.js]: i think we can just leave this one as is (regarding https://github.com/rancher/dashboard/pull/16642/changes#r2858717935). in theory ssp will be on permanently soon
