### PR TITLE
checks to see if membership editor is project and adds a project filter

### LINKED ISSUE #8574: Cannot load 'Members' page of Project in Rancher UI
Internal reference: SURE-6071
Reported in 2.6.8

Issue description:
When attempting to view the 'Members' page of a project in Rancher, the page does not load, and one of two problems occurs:
- Either the load seems to 'time out' fairly quickly and no members are displayed
- or the page enters a continuous loop of calling the `projectroletemplatebindings` endpoint and never loads.
This is impacting users as they say that their projects have been created incorrectly as there are no members.

Sample environment: ~1500 users and ~1500 projects across 50+ clusters, SSD disks, Okta via Azure AD

Happening in Vue (new UI) not Ember (old UI) -- Ember brings up a members page quickly across multiple projects & clusters. 

Troubleshooting steps and data available upon request.

### PR DESCRIPTION
**Pull request by Sean-McQ**
### Summary
Fixes #8574 
Progresses #9341

This looks to be primarily a performance issue wherein loading a project edit page with a 'members' list (actually the `projectRoleTemplateBindings` resource) can either simply fail or get stuck in a repeating pattern at scale due to the way that `projectRoleTemplateBindings` scales across projects and clusters. Adding a project filter to the `projectRoleTemplateBindings` should cut down on the cost of this API call significantly.

### Occurred changes and/or fixed issues
The membership editor will now check if it's type is set to Norman's `projectRoleTemplateBindings` and will append a `projectId` field (Norman specific, Steve's `management.cattle.io.projectRoleTemplateBindings` uses `projectName` but is not used on this page.

While not strictly required by this PR, changes have been added to better support filtering and Sorting for Steve.

Changed out `uriEncodeComponent` for `uriEncode` since `uriEncodeComponent` was encoding characters that it shouldn't such as ":". Tested thoroughly and all existing tests still pass. New tests added to cover Steve specific url options.

### Technical notes summary
Please refer to the ReadMe on https://github.com/rancher/steve to verify URL options correctness for Steve. Specific Correctness of the "projectId" field for Norman's `projectRoleTemplateBindings` can be found on the collection itself under the `filters` key and the API call can also always be called directly or inspected in the network tab of the browser's developer tools to validate correctness. The actual spec used for Norman's query options can be found [here](https://github.com/rancher/api-spec/blob/master/specification.md#filtering).

### Areas or cases that should be tested
This is primarily a performance enhancement, if you'd like to actually see the specific performance impact, you'll want to create a rancher instance with a downstream cluster using ~400 projects and ~150 users on a single-node rancher instance but for the most part what is needed is just simple functional validation. The members list does load, it shows the correct members, no broken API calls, etc...

### Areas which could experience regressions
No Steve API calls were using filters and/or sorting in them so nothing should break there, all existing unit tests on urlOptions still pass so I'm not assuming any regressions there either.

### CODE REVIEW

**Review by aalves08 — COMMENTED** [review]
@Sean-McQ changes seem to be "trivial" but I don't have any info on how to reproduce this and also I don't know about this `filter` option on the `findAll` 😛 . I would say that if @mantis-toboggan-md is okay with this change, I'm also okay with it.

**Comment by Sean-McQ** [comment]
Changed out uriEncodeComponent for uriEncode since uriEncodeComponent was encoding characters that it shouldn't such as ":". Tested thoroughly and all existing tests still pass. While I was in there I also addressed the fact that filters and sorting criteria for Steve requests wouldn't be formatted correctly for that API so I added in some code to support that. New tests added to cover Steve specific url options. There's still quite a bit of functionality we're not using in Steve's URL options but that's covered under #9341

File: shell/components/form/Members/MembershipEditor.vue [hunk 1]
```diff
@@ -56,8 +56,13 @@ export default {
   },
 
   async fetch() {
+    const roleBindingRequestParams = { type: this.type, opt: { force: true } };
+
+    if (this.type === NORMAN.PROJECT_ROLE_TEMPLATE_BINDING) {
+      Object.assign(roleBindingRequestParams, { opt: { filter: { projectId: this.parentId.split('/').join(':') } } });
```
Comment (aalves08) [inline shell/components/form/Members/MembershipEditor.vue:62]: Is there any chance of `this.parentId` might be `undefined`? If so then `this.parentId.split` would throw an error. (optional chaining)

File: shell/plugins/steve/__tests__/getters.spec.ts [hunk 2]
```diff
@@ -86,8 +92,17 @@ describe('steve: getters', () => {
...
+    });
     it('returns a string with a sorting criteria if the sort option is provided and an order if sortOrder is provided', () => {
       expect(urlOptionsGetter('foo', { sortBy: 'bar', sortOrder: 'baz' })).toBe('foo?sort=bar&order=baz');
     });
+    it('returns a string with a sorting criteria formatted for steve if the sort option is provided and an order if sortOrder is provided and the url starts with "/v1"', () => {
+      expect(urlOptionsGetter('/v1/foo', { sortBy: 'bar', sortOrder: 'baz' })).toBe('/v1/foo?exclude=metadata.managedFields&sort=bar');
+    });
+    it('returns a string with a sorting criteria formatted for steve if the sort option is provided and an order if sortOrder is "desc" and the url starts with "/v1"', () => {
+      expect(urlOptionsGetter('/v1/foo', { sortBy: 'bar', sortOrder: 'desc' })).toBe('/v1/foo?exclude=metadata.managedFields&sort=-bar');
+    });
```
Comment (aalves08) [inline shell/plugins/steve/__tests__/getters.spec.ts:106]: Very interesting all of these options! never knew about these. Nice! 🤜

**Review by aalves08 — COMMENTED** [review]
just a small comment, but otherwise looks good. Still need to test it. Once you have that system ready, let me know 🙏

File: shell/components/form/Members/MembershipEditor.vue (hunk 1 above)
Comment (Sean-McQ) [reply shell/components/form/Members/MembershipEditor.vue:62]: It shouldn't be possible for it to be undefined or null while the type is `NORMAN.PROJECT_ROLE_TEMPLATE_BINDING` since the route requires it but it's trivial to add code to ensure that that's so prior to running so I'll do that.

File: shell/plugins/steve/__tests__/getters.spec.ts (hunk 2 above)
Comment (Sean-McQ) [reply shell/plugins/steve/__tests__/getters.spec.ts:106]: Thank @cmurphy, she gave us all sorts of goodies in Steve!

**Comment by aalves08** [comment]
All good @Sean-McQ ! 🚢 it

**Review by aalves08 — APPROVED** [review]
LGTM!
