### PR TITLE
Ensure `too old` messages for watches in individual resources are handled correctly

### LINKED ISSUE #10540: Steve socket is spammed on fresh visit to a resource detail page
We should tackle this after fix for https://github.com/rancher/rancher/issues/41809 has merged

**Setup**
- Rancher version: 2.7.x

**Describe the bug**

After visiting by url / refreshing on an oldish steve based resource's detail page the steve socket gets spammed with messages.

This probably applies to the resource's edit page as well.

- Very roughly we fetch resources. That response contains a `revision`. We watch for changes for that set of resource over web socket using the revision as a starting point
- If that `revision` is too old we should get a resource.error `too old` message
- The UI then knows to make a fresh request for resources which will have the latest changes and the current reviewed
- There were scenarios where the `too old` message was not provided and will be / has been fixed via https://github.com/rancher/rancher/issues/41809
  - Socket spamming was due to a resource.stop --> resource.start --> resource.stop --> resource.start forever cycle
  - Fix means the cycle does not occurr resource.stop & resource.error 'too old' --> http request --> resource.start 
- This revealed another issue related to spamming sockets to do with `too old` handling
- With the fix above fetched / watching resources is fine, however fetching / watching a single resource is not
  - Fetch single resource & use revision from within to watch (note - not the current system revision) --> resource.start with old revision --> resource stop & resource.error `too old` --> http request for single resource & use revision from within forever cycle
  - There's also a bug where the namespace for the single resource http request isn't passed through to the url construction, so the request is borked anyway

**To Reproduce**
- Bring up a system with the fix from https://github.com/rancher/rancher/issues/41809
- Navigate to a configmap page that's pretty old
- Bring up dev tools --> network tab
- Refresh the page
- View the socket messages for the ds cluster's socket connection

**Result**
- LOTS of `too old` messages as the ui tries to watch with the old revision AND http requests with a bad url (no ns)
- image

**Expected Result**
- After the first resource.error message is received the UI should make a new http request to fetch the resource and then send a watch message with no revision.
- There should not be any repeat cycles of this (for example no spammed green lines )
- image

### PR DESCRIPTION
**Pull request by richard-cox**
> Requires v2.9-head at or passed 793118f (from late 2024-03-07)

### Summary
Fixes #10540

### Occurred changes and/or fixed issues
- See issue description for detail. Description on how sockets work in https://github.com/rancher/rancher/issues/41809#issuecomment-1584899188
- Ensure that watches on single resources that fail with `too old` fetch the latest version of the resource and re-watch without a revision
- There were three bugs
  - core issue - the re-watch used the same `too old` revision from the resource, resulting in the `too old` message again ad nauseam 
  - the http request to fetch the latest version failed for namespaced resources
  - the inError state is fetched via a key constructed of id, namespace and selector, however the inError state from resource.error messages only used the key... which meant for watches that used id or selector the watches were never classed as in error

### Technical notes summary
- The first bug needed the plumbing for namespace to be fixed.... though it's not actually honoured via the watch (it just watches all resources with the same id
- ~TODO: the fix for the second bug involves NOT sending a revision. this currently mean all changes are replayed over socket instead of just changes occurring after the watch~ Not sending a revision means we get the latest version of the resource in a resource.create event (it's not the original resource.create followed by everything else)

### Areas or cases that should be tested
As per repo steps

### Areas which could experience regressions
- changes to a resource following a refresh on the details page not showing up correctly

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: shell/plugins/steve/getters.js [hunk 1]
```diff
@@ -128,10 +128,30 @@ export default {
...
+      // Update path to include `namespace`, but take into account
+      // - if there is an id
+      // - if there are query params
 
-      url = `${ parts.join('/') }/${ opt.namespaced }`;
+      // Construct a url so query params / fragments are avoided
+      const urlObj = new URL(url);
+      const path = urlObj.pathname;
+
+      if (!!path?.length && path[path.length - 1] === '/') {
```
Comment (nwmac) [inline shell/plugins/steve/getters.js:140]: Could have used `endsWith`

**Review by nwmac — APPROVED** [review]
