### PR TITLE
Fix masthead's create title for project secrets

### LINKED ISSUE #14779: Project Scoped Secrets: creating a new secret shows the `secret` title and links to `secret` list
**Setup**
- Rancher version: v2.12.0 (dev of)

**Describe the bug**

**To Reproduce**
- creating a new secret shows the `secret` title and links to `secret` list

**Result**

**Expected Result**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by momesgin**
### Summary
Fixes #14779 

### Occurred changes and/or fixed issues
- Fixed an issue where a wrong title was displayed on the create page for project secrets.

### Technical notes summary
- The `ResourceDetail` component was remapping `projectsecret` to `secret` (via `options.resource` configured in `shell/config/product/explorer.js`) *before* the Masthead component received the resource type. This caused the Masthead to look up the label for `secret`.
- I updated `ResourceDetail/index.vue` to capture the `mastheadResourceType` (specifically for `projectsecret`) from the route *before* this remapping occurs and pass it explicitly to the `<Masthead>` component.
- I updated `Masthead/legacy.vue` to handle cases where a schema definition is missing for the provided resource ID (which happens for `projectsecret`). It now returns a fallback object `{ id: this.resource }` in the `schema` computed property, ensuring that `labelFor` and translation lookups function correctly.
- Added unit tests.

### Areas or cases that should be tested
- **Create Project Secret:** Navigate to **Explorer > Storage > Project Secrets**. Click "Create". Verify the page title says "Project Secret: Create" and clicking on it redirects you the Project Secrets list page.
- **Edit Project Secret:** Edit an existing Project Secret. Verify the page title says "Edit Project Secret" (or just "Project Secret: <name>"). Note: The Edit/View pages for downstream cluster's PSS is broken, there's an open PR to fix it, but you can test this on the local cluster.
- **Standard Secrets:** Navigate to **Explorer > Storage > Secrets**. Create and Edit standard secrets. Verify the titles remain "Secret: Create" and clicking on it redirects you the Secrets list page.

### Areas which could experience regressions
- The `schema` computed property in `legacy.vue` is used by other parts of the Masthead. While the fix targets missing schemas, verify that standard resources with valid schemas still load their full schema correctly and that header renders properly.

### Screenshot/Video

https://github.com/user-attachments/assets/b6dc8cb8-faff-420a-a454-bdd71d1870a9

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes
- [x] The PR has been reviewed in terms of Accessibility
- [x] The PR has considered, and if applicable tested with, the three Global Roles `Admin`, `Standard User` and `User Base`

### CODE REVIEW

File: shell/components/ResourceDetail/Masthead/legacy.vue [hunk 1]
```diff
@@ -122,8 +122,16 @@ export default {
 
     schema() {
       const inStore = this.storeOverride || this.$store.getters['currentStore'](this.resource);
+      const schema = this.$store.getters[`${ inStore }/schemaFor`]( this.resource );
 
-      return this.$store.getters[`${ inStore }/schemaFor`]( this.resource );
+      if (!schema && this.resource) {
+        // For virtual types (like projectsecret) or cases where the schema isn't loaded yet,
```
Comment (richard-cox) [inline shell/components/ResourceDetail/Masthead/legacy.vue]: This doesn't feel right, all schemas for all stores should be settled before we reach this page + component.

The PR description says the product config hasn't completed by the time the page is shown, are we 100% sure? If so it feels like the fix should be to ensure the blocking mechanism there works

File: shell/components/ResourceDetail/index.vue [hunk 2]
```diff
@@ -94,6 +94,12 @@ export default {
     const params = route.params;
     let resourceType = this.resourceOverride || params.resource;
 
+    // 'projectsecret' is a virtual type configured in 'shell/config/product/explorer.js' using
+    // configureType(..., { resource: SECRET }). It maps to 'secret' for reuse, but we must
+    // explicitly capture the original ID here so the Masthead displays the specific
+    // "Project Secret" title instead of the generic "Secret".
+    const mastheadResourceType = resourceType === VIRTUAL_TYPES.PROJECT_SECRETS ? resourceType : null;
```
Comment (richard-cox) [inline shell/components/ResourceDetail/index.vue]: We shouldn't be putting resource specific workarounds into generic components

File: shell/components/ResourceDetail/Masthead/legacy.vue (hunk 1 above)
Comment (momesgin) [reply shell/components/ResourceDetail/Masthead/legacy.vue]: I should have made this PR in a draft mode since I wanted to ask @codyrancher 's help on this since he's been recently focused on working on the resource pages.

File: shell/components/ResourceDetail/index.vue (hunk 2 above)
Comment (momesgin) [reply shell/components/ResourceDetail/index.vue]: I wanted to limit this to only project secrets for the sake of avoiding regressions. I think based on your previous feedback I should rethink the whole solution altogether.

File: shell/components/ResourceDetail/Masthead/legacy.vue (hunk 1 above)
Comment (richard-cox) [reply shell/components/ResourceDetail/Masthead/legacy.vue]: ah sorry for jumping the gun!

just send me a ping when it's ready

Comment (momesgin) [reply shell/components/ResourceDetail/Masthead/legacy.vue]: It was my mistake, thanks for the feedback.

Sure thing, will ping you.

**Comment by codyrancher** [comment]
I guess I have some points here after digging around:

1. I think the change you're proposing here is probably the most minimally invasive so I think we could go forward with it.
2. Long term fix I believe would be
    - Continue decoupling or deconflating concepts.
      - Let's stop using say the ResourceDetail component to render ResourceCreate pages. Both could be composed of some shared components.
      - Also, I don't think `dashboard/shell/pages/c/_cluster/explorer/projectsecret.vue` is ever actually used even though that would've been closer to the direction I would've liked projectsecrets to go.
    - When we want to create special cases, create a new page with a specific route and use the simpler composable components. 
      - Adding support for all of our special cases mucks up the generic components. The new detail page masthead was originally of the form `<Masthead title="title" location="location" subtitle="subtitle" bannerProps="bannerProps" metadatProps="metadataProps" />` but then we had to support all the override behavior which makes things more rigid again.

**Comment by momesgin** [comment]
> I guess I have some points here after digging around:
> 
> 1. I think the change you're proposing here is probably the most minimally invasive so I think we could go forward with it.
> 2. Long term fix I believe would be
>    
>    * Continue decoupling or deconflating concepts.
>      
>      * Let's stop using say the ResourceDetail component to render ResourceCreate pages. Both could be composed of some shared components.
>      * Also, I don't think `dashboard/shell/pages/c/_cluster/explorer/projectsecret.vue` is ever actually used even though that would've been closer to the direction I would've liked projectsecrets to go.
>    * When we want to create special cases, create a new page with a specific route and use the simpler composable components.
>      
>      * Adding support for all of our special cases mucks up the generic components. The new detail page masthead was originally of the form `<Masthead title="title" location="location" subtitle="subtitle" bannerProps="bannerProps" metadatProps="metadataProps" />` but then we had to support all the override behavior which makes things more rigid again.

Thank you @codyrancher 🙏 @richard-cox this should be ready for your re-review.

**Comment by momesgin** [comment]
> Spent some time looking at this today and the proposed fixes are workarounds for a process already in place... which isn't working correctly.
> 
> For the create experience the page gets it's title from `displayName` in shell/components/ResourceDetail/Masthead/legacy.vue `parent` getter. That checks `value.parentNameOverride` before it checks schema things.
> 
> For secrets the model does contain a parentNameOverride. It checks if the secret has a PSS label and returns the PSS text instead of Secret.
> 
> The bug is that the `parent` getter is evaluated and checks value.parentNameOverrride before the shell/edit/secret/index.vue $fetch runs ... which updates the value's labels. So initially it's incorrect. Once fetch runs and sets the label the `parent` getter doesn't run again to provide the correct value.
> 
> There's some reactivity missing somewhere. `parent` depends on `value.parentNameOverrride` depends on isProjectScopedRelated depends on labels. When labels is updated `parent` should re-evaluate

@richard-cox I reverted all the changes and tried using the query param for project secrets in the URL to set the parent overrides. I haven't found any issues so far, but will continue checking. Please let me know what you think.

File: shell/models/secret.js [hunk 3]
```diff
@@ -611,6 +616,17 @@ export default class Secret extends SteveModel {
...
+        params: {
+          product:  this.$rootGetters['productId'],
+          cluster:  this.$rootGetters['clusterId'],
+          resource: VIRTUAL_TYPES.PROJECT_SECRETS,
+        }
+      };
+    }
+
     if (!this.isProjectScoped) {
       return super.parentNameOverride;
```
[the remark this answers is not in the document]
Comment (momesgin) [reply shell/models/secret.js]: done

File: shell/models/secret.js [hunk 4]
```diff
@@ -611,6 +616,17 @@ export default class Secret extends SteveModel {
   }
```
[the remark this answers is not in the document]
Comment (momesgin) [reply shell/models/secret.js:614]: done

**Comment by richard-cox** [comment]
I had a quick look with the minor tweaks we discussed yesterday and it looks like it works.

```
@@ -494,11 +494,16 @@ export default class Secret extends SteveModel {
 
   /**
    * is this a project scoped secret
    */
   get isProjectScoped() {
-    return !!this.metadata.labels?.[UI_PROJECT_SECRET] && !this.isProjectSecretCopy && this.$rootGetters['isRancher'];
+    /**
+     * is this a project scoped secret .... or also a cloned project scoped secret
+     */
+    const isProjectScopedRelated = !!this.metadata.labels?.[UI_PROJECT_SECRET];
+
+    return isProjectScopedRelated && !this.isProjectSecretCopy && this.$rootGetters['isRancher'];
   }
 
   get projectScopedClusterId() {
     if (!this.projectScopedProjectId) {
       return undefined;
@@ -580,22 +585,22 @@ export default class Secret extends SteveModel {
 
     return this._detailLocation;
   }
 
   get listLocation() {
-    if (!this.isProjectScoped) {
-      return super.listLocation;
+    if (this.hasProjectScopedUrlQueryParam || this.isProjectScoped) {
+      return {
+        name:   'c-cluster-product-resource',
+        params: {
+          product:  this.$rootGetters['productId'],
+          cluster:  this.$rootGetters['clusterId'],
+          resource: VIRTUAL_TYPES.PROJECT_SECRETS,
+        }
+      };
     }
 
-    return {
-      name:   'c-cluster-product-resource',
-      params: {
-        product:  this.$rootGetters['productId'],
-        cluster:  this.$rootGetters['clusterId'],
-        resource: VIRTUAL_TYPES.PROJECT_SECRETS,
-      }
-    };
+    return super.listLocation;
   }
 
   get hasProjectScopedUrlQueryParam() {
     return this.currentRoute()?.query?.[SECRET_SCOPE] === SECRET_QUERY_PARAMS.PROJECT_SCOPED;
   }
@@ -608,18 +613,11 @@ export default class Secret extends SteveModel {
     return super.parentNameOverride;
   }
 
   get parentLocationOverride() {
     if (this.hasProjectScopedUrlQueryParam || this.isProjectScoped) {
-      return {
-        name:   'c-cluster-product-resource',
-        params: {
-          product:  this.$rootGetters['productId'],
-          cluster:  this.$rootGetters['clusterId'],
-          resource: VIRTUAL_TYPES.PROJECT_SECRETS,
-        }
-      };
+      return this.listLocation;
     }
 
     return super.parentLocationOverride;
   }
```

**Comment by momesgin** [comment]
> I had a quick look with the minor tweaks we discussed yesterday and it looks like it works.
> 
> ```
> @@ -494,11 +494,16 @@ export default class Secret extends SteveModel {
>  
>    /**
>     * is this a project scoped secret
>     */
>    get isProjectScoped() {
> -    return !!this.metadata.labels?.[UI_PROJECT_SECRET] && !this.isProjectSecretCopy && this.$rootGetters['isRancher'];
> +    /**
> +     * is this a project scoped secret .... or also a cloned project scoped secret
> +     */
> +    const isProjectScopedRelated = !!this.metadata.labels?.[UI_PROJECT_SECRET];
> +
> +    return isProjectScopedRelated && !this.isProjectSecretCopy && this.$rootGetters['isRancher'];
>    }
>  
>    get projectScopedClusterId() {
>      if (!this.projectScopedProjectId) {
>        return undefined;
> @@ -580,22 +585,22 @@ export default class Secret extends SteveModel {
>  
>      return this._detailLocation;
>    }
>  
>    get listLocation() {
> -    if (!this.isProjectScoped) {
> -      return super.listLocation;
> +    if (this.hasProjectScopedUrlQueryParam || this.isProjectScoped) {
> +      return {
> +        name:   'c-cluster-product-resource',
> +        params: {
> +          product:  this.$rootGetters['productId'],
> +          cluster:  this.$rootGetters['clusterId'],
> +          resource: VIRTUAL_TYPES.PROJECT_SECRETS,
> +        }
> +      };
>      }
>  
> -    return {
> -      name:   'c-cluster-product-resource',
> -      params: {
> -        product:  this.$rootGetters['productId'],
> -        cluster:  this.$rootGetters['clusterId'],
> -        resource: VIRTUAL_TYPES.PROJECT_SECRETS,
> -      }
> -    };
> +    return super.listLocation;
>    }
>  
>    get hasProjectScopedUrlQueryParam() {
>      return this.currentRoute()?.query?.[SECRET_SCOPE] === SECRET_QUERY_PARAMS.PROJECT_SCOPED;
>    }
> @@ -608,18 +613,11 @@ export default class Secret extends SteveModel {
>      return super.parentNameOverride;
>    }
>  
>    get parentLocationOverride() {
>      if (this.hasProjectScopedUrlQueryParam || this.isProjectScoped) {
> -      return {
> -        name:   'c-cluster-product-resource',
> -        params: {
> -          product:  this.$rootGetters['productId'],
> -          cluster:  this.$rootGetters['clusterId'],
> -          resource: VIRTUAL_TYPES.PROJECT_SECRETS,
> -        }
> -      };
> +      return this.listLocation;
>      }
>  
>      return super.parentLocationOverride;
>    }
> ```

@richard-cox thanks so much for the review and the tweak for the `listLocation` 🙏
