### PR TITLE
Fix KeyValue behaviour when parent component updates value prop

### LINKED ISSUE #10587: KeyValue component doesn't update when its parent component changes its value prop
Found as part of rancher/dashboard#8966

The KeyValue component does not re-calculate its display 'rows' when asMap is true (KeyValue's `value` is an object). If the value changes in the parent component, the KeyValue component must be re-rendered to display that change.

### PR DESCRIPTION
**Pull request by mantis-toboggan-md**
### Summary
Fixes #10587

### Occurred changes and/or fixed issues
This PR updates keyvalue so that the component accurately reflects changes to its value prop made by the parent component. This PR was found as part of https://github.com/rancher/dashboard/pull/10581. I ended up adding test code to re-create the bug outside of that PR: https://github.com/rancher/dashboard/pull/10643/commits/48b3e36538f76d51c0378218a00d2d38c1fb87da

### Technical notes summary
KeyValue accepts a `value` prop and emits `input` events to update it, so that it works with `v-model`. When empty rows are added to KeyValue the component does _not_ include these in its `value` updates. Consequently KeyValue needs another property to track the combination of `value` + empty rows locally - `rows`. `rows` is calculated when the component is initialized. If the parent component updates `value`, it is not reflected in KeyValue because `rows` has not re-computed. The PR adds a watcher to re-compute rows when the parent component changes the value. We detect the difference between the parent component introducing the change to `value` and the change having come from the user interacting with KeyValue by tracking the last `value` KeyValue emitted.

### Areas or cases that should be tested
* adding new rows with the keyvalue add button
* adding rows programatically (see EKS launch templates)
* removing rows
* uploading data by file or copy-paste
* editing rows - specifically verifying that the getRows method isn't running excessively

### Areas which could experience regressions
This PR alters code added to fix https://github.com/rancher/dashboard/issues/7073

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: shell/components/form/KeyValue.vue [hunk 1]
```diff
@@ -303,14 +303,28 @@ export default {
...
+    value: {
+      deep: true,
+      handler(neu, old) {
+        this.valuePropChanged(neu, old);
       }
     }
   },
   methods: {
+    valuePropChanged(neu, old) {
+      if (JSON.stringify(neu) !== JSON.stringify(this.lastUpdated)) {
```
Comment (codyrancher) [inline shell/components/form/KeyValue.vue:323]: I'm a little concerned that this could be slow, By any chance would loadash isEqual be faster? Probably fine to go forward anyway.

**Review by codyrancher — DISMISSED** [review]
It's amazing how many props this component has.

**Review by codyrancher — APPROVED** [review]

**Comment by richard-cox** [comment]
@mantis-toboggan-md  This PR and the linked issue have no milestone
