### PR TITLE
Explicitly pass `undefined` when closing MoveNamespaceDialog.vue

### LINKED ISSUE #14392: a11y: Projects/Namespaces: 'Move' dropdown item is unresponsive to click
**Setup**
- Rancher version: v2.12
- Rancher UI Extensions:
- Browser type & version: Chrome, FF

**Describe the bug**
'Move' dropdown item is unresponsive to click. 

**To Reproduce**
1. go to Projects/Namespaces page
2. toggle Flat list
3. open action menu for any NS within the sortable table
4. click Move
5. click Cancel
6. open action menu again 
7. click Move

**Result**
'Move' dropdown item is unresponsive to click. 

**Expected Result**
'Move' dropdown item is responsive to click. 

**Screenshots**

https://github.com/user-attachments/assets/4490d3ea-2b6f-4114-aabc-f70307b9782f

**Additional context**
Discovered while testing: https://github.com/rancher/dashboard/issues/13938

### PR DESCRIPTION
**Pull request by rak-phillip**
### Summary
This explicitly sets data to `undefined` for when cancelling `MoveNamespaceDialog.vue` to fix an issue with the cancel button preventing the modal from raising again. 

Fixes #14392

### Occurred changes and/or fixed issues

- pass undefined to close event in `MoveNamespaceDialog.vue`

### Technical notes summary

The `click` event was implicitly passed to close when clicking on the cancel button. This can cause issues in `togglePromptModal` in `shell/store/action-menu.js`. `data` is defined, but it doesn't have a value for `performCallback`; `showModal` will default to true, but the modal will no longer and the `modalData` will become malformed. Making sure that we don't provided any data resolves the issues.

### Areas or cases that should be tested

See issue for details.

### Areas which could experience regressions

This should only affect the `MoveNamespaceDialog`.

### Screenshot/Video

NA

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes
- [x] The PR has been reviewed in terms of Accessibility

### CODE REVIEW

File: shell/dialog/MoveNamespaceDialog.vue [hunk 1]
```diff
@@ -63,8 +63,8 @@ export default {
   },
 
   methods: {
-    close(data) {
-      this.$emit('close', data);
+    close() {
+      this.$emit('close');
```
Comment (rak-phillip) [inline shell/dialog/MoveNamespaceDialog.vue:67]: @aalves08 I'm trying to pinpoint _why_ this emitted close with data. `MoveNamespaceDialog` is the only dialog that has this behavior. Do you recall why this is or is it an artifact of some implementation from before we refactored the modals/drodown menus?

Comment (aalves08) [reply shell/dialog/MoveNamespaceDialog.vue:67]: Because it's what triggers a callback, as per https://github.com/rancher/dashboard/pull/14187

The main aspect we lost with modals being centralised in the `PromptModal` mechanism was the ability to perform callbacks when it's being closed because the context was no longer the component itself. 

I created this store-based mechanism to handle that. This shouldn't be removed, btw

Comment (rak-phillip) [reply shell/dialog/MoveNamespaceDialog.vue]: So it sounds like there could be something associated with the callback that can is preventing the modal from invoking multiple times? I think that I will take a closer look at the callback mechanism to see if we can address the issue closer to the root cause.

**Comment by rak-phillip** [comment]
@aalves08 this is ready for another review

**Review by aalves08 — APPROVED** [review]
Tested and LGTM! Thanks for addressing this @rak-phillip 🙇 🙇 🙇 🙇
