### PR TITLE
Fleet allow encoded whitespaces in gitRepo url field

### LINKED ISSUE #14278: Fleet Cannot create gitrepos that contain spaces on the repo url
Internal Ref [ SURE-10157 ]

**Setup**
- Rancher version: 2.11.1
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**

The Rancher UI now does not allow for the creating of the GitRepos if there is a space in the URL (even trying with %20). The next button is greyed out as Url validation fails.

**Expected Result**

It should be possible to add a GitRepo containing encoded white spaces.

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by torchiaf**
### Summary
Fixes #14278

### Technical notes summary

We are changing the `gitRepository` validation rule to accept `%20` encoded white spaces.
We are not going to use a more complex regex to avoid performance issues.

### Areas or cases that should be tested

Fleet -> GitRepo create

- Go to Fleet -> GitRepos -> Create
- Add spaces in the url field:
  - `https://github.com/rancher/dashbo%20ard/` ok
  - `https://github.com/rancher/da%20shbo%20ard/` ok
  - `https://github.com/rancher/dashbo   ard/` ko

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: shell/utils/validators/formRules/index.ts [hunk 1]
```diff
@@ -170,7 +170,18 @@ export default function(
 
   const url: Validator = (val: string) => val && !isUrl(val) ? t('validation.setting.serverUrl.url') : undefined;
 
-  const gitRepository: Validator = (val: string) => val && !/^((http|git|ssh|http(s)|file|\/?)|(git@[\w\.]+))(:(\/\/)?)([\w\.@\:\/\-]+)([\d\/\w.-]+?)(.git){0,1}(\/)?$/gm.test(val) ? t('validation.git.repository') : undefined;
+  const gitRepository: Validator = (url: string) => {
```
Comment (richard-cox) [inline shell/utils/validators/formRules/index.ts:173]: This could be simplified by just removing the %20 chars from `url` up front. 

Positives: It's a lot cleaner and a smidge quicker
Negatives: encoded whitespace char in schema, host, etc would be allowed 

Another option would be to allow `%` in the capture group `([\w\.@\:\/\-]+)`, though that applies to the host as well as path and doesn't check for digits afterwards. Maybe the worst of the three.

We need to come back and visit this anyway (to only accept encoded chars path and later, and is a file a valid git url?)

Comment (torchiaf) [reply shell/utils/validators/formRules/index.ts:173]: Yes, here I decided to test the two chunks of URL separately to avoid accepting the %20 in the protocol.
The regex is generic, the `file` would be for URL scheme that refers to a file in local machine, definitely not Fleet usage, it can be removed.
I would keep it like this and improve it later.

Comment (richard-cox) [reply shell/utils/validators/formRules/index.ts:173]: My reasoning was this solution is more complex and possibly unsafe, which isn't good for a temporary quick fix.

It looks like

`!urlPart2` - is it JUST part1 (part2 missing)
`url === urlPart2` - is it JUST part2 (part1 missing)
`regexPart2.test` - is part2 valid

I've given it a test and bar the fix it does look like it works. 

Can you create an issue to reduce complexity and fix the issue of the white space in the host part of the url?

FWIW these invalid scenarios fail in both this PR and our current code. If we're looking at fixing this properly we should also cover them
`https://https://`
`http:/ww.abc.com`, `http:ww.abc.com`
`git@github.com:a/`

**Review by richard-cox — APPROVED** [review]
See comment for follow on work

File: shell/utils/validators/formRules/index.ts (hunk 1 above)
Comment (torchiaf) [reply shell/utils/validators/formRules/index.ts:173]: part1 (the scheme) is tested by `const urlPart2 = url.replaceAll(regexPart1, '');` + `url === urlPart2` . If both are verified it means part1 fails on scheme validation via regexPart1 regex.

Nevertheless, I agree in revisiting the validation to reduce the complexity and also because your test cases failed with version in master, so definitely to improve.

I'm meging current PR and creating the new issue.
