### PR TITLE
Handle charts zero date

### LINKED ISSUE #14819: Broken date for the apps from OCI repositories
**Setup**
- Rancher version:
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**

**To Reproduce**

1. Add an OCI repository e.g. `oci://registry-1.docker.io/bitnamicharts/redis`
2. Go to Apps/Charts page
3. Filter the result by only displaying apps from the repo you added
4. Check the date on the app card

**Result**

A broken date is displayed(e.g. `Dec 31, -0815`)

**Expected Result**

We should display `n/a` with a tooltip: `Last updated date is not available for this chart`.

**Screenshots**

Image

**Additional context**

### LINKED ISSUE #15124: Chart Detail Page - Update tooltip message
**To Reproduce**

Add an OCI repo like `oci://registry-1.docker.io/bitnamicharts/redis` then go to the detail page for that chart

**Result**
The tooltip says "The info is missing"

**Expected Result**
The tooltip should say "No date available for this chart version"

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by momesgin**
### Summary
Fixes #14819 
Fixes #15124 

### Technical notes summary

- Check for `ZERO_TIME` in `shell/models/chart.js` when generating `cardContent`
- Updated `AppChartCardSubHeader.vue` to display a tooltip for when the date is missing
- Unit tests

### Areas or cases that should be tested

Reproduce steps on the issue
### Areas which could experience regressions

Check if cards display the date properly from both oci and non-oci repositories
### Screenshot/Video

Charts page:
image
Chart detail page:
image

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes
- [x] The PR has been reviewed in terms of Accessibility

### CODE REVIEW

File: shell/models/chart.js [hunk 1]
```diff
@@ -121,18 +121,27 @@ export default class Chart extends SteveModel {
...
+          {
+            icon:        'icon-version-alt',
+            iconTooltip: { key: 'tableHeaders.version' },
+            label:       latestVersion.version
+          },
+          {
+            icon:        'icon-refresh-alt',
+            iconTooltip: { key: 'tableHeaders.lastUpdated' },
+            label:       hasZeroTime ? this.t('generic.na') : day(latestVersion.created).format('MMM D, YYYY'),
+            ...(hasZeroTime && { labelTooltip: this.t('generic.missingInfoMessage') })
```
Comment (nwmac) [inline shell/models/chart.js]: Won't that push `false` into the array? Does that just get ignored?

I'd probably go with an if statement and only add the sub header if hasZeroTime is true.

Comment (nwmac) [reply shell/models/chart.js]: Not sure who added `missingInfoMessage` - I think we should add a specific translation `Last updated date is not available for this chart`

**Review by nwmac — DISMISSED** [review]

File: shell/models/chart.js (hunk 1 above)
Comment (momesgin) [reply shell/models/chart.js]: > Won't that push false into the array? Does that just get ignored?

`...false` inside an object literal gets ignored, but I think for better readability I'll switch back to `if` statement 

> Not sure who added `missingInfoMessage` - I think we should add a specific translation `Last updated date is not available for this chart`

That was my idea to use a generic translation so it can be used in multiple places. I'll update the translation.

**Review by codyrancher — APPROVED** [review]
