### PR TITLE
Fixed unit tests warnings

### LINKED ISSUE #8907: Fix warnings in unit tests on pull request
# Description

Fix several warnings within the unit tests.

## Context

It seems like some may have not been caught in the local runs and it may have been merged beside the warnings due some configuration changes.

Added here the log with the warnings. It currently does not contain the linting part.

[output.txt](https://github.com/rancher/dashboard/files/12540305/output.txt)
<details>
 <summary>Expand log</summary>
<code>
PASS shell/plugins/dashboard-store/__tests__/actions.spec.ts
  ● Console

    console.log
      Find All: [unitTest] getters.normalizeType

      at findAll (shell/plugins/dashboard-store/actions.js:185:13)

PASS shell/plugins/dashboard-store/__tests__/mutations.spec.ts
PASS shell/plugins/dashboard-store/__tests__/getters.spec.ts
PASS shell/models/__tests__/namespace.test.ts
PASS shell/edit/__tests__/management.cattle.io.setting.test.ts
PASS shell/plugins/steve/__tests__/getters.spec.ts
PASS shell/edit/__tests__/ui.cattle.io.navlink.test.ts
PASS shell/edit/__tests__/fleet.cattle.io.gitrepo.test.ts
PASS shell/edit/logging.banzaicloud.io.output/__tests__/logging.banzaicloud.io.output.test.ts
PASS shell/mixins/__tests__/chart.test.ts
PASS shell/edit/persistentvolume/__tests__/persistentvolume.test.ts
PASS shell/edit/__tests__/monitoring.coreos.com.prometheusrule.test.ts
PASS shell/edit/__tests__/namespace.test.ts
  ● Console

    console.error
      [vuex] unknown getter: isStandaloneHarvester

       98 |       return this.value.listLocation;
       99 |     },
    > 100 |
          | ^
      101 |     showResourceQuota() {
      102 |       return (!this.isStandaloneHarvester) && Object.keys(this.project?.spec?.resourceQuota?.limit || {}).length > 0;
      103 |     },

      at VueComponent.mappedGetter (node_modules/vuex/dist/vuex.common.js:1025:17)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at Watcher.evaluate (node_modules/vue/dist/vue.runtime.common.dev.js:3501:27)
      at VueComponent.computedGetter [as isStandaloneHarvester] (node_modules/vue/dist/vue.runtime.common.dev.js:5464:25)
      at VueComponent.showResourceQuota (shell/edit/namespace.vue:100:20)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at Watcher.evaluate (node_modules/vue/dist/vue.runtime.common.dev.js:3501:27)
      at VueComponent.computedGetter [as showResourceQuota] (node_modules/vue/dist/vue.runtime.common.dev.js:5464:25)
      at Object.get (node_modules/vue/dist/vue.runtime.common.dev.js:5264:26)
      at Proxy.render (shell/edit/namespace.vue:167:1)
      at VueComponent.Vue._render (node_modules/vue/dist/vue.runtime.common.dev.js:2590:28)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:27)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:3390:51)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3845:5)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8687:12)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:4353:19)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:6489:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6443:13)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6991:13)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3718:25)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:16)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:3390:51)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3845:5)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8687:12)
      at Object.mount (node_modules/@vue/test-utils/dist/vue-test-utils.js:14066:21)
      at Object.<anonymous> (shell/edit/__tests__/namespace.test.ts:11:21)

PASS shell/edit/networking.k8s.io.networkpolicy/__tests__/PolicyRuleTarget.spec.ts
PASS shell/models/__tests__/batch.cronjob.test.ts
PASS shell/edit/workload/storage/__tests__/Storage.test.ts
  ● Console

    console.error
      [Vue warn]: Avoid using non-primitive value as key, use string/number value instead.
      
      found in
      
      ---> <VSelect>
             <LabeledSelect>
               <Anonymous>
                 <InfoBox>
                   <ArrayList>
                     <ArrayListGrouped>
                       <Storage>
                         <Root>

      at warn (node_modules/vue/dist/vue.runtime.common.dev.js:4548:21)
      at _createElement (node_modules/vue/dist/vue.runtime.common.dev.js:2788:9)
      at createElement$1 (node_modules/vue/dist/vue.runtime.common.dev.js:2771:12)
      at vm.$createElement (node_modules/vue/dist/vue.runtime.common.dev.js:2549:41)
      at createElement (node_modules/@vue/test-utils/dist/vue-test-utils.js:2511:38)
      at node_modules/vue-select/dist/webpack:/VueSelect/src/components/Select.vue?b0fa:1:776
      at Proxy.renderList (node_modules/vue/dist/vue.runtime.common.dev.js:1947:22)
      at Proxy.<anonymous> (node_modules/vue-select/dist/webpack:/VueSelect/src/components/Select.vue?b0fa:1:710)
      at VueComponent.Vue._render (node_modules/vue/dist/vue.runtime.common.dev.js:2590:28)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:27)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:3390:51)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3845:5)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8687:12)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:4353:19)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:6489:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6443:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6991:13)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3718:25)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:16)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:3390:51)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3845:5)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8687:12)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:4353:19)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:6489:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6443:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6991:13)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3718:25)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:16)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:3390:51)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3845:5)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8687:12)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:4353:19)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:6489:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6443:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)

    console.error
      [Vue warn]: Avoid using non-primitive value as key, use string/number value instead.
      
      found in
      
      ---> <VSelect>
             <LabeledSelect>
               <Anonymous>
                 <InfoBox>
                   <ArrayList>
                     <ArrayListGrouped>
                       <Storage>
                         <Root>

      at warn (node_modules/vue/dist/vue.runtime.common.dev.js:4548:21)
      at _createElement (node_modules/vue/dist/vue.runtime.common.dev.js:2788:9)
      at createElement$1 (node_modules/vue/dist/vue.runtime.common.dev.js:2771:12)
      at vm.$createElement (node_modules/vue/dist/vue.runtime.common.dev.js:2549:41)
      at createElement (node_modules/@vue/test-utils/dist/vue-test-utils.js:2511:38)
      at node_modules/vue-select/dist/webpack:/VueSelect/src/components/Select.vue?b0fa:1:776
      at Proxy.renderList (node_modules/vue/dist/vue.runtime.common.dev.js:1947:22)
      at Proxy.<anonymous> (node_modules/vue-select/dist/webpack:/VueSelect/src/components/Select.vue?b0fa:1:710)
      at VueComponent.Vue._render (node_modules/vue/dist/vue.runtime.common.dev.js:2590:28)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:27)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:3390:51)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3845:5)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8687:12)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:4353:19)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:6489:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6443:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6991:13)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3718:25)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:16)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:3390:51)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3845:5)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8687:12)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:4353:19)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:6489:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6443:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6991:13)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3718:25)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:16)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:3390:51)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3845:5)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8687:12)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:4353:19)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:6489:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6443:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)

    console.error
      [Vue warn]: Avoid using non-primitive value as key, use string/number value instead.
      
      found in
      
      ---> <VSelect>
             <LabeledSelect>
               <Anonymous>
                 <InfoBox>
                   <ArrayList>
                     <ArrayListGrouped>
                       <Storage>
                         <Root>

      at warn (node_modules/vue/dist/vue.runtime.common.dev.js:4548:21)
      at _createElement (node_modules/vue/dist/vue.runtime.common.dev.js:2788:9)
      at createElement$1 (node_modules/vue/dist/vue.runtime.common.dev.js:2771:12)
      at vm.$createElement (node_modules/vue/dist/vue.runtime.common.dev.js:2549:41)
      at createElement (node_modules/@vue/test-utils/dist/vue-test-utils.js:2511:38)
      at node_modules/vue-select/dist/webpack:/VueSelect/src/components/Select.vue?b0fa:1:776
      at Proxy.renderList (node_modules/vue/dist/vue.runtime.common.dev.js:1947:22)
      at Proxy.<anonymous> (node_modules/vue-select/dist/webpack:/VueSelect/src/components/Select.vue?b0fa:1:710)
      at VueComponent.Vue._render (node_modules/vue/dist/vue.runtime.common.dev.js:2590:28)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:27)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at Watcher.run (node_modules/vue/dist/vue.runtime.common.dev.js:3476:32)
      at flushSchedulerQueue (node_modules/vue/dist/vue.runtime.common.dev.js:4073:17)
      at Array.<anonymous> (node_modules/vue/dist/vue.runtime.common.dev.js:3045:20)
      at flushCallbacks (node_modules/vue/dist/vue.runtime.common.dev.js:2967:18)

PASS shell/components/form/__tests__/Probe.test.ts
PASS shell/config/__test__/home-links.test.ts
PASS shell/edit/workload/storage/__tests__/Mount.test.ts
PASS shell/chart/__tests__/S3.test.ts
PASS shell/components/form/__tests__/Command.test.ts
PASS shell/edit/workload/__tests__/Job.test.ts
PASS shell/edit/workload/__tests__/index.test.ts
PASS shell/edit/provisioning.cattle.io.cluster/__tests__/rke2.test.ts (5.509 s)
PASS shell/components/form/__tests__/ArrayList.test.ts
PASS shell/components/form/__tests__/Security.test.ts
PASS shell/edit/monitoring.coreos.com.receiver/types/__tests__/email.test.ts
PASS shell/edit/logging.banzaicloud.io.output/providers/__tests__/loki.test.ts
PASS shell/components/form/__tests__/MatchExpressions.test.ts
PASS shell/edit/workload/__tests__/Upgrading.test.ts
PASS shell/utils/__tests__/selector.test.ts
PASS shell/utils/__tests__/array.test.ts
PASS shell/components/form/__tests__/UnitInput.test.ts
PASS shell/utils/validators/formRules/__tests__/index.test.ts
PASS shell/components/form/__tests__/LabeledSelect.test.ts
PASS shell/components/form/__tests__/NodeAffinity.test.ts
PASS shell/components/form/__tests__/FileImageSelector.test.ts
PASS shell/components/form/__tests__/PodAffinity.test.ts
PASS shell/utils/__tests__/version.test.ts
PASS shell/components/form/__tests__/FileSelector.test.ts
PASS shell/plugins/steve/__tests__/header-warnings.spec.ts
PASS shell/utils/__tests__/pod-security-admission.test.ts
PASS shell/utils/__tests__/string.test.ts
PASS shell/utils/__tests__/grafana.test.ts
PASS shell/utils/__tests__/object.test.ts
PASS shell/mixins/__tests__/create-edit-view.test.ts
PASS shell/utils/validators/__tests__/cidr.test.ts
PASS shell/utils/__tests__/create-yaml.test.ts
PASS shell/components/form/__tests__/ArrayListGrouped.test.ts
PASS shell/components/form/__tests__/NameNsDescription.ts
PASS shell/edit/provisioning.cattle.io.cluster/__tests__/CustomCommand.tests.ts
PASS shell/list/__tests__/workload.test.ts
PASS shell/pages/__tests__/prefs.test.ts
PASS pkg/rancher-components/src/components/StringList/StringList.test.ts
PASS shell/components/__tests__/PromptRestore.test.ts
PASS pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineNetwork/__tests__/HarvesterEditNetwork.test.ts
PASS shell/cloud-credential/__tests__/azure.test.ts
PASS shell/components/__tests__/NamespaceFilter.test.ts
PASS shell/store/__tests__/index.test.ts
PASS shell/components/__tests__/PodSecurityAdmission.test.ts
PASS shell/components/formatter/__tests__/ClusterLink.test.ts
PASS shell/components/Questions/__tests__/Int.test.ts
PASS shell/components/nav/WindowManager/__tests__/ContainerShell.test.ts
PASS shell/components/Questions/__tests__/Float.test.ts
PASS shell/components/__tests__/FixedBanner.test.ts
PASS pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/__tests__/HarvesterEditVMImage.test.ts
PASS shell/components/formatter/__tests__/LiveDate.test.ts
PASS pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/__tests__/HarvesterEditExisting.test.ts
PASS shell/components/__tests__/CruResource.test.ts
PASS pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/__tests__/HarvesterEditVolume.test.ts
PASS shell/components/Questions/__tests__/Boolean.test.ts
PASS shell/components/form/__tests__/KeyValue.test.ts
  ● Console

    console.error
      Code mirror loader not available

      76 |     if (window.__codeMirrorLoader) {
      77 |       window.__codeMirrorLoader().then(() => {
    > 78 |         this.loaded = true;
         |               ^
      79 |       });
      80 |     } else {
      81 |       console.error('Code mirror loader not available'); // eslint-disable-line no-console

      at VueComponent.created (shell/components/CodeMirror.vue:78:15)
      at invokeWithErrorHandling (node_modules/vue/dist/vue.runtime.common.dev.js:2919:61)
      at callHook$1 (node_modules/vue/dist/vue.runtime.common.dev.js:3983:13)
      at VueComponent.Vue._init (node_modules/vue/dist/vue.runtime.common.dev.js:5617:9)
      at new VueComponent (node_modules/vue/dist/vue.runtime.common.dev.js:5750:18)
      at createComponentInstanceForVnode (node_modules/vue/dist/vue.runtime.common.dev.js:4490:12)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:4352:54)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:6489:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6443:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6991:13)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3718:25)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:16)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:3390:51)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3845:5)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8687:12)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:4353:19)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:6489:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6443:13)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6991:13)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3718:25)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:16)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:3390:51)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3845:5)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8687:12)
      at Object.mount (node_modules/@vue/test-utils/dist/vue-test-utils.js:14066:21)
      at Object.<anonymous> (shell/components/form/__tests__/KeyValue.test.ts:20:21)

PASS pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/__tests__/HarvesterEditContainer.test.ts
PASS shell/components/__tests__/GrowlManager.test.ts
PASS shell/components/Questions/__tests__/Yaml.test.ts
  ● Console

    console.error
      Code mirror loader not available

      76 |     if (window.__codeMirrorLoader) {
      77 |       window.__codeMirrorLoader().then(() => {
    > 78 |         this.loaded = true;
         |               ^
      79 |       });
      80 |     } else {
      81 |       console.error('Code mirror loader not available'); // eslint-disable-line no-console

      at VueComponent.created (shell/components/CodeMirror.vue:78:15)
      at invokeWithErrorHandling (node_modules/vue/dist/vue.runtime.common.dev.js:2919:61)
      at callHook$1 (node_modules/vue/dist/vue.runtime.common.dev.js:3983:13)
      at VueComponent.Vue._init (node_modules/vue/dist/vue.runtime.common.dev.js:5617:9)
      at new VueComponent (node_modules/vue/dist/vue.runtime.common.dev.js:5750:18)
      at createComponentInstanceForVnode (node_modules/vue/dist/vue.runtime.common.dev.js:4490:12)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:4352:54)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:6489:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6443:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6991:13)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3718:25)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:16)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:3390:51)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3845:5)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8687:12)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:4353:19)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:6489:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6443:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6991:13)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3718:25)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:16)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:3390:51)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3845:5)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8687:12)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:4353:19)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:6489:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6443:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6991:13)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3718:25)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:16)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:3390:51)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3845:5)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8687:12)

    console.error
      Code mirror loader not available

      76 |     if (window.__codeMirrorLoader) {
      77 |       window.__codeMirrorLoader().then(() => {
    > 78 |         this.loaded = true;
         |               ^
      79 |       });
      80 |     } else {
      81 |       console.error('Code mirror loader not available'); // eslint-disable-line no-console

      at VueComponent.created (shell/components/CodeMirror.vue:78:15)
      at invokeWithErrorHandling (node_modules/vue/dist/vue.runtime.common.dev.js:2919:61)
      at callHook$1 (node_modules/vue/dist/vue.runtime.common.dev.js:3983:13)
      at VueComponent.Vue._init (node_modules/vue/dist/vue.runtime.common.dev.js:5617:9)
      at new VueComponent (node_modules/vue/dist/vue.runtime.common.dev.js:5750:18)
      at createComponentInstanceForVnode (node_modules/vue/dist/vue.runtime.common.dev.js:4490:12)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:4352:54)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:6489:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6443:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6991:13)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3718:25)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:16)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:3390:51)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3845:5)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8687:12)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:4353:19)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:6489:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6443:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6991:13)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3718:25)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:16)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:3390:51)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3845:5)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8687:12)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:4353:19)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:6489:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6443:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6991:13)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3718:25)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:16)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:3390:51)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3845:5)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8687:12)

    console.error
      Code mirror loader not available

      76 |     if (window.__codeMirrorLoader) {
      77 |       window.__codeMirrorLoader().then(() => {
    > 78 |         this.loaded = true;
         |               ^
      79 |       });
      80 |     } else {
      81 |       console.error('Code mirror loader not available'); // eslint-disable-line no-console

      at VueComponent.created (shell/components/CodeMirror.vue:78:15)
      at invokeWithErrorHandling (node_modules/vue/dist/vue.runtime.common.dev.js:2919:61)
      at callHook$1 (node_modules/vue/dist/vue.runtime.common.dev.js:3983:13)
      at VueComponent.Vue._init (node_modules/vue/dist/vue.runtime.common.dev.js:5617:9)
      at new VueComponent (node_modules/vue/dist/vue.runtime.common.dev.js:5750:18)
      at createComponentInstanceForVnode (node_modules/vue/dist/vue.runtime.common.dev.js:4490:12)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:4352:54)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:6489:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6443:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6991:13)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3718:25)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:16)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:3390:51)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3845:5)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8687:12)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:4353:19)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:6489:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6443:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6991:13)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3718:25)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:16)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:3390:51)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3845:5)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8687:12)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:4353:19)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:6489:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6443:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6991:13)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3718:25)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:16)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:3390:51)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3845:5)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8687:12)

    console.error
      Code mirror loader not available

      76 |     if (window.__codeMirrorLoader) {
      77 |       window.__codeMirrorLoader().then(() => {
    > 78 |         this.loaded = true;
         |               ^
      79 |       });
      80 |     } else {
      81 |       console.error('Code mirror loader not available'); // eslint-disable-line no-console

      at VueComponent.created (shell/components/CodeMirror.vue:78:15)
      at invokeWithErrorHandling (node_modules/vue/dist/vue.runtime.common.dev.js:2919:61)
      at callHook$1 (node_modules/vue/dist/vue.runtime.common.dev.js:3983:13)
      at VueComponent.Vue._init (node_modules/vue/dist/vue.runtime.common.dev.js:5617:9)
      at new VueComponent (node_modules/vue/dist/vue.runtime.common.dev.js:5750:18)
      at createComponentInstanceForVnode (node_modules/vue/dist/vue.runtime.common.dev.js:4490:12)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:4352:54)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:6489:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6443:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6991:13)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3718:25)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:16)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:3390:51)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3845:5)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8687:12)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:4353:19)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:6489:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6443:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6991:13)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3718:25)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:16)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:3390:51)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3845:5)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8687:12)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:4353:19)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:6489:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6443:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6562:17)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:6466:13)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6991:13)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3718:25)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3828:16)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:3400:33)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:3390:51)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:3845:5)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8687:12)

PASS shell/components/__tests__/CollapsibleCard.test.ts
PASS shell/components/Questions/__tests__/String.test.ts
PASS shell/components/formatter/__tests__/LinkDetail.test.ts
PASS shell/components/form/__tests__/Error.test.ts
PASS pkg/rancher-components/src/components/Banner/Banner.test.ts
PASS shell/components/__tests__/SimpleBox.spec.ts
PASS shell/components/__tests__/Collapse.spec.ts
PASS shell/components/__tests__/ConsumptionGauge.test.ts
PASS shell/components/__tests__/ApplicationCard.test.ts
PASS shell/components/formatter/__tests__/Date.test.ts
PASS shell/components/__tests__/ChartPsp.test.ts
PASS pkg/rancher-components/src/components/Card/Card.test.ts
PASS shell/components/__tests__/AsyncButton.test.ts
PASS shell/components/formatter/__tests__/ClusterProvider.test.ts
PASS shell/components/formatter/__tests__/PodsUsage.test.ts
PASS shell/components/formatter/__tests__/Si.test.ts
PASS pkg/rancher-components/src/components/Form/Checkbox/Checkbox.test.ts
PASS shell/components/__tests__/BackLink.test.ts
PASS shell/components/__tests__/ButtonGroup.test.ts
PASS shell/components/__tests__/ClusterBadge.test.ts
PASS pkg/rancher-components/src/components/Form/LabeledInput/LabeledInput.test.ts
PASS shell/components/__tests__/CopyCode.test.ts
PASS pkg/rancher-components/src/components/Form/ToggleSwitch/ToggleSwitch.test.ts
PASS pkg/rancher-components/src/components/Form/Radio/RadioButton.test.ts
PASS pkg/rancher-components/src/components/BadgeState/BadgeState.spec.ts
PASS shell/components/__tests__/PercentageBar.test.ts
PASS shell/pages/c/_cluster/apps/charts/__tests__/install.helper.test.ts

Test Suites: 102 passed, 102 total
Tests:       7 skipped, 19 todo, 937 passed, 963 total
Snapshots:   0 total
Time:        9.358 s, estimated 11 s
Ran all test suites.

<code>
</details>

### PR DESCRIPTION
**Pull request by momesgin**
### Summary
Fixes #8907 

### Screenshot/Video
https://github.com/rancher/dashboard/assets/135728925/ad03d3b0-3b1a-424d-9fd3-e3fea038c53d

### CODE REVIEW

File: shell/components/ClusterIconMenu.vue [hunk 1]
```diff
@@ -12,6 +12,14 @@ export default {
     isEnabled() {
       return !!this.cluster?.ready;
     },
+    showLocalIcon() {
+      return this.cluster.isLocal && !this.cluster.isHarvester && !this.cluster.badge?.iconText;
+    },
+    badgeLogoBorderBottom() {
+      const { color } = this.cluster.badge;
```
Comment (cnotv) [inline shell/components/ClusterIconMenu.vue:19]: It seems like badge is not always present in the pre-existing code (and we don't have types), so to destructure it will cause error.

**Review by cnotv — CHANGES_REQUESTED** [review]
Good job, but I found a tiny annoying point in the code change.

File: shell/components/ClusterIconMenu.vue (hunk 1 above)
Comment (momesgin) [reply shell/components/ClusterIconMenu.vue]: good catch, thanks!

**Review by cnotv — APPROVED** [review]
LGTM
