### PR TITLE
Ensure lists update when switching between workspaces with the same number of rows

### LINKED ISSUE #12437: As custom user incorrect fleet gitrepos are shown given the workspace filter
**Setup**
- Rancher version: 2.10.0-alpha5
- Rancher UI Extensions:
- Browser type & version:Brave 1.70

**Describe the bug**
After an admin deploys 2 girepos one in fleet-local and the other in fleet-default, an user with access to these gitrepos will see them in incorrect order when using the toggle (the ones meant to be in local will appear in default and the one in default will appear in local)

**To Reproduce**
- Deploy Rancher `2.10.0-alpha5` with at least 1 downstream cluster
- As an admin deploy these 2 gitrepos:
**Local cluster**
```
Name: fleet-local-simple-chart
URL: https://github.com/rancher/fleet-test-data
branch: master
path: simple-chart
```
 **Default cluster**
```
Name: fleet-default-nginx
URL: https://github.com/rancher/fleet-test-data
branch: master
path: qa-test-apps/nginx-app
```
 - Create standard user `std-user-46` with this custom roles:
 ```
  { resource: "fleetworkspaces", verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]},
  { resource: "gitrepos", verbs: ["list"]},
  { resource: "bundles", verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]},
```
- Access as `std-user-46`

**Result**
When navigating to gitrepos `std-user-46` sees: 
- when changing toggle to `fleet-local` gitrepo `fleet-default-nginx` 
- when changing toggle to `fleet-default` gitrepo `fleet-local-simple-chart`
image

**Expected Result**
When navigating to gitrepos `std-user-46` should see: 
- when changing toggle to `fleet-local` gitrepo `fleet-local-simple-chart`
- when changing toggle to `fleet-default` gitrepo `fleet-default-nginx`

**Screenshots**

[Screencast from 30-10-24 17:15:59.webm](https://github.com/user-attachments/assets/a97b2c32-19e3-459d-a7df-fb2a7316cf0d)

**Additional context**

### PR DESCRIPTION
**Pull request by richard-cox**
### Summary
Fixes #12437

### Occurred changes and/or fixed issues
- Switching between fleet workspaces which contain the same number of resources will fail to update the rows
  - sometimes this would happen anyway, for instance the generation of the resource was updated
- Caused by change in reactivity with base [fn](https://github.com/rancher/dashboard/blob/master/shell/components/SortableTable/sorting.js#L35) in sortable table pagination pipeline
  - this was fired with stale rows (rows from old workspace) BUT would be cached against the new state (new workspace)
  - whenever the pipeline was triggered again (sans other changes) it would then return the cached stale rows
- fixed by providing a specific hash to use instead of one generated on demand (which fetched new state)
  - i've limited this to the workspace world to reduce impact / bugs

### Technical notes summary
- this is a quicker fix than re-rewriting the whole thing... or finding out why vue changed behaviour

### Areas or cases that should be tested
- Everything list based

### Areas which could experience regressions
- Everything list based

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

**Comment by eva-vashkevich** [comment]
Do we need to have a follow up issue to investigate the non-workspace case?

File: shell/components/ResourceTable.vue [hunk 1]
```diff
@@ -556,6 +580,7 @@ export default {
     :adv-filter-hide-labels-as-cols="advFilterHideLabelsAsCols"
     :adv-filter-prevent-filtering-labels="advFilterPreventFilteringLabels"
     :key-field="keyField"
+    :sortGeneration="sortGeneration"
```
Comment (eva-vashkevich) [inline shell/components/ResourceTable.vue:583]: this should be kebab case

**Comment by eva-vashkevich** [comment]
I've tested the original scenario as well as played with namespaces in other areas of rancher and it seems to work

**Review by mantis-toboggan-md — APPROVED** [review]
Code-wise this looks safe enough and I've tried testing both fleet workspace switching and explorer namespace switching. 

This solution seems appropriate given time constraints but I agree with @eva-vashkevich about filing a follow-up issue to re-evaluate. I'm wary of leaving the root cause of this bug undiscovered but agree with the assessment that it'd take substantial time.
