### PR TITLE
Fix storybook build crash on node 20.19+

### LINKED ISSUE #16766: Storybook fails to build when using Node 20.19+
**Setup**
- Rancher version: v2.14-head
- Rancher UI Extensions: NA
- Browser type & version: Node v20.19+

**Describe the bug**

Running Storybook with Node 20.19+ produces the following error:

```
SB_CORE-SERVER_0002 (CriticalPresetLoadError): Storybook failed to load the following preset: ./.storybook/main.ts.

Please check whether your setup is correct, the Storybook dependencies (and their peer dependencies) are installed correctly and there are no package version clashes.

If you believe this is a bug, please open an issue on Github.

SB_CORE-SERVER_0002 (CriticalPresetLoadError): Storybook failed to load the following preset: ./node_modules/@storybook/addon-webpack5-compiler-babel/preset.js.

Please check whether your setup is correct, the Storybook dependencies (and their peer dependencies) are installed correctly and there are no package version clashes.

If you believe this is a bug, please open an issue on Github.

ReferenceError: module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and './node_modules/@storybook/addon-webpack5-compiler-babel/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file://./node_modules/@storybook/addon-webpack5-compiler-babel/preset.js:1:1
    at ModuleJobSync.runSync (node:internal/modules/esm/module_job:437:37)
    at ModuleLoader.importSyncForRequire (node:internal/modules/esm/loader:389:47)
    at loadESMFromCJS (node:internal/modules/cjs/loader:1363:24)
    at Module._compile (node:internal/modules/cjs/loader:1503:5)
    at Module._extensions..js (node:internal/modules/cjs/loader:1623:10)
    at Object.newLoader (./node_modules/esbuild-register/dist/node.js:2262:9)
    at extensions..js (./node_modules/esbuild-register/dist/node.js:4833:24)
    at Module.load (node:internal/modules/cjs/loader:1266:32)
    at Module._load (node:internal/modules/cjs/loader:1091:12)

More info:

    at loadPreset (./node_modules/@storybook/core/dist/common/index.cjs:16515:13)

More info:

    at loadPreset (./node_modules/@storybook/core/dist/common/index.cjs:16515:13)
    at async Promise.all (index 1)
    at async loadPresets (./node_modules/@storybook/core/dist/common/index.cjs:16525:55)
    at async getPresets (./node_modules/@storybook/core/dist/common/index.cjs:16558:11)
    at async buildDevStandalone (./node_modules/@storybook/core/dist/core-server/index.cjs:37583:11)
    at async withTelemetry (./node_modules/@storybook/core/dist/core-server/index.cjs:35788:12)
    at async dev (./node_modules/@storybook/core/dist/cli/bin/index.cjs:5874:3)
    at async s.<anonymous> (./node_modules/@storybook/core/dist/cli/bin/index.cjs:6052:74)
```

**To Reproduce**

- Ensure that node 20.19+ is installed 
- Change the directory to Storybook: `pushd storybook`
- Install dependencies: `yarn install`
- Run Storybook: `yarn storybook`

**Result**

The storybook build fails with the error detailed above.

**Expected Result**

The storybook build completes without failure and storybook is accessible via the web browser.

**Screenshots**

NA

**Additional context**

This appears to be related to recent changes in node to drop CJS buils:

- https://github.com/nodejs/node/releases/tag/v20.19.0
- https://socket.dev/blog/require-esm-backported-to-node-js-20

### PR DESCRIPTION
**Pull request by rak-phillip**
### Summary
This resolves issues with building an running storybook on nodejs 20.19+.

fixes #16766

### Occurred changes and/or fixed issues

- Fix storybook build crash on node 20.19+
- Use `--frozen-lockfile` for reproducible Storybook builds

### Technical notes summary

Node.js v20.19.0 introduced a change to help drop support for CJS builds[^1][^2]. This change conflicts when using `getAbsolutePath()` with `@storybook/addon-webpack5-compiler-babel`. Omitting the `getAbsolutePath()` allows node to treat the package properly.

This affects node versions v20.19+

[^1]: https://github.com/nodejs/node/releases/tag/v20.19.0
[^2]: https://socket.dev/blog/require-esm-backported-to-node-js-20

This also replaces the `--no-lockfile` flag with `--frozen-lockfile` or the storybook build step. `--frozen-lockfile` ensures that the lockfile is respected during installation; it helps identify dependency drift and guarantees deterministic builds in CI.

### Areas or cases that should be tested

Storybook builds should succeed. Storybook can run locally.

### Areas which could experience regressions

This change could affect node versions below 20.19.

### Screenshot/Video

NA

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes
- [x] The PR has been reviewed in terms of Accessibility
- [x] The PR has considered, and if applicable tested with, the three Global Roles `Admin`, `Standard User` and `User Base`

### CODE REVIEW

File: storybook/.storybook/main.ts [hunk 1]
```diff
@@ -106,7 +106,7 @@ const config: StorybookConfig = {
     getAbsolutePath("@storybook/addon-links"),
     getAbsolutePath("@storybook/addon-essentials"),
     getAbsolutePath("@storybook/addon-interactions"),
-    getAbsolutePath('@storybook/addon-webpack5-compiler-babel'),
+    '@storybook/addon-webpack5-compiler-babel',
```
Comment (codyrancher) [inline storybook/.storybook/main.ts:109]: I think we should prolly add a comment with a link to the release note or description.
