### PR TITLE
Deployment creation view - fix health check - #5734

### LINKED ISSUE #5734: Improve Deployment creations screen and add Pod creation view
Details TBD

Implement the new design for the deployment creation screen.

Do this in a way that allows this to be reused for the Pods edit screen (which does not currently exist).

Rough design here - https://xd.adobe.com/view/3a0ff278-5d42-4f38-82fe-647fe3472cc7-6f5c/screen/fd9531dc-24ef-4425-b6df-fbd8c980544a - still some tweaks to be made.

### PR DESCRIPTION
**Pull request by Shavindra**
### Summary
Fixes #5734 - Deployment Pod creation view.
https://github.com/rancher/dashboard/pull/6329 - UI was already demo locally. However, [commit wasn't pushed to branch](https://github.com/rancher/dashboard/commit/b776b53bcd4c493f4f9a78e0c164fd1cdfc217a3). So was missing it PR merge which include hiding the Health Check when user select `Init container`

### Areas or cases that should be tested
1. Cluster explorer > Cluster > Workload > Deployments
2. Click Create button on top right
3. You will notice now there are 3 Tabs - `Deployments`, `Pods` and `Containers`.
4. Settings related to specific section is under each different tab.
5. Under containers `Add Container` will add another container to the config. Previously this was a drop down outside of the tabs.
6. To Remove a container use the link on top right of each container tab content
7. No functional changes. User should still be able to set the same settings as before

### Areas which could experience regressions
- Workloads Create / Edit / View
  - Cronjobs
  - Daemonsets
  - Deployments
  - Jobs
  - StatefulSets
  - Pods

There is no functional changes. User should be able to set/view same settings as before. Only difference is arrangement of different fields

### CODE REVIEW

File: shell/edit/workload/Upgrading.vue [hunk 1]
```diff
@@ -221,7 +231,7 @@ export default {
         />
       </div>
     </div>
-    <div v-if="isStatefulSet" class="row mb-20">
+    <div v-if="isStatefulSet&& !noDeploymentSpec" class="row mb-20">
```
Comment (aalves08) [inline shell/edit/workload/Upgrading.vue:234]: missing a space here...
`<div v-if="isStatefulSet&& !noDeploymentSpec" class="row mb-20">`
to 
`<div v-if="isStatefulSet && !noDeploymentSpec" class="row mb-20">`

File: shell/edit/workload/types/Deployment.vue [hunk 2]
```diff
@@ -178,10 +191,18 @@ export default {
             </template>
           </Tabbed>
         </Tab>
-        <Tab :label="'Deployments'" :name="'deployments'" :weight="99">
-          <Labels v-model="value" :mode="mode" />
+        <Tab :label="'Deployment'" :name="'deployments'" :weight="99">
```
Comment (aalves08) [inline shell/edit/workload/types/Deployment.vue:194]: We should avoid using hardcoded strings `:label`. On line 196 `label-key` is used instead, which looks like the right pattern. 🙏

File: shell/edit/workload/types/Deployment.vue [hunk 3]
```diff
@@ -178,10 +191,18 @@ export default {
...
+              <Labels v-model="value" :mode="mode" />
+            </Tab>
+            <Tab :label="t('workload.container.titles.upgrading')" name="upgrading" :weight="tabWeightMap['upgrading']">
+              <Job v-if="isJob || isCronJob" v-model="spec" :mode="mode" :type="type" />
+              <Upgrading v-else v-model="spec" :mode="mode" :type="type" :no-pod-spec="true" />
+            </Tab>
+          </Tabbed>
         </Tab>
-        <Tab :label="'Pods'" :name="'pods'" :weight="99">
+        <Tab :label="'Pod'" :name="'pods'" :weight="99">
```
Comment (aalves08) [inline shell/edit/workload/types/Deployment.vue:205]: Same here

**Review by aalves08 — COMMENTED** [review]
Left a couple of small comments @Shavindra 🙏

File: shell/config/types.js [hunk 4]
```diff
@@ -306,3 +306,9 @@ export const AUTH_TYPE = {
   _SSH:   '_ssh',
   _S3:    '_S3'
 };
+
+export const WORKLOAD_TABS = {
```
Comment (aalves08) [inline shell/config/types.js:310]: I am sorry if I wasn't clear enough on my explanation @Shavindra , but what I meant is to include these strings on the `en-us` yaml, like we do for all translatable strings like these ones 🙏 🙏 🙏  sorry for that

**Review by aalves08 — COMMENTED** [review]
minor comment... sorry about that 🙏

**Review by aalves08 — APPROVED** [review]
LGTM
