### PR TITLE
Table actions 'enabled' function not working correctly

### LINKED ISSUE #9330: Extensions: Table actions 'enabled' function not working correctly
**Setup**
- Rancher version: head
- Rancher UI Extensions: ----
- Browser type & version: ----

**Describe the bug**
Using the `enabled` on the table actions hook on extensions 

**To Reproduce**
- create a new package `yarn create @rancher/pkg test`
- on the `index.ts` file, add the code for adding an action for a table (replace the string on `ctx.nameDisplay` to match the name of one of your pods `elemental-operator-55bf74dccd-4tn2s`
```
plugin.addAction(
    ActionLocation.TABLE,
    { resource: ['pod'] },
    {
      label:    'some-bulkable-action',
      // labelKey: 'plugin-examples.table-action-two',
      icon: 'icon-gear',
      // svg:      require('@pkg/extensions-api-demo/icons/rancher-desktop.svg'),
      multiple: true,
      invoke(opts: ActionOpts, values: any[]) {
        console.log('table action executed 2', this); // eslint-disable-line no-console
        console.log(opts); // eslint-disable-line no-console
        console.log(values); // eslint-disable-line no-console
      },
      enabled(ctx: any) {
        console.log('ctx', ctx.nameDisplay)
        return ctx.nameDisplay === 'elemental-operator-55bf74dccd-4tn2s';
      },
    }
  );
```
- Go to the `pods` list view and go to a table action per row

**Result**
The condition is applied globally

**Expected Result**
The condition should be applied per row

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by aalves08**
- Fixes #9330 

- Fix bug where table actions `enabled` function wasn't working correctly (was being applied globally instead of per row)

## How to test
- create a new package `yarn create @rancher/pkg test`
- on the `index.ts` file, add the code for adding an action for a table (replace the string on `ctx.nameDisplay` to match the name of one of your pods `elemental-operator-55bf74dccd-4tn2s`
```
plugin.addAction(
    ActionLocation.TABLE,
    { resource: ['pod'] },
    {
      label:    'some-bulkable-action',
      // labelKey: 'plugin-examples.table-action-two',
      icon: 'icon-gear',
      // svg:      require('@pkg/extensions-api-demo/icons/rancher-desktop.svg'),
      multiple: true,
      invoke(opts: ActionOpts, values: any[]) {
        console.log('table action executed 2', this); // eslint-disable-line no-console
        console.log(opts); // eslint-disable-line no-console
        console.log(values); // eslint-disable-line no-console
      },
      enabled(ctx: any) {
        console.log('ctx', ctx.nameDisplay)
        return ctx.nameDisplay === 'elemental-operator-55bf74dccd-4tn2s';
      },
    }
  );
```
- Go to the `pods` list view and go to a table action per row

### CODE REVIEW

File: shell/plugins/dashboard-store/resource-class.js [hunk 1]
```diff
@@ -910,7 +910,23 @@ export default class Resource {
...
       all.push({ divider: true });
-      all = all.concat(extensionMenuActions);
+
+      extensionMenuActions.forEach((action) => {
+        const newActionInstance = { ...action };
+
+        // sets the enabled flag to true if omitted on the config
+        if (!Object.keys(newActionInstance).includes('enabled')) {
+          newActionInstance.enabled = true;
+        } else if (Object.keys(newActionInstance).includes('enabled') && typeof newActionInstance.enabled === 'function') {
```
Comment (richard-cox) [inline shell/plugins/dashboard-store/resource-class.js:920]: `typeof newActionInstance.enabled !== 'undefined'` is a bit neater

Comment (richard-cox) [inline shell/plugins/dashboard-store/resource-class.js:920]: The below will fix linting, improve readability, fix the max call size error and handle missconfigurations nicer

```
      extensionMenuActions.forEach((action) => {
        const newActionInstance = { ...action };

        const enabledFn = newActionInstance.enabled;
        const typeofEnabled = typeof enabledFn;

        switch (typeofEnabled) {
        case 'undefined':
          newActionInstance.enabled = true;
          break;
        case 'function':
          Object.defineProperty(newActionInstance, 'enabled', { get: () => enabledFn(this) });
          break;
        case 'boolean':
          // no op, just use it directly
          break;
        default:
          // unsupported value
          console.warn(`Unsupported 'enabled' property type for action: ${ action.label || action.labelKey }` ); // eslint-disable-line no-console
          delete newActionInstance.enabled;
          break;
        }

        all.push(newActionInstance);
      });
```

**Review by richard-cox — CHANGES_REQUESTED** [review]

File: shell/plugins/dashboard-store/resource-class.js (hunk 1 above)
Comment (aalves08) [reply shell/plugins/dashboard-store/resource-class.js]: Thanks @richard-cox ! 🙏 🙇

**Review by richard-cox — APPROVED** [review]
