### PR TITLE
Render wizard footer in CruResource

### LINKED ISSUE #11882: Vue3: Fleet's Create Page doesn't show the footer
**Setup**
- Rancher version:
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**

**To Reproduce**

**Result**
fleet-vue3

**Expected Result**

fleet-vue2

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by rak-phillip**
### Summary
This ensures that the Wizard footer will render properly within CruResource. 

I'm not finding any docs that explains this change, but the best I can infer is that the `footer` slot is defined within the `controlsContainer` slot of the Wizard component; Vue3 must be more strict about slot hierarchy than Vue2. (footer is a slot of CruResource, not Wizard)

Fixes #11882

### Occurred changes and/or fixed issues

- Remove the nested `<template #footer>` to render the footer for the Wizard
- Resolve console warning related to missing `LazyImage` component import

### Areas or cases that should be tested

- Fleet

### Areas which could experience regressions

- Other instances of CruResource that render the Wizard component

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [ ] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: shell/components/CruResource.vue [hunk 1]
```diff
@@ -587,76 +587,74 @@ export default {
               </template>
             </template>
             <template #controlsContainer="{showPrevious, next, back, activeStep, canNext, activeStepIndex, visibleSteps}">
-              <template name="form-footer">
```
Comment (cnotv) [inline shell/components/CruResource.vue:590]: That's something that has to be investigated because unless the custom footer has been removed along the way, it must have been added for sure somewhere.

File: shell/components/Wizard.vue [hunk 2]
```diff
@@ -4,6 +4,7 @@ import AsyncButton from '@shell/components/AsyncButton';
 import { Banner } from '@components/Banner';
 import Loading from '@shell/components/Loading';
 import { stringify } from '@shell/utils/error';
+import LazyImage from '@shell/components/LazyImage';
```
Comment (cnotv) [inline shell/components/Wizard.vue:7]: I can see that it was present as markup and not imported as a component. How come you noticed it now and why was it not failing? 🤔

File: shell/components/CruResource.vue (hunk 1 above)
Comment (rak-phillip) [reply shell/components/CruResource.vue:590]: > That's something that has to be investigated because unless the custom footer has been removed along the way, it must have been added for sure somewhere.

The other instances of `form-footer` appear to be direct descendants of CruResource. In the description for this PR, it was mentioned that this behavior could be related to a change in how Vue3 deals with nested slots, or Vue3 is more strict about matching slots. 

I've created a barebones example to demonstrate this behavior[^1]:

```
<script setup>
import CruResource from './CruResource.vue';
import Wizard from './Wizard.vue';
</script>

<template>
  <CruResource>
    <template #cru-header>
      <h1>CRU HEADER</h1> 
    </template>
    <template #cru-body>
      <h2>CRU BODY</h2>
      <Wizard>
        <template #wiz-body>
          <h3>WIZ BODY</h3>
        </template>
        <template #wiz-footer>
          <template #cru-footer>
            <h3>NOT FAIL</h3>
          </template>
        </template>
      </Wizard>
    </template>
  </CruResource>
</template>
```

In the example above, `#cru-footer` is nested under `#wiz-footer`. This is invalid because the Wizard is unable to match a slot that named `cru-footer` and nothing renders (the template fails to compile in the example, but the overall concept appears to be the same). The component will render as expected we reorganize our slot usage so that `#cru-footer` is a child of `CruResource`.

I'm unable to locate a specific mention of this change in behavior in the vue 3 migration guide. If I had to guess, I think it would be a knock-on effect related to this change[^2]:

> `<template>` tags with no special directives (v-if/else-if/else, v-for, or v-slot) are now treated as plain elements and will result in a native `<template>` element instead of rendering its inner content.

[^2]: https://v3-migration.vuejs.org/breaking-changes/#other-minor-changes

[^1]: https://play.vuejs.org/#eNqtU11PwjAU/StNffBFtyj6opMEESPGiEGN0Swxc7tAdWuXfiBq+O+2Kx0bDHzxrfeec889be/9wZ0896YK8AkORMxJLpEAqfJ2SEmWMy5Rl6shCKZ4DGjEWYZ2Pb+SM8W7pyX7iXxHPCmJNnScwLcttLgOJGR5GknQEUJBRbJI6JQjoJ2Yq/0JRAnwBabRyUG7O3xEV73ORW8Y+DpEizq/prwm9MaSr4rMYSFzPrh41iKHS8BaL+OazCf5rstYqVb7qf/ipFrV0lVLDXojxmTlfg3GGxi26+3gAV12+jcrXTf1XU8Gi49yD1ZnBNX/1pkajPewFDGjIzL23gWjepB+TFGIY5blJAU+yCVhVIT4BBWIwaI0ZZ/XRU5yBXsuH08g/mjIv4uZyYX4joMAPoUQl5iM+BikhXv3tzDT5xLMWKJSzd4Cmpulyni0tHNFE227wivc9osBJ3T8IHozCVS4Sxmjhjkv+CHWw97dcvWl3ZZ3VNSFdK5fcWWn1hZy2/IkZOq+TqRMIhplcKZfs1ybECN/E8MM8jbcjl3JCHzbbXUKlqv+H9bNRjjrjc7cCm5yvlypP52/ToGb39S+W96xd4Tnv2TSnN8=

File: shell/components/Wizard.vue (hunk 2 above)
Comment (rak-phillip) [reply shell/components/Wizard.vue:7]: That's a good callout - this change resolves a warning that was printed to the console

```
[Vue warn]: Failed to resolve component: LazyImage
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <Wizard key=0 ref="Wizard" header-mode="create"  ... > 
  at <CruResource key=1 done-route="c-cluster-product-resource" mode="create"  ... > 
  at <CruGitRepo key=3 ref="comp" value= 
Object { type: "fleet.cattle.io.gitrepo", metadata: {…}, __clone: true, spec: {…}, … }
  ... > 
  at <AsyncComponentWrapper key=3 ref="comp" value= 
Object { type: "fleet.cattle.io.gitrepo", metadata: {…}, __clone: true, spec: {…}, … }
  ... > 
  at <Index component-testid="cluster-manager-create" class="outlet" > 
  at <ClusterResourceCreate class="outlet" onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< 
Proxy { <target>: {…}, <handler>: {…} }
 > > 
  at <RouterView key="/c/_/fleet/fleet.cattle.io.gitrepo/create" class="outlet" > 
  at <Default onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< 
Proxy { <target>: {…}, <handler>: {…} }
 > > 
  at <RouterView key=1 > 
  at <App>
```

I've updated the description to include this detail.

Comment (cnotv) [reply shell/components/Wizard.vue:7]: Wow, should we not make it fail in these cases instead of returning a warning? At least from the build.

File: shell/components/CruResource.vue (hunk 1 above)
Comment (cnotv) [reply shell/components/CruResource.vue:590]: The generated error in Vue SFC Playground is so confusing 😬

Comment (cnotv) [reply shell/components/CruResource.vue:590]: Ok, I mixed up when the named slot is defined and when it's used.
`name="form-footer"` and `#form-footer` mean the same.

**Review by cnotv — APPROVED** [review]
LGTM
