### PR TITLE
LabeledSelect: Displayed label does not update with options

### LINKED ISSUE #8149: LabeledSelect: Displayed label does not update with options
**Setup**
- Rancher version: any
- Browser type & version: any

**Describe the bug**
While changing the options for the `LabeledSelect` component, the selected displayed label does not update with them.

**To Reproduce**
- Identify any existing `LabeledSelect` component or create a new case with new options
- Update the options with an event (e.g. checkbox)

**Result**
Label stays the same.

**Expected Result**
New value is applied

**Screenshots**

https://user-images.githubusercontent.com/5009481/218461203-229738f8-0a6c-41b5-af7b-eec690024f1b.mov

### PR DESCRIPTION
**Pull request by cnotv**
### Summary
Fixes #8149

### Occurred changes and/or fixed issues
As in issue description.

To reproduce create/extend in the UI something like:

```ts
// ...
data: () {
  return {
    // ...
    toggleLabel:           false,
    myValue:               '',
  }
},


computed: {
  // ...

  myOptions() {
    return this.toggleLabel 
      ? [{ label: 'Old Label', value: '' }] 
      : [{ label: 'New Label', value: '' }];
  },
}
// ...
``` 

```html
      <LabeledSelect
        v-model="myValue"
        :options="myOptions"
      />
      <Checkbox
        v-model="toggleLabel"
        label="Toggle my label"
      />
```

### Technical notes summary
- Added unit tests for ensuring label updates
- Forced displayed label to match existing options with the same value

### Areas or cases that should be tested
Any dropdown as we have no story nor tests.

### Areas which could experience regressions
Any dropdown as we have no story nor tests.

### Screenshot/Video

https://user-images.githubusercontent.com/5009481/218513012-fa6f3a03-8f89-4fee-80d5-7951aa01da7d.mov

### CODE REVIEW

File: shell/components/form/LabeledSelect.vue [hunk 1]
```diff
@@ -159,6 +148,13 @@ export default {
         return;
       }
 
+      // Force to update the option label if prop has been changed
+      const isOutdated = !this.options.find(({ label }) => option.label === label);
```
Comment (mantis-toboggan-md) [inline shell/components/form/LabeledSelect.vue:152]: It's possible to work with options that do not have `label` and `value` properties by setting the `optionLabel` and `optionValue` props, so I think this needs to use eg 
`!this.options.find((opt) => option[this.optionLabel]===opt[this.optionLabel]);`

File: shell/components/form/LabeledSelect.vue [hunk 2]
```diff
@@ -159,6 +148,13 @@ export default {
...
+
+      if (isOutdated) {
+        return this.options.find(({ value }) => option.value === value)?.label;
```
Comment (mantis-toboggan-md) [inline shell/components/form/LabeledSelect.vue:155]: This should account for `this.localizedLabel` as lines 161-165 do. It should also reference `this.optionLabel` and `this.optionKey` (if defined)

**Review by mantis-toboggan-md — CHANGES_REQUESTED** [review]
I suggested a couple small changes due to `LabeledSelect` being used 1,001 different ways, otherwise the pr looks good

**Review by mantis-toboggan-md — APPROVED** [review]
