### PR TITLE
SCC: Online registration - Click Product name and jump to 404 page

### LINKED ISSUE #15375: SCC: Online registration - Click Product name and jump to 404 page
**Setup**
- Rancher version: v2.12.1（scc-operator:v0.1.2）
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**

After successful online registration, click Product name and jump to 404 page

**To Reproduce**

1. Register online using the correct registration code.
2. After successful registration, click the project name SUSE Rancher 2.12.1

**Result**
Redirect page 404.

**Expected Result**

Go to the correct page.

**Screenshots**

Image

Image

**Additional context**

### PR DESCRIPTION
**Pull request by cnotv**
### Summary
Fixes #15375

### Occurred changes and/or fixed issues

- Added ID mapped value to registration
- Replaced link to router-link
- Ensured correct path by routing resolution
- Added test to link (resolution is out of scope)

### Screenshot/Video

Screenshot 2025-09-22 at 12 38 05

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes
- [x] The PR has been reviewed in terms of Accessibility

### CODE REVIEW

File: pkg/rancher-prime/pages/Registration.vue [hunk 1]
```diff
@@ -213,11 +224,13 @@ onMounted(async() => {
           />
         </div>
         <div>
-          <a
-            v-if="registration.resourceLink"
-            :href="registration.resourceLink"
-            target="_blank"
-          >{{ registration.product }}</a>
+          <router-link
```
Comment (richard-cox) [inline pkg/rancher-prime/pages/Registration.vue:227]: The check to confirm the user can see the local cluster wasn't added (referenced in the slack thread). Can users who don't have access to that cluster access this page (i couldn't specifically find somewhere that limited access to admins)?

Comment (cnotv) [reply pkg/rancher-prime/pages/Registration.vue:227]: Registration page is intended for admin users AFAIK, so any request is supposed to be as well.

Comment (cnotv) [reply pkg/rancher-prime/pages/Registration.vue:227]: You have also to remember that this page requires together Namespace, Secrets, and Registration. These all 3 necessary for the existing logic to work.

Comment (richard-cox) [reply pkg/rancher-prime/pages/Registration.vue:227]: I've double checked and there's no gates on permissions (created https://github.com/rancher/dashboard/issues/15510).

Depending on how that pans out this check for access to the local cluster may still be needed, but could be done as part of that change.

Access to the local cluster (fetching local cluster resources directly from that cluster) is slightly different to accessing management style resources (fetching local cluster resources indirectly via /v1). Only admins will normally have the former, whilst others are likely to have some kind of access to resources in the later. For example this is how standard-users can create cluster resources in the local cluster without being able to access all resources within it.

Comment (cnotv) [reply pkg/rancher-prime/pages/Registration.vue:227]: Ok but that page is still planned to be restricted to admins only.

Also notifications are supposed to be for admin only.

The whole thing is only for admin.

Comment (cnotv) [reply pkg/rancher-prime/pages/Registration.vue:227]: Can we then resolve this one?

Comment (richard-cox) [reply pkg/rancher-prime/pages/Registration.vue:227]: Given the issue and slack discussion, yes. We'll still need to be aware of this if the page is opened up in read-only mode for non-admins
