### PR TITLE
Fix Featured Charts Carousel

### LINKED ISSUE #12480: Navigation in the apps charts carousel is not working correctly
**Setup**
- Rancher version: v2.10-212d8b6e92992235d791d8f2aaea8436ab4f6b77-head
- Browser type & version: Version 130.0.6723.70 (Official Build) (arm64)

**Describe the bug**
The charts displayed in the carousel animation are misaligned leading to the first one (Vault) not being clickable at all and many blank spaces are shown in the carousel navigation

**To Reproduce**
1- From the Rancher UI, select a cluster in the side menu bar
2- From the cluster menu options, go to Apps > Charts
3- Observe how the carousel navigation is misaligned
4- Use the arrows to navigate the carousel

**Result**
User is not able to select the first chart that is displayed in the carousel, whereas there are a few blank spaces when navigating the charts carousel in both ways

**Expected Result**
Carousel must display an extension at a time and an chart should be displayed and clickable for each frame of the carousel, with no blank spaces

**Screenshots**

https://github.com/user-attachments/assets/1f674312-89e7-412e-8c5b-896b9e39b23d

### PR DESCRIPTION
**Pull request by momesgin**
### Summary
Fixes #12480 

### Occurred changes and/or fixed issues

Unfortunately css translate properties are treated differently in different browsers, so the css left property is used instead for consistent rendering.

### Technical notes summary

- Added `isTransitioning` flag to block fast clicking on the prev/next buttons.
- Added `shouldDisableTransition` to create the illusion of an infinite carousel.
- Used refs instead of DOM selectors.
- Fixed disabled styling for next/prev buttons.
- Removed some unused code.
- Added some unit tests

### Areas or cases that should be tested

Test it on different browsers.

### Screenshot/Video

https://github.com/user-attachments/assets/7087158e-6b23-4ab9-9016-09bebf16b4e0

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: shell/components/Carousel.vue [hunk 1]
```diff
@@ -120,23 +135,21 @@ export default {
   },
 
   mounted() {
-    const slideTrack = document.getElementById('slide-track');
+    const slideTrack = this.$refs.slider;
```
Comment (rak-phillip) [inline shell/components/Carousel.vue:138]: Thanks for refactoring this as a ref 💯

File: shell/components/Carousel.vue [hunk 2]
```diff
@@ -227,7 +238,7 @@ export default {
     </div>
     <div
       class="controls"
-      :class="{'disable': sliders.length === 1}"
+      :class="{'disabled': sliders.length === 1}"
```
Comment (rak-phillip) [inline shell/components/Carousel.vue:241]: nit: Shouldn't this be a `v-if`? What benefit do we get from the `disabled` class?

**Review by rak-phillip — APPROVED** [review]
LGTM, the carousel behaves much better than it did before!

File: shell/components/Carousel.vue (hunk 2 above)
Comment (momesgin) [reply shell/components/Carousel.vue:241]: thanks for finding this, here I just wanted to use better wording for that class and make it consistent in that file, you're right we don't need to render this at all, will update the code

Comment (momesgin) [reply shell/components/Carousel.vue]: done
