### PR TITLE
Select Member, add tooltip

### LINKED ISSUE #6925: Long user/display names will overflow the SelectPrincipal container
**Setup**
- Rancher version: `v2.6-a3b5237ce1da4228c97df7552d57464c64947b3b-head`
- Browser type & version: `FF 104.0`

**Describe the bug**

Long user names and display names will overflow the `SelectPrincipal` component container, if the name is long enough it will grow passed the window width. 
Recognized with [this comment](https://github.com/rancher/dashboard/pull/6909#pullrequestreview-1111292895).

**To Reproduce**

1. Create a user with a long user name and display name
  - user: long-username-hyz8ql12oa-0b2ewxkh29-vjnzbyqcmd-ohydd9bi3x-7rcje6k5hp-kr9ld7r1si
  - display name: long-displayname-e422ilkhqj-y4rzk02abt-c8m0scwcwl-reliod8oja-hj1jvu31mm-k28d9zppm1
2. Navigate to the local cluster, edit the config of a project and add the created user as a Project Member 

**Result**
The name will overflow the width of the container.

long-user-name

**Expected Result**

The user name should fold to fit within the container.

**Additional context**

This seems to appear in any instance where the `SelectPrincipal` component is used, for example adding a Cluster Member to a cluster:

long-cluster-member

### PR DESCRIPTION
**Pull request by torchiaf**
Signed-off-by: Francesco Torchia <francesco.torchia@suse.com>

### Summary
Fixes #6925

image

### CODE REVIEW

File: shell/components/auth/SelectPrincipal.vue [hunk 1]
```diff
@@ -41,6 +41,11 @@ export default {
       type:    Boolean,
       default: false
     },
+
+    showTooltip: {
```
Comment (mantis-toboggan-md) [inline shell/components/auth/SelectPrincipal.vue:45]: Overall the behavior of the tooltip looks good to me, but I think it can be applied to almost all uses of SelectPrincipal because they (almost all) have the same issue as the cluster membership editor. I think whether or not to show the tooltip can be determined by the `retainSelection` prop instead of a new prop. This would enable the tooltip for project membership editing and group role assignment.


 When `retainSelection` is `false` the selected principal is not shown inside the select component and name length looks like a non-issue to me; there's a lot of vertical space in the form for the principal name to wrap around

Screen Shot 2022-12-15 at 1 39 14 PM

**Review by mantis-toboggan-md — CHANGES_REQUESTED** [review]

File: shell/components/auth/SelectPrincipal.vue (hunk 1 above)
Comment (torchiaf) [reply shell/components/auth/SelectPrincipal.vue:45]: Make sense to me! thanks.

**Review by mantis-toboggan-md — APPROVED** [review]
LGTM
