### PR TITLE
When creating a resource, limit the namespace options based on filters in top nav

### LINKED ISSUE #6094: When creating a resource, limit the namespace options based on filters in top nav
Internal reference: SURE-4311
Reported in 2.6.3

Issue description:

When creating a new workload in the new 2.6 UI, the "namespace" dropdown has no option for creating a new namespace. The 2.5 UI allows this, with a clickable link under the namespace dropdown that lets the user specify a new namespace for the workload.

Additionally, the namespace dropdown lists namespaces that aren't even in the selected project filter! This is very confusing for users, especially new ones that are not very familiar with Kubernetes yet.

Repro steps:

- Filter by project
- Create a new deployment in that project
- No option to create a namespace at the time of creating the deployment
- All namespaces are shown in the drop down for namespaces (even those not in the project).

Workaround:
Create a namespace separately, filter through list to find namespace

### PR DESCRIPTION
**Pull request by cnotv**
### Summary
Fixes #6094

### Occurred changes and/or fixed issues
Filtered NS options inside resource form, based on selection from top navigation filter.

### Technical notes summary
- Replaced component filtering logic with state getter
- Added comments to existing logic
- Added unit tests for the component and state
- Moved logic for other filters
- Split function used by getters in more understandable bits
 
### Areas or cases that should be tested
In resource NS filter inspect the list of the available values based on the conditions:
- Filter by user NS
- Display all NS
- Filter by NS inside projects
- Filter by single NS
- Hide/show Rancher system NS
- Local and provisioned clusters
- Filter NS which are readonly as the user has no rights to create resources ([follow these steps to reproduce](https://github.com/harvester/harvester/issues/1986#issuecomment-1261745712))
- Filter NS for products (e.g. Harvester) which have flag `hideSystemResources`
- Filter NS for Harvester NS with flag `isFleetManaged `

### Screenshot/Video

Namespaces dropdown filtering Rancher system items

https://user-images.githubusercontent.com/5009481/225085965-f0cef244-41f2-4aa0-8ecf-27764a93147e.mov

Dropdown for user with role `Cluster Member` and `View All Projects` ([as indicated here](https://github.com/harvester/harvester/issues/1986#issuecomment-1261745712)) while creating a resource 

https://user-images.githubusercontent.com/5009481/226931851-34e42a08-eaeb-404d-a38a-c0e4a95348f0.mov

### CODE REVIEW

File: shell/components/form/NameNsDescription.vue [hunk 1]
```diff
@@ -220,39 +220,18 @@ export default {
...
-      const namespaces = this.namespacesOverride || this.$store.getters[`${ currentStore }/all`](this.namespaceType);
-      const filterNamespace = this.$store.getters['allNamespaces'];
-
-      const filtered = namespaces.filter( this.namespaceFilter || ((namespace) => {
-        // By default, include the namespace in the dropdown.
-        let out = true;
-
-        if (this.currentProduct?.customNamespaceFilter && this.currentProduct?.inStore) {
-          out = filterNamespace.find(NS => NS.metadata.name === namespace.metadata.name);
-        } else if (this.currentProduct?.hideSystemResources) {
```
Comment (cnotv) [inline shell/components/form/NameNsDescription.vue:234]: It is unclear if the logic related to fleet matches the one in the store, as they check different values while the condition itself is quite similar.

File: shell/components/form/NameNsDescription.vue [hunk 2]
```diff
@@ -220,39 +220,18 @@ export default {
...
-          // Filter out the namespace
-          // if it is a system namespace or if it is managed by
-          // Fleet.
-          out = !namespace.isSystem && !namespace.isFleetManaged;
-        }
-
-        if (this.mode === _CREATE) {
-          out = out && !!namespace.links.update;
```
Comment (cnotv) [inline shell/components/form/NameNsDescription.vue:242]: Not so sure if we are removing anything here.

Comment (mantis-toboggan-md) [reply shell/components/form/NameNsDescription.vue:242]: If a namespace is missing `links.update` the current user doesn't have permission to create resources within it, so it shouldn't be shown as an option in `NameNsDescription`. Read-only namespaces are still a valid choice in the `NamespaceFilter` since the user would be able to see resources within the namespace, so I think it makes sense to keep this logic within `NameNsDescription`

File: shell/components/form/NameNsDescription.vue (hunk 1 above)
Comment (mantis-toboggan-md) [reply shell/components/form/NameNsDescription.vue:234]: I see the namespace store logic is updated to account for the user pref to toggle visibility of system namespaces but `hideSystemResources` should still be checked as it works independently

File: shell/components/form/NameNsDescription.vue (hunk 2 above)
Comment (mantis-toboggan-md) [reply shell/components/form/NameNsDescription.vue:242]: I'm not sure why `isFleetManaged` is checked here but not in `NamespaceFilter` - I think this was added for Harvester specifically, maybe @WuJun2016 knows why we would be filtering fleet-managed namespaces from `NameNsDescription` and the namespace list view but not `NamespaceFilter`

File: shell/components/form/NameNsDescription.vue (hunk 1 above)
Comment (cnotv) [reply shell/components/form/NameNsDescription.vue:234]: But what is `hideSystemResources` for? in which case we have to check it?

File: shell/components/form/NameNsDescription.vue (hunk 2 above)
Comment (cnotv) [reply shell/components/form/NameNsDescription.vue:242]: `NamespaceFilter` does not use the action, although we have to flag them as readonly in case we want to switch it to this as well. I'll have to think about this option, maybe by simply using the false value. 
The returned namespaces do not provide informations about the links, so or we extend it and change the logic or we set it in the state.

Comment (cnotv) [reply shell/components/form/NameNsDescription.vue:242]: What does `isFleetManaged` stand for?

File: shell/components/form/NameNsDescription.vue (hunk 1 above)
Comment (mantis-toboggan-md) [reply shell/components/form/NameNsDescription.vue:234]: `hideSystemResources` allows a product to specify that system namespaces should be hidden _all_ the time - added for the sake of Harvester but could be used by any product potentially. I think it should be checked in the namespace store logic instead of every component that filters by ns as it currently is but either way it shouldn't be ignored in the NameNsDescription dropdown

File: shell/components/form/NameNsDescription.vue (hunk 2 above)
Comment (WuJun2016) [reply shell/components/form/NameNsDescription.vue:242]: > 

@mantis-toboggan-md   This filtering rule was used by the old version of the `harvester`, although it is no longer in use in the `new version`. However, I believe it should still be retained now because we need to be compatible with `older` `harvester` versions, and we may remove it at some point in the future （such as rancher 2.8.0).

Comment (cnotv) [reply shell/components/form/NameNsDescription.vue:242]: @mantis-toboggan-md how can I create a namespace without `links.update`, so I can do a QA?

**Comment by cnotv** [comment]
For what is worth it, I noticed that the logic for `customNamespaceFilter` (which I still don't get where it's coming from) seems to be used also for `ExplorerProjectsNamespaces`, `Header` and `NamespaceFilter` components.
Here's an issue where we address and unify the logic for the filtering instead of have them in 4+ places.

https://github.com/rancher/dashboard/issues/8469

File: shell/components/form/NameNsDescription.vue (hunk 2 above)
Comment (n313893254) [reply shell/components/form/NameNsDescription.vue:242]: Hi, @cnotv. You could follow the "Explorer Test case" to QA it. https://github.com/harvester/harvester/issues/1986#issuecomment-1261745712.

**Review by mantis-toboggan-md — APPROVED** [review]
LGTM - tested in cluster explorer, latest harvester plugin build, and harvester 1.0.3 plugin build
