### PR TITLE
Fix app bar overlaps issue

### LINKED ISSUE #9673: APP Bar overlaps with the cluster management/virtualization/CD menu.
**Setup**
- Rancher version:
- Rancher UI Extensions:
- Browser type & version:
Screenshot from 2023-09-11 15-38-18

**Describe the bug**

The new APP Bar overlaps with the menu. This overlap happens with all the menu.

**To Reproduce**

1. Use rancher-latest with rancherImageTag=v2.8-head.
```sh
helm upgrade --install rancher --devel rancher-latest/rancher --namespace cattle-system --set hostname=$hostname --set replicas=1 --set bootstrapPassword=adminadmin --create-namespace --set rancherImageTag=v2.8-head 
```
2. Visit Cluster Management/Virtualization Management/Fleet page.

**Result**
1. The APP Bar overlaps with the menu.

**Expected Result**

1. The APP Bar should not overlap any menu.

**Screenshots**
Screenshot from 2023-09-11 14-40-37

**Additional context**

_Originally posted by @valaparthvi in https://github.com/rancher/dashboard/issues/9659#issuecomment-1713486111_

### PR DESCRIPTION
**Pull request by bisht-richa**
### Summary
Fixes #9673

Fixed APP Bar overlaps bug in Firefox. 

### Screenshot/Video

Screenshot 2023-09-12 at 16 36 31

=====================

Screenshot 2023-09-12 at 16 37 09

=====================

Screenshot 2023-09-12 at 16 36 43

=====================

Screenshot 2023-09-12 at 16 36 59

### CODE REVIEW

File: shell/layouts/default.vue [hunk 1]
```diff
@@ -237,7 +237,7 @@ export default {
     <div
       v-if="managementReady"
       class="dashboard-content"
-      :class="{[pinClass]: true}"
+      :class="{[pinClass]: true, 'dashboard-padding-left': isRancherInHarvester || isMultiCluster || !isSingleProduct}"
```
Comment (richard-cox) [inline shell/layouts/default.vue:240]: it looks like these all match the if statement for `TopLevelMenu`. i think it's a sound idea to add padding using the same condition.

however they should be done in a common way to avoid regression. as `isRancherInHarvester`, `isMultiCluster` and `isSingleProduct` all come from the root store, suggest adding a `showTopLevelMenu` getter there which is used in the three new places and in the header for TopLevelMenu

**Review by richard-cox — CHANGES_REQUESTED** [review]

**Review by richard-cox — APPROVED** [review]
