### PR TITLE
fixed some console errors for standard user

### LINKED ISSUE #12478: Errors thrown in console for some components if user doesn't have permissions
**Setup**
- Rancher version: 2.10
- Rancher UI Extensions: N/A
- Browser type & version: N/A

**Describe the bug**

Some pages show error in the console when opened as a non-admin user

**To Reproduce**

Create a new standard user with the following custom roles
 { resource: "fleetworkspaces", verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]},
 { resource: "gitrepos", verbs: ["list"]},
 { resource: "bundles", verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]},

Go to Cluster management -> Advanced -> Pod Security Admissions
**Result**
Uncaught (in promise) Error: Unknown schema for type: storage.k8s.io.storageclass
    at getters.js:24:1
    at Object.<anonymous> (getters.js:139:1)
    at Store.findAll (actions.js:196:1)
    at Array.wrappedActionHandler (vuex.esm-bundler.js:305:1)
    at Store.dispatch (vuex.esm-bundler.js:1032:1)
    at Store.boundDispatch [as dispatch] (vuex.esm-bundler.js:914:1)
    at Proxy.fetch (management.cattle.io.podsecurityadmissionconfigurationtemplate.vue:27:1)
    at Proxy.$_fetch (fetch.client.js:73:1)
    at Proxy.$fetch (fetch.client.js:53:1)
    at Proxy.beforeMount (fetch.client.js:46:1)

Cluster management -> Drivers -> Node Drivers
**Result**
entry-helpers.js:40 TypeError: Cannot read properties of undefined (reading 'activate')
    at get _availableActions (nodedriver.js:21:1)
    at Reflect.get (<anonymous>)
    at Object.get (reactivity.esm-bundler.js:492:1)
    at get availableActions (resource-class.js:842:1)
    at Reflect.get (<anonymous>)
    at Object.get (reactivity.esm-bundler.js:492:1)
    at Proxy.bulkActionsForSelection (selection.js:73:1)
    at ReactiveEffect.run (reactivity.esm-bundler.js:190:1)
    at get value (reactivity.esm-bundler.js:1171:1)
    at Object.get [as bulkActionsForSelection] (

**Expected Result**

No error should be shown in the console

Continuous delivery -> Git repos -> Create a new repo -> Edit YAML this repo 
**Result**
Page fails to load with the following error in the console:
entry-helpers.js:40 TypeError: Cannot read properties of null (reading 'doneOverride')
    at Proxy.render (index.vue:420:1)
    at renderComponentRoot (runtime-core.esm-bundler.js:914:1)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5720:1)
    at ReactiveEffect.run (reactivity.esm-bundler.js:190:1)
    at instance.update (runtime-core.esm-bundler.js:5763:1)
    at callWithErrorHandling (runtime-core.esm-bundler.js:173:1)
    at flushJobs (runtime-core.esm-bundler.js:406:1)

**Expected Result**
Page should load and error banner should be displayed 

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by eva-vashkevich**
### Summary
Fixes #12478

Added some error catching to
- node drivers
- pod security admissions
- edit YAML for fleet git repos

### Areas or cases that should be tested

Create a new standard user with this custom roles:
 { resource: "fleetworkspaces", verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]},
 { resource: "gitrepos", verbs: ["list"]},
 { resource: "bundles", verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]},

Log in as this user. 
Going to the following pages shouldn't throw any errors in the console:
Cluster management -> Advanced -> Pod Security Admissions
Cluster management -> Drivers -> Node Drivers

Continuous delivery -> Git repos -> Edit YAML for existing git repo should open with an error banner

### Areas which could experience regressions

None

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: shell/components/ResourceDetail/index.vue [hunk 1]
```diff
@@ -209,13 +212,23 @@ export default {
...
-
-      initialModel = await store.dispatch(`${ inStore }/clone`, { resource: liveModel });
-
       if ( as === _YAML ) {
-        yaml = await getYaml(this.$store, liveModel);
+        try {
+          yaml = await getYaml(this.$store, liveModel);
+        } catch (e) {
+          this.errors.push(e);
+        }
```
Comment (rak-phillip) [inline shell/components/ResourceDetail/index.vue:231]: It looks like we can wrap all of these statements into a single `try...catch` block:

```
      try {
        if (realMode === _VIEW) {
          model = liveModel;
        } else {
          model = await store.dispatch(`${ inStore }/clone`, { resource: liveModel });
        }

        initialModel = await store.dispatch(`${ inStore }/clone`, { resource: liveModel });

        if ( as === _YAML ) {
          yaml = await getYaml(this.$store, liveModel);
        }
      } catch (e) {
        this.errors.push(e);
      }
```

File: shell/components/ResourceDetail/index.vue [hunk 2]
```diff
@@ -229,7 +242,9 @@ export default {
     }
 
     // Ensure common properties exists
-    model = await store.dispatch(`${ inStore }/cleanForDetail`, model);
+    try {
+      model = await store.dispatch(`${ inStore }/cleanForDetail`, model);
+    } catch (e) {}
```
Comment (rak-phillip) [inline shell/components/ResourceDetail/index.vue:247]: Are we intentionally performing a noop in the `catch` block?

**Review by rak-phillip — CHANGES_REQUESTED** [review]

File: shell/components/ResourceDetail/index.vue (hunk 2 above)
Comment (eva-vashkevich) [reply shell/components/ResourceDetail/index.vue]: Added a push to errors

**Review by rak-phillip — APPROVED** [review]
