### PR TITLE
fix issue banner extensions prime users not being displayed

### LINKED ISSUE #12376: Extensions banner for Rancher Prime is broken (not being displayed)
**Setup**
- Rancher version: 2.9.3 (prime)
- Rancher UI Extensions: master/head
- Browser type & version: any

**Describe the bug**

The Banner to warn users that they can add new repos for extensions `There are new extensions repositories available. To enable these repositories, click the button on the right.`  when entering the main extensions screen is **NOT** being displayed.

The culprit is this unmet condition https://github.com/rancher/dashboard/blob/master/shell/pages/c/_cluster/uiplugins/index.vue#L157 and the root cause is https://github.com/rancher/rancher/pull/45894 .

We should also check if these other settings https://github.com/rancher/rancher/pull/45894 are broken on the UI side as well and fix them.

**To Reproduce**

Provision a Rancher Prime 2.9.3 system and enter the main extensions screen

**Result**
Banner not being displayed on the top of the page

**Expected Result**

Banner should be displayed on the top of the page

**Screenshots**

https://github.com/user-attachments/assets/e1d3489a-4656-442d-a261-c44aa36e2c46

**Additional context**

### PR DESCRIPTION
**Pull request by aalves08**
### Summary
Fixes #12376 

### Occurred changes and/or fixed issues

- fix issue banner extensions prime users not being displayed due to setting value being defined as an empty string by backend 
- add e2e test

### Areas or cases that should be tested

- Check issue description for repro steps

### Screenshot/Video

Screenshot 2024-10-28 at 17 37 09
Screenshot 2024-10-28 at 17 36 43

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: shell/pages/c/_cluster/uiplugins/index.vue [hunk 1]
```diff
@@ -615,7 +615,7 @@ export default {
     },
 
     updateAddReposSetting() {
-      if (this.addExtensionReposBannerSetting?.value === 'true') {
+      if (this.addExtensionReposBannerSetting?.value === 'true' || this.addExtensionReposBannerSetting?.value === '') {
```
Comment (rak-phillip) [inline shell/pages/c/_cluster/uiplugins/index.vue:618]: It looks like the initial value for `addExtensionReposBannerSetting` is `undefined`, so that means all possible values for `addExtensionReposBannerSetting` include:

- `'true'`
- `'false'`
- `''`
- `undefined`

Is there any scenario where we might want to update if `this.addExtensionReposBannerSetting` is also `undefined`?

Comment (aalves08) [reply shell/pages/c/_cluster/uiplugins/index.vue:618]: @rak-phillip the initial value for `addExtensionReposBannerSetting` is `''` in `2.9.3` but I can add `undefined` if want... Where have you seen that? Which system?

Screenshot 2024-10-29 at 08 22 08

Comment (aalves08) [reply shell/pages/c/_cluster/uiplugins/index.vue]: I've added the `undefined` condition. We need to move this forward. Thanks for the review @rak-phillip ! 🙏

**Review by rak-phillip — DISMISSED** [review]
LGTM

File: shell/pages/c/_cluster/uiplugins/index.vue (hunk 1 above)
Comment (aalves08) [reply shell/pages/c/_cluster/uiplugins/index.vue]: 🤦  thanks @rak-phillip !

**Review by nwmac — APPROVED** [review]
