### PR TITLE
The highlighted cluster in the App Bar retains its highlighting even when clicking on an item from the bottom category of the App Bar

### LINKED ISSUE #10576: The highlighted cluster in the App Bar retains its highlighting even when clicking on an item from the bottom category of the App Bar
**Setup**
- Rancher version: 2.9-head

**To Reproduce**

1. Select any cluster from the App bar
2. Click on any icons from the bottom category on the App bar, e.g. Global Settings icon

**Result**
- Only one item should be highlighted

**Expected Result**
- Two items are highlighted at the same time

**Screenshots**

image

### PR DESCRIPTION
**Pull request by aalves08**
### Summary
Fixes #10576 

### Occurred changes and/or fixed issues

- fix issue with double active main menu items in app bar 
- add sneaky fix for Cluster and Project Members menu item not being highlighted
- add e2e test to prevent regression

### Areas or cases that should be tested

- click on `local` cluster in app bar
- after than, go to one of the products that uses the `local` cluster for context such as `Global Settings`, `Extensions` or `Users & Authentication` and make sure the `local` cluster app bar menu is not highlighted as well.
- Try other page changes to make sure no double highlighting is occurring in the app bar

### Screenshot/Video

**Before**
before

**After**
after

**Cluster and Project members sneaky fix**
Screenshot 2024-05-21 at 11 59 58

### Checklist

- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: shell/components/nav/TopLevelMenu.vue [hunk 1]
```diff
@@ -259,6 +259,40 @@ export default {
...
+        });
+
+        if (!activeFound) {
+          const currActiveMenu = menuSectionItems.find((item) => this.checkActiveRoute(item, isClusterCheck));
+
+          if (currActiveMenu) {
+            activeFound = true;
+            currActiveMenu.isMenuActive = true;
+          }
+        }
```
Comment (rak-phillip) [inline shell/components/nav/TopLevelMenu.vue:291]: I think that performing the `find` might be a redundant since we're already iterating over `menuSectionItems` to set the active state to false

```suggestion
        menuSectionItems.forEach((item) => {
          item.isMenuActive = false;
          
          if (!activeFound && this.checkActiveRoute(item, isClusterCheck)) {
            activeFound = true;
            item.isMenuActive = true;
          }
        });
```

**Review by rak-phillip — DISMISSED** [review]
LGTM - I left one comment related to using a single loop to track the active state, but I think this comment is optional and doesn't affect functionality whatsoever.

Unrelated to this change, I did note that Cluser and Project Members does not receive an active state when navigating to it

cluster-and-project-members-active

**Comment by aalves08** [comment]
@rak-phillip committed your code suggestion. Thanks for the review! 🙇 

Added sneaky fix for Cluster and Project Members menu item not being highlighted (check last [commit](https://github.com/rancher/dashboard/pull/11055/commits/b3a167dbebf3002d02b898e94faf419435725f13))

Requested final approval 🙏

**Review by rak-phillip — APPROVED** [review]
LGTM
