### PR TITLE
Project/namespace fixes

### LINKED ISSUE #3175: After deleting a Project with a namespace the UI shows the namespace in the Not in a Project group but the Project is now displayed empty
Rancher version `2.6 master-head (05/07/2021)` _b2f8824_

Create a Project I set also the resource quotas fields in the UI
Create a namespace from the UI
Delete the project from the UI

The Namespace is moved to `Not in a Project` but the Project is displayed in the UI as empty

UI Screenshot after deleting Project `test3` (namespace `test3` is moved to `Not in Project`)

Screen Shot 2021-06-07 at 4 27 08 PM

Screenshot after refreshing UI

Screen Shot 2021-06-07 at 4 27 22 PM

### PR DESCRIPTION
**Pull request by mantis-toboggan-md**
#3175  - per discussion w/ Darren, removing projects through Steve is acceptable. This avoids issues with the project list not refreshing correctly when deleting a project in a downstream cluster
 
#3422 - this ticket says remove the 'Move' action from namespace detail but I don't see why users shouldn't be allowed to change the project from this view, so I just made it work correctly there instead.

Other things noticed and addressed here:
- projects were being created without saving `defaultBinding` (aka the current user) as owner
- namespace edit page exploded for namespaces formerly in projects. The project label on each namespace sticks around after the project is deleted (whether it's done through Steve or Norman). In such instances the detail page correctly shows no project for the namespace; I've updated the edit page to account for this possibility as well.

### CODE REVIEW

File: edit/namespace.vue [hunk 1]
```diff
@@ -31,14 +33,24 @@ export default {
...
-      project,
-      containerResourceLimits: this.value.annotations[CONTAINER_DEFAULT_RESOURCE_LIMIT] || this.getDefaultContainerResourceLimits(project)
-    };
+    // namespaces' project label remains when a project has been deleted: verify this project still exists
+    if (!project && this.value?.metadata?.labels?.[PROJECT]) {
+      delete this.value.metadata.labels[PROJECT];
+      projectName = null;
+    }
+
+    if (this.mode === 'edit') {
```
Comment (richard-cox) [inline edit/namespace.vue:47]: This breaks a few things when in view mode

**Review by richard-cox — CHANGES_REQUESTED** [review]
I hit an issue when editing via yaml, though it looks like it's unrelated to this pr (#3500). Apart from two comments, looks good

File: edit/namespace.vue (hunk 1 above)
Comment (mantis-toboggan-md) [reply edit/namespace.vue]: This if block...doesn't need to be here at all. I don't know how that got there. Removed.

File: components/FleetSummary.vue [hunk 2]
```diff
@@ -69,7 +74,7 @@ export default {
     <div v-for="(v, k) in counts" :key="k" class="col span-2-of-10">
       <CountBox
         :count="v['count']"
-        :name="capitalize(k)"
+        :name="t(`${stateKey}.${k}`) || capitalize(k)"
```
[the remark this answers is not in the document]
Comment (mantis-toboggan-md) [reply components/FleetSummary.vue]: updated to use `withFallBack` in the computed prop

**Review by richard-cox — APPROVED** [review]
