### PR TITLE
[rancher-components] fix lint warnings

### LINKED ISSUE #7596: [pkg/rancher-components] resolve linter warnings
# Description

`yarn lint:lib` returns some linter warnings during CI runs.

As mention to: https://github.com/rancher/dashboard/pull/7578#pullrequestreview-1198958523

### PR DESCRIPTION
**Pull request by torchiaf**
Signed-off-by: Francesco Torchia <francesco.torchia@suse.com>

### Summary
Fixes #7596

### CODE REVIEW

File: pkg/rancher-components/src/components/Form/Checkbox/Checkbox.vue [hunk 1]
```diff
@@ -114,6 +114,9 @@ export default Vue.extend({
   },
 
   computed: {
+    modelValue() {
```
Comment (rak-phillip) [inline pkg/rancher-components/src/components/Form/Checkbox/Checkbox.vue:117]: A data prop would be more appropriate for `modelValue` if we intend to mutate it via `v-model`.

We should consider computed props to be getters. We can provide a setter if we need it, but I don't see the benefit in this scenario

https://v2.vuejs.org/v2/guide/computed.html#Computed-Setter

Comment (rak-phillip) [reply pkg/rancher-components/src/components/Form/Checkbox/Checkbox.vue]: Explicitly specifying the getter still doesn't fix the issue at hand. We are still mutating `modelValue` without a setter as well as mutating the `value` prop. The computed prop implementation works, but just because we are mutating `value` in a roundabout way and the vue template compiler isn't picking up on it. 

I don't think we need to be tracking state locally at all. I hope you don't mind, but I took a closer look and ended up amending this PR so that we could address the root issue.
