### PR TITLE
fix(rc-dropdown): fix memory leak by removing pointerdown listener co…

### LINKED ISSUE #16604: [backport v2.12.7] [BUG][Dashboard] Memory keeps growing and eventually OOM when listing Pods in a namespace with continuously restarting Deployments (even with server-side pagination)
This is a backport issue for https://github.com/rancher/dashboard/issues/16425, automatically created via [GitHub Actions workflow](https://github.com/rancher/dashboard/actions/runs/21830958365) initiated by @rak-phillip

Original issue body:

## Summary

Rancher Dashboard shows continuous browser memory growth when opening the Pods list for a namespace that contains multiple Deployments whose Pods keep restarting (CrashLoopBackOff). The browser memory keeps increasing over time until the UI becomes unresponsive or hits OOM.

## Environment

* Rancher version: `v2.12.5` `v2.13.1`

## Steps to Reproduce

1. Create a namespace:

   ```bash
   kubectl create ns stress-auto
   ```
2. Apply the following workloads (example uses 11 replicas and a container that exits to force continuous restarts). Create several Deployments if you want higher churn (e.g. target-app-1..target-app-5).

   ```yaml
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: target-app-1
     namespace: stress-auto
   spec:
     replicas: 11
     selector:
       matchLabels:
         app: target-1
     template:
       metadata:
         labels:
           app: target-1
       spec:
         containers:
         - name: crash
           image: busybox:1.36
           command: ["sh","-c","echo crash; sleep 1; exit 1"]
   ```
3. Wait until Pods are in CrashLoopBackOff / restarting.
4. Open Rancher Dashboard:

   * Go to **Cluster Explorer → Workloads → Pods**
   * Filter/Scope to namespace `stress-auto`
5. Keep the page open for a few minutes (no interaction required, but scrolling/refreshing makes it faster).

Image

Image

## Actual Result

* Browser memory continuously increases (JS heap / total memory).
* The Pods page becomes sluggish and eventually the tab crashes (OOM).
* This happens even when server-side pagination (`ui-sql-cache`) is enabled.

## Expected Result

* Memory usage should stabilize after initial load.
* The UI should not keep accumulating memory simply by viewing a namespace with high churn Pods.

## Notes / Observations

* The issue seems correlated with continuous updates (Pod restarts).

* Chrome DevTools:

  * Performance recording (30–60s) showing JS heap trend
  * Heap snapshots: compare after 30s vs after 5min

## Workaround

* Refreshing the tab

### PR DESCRIPTION
**Pull request by smallteeths**
### Summary
Fixes #16604
### Occurred changes and/or fixed issues

* Fixed a memory leak in the `useClickOutside` composable where a `pointerdown` event listener was added on mount but not removed on unmount due to an incorrect event name (`pointerDown`).

### Technical notes summary

* Corrected the `removeEventListener` call to use the exact same event name registered by `addEventListener`:

  * `addEventListener('pointerDown', ...)`
  * `removeEventListener('pointerDown', ...)` ✅

### Areas or cases that should be tested

* Dropdown behavior:

  * Open/close dropdown and ensure click-outside closes the menu as expected.
  
* High-churn list scenarios (repro for the leak):
    
  1. Create many pod that keeps restarting.  
  2. Navigate to event page.
  3. Observe that browser memory stabilizes and does not continuously grow.
  
* Local browser tested: **Chrome**

### Screenshot/Video

截屏2026-01-22 12 10 28

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes
- [x] The PR has been reviewed in terms of Accessibility
- [x] The PR has considered, and if applicable tested with, the three Global Roles `Admin`, `Standard User` and `User Base`

### CODE REVIEW

**Comment by richard-cox** [comment]
The component was introduced in 2.10 via https://github.com/rancher/dashboard/pull/12076

File: shell/composables/useClickOutside.ts [hunk 1]
```diff
@@ -71,7 +71,7 @@ export const useClickOutside = <T extends OnClickOutsideOptions>(
 
   onMounted(() => {
     window.addEventListener('click', listener as any);
-    window.addEventListener('pointerdown', setShouldListen);
+    window.addEventListener('pointerDown', setShouldListen);
```
Comment (rak-phillip) [inline shell/composables/useClickOutside.ts]: It looks like all lowercase `pointerdown` is correct [^1], I think that we should make the correction on line 79 where we remove the listener. 

[^1]: https://developer.mozilla.org/en-US/docs/Web/API/Element/pointerdown_event

**Review by rak-phillip — COMMENTED** [review]
@smallteeths great catch and thanks for raising a PR to address this. There's one comment to address before moving forward.

File: shell/composables/useClickOutside.ts (hunk 1 above)
Comment (smallteeths) [reply shell/composables/useClickOutside.ts]: Thanks! Done.

**Comment by rak-phillip** [comment]
@smallteeths I'm just noticing that the target branch is `release-2.12`. Can we also update this PR to target `master`? Our process is to target `master` with fixes and then backport to supported releases; this helps our team to avoid regressions.

**Comment by richard-cox** [comment]
https://github.com/rancher/dashboard/pull/16449 created for master, removing master issue linked to this pr

**Comment by rak-phillip** [comment]
@smallteeths This PR needs a rebase on top of `release-2.12` in order to pass CI.

**Comment by smallteeths** [comment]
> @smallteeths This PR needs a rebase on top of `release-2.12` in order to pass CI.

Thank you for the reminder. Done
