### PR TITLE
remove $set usage in eks provisioning and gatekeeper constraints

### LINKED ISSUE #12442: [EKS] - Changing nodegroup name to an existing name abruptly closes the edit form
**Setup**
- Rancher version: 2.10.0-alpha5
- Rancher UI Extensions: v2.10.0-alpha3
- Browser type & version: Firefox

**Describe the bug**

Changing a nodegroup name to an existing name abruptly closes the edit form.

**To Reproduce**

1. Edit an existing cluster
2. Add a nodegroup and edit the name; change it to `somenode`; change it again to an existing nodegroup name.
**Result**
Changing the name to `somenode` is fine, but then changing it to an existing nodegroup name, abruptly closes the form.
**Expected Result**

The form should error out with an error like the following - 
```
Node group names must be unique within the [c-w94xd] cluster to avoid duplication
```
**Screenshots**

[Uploading Screencast from 10-31-2024 04:35:32 PM.webm…]()

**Additional context**

### PR DESCRIPTION
**Pull request by mantis-toboggan-md**
### Summary
Fixes #12442

I'm not sure why these instances of `$set` weren't caught in the vue3 migration. I searched the codebase and only additional instance I found was in gatekeeper constraints

### Areas or cases that should be tested
In addition to what is described in #12442, check creating gatekeeper constraints with parameters defined

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: shell/edit/constraints.gatekeeper.sh.constraint/index.vue [hunk 1]
```diff
@@ -356,7 +359,7 @@ export default {
             v-model:value="parametersYaml"
             class="yaml-editor"
             :editor-mode="editorMode"
-            @newObject="$set(value.spec, 'parameters', $event)"
+            @newObject="set(value.spec, 'parameters', $event)"
```
Comment (jordojordo) [inline shell/edit/constraints.gatekeeper.sh.constraint/index.vue:362]: This doesn't seem to set the `parameters` property correctly:


https://github.com/user-attachments/assets/f7d8c421-7ce3-4c3a-b286-672a2496ea98

**Review by jordojordo — CHANGES_REQUESTED** [review]
NodeGroup issue is fixed, one minor problem with the gatekeeper constraint parameter.

**Review by jordojordo — APPROVED** [review]
