### PR TITLE
Fix broken PSS detail route

### LINKED ISSUE #14780: Project Scoped Secrets: When viewing or editing a pss the side nav does not highlight the correct resource
**Setup**
- Rancher version: v2.12.0 (dev of)

**Describe the bug**

**To Reproduce**
When viewing or editing a pss the side nav does not highlight the correct resource

**Result**

**Expected Result**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by momesgin**
### Summary
Fixes #14780 

### Occurred changes and/or fixed issues
- Fixed a regression where clicking on a downstream project-scoped secret from the list caused the page to crash.

Note: A regression was caused by changing `detailLocation` logic in `secret.js`. It updated the route name to the generic `c-cluster-product-resource-namespace-id`. This caused the application to bypass the specialized `projectsecret.vue` component and instead attempt to load the generic resource view, leading to the crash.

### Technical notes summary
- Reverted the `detailLocation` in `shell/models/secret.js` to use the specialized route name `c-cluster-product-${ VIRTUAL_TYPES.PROJECT_SECRETS }-namespace-id`, ensuring the correct component is loaded.
- Updated the route definition in `shell/config/router/routes.js` to use the regex parameter syntax: `:resource(${ VIRTUAL_TYPES.PROJECT_SECRETS })`.
    - This allows the router to strictly match the literal `projectsecret` path segment (routing to the correct component).
    - Simultaneously, it captures this value into `route.params.resource`, which is required by the `SideNav` component to correctly identify and highlight the active menu item.
- Added a unit test in `shell/models/__tests__/secret.test.ts` to verify that `detailLocation` returns the correct route name and parameters for project-scoped secrets.

### Areas or cases that should be tested
Navigate to a downstream cluster > Explorer > Storage > Project Secrets then click on a secret on the list. You might need to create a PSS if you don't have any existing one there. Make sure the detail page loads successfully without crashing.
Also make sure the Side Navigation bar remains open, and the Project Secrets item remains highlighted.

### Areas which could experience regressions
- Routing and navigation specifically for Project Scoped Secrets in both Local and downstream clusters.

### Screenshot/Video

image

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes
- [x] The PR has been reviewed in terms of Accessibility
- [x] The PR has considered, and if applicable tested with, the three Global Roles `Admin`, `Standard User` and `User Base`

### CODE REVIEW

File: shell/config/router/routes.js [hunk 1]
```diff
@@ -514,7 +514,10 @@ export default [
         name:      'c-cluster-product-resource-id',
         meta:      { asyncSetup: true }
       }, {
-        path:      `/c/:cluster/:product/${ VIRTUAL_TYPES.PROJECT_SECRETS }/:namespace/:id`,
+        // Used this regex syntax in order to strict match the 'projectsecret' path segment
+        // while simultaneously capturing it as the 'resource' parameter.
+        // This is required because the Side Navigation relies on route.params.resource to determine which menu item to highlight.
+        path:      `/c/:cluster/:product/:resource(${ VIRTUAL_TYPES.PROJECT_SECRETS })/:namespace/:id`,
```
Comment (momesgin) [inline shell/config/router/routes.js:520]: As an alternative solution we can pass some extra info like { meta: VIRTUAL_TYPES.PROJECT_SECRETS } and then update `Group.vue` to use it for highlighting, but I think this regex approach is much cleaner.

**Review by richard-cox — APPROVED** [review]
