### PR TITLE
Workload force delete - #5549

### LINKED ISSUE #5549: Cluster Explorer in Rancher 2.5 and 2.6 don't have 'Force Delete' option
**Setup**
- Rancher version: 2.5 and 2.6
- Browser type & version:

**Describe the bug**

**To Reproduce**

1) Go to Workload/Deployment
2) Select a Pod and click Delete button
3) Confirm you don't see 'Force Delete' option on Cluster Explorer even though you see it on Cluster Manager.

**Result**
You can't do Force Delete pods on Cluster Explorer.

**Expected Result**

You can do Force Delete pods on both Cluster Explorer and Cluster Manager.

**Screenshots**
The screenshots were taken on Rancher 2.6.3.

Rancher2 6 3-Cluster-Explorer

Rancher2 6 3-Cluster-Manager

**Additional context**
I found the difference of 'Force Delete' option between Cluster Explorer and Cluster Manager when I investigated the issue where you have an error when you do Force Delete a pod on Cluster Manager on Rancher 2.5.9.

Internal reference: SURE-3582

Rancher2 6 3-Cluster-Manager-error

**Detailed Description**

**Context**

### PR DESCRIPTION
**Pull request by Shavindra**
### Summary
Fixes #5549 - Cluster explorer POD deletion doesn't have delete option

### Technical notes summary
 - Added `shell/components/dialog/ForcePodRemoveDialog.vue`
 - Override `promptRemove` Pod model `shell/models/pod.js` to include the `ForcePodRemoveDialog`

#### Single cluster deletion
1. Navigate to `Cluster Explorer > Cluster > Deployments > Pod >`
2. Select three dots on the right and select `Delete`
3. Select the force deletion and submit
4. Delete request should have payload `{"gracePeriod":0,"force":true}` 
5. If unticked there should not be a payload

#### Multiple cluster deletion

1. Navigate to `Cluster Explorer > Cluster > Deployments > Pod >`
2. From checkboxes on the left select multiple pods and select `Delete`
3. Select the force deletion and submit
4. All Delete requests should have payload `{"gracePeriod":0,"force":true}` 
5. If unticked there should not be a payload

### CODE REVIEW

File: shell/components/dialog/ForcePodRemoveDialog.vue [hunk 1]
```diff
@@ -0,0 +1,218 @@
+<script>
```
Comment (richard-cox) [inline shell/components/dialog/ForcePodRemoveDialog.vue:1]: There should be a way of doing this without a large amount of copy and paste from PromptRemove. It looks like you should be able to achieve something similar with via the custom prompt remove feature (see shell/promptRemove/kubevirt.io.virtualmachine.vue)

**Review by richard-cox — CHANGES_REQUESTED** [review]

File: shell/models/pod.js [hunk 2]
```diff
@@ -16,41 +15,36 @@ export const WORKLOAD_PRIORITY = {
...
-    return {
-      action:     'openLogs',
-      enabled:    !!this.links.view,
-      icon:       'icon icon-fw icon-chevron-right',
-      label:      'View Logs',
-      total:      1,
-    };
-  }
-
-  get containerActions() {
```
[the remark this answers is not in the document]
Comment (Shavindra) [reply shell/models/pod.js:49]: This is not removed. I just refactored it.

File: shell/components/dialog/ForcePodRemoveDialog.vue [hunk 3]
```diff
@@ -0,0 +1,218 @@
...
+      forceDelete: true
+    };
+  },
+
+  computed: {
+    names() {
+      return this.resources.map(obj => obj.metadata.name);
+    },
+
+    machine() {
```
Comment (catherineluse) [inline shell/components/dialog/ForcePodRemoveDialog.vue:40]: `machine`, `nameToMatch`, `type` and `forceRemoveMachine` should be removed because they are related to machines and that shouldn't be necessary for deleting workoads

File: shell/promptRemove/pod.vue [hunk 4]
```diff
@@ -0,0 +1,149 @@
...
+        parentComponent.close();
+      } catch (err) {
+        parentComponent.error = err;
+        confirm(false);
+      }
+    },
+
+    removePod(pod) {
+      if (this.forceDelete) {
+        return this.forceRemovePod(pod);
```
Comment (richard-cox) [inline shell/promptRemove/pod.vue:116]: I don't think `forceRemovePod` is needed. You can pass through `data` in `opt` directly to the `remove` function. So something like 

```
      const opts = this.forceDelete ? {
        gracePeriod: 0,
        force:       true
      } : undefined;

      return pod.remove(opts);
```

File: shell/promptRemove/pod.vue [hunk 5]
```diff
@@ -0,0 +1,149 @@
...
+      }
+    },
+  }
+};
+</script>
+
+<template>
+  <div class="mt-10">
+    <div class="mb-30">
+      {{ t('promptRemove.attemptingToRemove', { type }) }} <span class="machine-name" v-html="podNames" />
```
Comment (richard-cox) [inline shell/promptRemove/pod.vue:128]: This is just a comment for the future, nothing to tackle or change in this PR. 

The way we show lists of resources in prompt remove will update given https://github.com/rancher/dashboard/issues/6260. When that's done we should consider how this and kubecirt.io.virtualmachine display theirs. Ideally we should split the list out in to it's own component and use in all three places

**Review by richard-cox — CHANGES_REQUESTED** [review]

**Review by catherineluse — APPROVED** [review]
LGTM
