### PR TITLE
[2.13]force re-loading norman schemas in generic cloud credential component

### LINKED ISSUE #13723: Node Drivers: The cloud credential page form changes before and after reload
**Setup**
- Rancher version: v2.10, v2.11
- Rancher UI Extensions:
- Browser type & version: Any

**Describe the bug**
When creating a Nutanix/Oracle OCI cluster, the cloud credential form displays different input fields before and after a page reload. This issue occurs only when accessing the page for the first time. After reloading, the form remains consistent on subsequent visits..
Possibly related to what is described [here](https://github.com/rancher/dashboard/issues/11983#issuecomment-2430529867). 

**To Reproduce**

1. go to Cluster Management > Drivers > Node Drivers
2. enable the non-builtin `Nutanix` Node driver
3. navigated to Cluster Management > Create Cluster > Nutanix
4. observe the input fields on the cloud credential create/select page
5. reload page
6. notice the input fields have changed

**Result**

- Before Reload: One version of the cloud credential form is displayed.
- After Reload: The form structure or fields change.

**Expected Result**
The cloud credential form should remain the same before and after a page reload.

**Screenshots**

https://github.com/user-attachments/assets/76162642-ce6c-4dea-b5d3-fa61f494b679

  
**Additional context**

### PR DESCRIPTION
**Pull request by mantis-toboggan-md**
### Summary
Fixes #13723 

### Occurred changes and/or fixed issues
This PR updates the generic credential component to fetch the new node driver credential schema and show the correct fields after a user has enabled a node driver.

### Technical notes summary
The url used to fetch the schema is hardcoded because automatically constructing those urls requires a schema, and there is no schema for norman schemas (ie /v3/schemas/schema returns 404). 

### Areas or cases that should be tested
The scenario described in #13723

### Areas which could experience regressions
None

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes
- [x] The PR has been reviewed in terms of Accessibility

### CODE REVIEW

File: shell/cloud-credential/generic.vue [hunk 1]
```diff
@@ -23,10 +24,15 @@ export default {
   async fetch() {
     let keyOptions = [];
 
-    const { normanSchema } = this;
+    const normanType = this.$store.getters['plugins/credentialFieldForDriver'](this.driverName);
+    const configId = `${ normanType }credentialconfig`;
+
+    this.normanSchema = await this.$store.dispatch('rancher/find', {
+      type: SCHEMA, id: configId, opt: { url: `/v3/schemas/${ configId }`, force: true }
```
Comment (richard-cox) [inline shell/cloud-credential/generic.vue]: looking at this now, i've got my suggestion wrong. we don't need to `force` this, if the resource isn't in the cache the ui will go out and fetch it. we would only need to `force` if we already had the schema but it wasn't yet correctly populated (which i don't think is a thing, but worth checking?).

This would remove a blocking http request every time the user navs creates/edits that cloudcred type

**Review by richard-cox — DISMISSED** [review]
one minor change (i suggested the wrong thing), otherwise looks good

File: shell/cloud-credential/generic.vue (hunk 1 above)
Comment (mantis-toboggan-md) [reply shell/cloud-credential/generic.vue]: Ahhh good call! I checked and this does work without using `force`. I've updated the PR accordingly.

**Review by eva-vashkevich — APPROVED** [review]
lgtm
https://github.com/user-attachments/assets/75b1f59f-4c47-4b05-b828-28557620c456
