### PR TITLE
Fix Node Scheduling / Node Name option in Workloads page

### LINKED ISSUE #12939: Node Scheduling option is ignored when creating/edit workloads
**Setup**
- Rancher version: 2.10.1
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**

It's not possible to select a node selector when creating or edit new pods or deployment.
The selected node is discarded and the first element in the list is used instead.

- For deployments, the workaround is to edit the YAML and add the `nodeName: yourNode` to the `spec` field.
- For pods I cannot change the YAML, see https://github.com/rancher/dashboard/issues/12938 .

image

**To Reproduce**

- Create or edit new pods/deployments.

**Screenshots**

https://github.com/user-attachments/assets/5240785a-8d2f-4f9c-acb8-1ca6f64522b0

**Additional context**

### PR DESCRIPTION
**Pull request by torchiaf**
### Summary
Fixes #12939

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: shell/components/form/NodeScheduling.vue [hunk 1]
```diff
@@ -182,7 +184,8 @@ export default {
             :mode="mode"
             :multiple="false"
             :loading="loading"
-            @input="update"
+            :data-testid="'node-scheduling-nodeSelector'"
+            @update:value="update"
```
Comment (richard-cox) [inline shell/components/form/NodeScheduling.vue:188]: do we have the same issue for the other 12 places `@input="update"` is used?

File: shell/components/form/__tests__/NodeScheduling.test.ts [hunk 2]
```diff
@@ -0,0 +1,44 @@
+import { mount } from '@vue/test-utils';
+import NodeScheduling from '@shell/components/form/NodeScheduling.vue';
+import { _CREATE, _EDIT, _VIEW } from '@shell/config/query-params';
+
+const requiredSetup = () => {
```
Comment (cnotv) [inline shell/components/form/__tests__/NodeScheduling.test.ts:5]: It's not convenient to have mocks outside the tests, but it's not a blocker.

**Review by cnotv — APPROVED** [review]
Reported issue seems solved.

LGTM
