### PR TITLE
duration field live refresh

### LINKED ISSUE #6899: Job list Duration field is sorted incorrectly
**Setup**
- Rancher version: v2.6.8
- Browser type & version: chrome 105.0.5195.125

**Describe the bug**

Job list Duration field is sorted incorrectly

**To Reproduce**

1. Navigate to the Job page
2. Click Duration to sort

**Result**
Not sorted by time

**Screenshots**

image

image

**Others**

Same problem with Last Schedule field in CronJobs

### LINKED ISSUE #6925: Long user/display names will overflow the SelectPrincipal container
**Setup**
- Rancher version: `v2.6-a3b5237ce1da4228c97df7552d57464c64947b3b-head`
- Browser type & version: `FF 104.0`

**Describe the bug**

Long user names and display names will overflow the `SelectPrincipal` component container, if the name is long enough it will grow passed the window width. 
Recognized with [this comment](https://github.com/rancher/dashboard/pull/6909#pullrequestreview-1111292895).

**To Reproduce**

1. Create a user with a long user name and display name
  - user: long-username-hyz8ql12oa-0b2ewxkh29-vjnzbyqcmd-ohydd9bi3x-7rcje6k5hp-kr9ld7r1si
  - display name: long-displayname-e422ilkhqj-y4rzk02abt-c8m0scwcwl-reliod8oja-hj1jvu31mm-k28d9zppm1
2. Navigate to the local cluster, edit the config of a project and add the created user as a Project Member 

**Result**
The name will overflow the width of the container.

long-user-name

**Expected Result**

The user name should fold to fit within the container.

**Additional context**

This seems to appear in any instance where the `SelectPrincipal` component is used, for example adding a Cluster Member to a cluster:

long-cluster-member

### PR DESCRIPTION
**Pull request by torchiaf**
Signed-off-by: Francesco Torchia <francesco.torchia@suse.com>

### Summary
Fixes #6899

### CODE REVIEW

File: shell/components/formatter/LiveDuration.vue [hunk 1]
```diff
@@ -0,0 +1,113 @@
+<script>
+import day from 'dayjs';
+
+/**
+ * return { diff: number; label: string }
+ *
+ * diff:  update frequency in seconds
+ * label: content of the cell's column
+ */
+function elapsedTime(seconds) {
```
Comment (mantis-toboggan-md) [inline shell/components/formatter/LiveDuration.vue:10]: Am I right in thinking that you've written this instead of using `diffFrom` (used to format the age column) because `diffFrom` does a lot of rounding? I think it makes sense to be more precise in this column, I just want to verify that I've understood the code correctly. The function seems general enough that it should probably live in `/shell/utils/time` though. Otherwise the PR looks good, and seems to work correctly.

**Review by mantis-toboggan-md — CHANGES_REQUESTED** [review]

**Review by mantis-toboggan-md — APPROVED** [review]
LGTM
