### PR TITLE
[FIX] Changed JWT Authentication page to disable ClusterProxyConfigs

### LINKED ISSUE #11444: [BUG]: Cluster Proxy Config is deleting when user disable the JWT Authentication
**Setup**
- Rancher version: `v2.9-3c4ccdc5bc9fde3510089153b5ad58fdbe604880-head`
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**
The resource Cluster Proxy Config is deleting when user disable the JWT Authentication

**To Reproduce**
1. Provision rancher
2. Create a downstream cluster
3. Local->Cluster Management->Advanced->JWT Authentication
4. Select the cluster and Disable the cluster(JWT Authentication)
5. Check for the Cluster Proxy Config resource update 

**Result**
1. The ClusterProxyConfig resource is deleted instead of updating the enabled flag from `true` to `false`
2. ```
    kubectl describe clusterproxyconfig -n c-m-tttttttt
    No resources found in c-m-dfcfz892 namespace.
    ```

**Expected Result**
1. On disable the clusterproxyconfig resource should be update the enabled flag from `true` to `false` instead of deleting the complete resource


**Additional context**
1. Currently this is not giving any issues to the users but good to update the flag to track updated flag time.

### PR DESCRIPTION
**Pull request by eva-vashkevich**
Changed JWT Authentication page to disable ClusterProxyConfigs instead of removing

### Summary
Fixes #11444 

The original behavior was to remove ClusterProxyConfig in the corresponding namespace if JWTA for that cluster is disabled. This change sets it to disabled instead.

### Occurred changes and/or fixed issues

This required changes to excludeFields behavior:
Current behavior: 'metadata.managedFields' is always excluded. If a list of fields to exclude is provided, 'metadata.managedFields' is appended to that list
New behavior: if a list of fields to exclude is provided, we just use it. A new option 'omitExcludeFields' is provided to make it possible to overwrite default exclude fields behavior.

### Areas or cases that should be tested

JWT Authentication page:
- Check that JWTA can be enabled, disabled, and re-enabled for clusters. (covered by existing tests)
- Check that ClusterProxyConfig still exists after JWTA has been disabled for a cluster

### Areas which could experience regressions

excludeFields change can affect all requests

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

**Comment by gaktive** [comment]
I'll check with the product owner if this is needed for 2.9.0 or if it can wait. @nwmac to discuss with @eva-vashkevich before we do things. Tagging @richard-cox to review though we need gates to pass first.

File: shell/pages/c/_cluster/manager/jwt.authentication/index.vue [hunk 1]
```diff
@@ -150,7 +150,8 @@ export default {
 
           const value = config?.enabled || '';
           const configName = config?.metadata?.name || '';
-          const updatedOn = value ? config?.metadata?.creationTimestamp : '';
+          const updatedOn = value ? config?.metadata?.managedFields.find((field) => field.operation === 'Update')?.time : '';
```
Comment (richard-cox) [inline shell/pages/c/_cluster/manager/jwt.authentication/index.vue:153]: should this be 
```
value ? config?.metadata?.managedFields.find((field) => field.operation === 'Update')?.time || '' : '';
```

or neater

```
let updatedOn = '';
if (value) {
  updatedOn = config?.metadata?.managedFields.find((field) => field.operation === 'Update')?.time || ''
}
```

File: shell/pages/c/_cluster/manager/jwt.authentication/index.vue [hunk 2]
```diff
@@ -159,7 +160,7 @@ export default {
             if (!configName) {
               const clusterProxyConfig = await this.$store.dispatch('management/create', {
                 enabled:  true,
-                metadata: { namespace: id, generateName: 'cluster-proxy-config-' },
+                metadata: { namespace: id, name: 'cluster-proxy-config' },
```
Comment (richard-cox) [inline shell/pages/c/_cluster/manager/jwt.authentication/index.vue:163]: as a general rule name should be unique within a namespace. as namespace is a cluster this should be safe, though it feels wrong. was there a reason to move to a static name?

**Review by richard-cox — CHANGES_REQUESTED** [review]
- After disabling and then re-enabling the same config a few times i get the following error and have to refresh to see the correct config state

  ```
  Cannot read properties of undefined (reading 'find')
      at index.vue:153:1
  ```
  All network requests looked correct (get's had no exclude, response to save's contained `managedFields`) and socket messages were good (all had `managedFields`).

In addition, I spotted a few existing things that might be worth changing in the future

- rows creates two functions (enabledActions and disableAction) on every call (they could both be defined in `data`)
- rows takes a collection of `management.cattle.io.clusterproxyconfig` resources, constructs a model like object and properties, and passes it to a resource table as if they were `management.cattle.io.clusterproxyconfig` models. This could be neatened and follow patterns by creating a `model/management.cattle.io.clusterproxyconfig` file. That would automatically get a lo of the required properties and have a neat place for actions. Doing this also means the two actions enabledActions and disableAction, plus enable and disable methods are only created once per model 
-

File: shell/pages/c/_cluster/manager/jwt.authentication/index.vue (hunk 2 above)
Comment (eva-vashkevich) [reply shell/pages/c/_cluster/manager/jwt.authentication/index.vue:163]: I've checked https://confluence.suse.com/pages/viewpage.action?pageId=1333068261#ServiceAccountTokenAuthentication(Vault)-Testing
And there under 3a they are saying " The only way to enable it is to create a clusterproxyconfig object named "clusterproxyconfig" in the namespace of the downstream cluster." so I've changed it to match this spec in case it will be enforced later on.

Comment (richard-cox) [reply shell/pages/c/_cluster/manager/jwt.authentication/index.vue:163]: Ahh makes sense. Probably needs to be without the hyphens as well.

Gave the spec a quick check and it seems not everyone has access to them, though we always show the menu item and list (it'll be empty and the following error will be in console ` Error in fetch(): Error: Unknown schema for type: management.cattle.io.clusterproxyconfig`). Can you create a 2.10 issue to hide the menu item if the user has no permissions to see the resource?

**Comment by eva-vashkevich** [comment]
@richard-cox I have not been able to reproduce the undefined problem

File: shell/pages/c/_cluster/manager/jwt.authentication/index.vue (hunk 2 above)
Comment (eva-vashkevich) [reply shell/pages/c/_cluster/manager/jwt.authentication/index.vue]: Created https://github.com/rancher/dashboard/issues/11461

**Comment by gaktive** [comment]
For this PR, let's target 2.10.0 but a backport ticket for 2.9.next1 was filed. If folks feel this PR is ready for its own backport, then I can do this for 2.9.x though I understand more discussion is in the cards.

**Comment by richard-cox** [comment]
@gaktive ah, was just bringing this back to 2.9.0. happy for this to go in right now if that's ok your side?

**Review by richard-cox — APPROVED** [review]
I couldn't reproduce either, but think it's down to `managedFields?` (which is a reasonable fix).

Given https://github.com/rancher/dashboard/issues/11461 this is good to merge (once version agreed)

**Comment by gaktive** [comment]
@richard-cox based on how close we are to release, and this isn't a blocker, let's aim for 2.9.1.
