### PR TITLE
Fix underline alignment on back to home link

### LINKED ISSUE #15885: Visual issue with the home link on Preferences page
**Setup**
- Rancher version: 2.13 and probably older versions
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**

The underline styling on the home link is off.

**To Reproduce**

Go to Preferences page and hover on the home link

**Result**

**Expected Result**

Image

**Screenshots**

Image

**Additional context**

### PR DESCRIPTION
**Pull request by momesgin**
### Summary
Fixes #15885 

### Occurred changes and/or fixed issues

Fixed the alignement issue with the underline styling of the icon and the text for back to home link.

### Technical notes summary

Added a span tag around the text and adjusted underline styling on both the icon and the text to align them.

### Areas or cases that should be tested

Go to Preferences page, hover on the Home link and make sure the chevron icon and the home text both have an aligned underline styling
### Areas which could experience regressions

Most likely none.

### Screenshot/Video
image
image

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes
- [x] The PR has been reviewed in terms of Accessibility
- [x] The PR has considered, and if applicable tested with, the three Global Roles `Admin`, `Standard User` and `User Base`

### CODE REVIEW

**Comment by eva-vashkevich** [comment]
A bit of a nitpic, does the underline look too long at the front? It's likely because of the paddings on the icon. Just wanted to not it.
Screenshot 2025-11-17 at 11 57 23 AM

**Comment by momesgin** [comment]
> A bit of a nitpic, does the underline look too long at the front? It's likely because of the paddings on the icon. Just wanted to not it. Screenshot 2025-11-17 at 11 57 23 AM

Padding doesn't work like that with `text-decoration: underline` but with borders which I switched to.

File: shell/components/BackLink.vue [hunk 1]
```diff
@@ -34,8 +34,16 @@ export default {
     display: flex;
     font-size: 16px;
     margin: 10px 0 20px 0;
+    padding: 0 4px 2px 0;
     outline: 0;
     width: fit-content;
+    border-bottom: 2px solid transparent;
```
Comment (momesgin) [inline shell/components/BackLink.vue:40]: to prevent layout shifting

**Review by eva-vashkevich — APPROVED** [review]
lgtm
