### PR TITLE
Link namespaces in mgmt cluster to local cluster

### LINKED ISSUE #9993: Rancher crashes when clicking the namespace in cluster view
Internal reference: SURE-7048
Reported in 2.7.6

Issue description:
In Cluster Management, if you open a cluster, there is the name of the cluster as a title and below that, there is the Namespace which is "fleet-default". That is a link, and when a user clicks on that link, Rancher crashes with "Cannot read properties of undefined (reading 'id')".

Business impact:
In environments where Rancher is used to manage a Harvester cluster the link in Cluster Management crashes the UI and the user needs to re-login or use the browser to go back in history to reach UI again. The error is happening via multiple paths and negatively impacts the user experience with the product. 

Troubleshooting steps:
They were able to reproduce it 100% on multiple environments. There is no clear workaround as refresh doesn't help

Repro steps:

- In Cluster Management pick a guest cluster on Harvester
- Click "fleet-default" namespace link below the title

Workaround:
None

Actual behavior:
Clicking fleet-default link ends up in app crash/error

Expected behavior:
Clicking fleet-default link should not end up in app crash/error

### PR DESCRIPTION
**Pull request by torchiaf**
### Summary
Fixes #9993

### Technical notes summary

Namespace's links in ClusterManagement/Cluster Detail header are broken because the `clusterId` is missing from the `namespaceLocation` of the namespace's links.
The issue can be reproduced with any type of clusters, is not specific for Harvester clusters.

Current changes will fix the issue assuming that the namespaces are always managed from `local` cluster.

### Areas or cases that should be tested

- Cluster Management list -> Cluster Details -> namespace details

image

### Areas which could experience regressions

- `Masthead` component -> namespace links section

### CODE REVIEW

File: shell/components/ResourceDetail/Masthead.vue [hunk 1]
```diff
@@ -148,7 +149,7 @@ export default {
         return this.value.namespaceLocation || {
           name:   'c-cluster-product-resource-id',
           params: {
-            cluster:  this.$route.params.cluster,
+            cluster:  this.$route.params.cluster === BLANK_CLUSTER ? this.value?.localCluster?.id : this.$route.params.cluster,
```
Comment (richard-cox) [inline shell/components/ResourceDetail/Masthead.vue:152]: we should do this via the provisioning cluster models `namespaceLocation` getter

File: shell/components/ResourceDetail/Masthead.vue [hunk 2]
```diff
@@ -370,7 +374,7 @@ export default {
     },
 
     hideNamespaceLocation() {
-      return this.$store.getters['currentProduct'].hideNamespaceLocation;
+      return this.$store.getters['currentProduct'].hideNamespaceLocation || !this.value?.localCluster;
```
Comment (richard-cox) [inline shell/components/ResourceDetail/Masthead.vue:377]: `this.$rootGetters['management/byId'](MANAGEMENT.CLUSTER, LOCAL_CLUSTER)` can be used here directly

**Review by richard-cox — CHANGES_REQUESTED** [review]

File: shell/components/ResourceDetail/Masthead.vue (hunk 1 above)
Comment (torchiaf) [reply shell/components/ResourceDetail/Masthead.vue:154]: Agree, define a `namespaceLocation` in provisioning model is better.

Comment (richard-cox) [reply shell/components/ResourceDetail/Masthead.vue:154]: this line can now be removed (given we should have `value.namespaceLocation`)

File: shell/components/ResourceDetail/Masthead.vue [hunk 3]
```diff
@@ -370,7 +376,7 @@ export default {
     },
 
     hideNamespaceLocation() {
-      return this.$store.getters['currentProduct'].hideNamespaceLocation;
+      return this.$store.getters['currentProduct'].hideNamespaceLocation || !this.$store.getters['management/byId'](MANAGEMENT.CLUSTER, LOCAL_CLUSTER);
```
Comment (richard-cox) [inline shell/components/ResourceDetail/Masthead.vue:379]: This is implementation specific code in a generic component. In prov cluster model we could overload `namespaceLocation` to return false if the user cannot see the local cluster ... and then here check for value.namespaceLocation === false

**Review by richard-cox — CHANGES_REQUESTED** [review]

File: shell/components/ResourceDetail/Masthead.vue (hunk 3 above)
Comment (torchiaf) [reply shell/components/ResourceDetail/Masthead.vue:379]: Yeah, `=== BLANK_CLUSTER ? this.value?.localCluster?.id : this.$route.params.cluster` is a typo from first commit, it can be removed.
I would set `namespaceLocation` to `null` in case the local cluster is not visible.

**Comment by torchiaf** [comment]
Thanks @richard-cox , code refactoring is done.

File: shell/components/ResourceDetail/Masthead.vue (hunk 3 above)
Comment (richard-cox) [reply shell/components/ResourceDetail/Masthead.vue]: Unfortunately it needs to be something specific rather than a falsey. Lots of models don't have a `namespaceLocation` which means the ns link will be hidden (instead of falling back on the generated one in)

```
namespaceLocation() {
      if (!this.isNamespace) {
        return this.value.namespaceLocation || {
          name:   'c-cluster-product-resource-id',
```

File: shell/components/ResourceDetail/Masthead.vue (hunk 2 above)
Comment (richard-cox) [reply shell/components/ResourceDetail/Masthead.vue]: i realise now this was the wrong suggestion! i should have commented here about using resource specific info instead of recommending the above line. Apologies

**Review by richard-cox — CHANGES_REQUESTED** [review]
Just one inline comment left (+ an apology for suggesting the wrong thing)

File: shell/components/ResourceDetail/Masthead.vue (hunk 3 above)
Comment (torchiaf) [reply shell/components/ResourceDetail/Masthead.vue]: I think it could be simply `this.value.namespaceLocation === null`. In the other models it will be undefined.

**Review by richard-cox — APPROVED** [review]
