### PR TITLE
Fix duplicate list rows on resource create race condition

### LINKED ISSUE #11151: After a resource is created duplicate rows are shown in list view
**Setup**
- Rancher version: dev 2.9.0 (and much older)

**Describe the bug**
- After a user creates a resource and is returned to the list view for that resource, sometimes a duplicate row for it is shown
- This will occur when there is a slow connection to rancher

**To Reproduce**
- Nav to local cluster --> Apps --> Repositories
- Click `Create`
- Open Dev Tools --> `Network` tab --> change `No throttling` to `Slow 3G`
- In the repo form Enter anything for `Name` and `Index URL`
- Click `Create`

**Result**
- User is shown the Repo list with two entries for the resource that was just created

**Expected Result**
- A single resource

**Screenshots**
image

**Additional context**
- This is the cause of the flaky respositories.spec e2e test

### PR DESCRIPTION
**Pull request by richard-cox**
### Summary
Fixes #11151

### Occurred changes and/or fixed issues
- Resources are added to our resource map & list on resource create and on socket updates
- When resources are created..
  - the http response is usually received first, and the resource is added to both resource map and list
  - any socket updates received afterwards will then update that first resource entry
- However there are scenarios where..
  - the http response is sent, but response not yet received
  - the socket event for the created resource is then received, and resource is added to resource map and list
  - the http response is then received. the load mutator would then ADD to the list and SET in the map
  - this caused two rows for the resource to show in it's list view
- Fix is to gate adding them to the list

Also contains
- General improvements for cypress/e2e/tests/pages/manager/repositories.spec.ts test
- Reliability improvements for cypress/e2e/tests/pages/fleet/gitrepo.spec.ts test

### Areas or cases that should be tested
- As per repo steps
- Random set of other resource creates

### Areas which could experience regressions
- Anywhere we create a resource

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
  - I haven't added e2e tests for this, as existing tests (specifically repositories.spec) will fail when it occurs. Given the reproduction steps (see issue) it'll need manual test as well
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: shell/plugins/dashboard-store/mutations.js [hunk 1]
```diff
@@ -104,7 +104,9 @@ export function load(state, {
     // A specific proxy instance to used was passed in (for create -> save),
     // use it instead of making a new proxy
     entry = replaceResource(existing, data, getters);
-    addObject(cache.list, entry);
+    if (!cache.list.find((e) => e[keyField] === id)) {
```
Comment (nwmac) [inline shell/plugins/dashboard-store/mutations.js:107]: Can we use `cache.map`? Is there ever a case when it is in `cache.map` but not in `cache.list`? Doesn't feel like there should - so feels like we could juts check the map - this would be a lot quicker.

Checking the list feels like it would be slow for a large number of resources.

Comment (richard-cox) [reply shell/plugins/dashboard-store/mutations.js:107]: I got very weirded out when looking at this (functionality has not change in a long while) so went down the low-bar and safest (but not performant) solution. In the near future we'll only be keeping a small amount of resources locally and it should only apply when users create new resources. I'll take another look and work out where else this (load with existing) is used and get confidence that map and list align

File: shell/plugins/dashboard-store/mutations.js [hunk 2]
```diff
@@ -98,37 +98,52 @@ export function load(state, {
...
+  const inMap = !!entry;
 
+  //
+  // Determine the `entry` that should be in the local map and list cache
+  //
   if ( existing && !existing.id ) {
-    // A specific proxy instance to used was passed in (for create -> save),
-    // use it instead of making a new proxy
-    entry = replaceResource(existing, data, getters);
-    addObject(cache.list, entry);
```
Comment (richard-cox) [inline shell/plugins/dashboard-store/mutations.js:107]: addObject used here (create resource) and below (load new resource via socket) iterates over entire list

File: shell/plugins/dashboard-store/mutations.js [hunk 3]
```diff
@@ -98,37 +98,52 @@ export function load(state, {
...
+  // Note - We should be safe assuming the two collections have parity (not in map means not in list)
+  //
+  if (!inMap) {
+    cache.list.push(entry);
+    cache.map.set(id, entry);
+  }
 
-      // If there is a limit to the number of resources we can store for this type then
-      // remove the first one to keep the list size to that limit
-      if (limit && cache.list.length > limit) {
```
Comment (richard-cox) [inline shell/plugins/dashboard-store/mutations.js:126]: this only ran outside of when the user manually creates a resource

File: shell/plugins/dashboard-store/mutations.js [hunk 4]
```diff
@@ -98,37 +98,52 @@ export function load(state, {
 
   cache.generation++;
 
-  let entry;
+  let entry = cache.map.get(id);
+  const inMap = !!entry;
 
+  //
```
Comment (richard-cox) [inline shell/plugins/dashboard-store/mutations.js:104]: I've simplified this whole section
Step 1 - Determine the `entry` that should be in the local map and list cache
- Ensure that this entry is the latest and greatest
- Ensure we merge the latest and greatest into the reference in the local map/list
Step 2 - Ensure the `entry` is in both both map and list
- Goes on the assumption parity between map and list

File: shell/plugins/dashboard-store/mutations.js (hunk 1 above)
Comment (richard-cox) [reply shell/plugins/dashboard-store/mutations.js]: I've reworked a lot of that section and added inline + review comments

File: shell/plugins/dashboard-store/mutations.js (hunk 4 above)
Comment (codyrancher) [reply shell/plugins/dashboard-store/mutations.js:104]: It really seems like we should have a custom class (combine the list and map) that handles these patterns for us. 

Probably a better fit for a future change.

**Review by codyrancher — APPROVED** [review]

File: shell/plugins/dashboard-store/mutations.js (hunk 4 above)
Comment (richard-cox) [reply shell/plugins/dashboard-store/mutations.js:104]: Strongly agree on both parts! Something that's performant and hides the complexity would be grand. Definitely one for the future
