### PR TITLE
Fix terminal preventing the main section from scrolling

### LINKED ISSUE #13036: Opening the shell blocks scrolling on the explorer pages
**Setup**
- Rancher version: 2.10
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**

Opening the shell blocks scrolling on the explorer pages

**To Reproduce**

Go to Explorer page => Open kubectl shell from the top navbar or press Ctrl+` => Try scrolling on the page

**Result**

Scrolling doesn't work

**Expected Result**

Scrolling should work

**Screenshots**

image

**Additional context**

### PR DESCRIPTION
**Pull request by momesgin**
### Summary
Fixes #13036 

### Technical notes summary

It seems Chrome behaves different from other browsers when the position property is absent on an element that's positioned by its parent's grid layout. Adding `position: relative;` to the terminal element fixed the scrolling conflict.

### Areas or cases that should be tested

https://github.com/rancher/dashboard/issues/5245 should also be checked
### Areas which could experience regressions

I've tested the scrolling and the original loading issue on many different pages while having the terminal open. Please do the same with any page you think it might have loading and scrolling capabilities.
### Screenshot/Video

https://github.com/user-attachments/assets/c898c524-707d-4e47-9543-7746b34a5736

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: shell/components/Loading.vue [hunk 1]
```diff
@@ -20,13 +20,17 @@ export default {
...
+      timer: null, showMessage: this.noDelay, isTerminalOpen: false
+    };
   },
 
   mounted() {
     this.timer = setTimeout(() => {
       this.showMessage = true;
     }, 250);
+
+    this.isTerminalOpen = this.$store.getters['wm/allTabs']?.length;
```
Comment (richard-cox) [inline shell/components/Loading.vue:33]: this breaks https://github.com/rancher/dashboard/issues/5245. if the loading indicator is already shown and the user opens the kube shell then the loading indicator appears above it

File: shell/components/Loading.vue [hunk 2]
```diff
@@ -72,6 +80,10 @@ export default {
     // Covers both default `content` mode, an often used `relative` mode and any other value of mode
     z-index: z-index('loading');
 
+    &.behind-terminal {
+      z-index: -1;
```
Comment (richard-cox) [inline shell/components/Loading.vue:84]: this means _anything_ on the page with a z-index of 0 or above (the default) will appear over the loading indicator.

**Review by richard-cox — CHANGES_REQUESTED** [review]

File: shell/components/Loading.vue (hunk 1 above)
Comment (momesgin) [reply shell/components/Loading.vue]: @richard-cox thank you for your review, yes I missed this case, I could finally fix the issue by a simple pure css change! though it took a good amount of my time 🥲

File: shell/components/Loading.vue (hunk 2 above)
Comment (momesgin) [reply shell/components/Loading.vue]: not relevant anymore

**Review by richard-cox — COMMENTED** [review]
The change looks good, however someone who can reproduce the bug should also take a look (i couldn't on linux + chrome)

**Review by codyrancher — APPROVED** [review]
Verified. Working on my end.
