### PR TITLE
[backport 2.12.1] Resolved an issue where the new masthead broke the existing extension panels

### LINKED ISSUE #15021: [backport v2.12.1] Broken masthead extension panels
This is a backport issue for https://github.com/rancher/dashboard/issues/14957, automatically created via [GitHub Actions workflow](https://github.com/rancher/dashboard/actions/runs/16686403603) initiated by @codyrancher

Original issue body:

In 2.12 the extension panels were broken:
- PanelLocation.DETAILS_MASTHEAD
- PanelLocation.DETAIL_TOP

Previously we could add these panels:

Image

Now:

Image

### PR DESCRIPTION
**Pull request by codyrancher**
### Summary
Puts the following extension points back into the masthead:
- PanelLocation.DETAILS_MASTHEAD
- PanelLocation.DETAIL_TOP

fixes #15021

### Occurred changes and/or fixed issues
The extension points were omitted from the new design. This puts them back in.

### Areas or cases that should be tested
I used the https://github.com/rancher/ui-plugin-examples with a `yarn link @rancher/shell` to verify these changes. The plugin examples will add both panels to the gitrepo resource.

### Screenshot/Video
image

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes
- [x] The PR has been reviewed in terms of Accessibility

### CODE REVIEW

File: shell/components/Resource/Detail/Metadata/index.vue [hunk 1]
```diff
@@ -25,7 +30,10 @@ const showBothEmpty = computed(() => labels.length === 0 && annotations.length =
 </script>
 
 <template>
-  <SpacedRow class="metadata ppb-3">
+  <SpacedRow
+    class="metadata ppb-3"
+    v-bind="$attrs"
```
Comment (codyrancher) [inline shell/components/Resource/Detail/Metadata/index.vue:35]: This change is included to prevent  introducing #14996 in the backport.
