### PR TITLE
Using addAction with an svg icon crashes the rancher ui

### LINKED ISSUE #9130: Using addAction with an svg icon crashes the rancher ui
Prod: 
image

Dev with sourcemap:
image

We can see that issue using this using:
repo - https://github.com/codyrancher/opni-chat
branch - main
line - https://github.com/codyrancher/opni-chat/blob/main/pkg/rancher-ai-assistant/index.ts#L23
rancher version - v2.7-fbca7c34e5aeae36b85d8b0e9af12a2f6f13e0ea-head

### PR DESCRIPTION
**Pull request by aalves08**
Fixes #9130 

- fix bug with custom svg icon in header action extension point where colors for icon were being grabbed incorrectly

### Technical notes summary
- The problem lies with the component IconOrSvg, where the colors for a custom icon were being grabbed incorrectly (we weren't targeting the correct stylesheet + css rule) on a remote instance (couldn't be reproduced in a local env) causing problems in subsequent functions and crashing the code

### How to test
Since this is only reproducible in a remote env, a few steps need to be taken in order to reproduce it:
- Access your remote env
- add the `ui-plugin-examples` repo https://github.com/rancher/ui-plugin-examples -> branch `main` in local cluster -> apps -> repositories
- install Extensions-Api-Demo
- go to cluster explorer --> local cluster
**Issue** 
- alternatively you add the `rancher-ai-assistant` repo https://github.com/codyrancher/opni-chat -> branch `gh-pages` in local cluster -> apps -> repositories 
**Issue** https://github.com/rancher/dashboard/issues/9130
- in Extensions -> install the extension from the repo you just added
- check that the extension installed has crashed Dashboard. Don't worry, you can recover from this by using the `safeMode` path (ex: https://<- YOUR REMOTE INSTANCE BASE URL ->/dashboard/safeMode)
- with `safeMode` enabled, uninstall the problematic extension
- Go to `Global Settings `-> `ui-offline-preferred` -> set to `Remote`
- Go to `Global Settings `-> `ui-dashboard-index` -> set to `https://releases.rancher.com/dashboard/alex-fix-dev/index.html` (this branch of Dashboard has the fix applied to it - https://github.com/rancher/dashboard/tree/alex-fix-dev)
- hard refresh Dashboard
- Installed the problematic extension again
- check that it now loads correctly

### CODE REVIEW

File: shell/components/IconOrSvg.vue [hunk 1]
```diff
@@ -75,11 +75,18 @@ export default {
         if (stylesheet && stylesheet.cssRules) {
           for (let x = 0; x < Object.keys(stylesheet.cssRules).length; x++) {
             const cssRules = stylesheet.cssRules[x];
-            const selectorText = currTheme === 'light' ? 'body, .theme-light' : '.theme-dark';
 
-            if (cssRules.selectorText && cssRules.selectorText === selectorText) {
+            if (cssRules.selectorText && ((currTheme === 'light' && cssRules.selectorText.includes('body') &&
```
Comment (richard-cox) [inline shell/components/IconOrSvg.vue:79]: the formatting of this is a bit hard to grep
