### PR TITLE
fix grouping of RadioGroup with meaningful title

### LINKED ISSUE #13837: a11y: Missing grouping of form controls. - RadioGroup
**Setup**
- Rancher version:
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**

**a11y issue 77**

The radio buttons are not programmatically grouped and associated with the instruction text resulting in screen reader users finding it difficult to understand the purpose of the radio buttons.

Main Content:
Login landing page
- Take me to the home page
- Take me to the area I last visited
- Take me to cluster
radio buttons 

Include the instruction "You can change where you land when you login" within `<legend>` element. Use `<fieldset>` and `<legend>` elements to group the instruction and radio buttons.

**To Reproduce**

**Result**

**Expected Result**

The screen reader should announce the instruction along with the label for the radio buttons.

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by aalves08**
### Summary
Fixes #13837

### Occurred changes and/or fixed issues

- fix grouping of `RadioGroup` with meaningful title/description

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: shell/components/LandingPagePreference.vue [hunk 1]
```diff
@@ -102,10 +102,12 @@ export default {
 </script>
 
 <template>
-  <div>
-    <p class="set-landing-leadin">
-      {{ t('landing.landingPrefs.body') }}
-    </p>
+  <fieldset>
```
Comment (rak-phillip) [inline shell/components/LandingPagePreference.vue:105]: It looks like this change indents radio groups a little bit:

## Before

image

## After

image

File: shell/components/LandingPagePreference.vue [hunk 2]
```diff
@@ -102,10 +102,12 @@ export default {
...
+    <legend>
+      <p class="set-landing-leadin">
+        {{ t('landing.landingPrefs.body') }}
+      </p>
+    </legend>
```
Comment (rak-phillip) [inline shell/components/LandingPagePreference.vue:110]: Would it make sense to supply this legend to the label slot for RadioGroup? It seems like the design of our component should be able to handle this.

Comment (aalves08) [reply shell/components/LandingPagePreference.vue:110]: The following screenshot shows a larger, repeated title, which is me adding the same title to the `label` prop of the component... Sizing is totally off in regards to the remaining title of the page

Screenshot 2025-03-27 at 12 17 15

I can only see 2 options:
- keep the hacky `fieldset` just for the `LandingPagePreference` component, which isn't the prettiest thing to do codewise but at least we keep the same styling
- create a prop-activated title styling just for this usecase in the `RadioGroup` component and pass the responsibility to the component, despite introducing an "edge-case" to the component code

Wdyt? 🤔

Comment (rak-phillip) [reply shell/components/LandingPagePreference.vue:110]: I gave it a try with the following template

```html
<template>
  <RadioGroup
    id="login-route"
    :value="afterLoginRoute"
    name="login-route"
    :options="routeRadioOptions"
    @update:value="updateLoginRoute"
  >
    <template #label>
      <legend>
        <p class="set-landing-leadin">
          {{ t('landing.landingPrefs.body') }}
        </p>
      </legend>
    </template>
    <template #2="{option}">
      <div class="custom-page">
        <RadioButton
          :label="option.label"
          :val="false"
          :value="afterLoginRoute=== 'home' || afterLoginRoute === 'last-visited'"
          :v-bind="$attrs"
          :prevent-focus-on-radio-groups="true"
          @update:value="updateLoginRoute(null)"
        />
        <Select
          v-model:value="routeFromDropdown"
          :aria-label="t('landing.landingPrefs.ariaLabelTakeMeToCluster')"
          :searchable="true"
          :disabled="afterLoginRoute === 'home' || afterLoginRoute === 'last-visited'"
          :clearable="false"
          :options="routeDropdownOptions"
          class="custom-page-options"
        />
      </div>
    </template>
  </RadioGroup>
</template>
```

Which renders the following

image

Comment (rak-phillip) [reply shell/components/LandingPagePreference.vue:110]: It's not as nice as I would like.. perhaps we can fix it if we ever have the opportunity to refactor the RadioGroup component

Comment (aalves08) [reply shell/components/LandingPagePreference.vue]: Mate, your solution is much nicer.... I didn't pay any attention to the `label` slot on the `RadioGroup`. I've just tweaked your solution slightly so that we can meet the requirements. 

Give it another review whenever you have the chance 🙏  Thanks!

**Review by rak-phillip — APPROVED** [review]
LGTM
