### PR TITLE
Fix issue with configmap description and pressing `space` shifting focus

### LINKED ISSUE #13506: Configmaps create -> hit space on description causes focus to shift to another UI element
**Setup**
- Rancher version: `head/master` version
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**

When on Configmaps -> create -> go to `description` field, start typing a description and hit `space` to enter a space on the description. Pressing space shifts the focus to the `KeyValue` component instead of entering the blank space on the `description` field

**To Reproduce**

As above

**Result**
Pressing space shifts the focus to the `KeyValue` component instead of entering the blank space on the `description` field

**Expected Result**

Pressing space should enter the blank space on the `description` field

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by aalves08**
### Summary
Fixes #13506 

### Occurred changes and/or fixed issues

- update wrongly used patterns for `computed` properties using `$refs`

### Technical notes summary

- Just learned that `$refs` aren't reactive and in the first evaluation of a `computed` they are always `undefined`, which in conjunction with the condition `this.isCodeMirrorContainerFocused && (ev.code === 'Enter' || ev.code === 'Space')` triggered the focus (`this.isCodeMirrorContainerFocused` => `this.currFocusedElem === this.$refs?.codeMirrorContainer` => `undefined` === `undefined`).

### Areas or cases that should be tested

- `Import YAML` modal (triggered from header)
- configmap, as per original issue
- `ContainerShell` -> opening terminal and clicking `space`

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: shell/components/CodeMirror.vue [hunk 1]
```diff
@@ -103,6 +104,13 @@ export default {
     },
 
     isCodeMirrorContainerFocused() {
+      // this is a gimmick so that vue only looks at this.$refs in this computed after it's mounted
+      // we do this because this.$refs is not reactive and is "undefined" at the time of the computed's
+      // first evaluation. Addresses https://github.com/rancher/dashboard/issues/13506
+      if (!this.isMounted) {
+        return false;
+      }
```
Comment (rak-phillip) [inline shell/components/CodeMirror.vue:112]: optional: Alternatively, we could use a reactive variable (e.g. `codeMirrorRef`) to store the ref during the mounted hook. This might be a little more clear and require less explanation about what is happening; it also might look less like a gimmick.

**Review by rak-phillip — COMMENTED** [review]
Looks good an resolves the issue. I just wonder if we could be more clear about our intent by storing the ref instead.

File: shell/components/CodeMirror.vue (hunk 1 above)
Comment (aalves08) [reply shell/components/CodeMirror.vue]: You're right @rak-phillip , that's much neater and is reactive 🙇

**Review by rak-phillip — APPROVED** [review]
