### PR TITLE
do not allow eks version upgrades >1 minor version

### LINKED ISSUE #11389: [v2.9] EKS - Allow version upgrade only from current version to next minor version
**Setup**
Rancher - v2.9-1c2b815c8dd66e141b21630904127adc8e03c3de-head
Dashboard - master df60f44
Browser type & version: Chrome latest

**Describe the bug**
EKS (Vue UI): Allow version upgrade only from current version to next minor version. The same is validated on v2.8 Ember UI.

**To Reproduce**
- Create EKS cluster from Rancher UI and select lowest supported k8s version
- Upgrade version to highest supported version

**Screenshots**
2.8:
image

2.9:
image

image

### PR DESCRIPTION
**Pull request by mantis-toboggan-md**
### Summary
Fixes #11389 

### Occurred changes and/or fixed issues
This PR restricts users from upgrading their EKS clusters more than one minor version at a time

### Areas or cases that should be tested
1 creating a new EKS cluster- users should be able to select versions 1.27, 1.28, 1.29 and 1.30
2. Editing an existing EKS cluster with a version >1 minor version behind the latest: users should only be able to pick the next minor version

### Screenshot/Video
Screenshot 2024-07-10 at 1 28 38 PM

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: pkg/eks/components/Config.vue [hunk 1]
```diff
@@ -145,19 +146,29 @@ export default defineComponent({
...
-        if (this.originalVersion && semver.gt(semver.coerce(this.originalVersion), coerced)) {
-          return false;
+        if (!this.originalVersion) {
+          versions.push({ value: v, label: v });
+        } else if (semver.lte(semver.coerce(this.originalVersion), coerced)) {
+          const withinOneMinor = semver.inc(semver.coerce(this.originalVersion), 'minor');
+
+          if (semver.gt(coerced, withinOneMinor)) {
+            versions.push({
+              value: v, label: `${ v } (minor version >1 not allowed by EKS)`, disabled: true
```
Comment (codyrancher) [inline pkg/eks/components/Config.vue:163]: We may want to put in a translation string.

**Review by codyrancher — DISMISSED** [review]
Verified 
image

If you want to switch out the translation in a separate pr that's fine with me. Whatever you prefer.

**Comment by mantis-toboggan-md** [comment]
Updated this PR to include the translation string- I rather just get it all done at once

**Review by codyrancher — APPROVED** [review]
