### PR TITLE
[FIX] Fixed validation on Gitrepo page

### LINKED ISSUE #12204: Form validation broken on GitRepo page
Go to Fleet, Git Repos and press 'Create'.

The 'Next' button is disabled as expected.
Enter a name.
Validation does not update until after you remove focus from the name field - it should do so as you type a name.

Note also that Repository URL is not marked as required, when it is.

if you create a  Git Repo without a URL, this breaks the UI when you try to list GitRepos.

To be fixed:

- Updates to the name field should update the validation status immediately as you type
- Repository URL should be marked as required and should be validated
- GitRepos list page should not break if the Repository URL of a repository is undefined

### PR DESCRIPTION
**Pull request by eva-vashkevich**
### Summary
Fixes #12204 

Updated validation for GitRepo form.

### Occurred changes and/or fixed issues

- Updated when name validation is triggered
- Added validation to repo url and made this field required
- Added a check to see if repo exists when displaying the list of repositories

### Areas or cases that should be tested

- Gitrepo form should become valid when required values are provided 
- Repository field should handle both HTTPS and SSH urls

### Areas which could experience regressions

N/A

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: shell/utils/validators/formRules/index.ts [hunk 1]
```diff
@@ -458,6 +458,8 @@ export default function(t: Translation, { key = 'Value' }: ValidationOptions): {
     return runValidators(val, [startHyphen('label'), endHyphen('label'), startDot('label'), endDot('label'), required]);
   };
 
+  const repo: Validator = (val) => val && !/((git|ssh|http(s)?)|(git@[\w\.]+))(\:(\/\/)?)([\w\.@\:/\-~]+)(\.git)?(\/)?/.test(val) ? t('validation.setting.repo', { key }) : undefined;
```
Comment (momesgin) [inline shell/utils/validators/formRules/index.ts:461]: I think this validation part is not a vue3 regression, and it might be good to have a unit test to try different cases against this regex

**Review by momesgin — APPROVED** [review]
