### PR TITLE
Fixing several issues that stem from a race condition access issue around namespaces

### LINKED ISSUE #16442: Namespace label is not displayed correctly for users that can't list namespaces
**Setup**
- Rancher version: 2.14-head
- Rancher UI Extensions: N/A
- Browser type & version: N/A

**Describe the bug**

**To Reproduce**

1. Create a standard user
2. Log in as that standard users and create  (ie an rke2) cluster
3. Go into that clusuter's details

**Result**
"Namespace: false..." is shown. Hovering over it just adds a blank white rectangle

**Expected Result**

We should show an appropriate message and should not add a tooltip if it's blank

**Screenshots**

Image

**Additional context**

### PR DESCRIPTION
**Pull request by codyrancher**
### Summary
Fixes #16442

### Occurred changes and/or fixed issues

The namespace `ResourcePopover` could crash when the user lacked permission to list namespaces or when `currentProduct`/`currentCluster` were unresolved due to a race condition.

### Technical notes summary

- `useNamespace` now evaluates `currentStore`/`canList` inside the `computed` so they remain reactive and aren't accessed before the store is ready. The popover is gated behind `canList`, falling back to plain text.
- `ResourcePopover` renders a plain text when its fetch fails
- Conditional check in `Namespace.hideDetailLocation` and `Resource._glance` for `currentProduct`/`currentCluster`

### Areas or cases that should be tested
The namespace popover on cluster pages immediately after the cluster was created.

- Reproducing was pretty inconsistent, you have to immediately visit the cluster detail page after creating it to repro.

### Areas which could experience regressions
- **Resource detail masthead** — namespace/project/workspace identifying fields
- **`ResourcePopover`** — the `v-if="!fetch.error"` guard affects all consumers, not just namespace
- **Glance panel** — `_glance` the conditional changes could affect other resources

### Screenshot/Video
If the request fails we default to showing the id of the resource we're attempting to show without a popover.

image

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes
- [x] The PR has been reviewed in terms of Accessibility
- [x] The PR has considered, and if applicable tested with, the three Global Roles `Admin`, `Standard User` and `User Base`

### CODE REVIEW

File: shell/plugins/dashboard-store/resource-class.js [hunk 1]
```diff
@@ -1956,12 +1956,12 @@ export default class Resource {
...
         label:         this.t('component.resource.detail.glance.namespace'),
-        formatter:     'Link',
+        formatter:     this.$rootGetters['currentProduct']?.id && this.$rootGetters['currentCluster']?.id ? 'Link' : undefined,
         formatterOpts: {
           to: {
             name:     `c-cluster-product-resource-id`,
-            product:  this.$rootGetters['currentProduct'].id,
-            cluster:  this.$rootGetters['currentCluster'].id,
+            product:  this.$rootGetters['currentProduct']?.id,
+            cluster:  this.$rootGetters['currentCluster']?.id,
```
Comment (codyrancher) [inline shell/plugins/dashboard-store/resource-class.js:1964]: Ran into an issue where currentProduct and currentCluster were both undefined.

We now just default to text if the location options aren't available.

File: shell/models/namespace.js [hunk 2]
```diff
@@ -267,7 +267,9 @@ export default class Namespace extends SteveModel {
   }
 
   get hideDetailLocation() {
-    return !!this.$rootGetters['currentProduct'].hideNamespaceLocation;
+    const currentProduct = this.$rootGetters['currentProduct'];
+
+    return currentProduct ? !!currentProduct.hideNamespaceLocation : true;
```
Comment (codyrancher) [inline shell/models/namespace.js:272]: ran into an issue where currentProduct wasn't defined. If that occurs I just default to hiding the location since it's safer and we won't have the data to link to it anyway.

File: shell/components/Resource/Detail/ResourcePopover/__tests__/index.test.ts [hunk 3]
```diff
@@ -79,6 +79,18 @@ describe('component: ResourcePopover/index.vue', () => {
       expect(wrapper.find('.display').exists()).toBe(false);
     });
 
+    it('should show plain text and no PopoverCard when fetch fails', async() => {
+      mockClusterFind.mockRejectedValue(new Error('Not found'));
+      const wrapper = createWrapper(undefined, undefined, PopoverCardStub);
+
+      await wrapper.vm.$nextTick();
```
Comment (eva-vashkevich) [inline shell/components/Resource/Detail/ResourcePopover/__tests__/index.test.ts:86]: why does it need 3 waits?

Comment (codyrancher) [reply shell/components/Resource/Detail/ResourcePopover/__tests__/index.test.ts:86]: It's odd but it's actually needed if we keep this structure. The ticks are for:

1. The mockRejectedValue promise settles
2. The useFetch catch/finally block runs, setting error and clearing loading
3. Re-renders  based on the updated reactive state (v-if="!fetch.error" switches to the v-else span)

Comment (codyrancher) [reply shell/components/Resource/Detail/ResourcePopover/__tests__/index.test.ts:86]: It's a little pervasive in this file and it's mostly because of the popover/fetch.
