### PR TITLE
fix keyboard nav on show advanced in cluster create/edit

### LINKED ISSUE #14306: Create Cluster: Cannot navigate to Show Advanced via keyboard
**Setup**
- Rancher version: v2.12-head
- Rancher UI Extensions: NA
- Browser type & version: Firefox & Chrome latest

**Describe the bug**

It's not possible to navigate to and activate the Show Advanced feature when creating Machine Pools for a cluster.

**To Reproduce**

1. Navigate to Cluster Management and click on Create
2. Click on Amazon EC2
3. Enter a cluster name
4. ⚠️ Using keyboard only, navigate to Show Advanced under Machine Pools

**Result**

It's not possible to focus on Show Advanced

**Expected Result**

Show Advanced can receive keyboard focus and can be activated via keyboard

**Screenshots**

NA

**Additional context**

### PR DESCRIPTION
**Pull request by aalves08**
### Summary
Fixes #14306

### Occurred changes and/or fixed issues

- fix keyboard nav on show advanced in cluster create/edit

### Screenshot/Video

https://github.com/user-attachments/assets/c03a1543-31cf-44bf-9c70-cbff676dea0a

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes
- [x] The PR has been reviewed in terms of Accessibility

### CODE REVIEW

File: shell/components/AdvancedSection.vue [hunk 1]
```diff
@@ -32,9 +32,17 @@ export default {
       v-t="show ? 'generic.hideAdvanced' : 'generic.showAdvanced'"
       class="hand block"
       :class="{'mb-10': show}"
+      tabindex="0"
+      @keydown.enter.space.prevent="toggle"
```
Comment (rak-phillip) [inline shell/components/AdvancedSection.vue:36]: I think that this is a good candidate for https://github.com/rancher/dashboard/issues/13174 - I added it to the list.

**Review by rak-phillip — APPROVED** [review]
