### PR TITLE
Fixes an issue where a user had to click items in a dropdown menu twice in order to trigger an action

### LINKED ISSUE #15520: First click on item in scrollable drop down menu fails
**Setup**
- Rancher version:
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**
- We now show a scrollable popup when clicking on a drop down menu and there's not enough room to show the entire height of it
- in some scenarios clicking on a menu item within it
  - sets focus to the item and centers it
  - fails to execute action
- when in a list view it also selects the row

**To Reproduce**
- nav to any list
- shrink the screen height of the screen (i was working with 678px, also seen at 449, but there were some odd heights and clicks that did not trigger behaviour)
- click on a menu item

**Result**
- as per description

**Expected Result**
- action associated with item is exectued
- row is not selected

**Screenshots**
pending

### PR DESCRIPTION
**Pull request by codyrancher**
### Summary
Fixes #15520

### Technical notes summary
We would scroll the menu item into view when the menu item received focus. This in turn would prevent the action from getting triggered. We now prevent the focusin event from occurring the user clicks. This allows the focus event to still fire during keyboard navigation.

### Areas or cases that should be tested
Anywhere that there's a dropdown menu which has a scrollbar.

### Areas which could experience regressions
Keyboard navigation in the dropdown menu.

### Screenshot/Video
The cluster page example isn't as obvious because I only had one event but you can tell it's working since the action menu closes on click.

https://github.com/user-attachments/assets/1611939e-2268-43fa-ba21-3424e64b5890

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes
- [x] The PR has been reviewed in terms of Accessibility
- [x] The PR has considered, and if applicable tested with, the three Global Roles `Admin`, `Standard User` and `User Base`

### CODE REVIEW

File: pkg/rancher-components/src/components/RcDropdown/RcDropdownItem.vue [hunk 1]
```diff
@@ -36,6 +36,7 @@ const handleClick = (e: MouseEvent) => {
     @click.stop="handleClick"
     @keydown.enter.space="handleActivate"
     @keydown.up.down.prevent.stop="handleKeydown"
+    @mousedown.prevent="() => {/*We use this to prevent clicks from triggering the @focusin below. When we scroll on a click it prevents the action from occurring on the first click.*/}"
```
Comment (codyrancher) [inline pkg/rancher-components/src/components/RcDropdown/RcDropdownItem.vue:39]: If there's a better way to leave a comment right next to the @focusin I'd be happy to switch.
