### PR TITLE
Fix Unable to add extension tab to Edit Storage Class page

### LINKED ISSUE #11122: Unable to add extension tab to Edit Storage Class page
I am developing a new extension for Portworx and as a usecase, i need to add a new tab in StorageClass tabSection.
Screenshot 2024-05-25 at 12 03 21 AM

I have added the below code in my index.ts

image

The same code is able to add a new tab when i give resourceType as persistentvolumeclaim or some other resource type. but for storageClass it fails.

image

Let me know if i am missing anything.

### PR DESCRIPTION
**Pull request by aalves08**
### Summary
Fixes #11122 

### Occurred changes and/or fixed issues

- Improve extension point for `tabs` to allow more use cases (also implement a "default" for locationConfig IF there's no `mode` specified)

### Areas or cases that should be tested

- Add the following code to https://github.com/rancher/dashboard/blob/master/pkg/harvester-manager/index.ts:
```
plugin.addTab(
    TabLocation.RESOURCE_DETAIL,
    { resource: ['persistentvolumeclaim', 'storage.k8s.io.storageclass', 'configmap'] },
    {
      name:       'some-name',
      labelKey:   'generic.comingSoon',
      label:      'some-label',
      weight:     -5,
      showHeader: true,
      tooltip:    'this is a tooltip message',
      component:  () => import('./../../shell/components/BackLink.vue')
    }
  );
```
- Check that tabs are added ONLY in `detail` view mode and that it cover the scenario specified on the issue
- Check other general uses of the TAB extension point and make sure it works

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: shell/core/plugin.ts [hunk 1]
```diff
@@ -162,6 +163,12 @@ export class Plugin implements IPlugin {
    * Adds a tab to the UI
    */
   addTab(where: string, when: LocationConfig | string, tab: Tab): void {
+    // tackling https://github.com/rancher/dashboard/issues/11122, we don't want the tab to added in _EDIT view, unless overriden
+    // on extensions side we won't document the mode param for this extension point
```
Comment (jordojordo) [inline shell/core/plugin.ts:167]: What's the reasoning behind not documenting this? It seems a useful feature that I believe other extension developers would be interested in correct?

**Review by jordojordo — APPROVED** [review]

File: shell/core/plugin.ts (hunk 1 above)
Comment (aalves08) [reply shell/core/plugin.ts:167]: We don't want them to possibly tamper with an `EDIT` view of a resource like `provisioning.cattle.io.cluster`, imho.

Comment (jordojordo) [reply shell/core/plugin.ts:167]: Makes sense, we don't need to let them know about the Pandora's box that is `IPlugin` 🙂
