### PR TITLE
Fixed error message when recieved from Norman

### LINKED ISSUE #14427: Wrong error is displayed in banners for operations that use Norman API
**Setup**
- Rancher version: 2.12
- Rancher UI Extensions: None
- Browser type & version: Any

**Describe the bug**

We do not process errors returned by Norman correctly

**To Reproduce**

Import Generic cluster name 'a'
Attempt to enter another generic cluster named 'a'

**Result**
{"baseType":"error","code":"NotUnique","fieldName":"Cluster name","message":"","status":422,"type":"error"}
error is displayed

**Expected Result**

Error should be displayed in a human-readable format

**Screenshots**

Image

**Additional context**

### PR DESCRIPTION
**Pull request by eva-vashkevich**
### Summary
Fixes #14427

Currently, we do not format errors received from Norman. This has been adjusted to match what we did in Ember more closely.

### Areas or cases that should be tested

Import a cluster and name it 'a'
Attempt to import another cluster named 'a'
The error returned should correctly inform of the issue

### Areas which could experience regressions

Any component that displays errors from responses

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes
- [x] The PR has been reviewed in terms of Accessibility

### CODE REVIEW

File: shell/components/CruResource.vue [hunk 1]
```diff
@@ -427,6 +427,83 @@ export default {
...
+      const msg = !!err?.message ? ` ${ err?.message }` : '';
+
+      if ( err?.code === 'ActionNotAvailable' ) {
+        str = this.t('errors.actionNotAvailable');
+      } else if ( err?.status === 422 ) {
+        str = this.t('errors.failedInApi');
+        let something = false;
+
+        if ( err?.fieldName ) {
+          str += ` '${ err?.fieldName }'${ msg }`;
```
Comment (codyrancher) [inline shell/components/CruResource.vue:446]: Is this how it was already done in Ember? If so, I'll accept this.

In general it tends to be a bad idea to modify/concatenate translated strings since not all languages are read left to right top to bottom.

Comment (codyrancher) [reply shell/components/CruResource.vue:446]: Got it, given it's a direct port I don't expect you to make any changes.

In general we should make better use of parameters in the translation strings.

**Review by codyrancher — DISMISSED** [review]
