### PR TITLE
Don't provide default slot to `CruResourceFooter`

### LINKED ISSUE #11716: Vue3: Resource Detail: Config View: Renders incorrectly
**Setup**
- Rancher version: dev 2.10.0

**Describe the bug**
- detail page's view config renders incorrectly

**To Reproduce**
- Pods list --> pod --> `Confg` tab
- cluster list --> cluster --> `Config` tab
- etc

## Additional Info

This is most likely related to changes in how slots are managed in Vue3. We had similar issues with rendering slot content when rendering create pages for provisioning new clusters. You can reference [shell/components/CruResource.vue](https://github.com/rancher/dashboard/pull/11686/commits/aedd3348035cebaeeea57832e5947f780511fdcd#diff-3949ec5a78c462b58bebb75bc06ccea895056a12129a9a8b8841dac3dd6b07d0) for more details.

**Result**
main content layout seems to push form to right

**Expected Result**
pre vu3 merge

**Screenshots**
### 2.10 (Vue3)

image

image

### 2.9 (Vue2)

Image

### LINKED ISSUE #11741: Vue3: Role Detail page table is duped
**Setup**
- Rancher version: dev of 2.10.0

**Describe the bug**
- Duplicate role table is shown in detail page of role
- Duplicate template element?

**To Reproduce**
Users & Authentication --> Role Templates --> click on Administrator 

**Result**
image

**Expected Result**
no table bottom right

### PR DESCRIPTION
**Pull request by rak-phillip**
### Summary
This resolves the issue of `CruResource` rendering duplicate templates by excluding the default slot from being provided to `CruResourceFooter`.

Fixes #11716
Fixes #11741

### Occurred changes and/or fixed issues

- don't expose the default slot in `CruResourceFooter`

### Technical notes summary

This behavior is directly related to Vue3 Slot Unification[^1] and is only an issue in instances where we iterate over slots.

In Vue2, this template would iterate over scoped slots via `v-for="(_, slot) of $scopedSlots"`. Since `$scopedSlots` has been merged with `$slots` in Vue3, we are now inadvertently picking up the default slot along with the rest. 

In previous instances of this error, we filtered for scoped slots via `v-if="typeof $slots[slot] === 'function'"`. For the offending instances addressed in this PR, `default` was also being treated as a scoped slot and we still don't want to render it in our templates.

[^1]: https://v3-migration.vuejs.org/breaking-changes/slots-unification#slots-unification

### Areas or cases that should be tested

- any form that makes use of `CruResource` and `CruResourceFooter`
- examples listed in issues

### Areas which could experience regressions

- any form that makes use of `CruResource` and `CruResourceFooter`
- examples listed in issues

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: shell/components/CruResource.vue [hunk 1]
```diff
@@ -596,7 +600,7 @@ export default {
                     v-for="(_, slot) of $slots"
```
Comment (richard-cox) [inline shell/components/CruResource.vue:600]: not sure i 100% follow this issue, but if vue3 handles $slots differently can we confirm other places we pass down $slots aren't also affected?

Comment (rak-phillip) [reply shell/components/CruResource.vue:600]: This behavior is directly related to Vue3 Slot Unification[^1] and is only an issue in instances where we iterate over slots.

In Vue2, this template would iterate over scoped slots via `v-for="(_, slot) of $scopedSlots"`. Since `$scopedSlots` has been merged with `$slots` in Vue3, we are now inadvertently picking up the default slot along with the rest. 

In previous instances of this error, we filtered for scoped slots via `v-if="typeof $slots[slot] === 'function'". For the offending instances addressed in this PR, `default` was also being treated as a scoped slot and we still don't want to render it in our templates.

I've updated the PR description to call more attention to this behavior. 

[^1]: https://v3-migration.vuejs.org/breaking-changes/slots-unification#slots-unification

Comment (richard-cox) [reply shell/components/CruResource.vue:600]: Gotcha. So we'd be vulnerable to anywhere we previously iterated through $slots that included one that was scoped. I had a look through and we very rarely did it. All good

**Review by richard-cox — APPROVED** [review]

**Comment by izaac** [comment]
Visual styling mostly, moving to done.
