### PR TITLE
Resolve an issue where we weren't allowing users to login with other auth providers

### LINKED ISSUE #10974: [v2.9] Missing Login button for external provider
**Setup**
- Rancher version: v2.9.0 (pre-release)
- Rancher UI Extensions: `master`

**Describe the bug**
When an external provider is configured the Login button is not shown

image

**To Reproduce**
- Configure an external provider
- Logout
- Try to login

**Result**
Login button is not visible

**Expected Result**
Login button should be visible

### PR DESCRIPTION
**Pull request by codyrancher**
https://github.com/rancher/dashboard/issues/

### Summary
Fixes #10974 

### Technical notes summary
In the self review comments I mentioned auth/verify being broken. This is due to the removal of the invocation of legacy fetch methods. I explained in a little more detail in that comment.

### Areas or cases that should be tested
Logging in with different auth providers. I've opened an issue to add test automation around auth providers https://github.com/rancher/dashboard/issues/10984

### Areas which could experience regressions
Logging in

### Screenshot/Video

https://github.com/rancher/dashboard/assets/55104481/91fea7ad-edb4-406e-8665-4b84b5c057cb

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: shell/pages/auth/verify.vue [hunk 1]
```diff
@@ -25,21 +25,21 @@ function isSaml($route) {
 }
 
 export default {
-  async fetch({ store, route, redirect }) {
-    const code = route.query[GITHUB_CODE];
-    const stateStr = route.query[GITHUB_NONCE];
+  async fetch() {
```
Comment (codyrancher) [inline shell/pages/auth/verify.vue:28]: While working on this the verify step of the auth provider was also failing.

It became apparent that the [legacy fetch](https://v2.nuxt.com/docs/features/data-fetching/#the-fetch-hook) was no longer being invoked. I converted this to the new version of fetch to resolve this.

I found one other usage of the legacy fetch https://github.com/rancher/dashboard/blob/master/shell/pages/clusters/index.vue. That page does not appear to be getting used or linked to anywhere and I'd rather address it in a separate PR.

Comment (richard-cox) [reply shell/pages/auth/verify.vue:28]: Sounds good. It's just a helper to redirect `/c` to a cluster. I don't think it's used anywhere other than when users nav directly to that url

Comment (richard-cox) [inline shell/pages/auth/verify.vue:28]: Comment only. Was wondering if something like below was better (cleaner diff) BUT the rest of the file uses `this.$` so that's a better pattern

```
  async fetch() {
    const { $store: store, $route: route, $router: router } = this;
```

**Review by richard-cox — APPROVED** [review]

File: shell/pages/auth/verify.vue (hunk 1 above)
Comment (codyrancher) [reply shell/pages/auth/verify.vue:28]: I'm honestly fine with either. If the team wanted to adopt destructing I'd be happy. I'd just like to be consistent with one, has that already started and I haven't noticed?

Comment (richard-cox) [reply shell/pages/auth/verify.vue:28]: It's in use in a fair number of places, but i'm not sure it's a universal either/or thing. I'd vote 100% fine to use `this.` in this case
