### PR TITLE
Ensure features that depend on local cluster continue to work when we don't fetch all clusters

### LINKED ISSUE #15846: Unexpected sidebar pops up in harvester standalone UI
**Setup**
- Rancher version: 2.13.0-alpha4 
- Shell: 3.0.8-rc.2
- Rancher UI Extensions: N/A
- Browser type & version: Chrome 

**Describe the bug**
Unexpected sidebar pop up in harvester standalone UI

**To Reproduce**
1. Git clone harvester-ui-ext by `git clone git@github.com:harvester/harvester-ui-extension.git`
2. Modify `@rancher/shell: 3.0.8-rc.2` in harvester-ui-extension/package.json
3. Local run up [standalone UI mode](https://github.com/harvester/harvester-ui-extension#standalone-mode).
4. Login 

**Result**

Image

**Expected Result**
No sidebar pop up.

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by richard-cox**
### Summary
Fixes #15846

### Occurred changes and/or fixed issues
- two store getters expected the store to contain all clusters and then find the local cluster from that list
  - isMultiCluster
  - isStandaloneHarvester
- when ssp is enabled for cluster side nav no longer up front fetches all clusters
- this means both getters could not find the local cluster 
  - isMultiCluster was always incorrectly false
  - isStandaloneHarvester also feeds into 
- both getters were used to determine things in harvester, like the visibility of the side bar in standalone mode (incorrectly shown)
- this is now fixed
  - functional changes are all in shell/store/index
  - when ssp is enabled we manually fetch local cluster
  - when ssp is disabled we already get all clusters
  - in both worlds we now cache the local cluster
  - this is then used straight away to determine harvester single product stuff
  - the cached copy is then used
    - in isMultiCluster, and we also get the count from COUNT resource instead of stored list
    - in isStandaloneHarvester
    - also used in the dynamic content world
- Tidying up
  - fix regression where header.vue wasn't using correct getter to determine if toplevelmenu was shown
  - added clarification on where IF_HAVE.MULTI_CLUSTER was used (not in dashboard, but an extension)
  - snuck in an update to api docs

### Areas or cases that should be tested
- Standalone Mode - point the harvester extension at the PR and run in standalone mode.
  - setup steps
    - clone https://github.com/harvester/harvester-ui-extension
    - yarn link `@rancher/shell`
    - `RANCHER_ENV=harvester API=<harvester domain> yarn dev`
  - validate
    - the side bar (clusters, global products, settings, etc) should not be visible
    - RBAC group should not visible
    - Projects/Namespaces not visible, Namespaces visible
    - Create namespace should not show resource limit and PSA tabs
- Embedded Mode - run the PR against a cluster with a harvester cluster imported to it
  - validate - Virtualization Manager --> click on harv cluster
    - the side bar (clusters, global products, settings, etc) should be visible
    - RBAC --> Cluster Members should be visible (https://github.com/harvester/harvester/issues/3701)
    - Projects/Namespaces visible, Namespaces not visible
    - Create namespace should show resource limit and PSA tabs
- with both vai on and off
  - Request to `https://updates.rancher.io/rancher/community/updates` should contain `lkv`, `lcp`, and `lnc` query params (this request is made once a day, to repeat request again delete the `rancher-updates-fetch-next` local storage entry)

### Areas which could experience regressions
- top level menu placement (given it depends on isMultiCluster)
- users who don't have access to the local cluster should still be able to log in and use the dashboard

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes
- [x] The PR has been reviewed in terms of Accessibility
- [x] The PR has considered, and if applicable tested with, the three Global Roles `Admin`, `Standard User` and `User Base`

### CODE REVIEW

File: shell/store/type-map.js [hunk 1]
```diff
@@ -1904,10 +1904,10 @@ function ifHave(getters, option) {
   case IF_HAVE.ADMIN: {
     return isAdminUser(getters);
   }
-  case IF_HAVE.MCM_DISABLED: {
+  case IF_HAVE.MCM_DISABLED: { // There's a general MCM ff, this is conflating it with a harvester concept
```
Comment (a110605) [inline shell/store/type-map.js:1907]: Typo ff -> off.

**Review by a110605 — APPROVED** [review]
Tested with harvester standalone UI is good. The sidebar doesn't display.

image

File: shell/store/type-map.js (hunk 1 above)
Comment (richard-cox) [reply shell/store/type-map.js:1907]: ah, i should have expanded that. `ff` here means `Feature Flag`.

 I'll sneak an update in another PR
