### PR TITLE
Fixing view yaml in general and specifically in the case of provisioning clusters

### LINKED ISSUE #15736: Cluster config YAML takes user to incorrect page
**Setup**
- Rancher version:

[Rancher](https://github.com/rancher/rancher)	v2.13.0-alpha3
[Dashboard](https://github.com/rancher/dashboard)	v2.13.0-alpha2
[Rancher CLI](https://github.com/rancher/cli)	v2.12.0-rc.1

**Describe the bug**

**To Reproduce**

**Result**

**Expected Result**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by codyrancher**
### Summary
Fixes #15736

### Occurred changes and/or fixed issues
There were actually two problems that got fixed here. 
- One issue was that when a resource detail page was fully overriden we'd display a blank page when viewing yaml.
- The other issue was that for provisioning clusters we would show the yaml for management clusters.
   - Historically I think this was the correct solution but I don't think it's correct anymore, for both download yaml and edit yaml we've been showing the provisioning yaml for quite some time. By viewing the provisioning yaml for all cluster types we're now making each of these actions consistent.
  
### Areas or cases that should be tested
Viewing, editing and downloading yaml for each cluster provider type.

To make `View Yaml` visible you should login to a standard user that has been made a cluster member to the cluster you wish to invoke `View Yaml` on.

### Areas which could experience regressions
See above

### Screenshot/Video

https://github.com/user-attachments/assets/efffb851-bebe-4beb-862a-5d58025119c9

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes
- [x] The PR has been reviewed in terms of Accessibility
- [x] The PR has considered, and if applicable tested with, the three Global Roles `Admin`, `Standard User` and `User Base`

### CODE REVIEW

File: shell/components/ResourceDetail/index.vue [hunk 1]
```diff
@@ -310,7 +310,7 @@ export default {
       }), {});
     },
     isFullPageOverride() {
-      return this.isView && this.value.fullDetailPageOverride;
+      return this.isView && this.value.fullDetailPageOverride && !this.isYaml;
```
Comment (codyrancher) [inline shell/components/ResourceDetail/index.vue:313]: This fixes the issue where we would display a blank page for view yaml

File: shell/models/provisioning.cattle.io.cluster.js [hunk 2]
```diff
@@ -260,26 +259,6 @@ export default class ProvCluster extends SteveModel {
...
-
-    location.query = {
-      ...location.query,
-      [MODE]: _VIEW,
-      [AS]:   _YAML
-    };
-
-    this.currentRouter().push(location);
-  }
-
```
Comment (codyrancher) [inline shell/models/provisioning.cattle.io.cluster.js:282]: This may feel risky but the reason I was comfortable taking this approach was because we don't override the edit yaml or download yaml location for this model. By removing this we're making things more consistent.

That's not to say that there isn't some unknown risk though.

**Review by momesgin — APPROVED** [review]
Tested and LGTM
