### PR TITLE
Guard against unhandled exceptions when using `waitFor()`

### LINKED ISSUE #15714: UI Links Unclickable After Login After Session Timeout
SURE-10878

**Setup**
- Rancher version: 2.12.1

**Describe the bug**
When a session expires, logging back into the UI works, but the landing page becomes unresponsive (except for the sidebar expanding when clicked) and mouse clicks do not allow you to natigate away from the page. 

**To Reproduce**
* Login to Rancher. 
* Allow Session to expire
* Log in to Rancher Again
* Be unable to click any links in the resulting page until you hard refresh the page. 

**Result**
The page will not navigate away from your landing page. 

**Expected Result**
You can click on other links that result in the URI changing. 

**Screenshots**
(Will attach screencap video in next response) 

**Additional context**
Happens to be Firefox, but was reproduced previously on Chrome and Safari. LDAP is the auth source. I don't know if other auth sources are also affected.

### PR DESCRIPTION
**Pull request by rak-phillip**
### Summary
This change resolves issues surrounding permanently hung promises when unhandled exceptions are thrown by `waitFor()`. This change aims to reduce the number of scenarios where developers can inadvertently cause promises to hang(cede2d3cd36ad0e56b745b9b70bf15c0d4be56a3) while also adding some additional safety nets in the event that an unhandled exception is raised(21e08935b346c71d2e2b6f00274add8b1812c490)

Fixes #15714

### Occurred changes and/or fixed issues

- Always reject regardless of message passed to `waitFor()`
- Guard against unhandled exceptions using `waitFor()`

### Technical notes summary

Permanently hung promises are prevented by always rejecting regardless whether a message was passed to `waitFor()`. Switching to a `throw` when a message is omitted subverts expectations and is prone to error if a developer does not anticipate this change in behavior. Relying on reject is more predictable and will properly propagate through the Promise chain.

This also adds some guards to resolve issues with `waitForSettingsSchema` and `waitForSettings` where unhandled exceptions can cause the promise chain to hang. When in this state, promises are permanently unresolved and users are unable to interact with certain links throughout Dashboard.

- Add msg parameters to `waitForSettingsSchema` and `waitForSettings` so that timeouts will reject with a clear message
- Wrap both calls to `waitForSettingsSchema` and `waitForSettings` in a try..catch block so that the worker can be cleaned up instead of risking blocking the caller
- Return early instead of throwing a null reference error on `postMessage` so that `allHashSettled` can safely settle

### Areas or cases that should be tested

The existing behavior can be tested more quickly by setting `timeoutMs` to some incredibly low value: `timeoutMs = 50000`

https://github.com/rak-phillip/dashboard/blob/f0c2fb0089fab197bb24d3479f638edf7af2968f/shell/utils/async.ts#L1

I also set several auth ttl values to low values so that we can speed up the automatic logout behavior:

image

In order to assert that this change works. First, set up your environment so that you can easily repro in master. Second, checkout this change with the same repro previously performed. We can expect two behaviors:

1. An absence of an error printed to the console:
   ```
   Uncaught Error: waitFor timed out after 50 seconds
    timeout async.ts:16
    setTimeout handler*./shell/utils/async.ts/waitFor/< async.ts:9
    waitFor async.ts:4
    waitForSettingsSchema subscribe.js:134
    createWorker subscribe.js:198
    steveStoreInit index.js:62
    __WEBPACK_DEFAULT_EXPORT__ index.js:51
    Store vuex.esm-bundler.js:958
    Store vuex.esm-bundler.js:958
    createStore vuex.esm-bundler.js:897
    extendStore store.js:87
    extendApp app-extended.js:37
    js entry.js:33
   ```
2. After logging in, the links in question function as expected

### Areas which could experience regressions

I think there are some risks in modifying the behavior of our websocket connections. Most notably, I can be incorrect about my assumptions in how to properly clean up workers in 21e08935b346c71d2e2b6f00274add8b1812c490. 

### Screenshot/Video

NA - the demonstrable change is of hard to prove with video/screenshots. I highly recommend a repro to assert that the issue is resolved. 

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes
- [x] The PR has been reviewed in terms of Accessibility
- [x] The PR has considered, and if applicable tested with, the three Global Roles `Admin`, `Standard User` and `User Base`

### CODE REVIEW

File: shell/plugins/steve/subscribe.js [hunk 1]
```diff
@@ -195,8 +201,20 @@ export async function createWorker(store, ctx) {
...
+  try {
+    await waitForSettingsSchema(storeName, store);
+    await waitForSettings(storeName, store);
+  } catch (e) {
+    // Clean up the mock worker and abort so callers are not permanently blocked.
+    if (store.$workers[storeName]?.destroy) {
+      store.$workers[storeName].destroy();
+    } else {
+      delete store.$workers[storeName];
+    }
```
Comment (codyrancher) [inline shell/plugins/steve/subscribe.js:213]: Just like you mentioned in the description this is the only part that kind of concerns me.

1. Do we want to destroy mock workers since they're just queuing up messages and may be useful when we retry subscribing?
2. `delete store.$workers[storeName];` the comment at the catch level could be interpreted to mean we're cleaning up a mock here even though the absence of destroy would imply it's not a mock.

That said this seems to work and i think it's better practice to clean these resources up.
