### PR TITLE
Fix Console Router invalid param warnings

### LINKED ISSUE #12128: Vue3: Fix warnings with vue-router - `[Vue Router warn]: Discarded invalid param(s)`
**Setup**
- Rancher version: 2.10 - Vue3
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**

There's a lot of warnings from vue-router due to the fact that we use custom `params` in our application. According to https://github.com/vuejs/router/blob/main/packages/router/CHANGELOG.md#414-2022-08-22 it's an anti-pattern that is discouraged to use, since we shouldn't define `params` that aren't defined on the route.
 
 One of the biggest problems is that extensions rely on it, despite "hardcoding" it on their routes, so that the routes become unique and don't get a match with our broad wildcarded routes like: 
 
**broad dashboard routes**
` /:product/c/:cluster`
 
 vs
 
 **elemental example**
 `/elemental/c/:cluster`
 
 With that in mind, since our architecture needs the `product` param to work it's magic, in an extension we get a lot of warnings. I believe that dashboard also throws a few warnings as well.
 
Screenshot 2024-10-03 at 14 45 41

**To Reproduce**

- Run dashboard locally, vue3 edition, and check console

**Result**
Registering/navigating to a route with these "anti-pattern" `params` throws warnings to the console

**Expected Result**

No warnings should be thrown to the console

**Screenshots**

**Additional context**

### LINKED ISSUE #16220: Console Warning `[Vue warn]: Invalid prop: type check failed for prop "descending". Expected Boolean, got Undefined `
**Setup**
- Rancher version: v2.14.0 dev of and before

**Describe the bug**
- console warning

**To Reproduce**
- nav to a resource list

**Result**

Image

**Expected Result**
no console warning

**Additional context**
- I'm not 100% but these were changed as part of some recent ssp changes, i'll take first stab

### PR DESCRIPTION
**Pull request by codyrancher**
### Summary
Fixes #12128 
Fixes #16220

### Occurred changes and/or fixed issues
We now check to make sure params are present on a route definition before passing it to any $router methods. 

### Technical notes summary
Sometimes we look up the route definition and sometimes we conditionally send a param if we know they're available.

### Areas or cases that should be tested
Any management, global or explorer page should be checked. This was primarily an issue with out navigation sections.

### Areas which could experience regressions
Any management, global or explorer page should be checked. This was primarily an issue with out navigation sections.

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes
- [x] The PR has been reviewed in terms of Accessibility
- [x] The PR has considered, and if applicable tested with, the three Global Roles `Admin`, `Standard User` and `User Base`

### CODE REVIEW

File: shell/components/SortableTable/THead.vue [hunk 1]
```diff
@@ -31,7 +31,8 @@ export default {
     },
     descending: {
       type:     Boolean,
-      required: true
+      required: false,
```
Comment (codyrancher) [inline shell/components/SortableTable/THead.vue:34]: Unrelated but there was another warning where we were passing undefined to this. Since there wasn't any related bugs that I found I think it's safe to default to false.

File: shell/utils/router.js [hunk 2]
```diff
@@ -117,3 +117,53 @@ export function findMeta(route, key) {
...
+ * Find a route definition given a routeName
+ * @param {*} router VueRouter instance
+ * @param {*} routeName the name we want to look up
+ * @returns the route definition or undefined if it wasn't found
+ */
+export function findRouteDefinitionByName(router, routeName) {
+  const routes = router.getRoutes();
+
+  return routes.find((r) => r.name === routeName);
+}
```
Comment (codyrancher) [inline shell/utils/router.js:131]: I did this in the simplest programmatic way. I didn't find any performance issues so I left it but it would be possible to cashing these in a name-to-route object. We'd  have to be careful with extensions which I wanted to avoid unless it becomes necessary.

File: shell/components/SortableTable/THead.vue (hunk 1 above)
Comment (codyrancher) [reply shell/components/SortableTable/THead.vue:34]: It has an issue  #16220

File: shell/utils/fleet.ts [hunk 3]
```diff
@@ -194,6 +194,13 @@ class Fleet {
         id:        r.name,
       },
     };
+
+    // Having an undefined param can yield a console warning like [Vue Router warn]: Discarded invalid param(s) "namespace" when navigating
+    if (location && !location.params.namespace) {
+      delete location.params.namespace;
+    }
+
+    return location;
```
Comment (rak-phillip) [inline shell/utils/fleet.ts:203]: If I understand, the lack of access to a valid router is what prevents us from using the new `filterLocationValidParams()` in locations like this, RelatedResource, and LinkName so the manual deletion is needed in these areas. Is that correct?

**Review by rak-phillip — COMMENTED** [review]
Testing these changes and everything is looking good. The warnings appear to be resolved across the board. I only have one question before we merge.

File: shell/utils/fleet.ts (hunk 3 above)
Comment (codyrancher) [reply shell/utils/fleet.ts:203]: So that would be a reasonable reason for this change but it wasn't the motivation for my choice. In this scenario and the other like it, we know what route we're navigating to and we can adjust the params without having to do a lookup. 

If you'd like to be consistent I can look into plumping the router in.

Comment (rak-phillip) [reply shell/utils/fleet.ts:203]: Hmm.. While the consistency might be nice, I don't think it will be worth it if there's a level of effort involved. I think this is good as it is.

Comment (rak-phillip) [reply shell/utils/fleet.ts:203]: Hmm.. While the consistency might be nice, I don't think it will be worth it if there's a level of effort involved. I think this is good as it is.

**Review by rak-phillip — APPROVED** [review]
