### PR TITLE
Passes rules to certificate host field, extends arraylist to use rules

### LINKED ISSUE #4575: Additional UI-side validation for Ingress form
Original description below. Per the comments, there is no backend issue, but the ask is for UI to have additional validation to prevent these requests from going through until data is valid.

**Rancher Server Setup**
- Rancher version: 2.6.2
- Installation option (Docker install/Helm Chart):  Docker install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):  RKE1
- Proxy/Cert Details:  self signed

**Information about the Cluster**
- Kubernetes version:   v1.21.6
- Cluster Type (Local/Downstream): Local installation via docker, 1x Rancher, 2x Worker Nodes

**Describe the bug**
I can't create an ingress.  No matter what value I use for "Name" I get the message:

`Ingress.extensions "example.com" is invalid: [spec.rules[0].http.paths[0].path: Invalid value: "": must be an absolute path, spec.tls[0].hosts[0]: Invalid value: "": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]`

**To Reproduce**
Try to create an ingress and use any name.  Click create and the error message appears. 

**Result**
The error `Ingress.extensions "whatever" is invalid` and the ingress is not created.

**Expected Result**
Create the ingress with the name given.

**Screenshots**
With example.com (like the error message even gives as a valid example):
image

With 'something-else':
image

With 'foo':
image

**Additional context**

### PR DESCRIPTION
**Pull request by Sean-McQ**
### Summary
Fixes #4575
Adds in rules for certificate host when present, passes down to certificate host input, extends arraylist to allow for rules

### CODE REVIEW

File: shell/components/form/ArrayList.vue [hunk 1]
```diff
@@ -266,6 +274,17 @@ export default {
                 @paste="onPaste(idx, $event)"
                 @input="queueUpdate"
               />
+              <LabeledInput
```
Comment (codyrancher) [inline shell/components/form/ArrayList.vue:277]: This only makes rules work for a small subset of the ArrayList functionality. I think rules need to be evaluated within arraylist itself otherwise it won't work with slots, multiline or regular input.

**Review by codyrancher — CHANGES_REQUESTED** [review]

File: shell/components/form/ArrayList.vue (hunk 1 above)
Comment (Sean-McQ) [reply shell/components/form/ArrayList.vue:277]: With slots, we'll be able to pass in rules directly to the input component where they're passed into the slot and the arraylist itself won't even need the rules passed into it. As far as multi-line input, it doesn't look like we actually use this option for arraylist anywhere in the codebase (I considered ripping it out actually but figured that'd be stepping outside of the scope of the ticket a bit much). For regular input, it should never actually be used if there are more than 0 rules passed in since the rules array length is what I'm actually evaluating to know if I should be using labeled-input or the standard input.

I _could_ refactor this component to add in the labeled tool-tip to the basic html input on arraylist that we're using here but that'd basically just be copy/pasta from labeled-input which already knows how to handle rules and really just needs the compact option turned off in order to fit into this form correctly. I could also just rip out the basic html input altogether but I'd run the risk of messing up any deep targeted CSS that might be using arraylist and potentially increase the QA overhead (I didn't do a full analysis to figure out how common that is though); instead I chose to basically gate it behind the presence of rules so that I know it's only used in one place for now.

Comment (codyrancher) [reply shell/components/form/ArrayList.vue:277]: I think you should file an issue to do the refactor so we can remove the dead code. Once the issue is filed so we can track it I'm fine to ship it.

Comment (Sean-McQ) [reply shell/components/form/ArrayList.vue:277]: https://github.com/rancher/dashboard/issues/6507

**Review by codyrancher — APPROVED** [review]
