### PR TITLE
[backport v2.12.5] Subnetwork full name

### LINKED ISSUE #16041: [backport v2.12.5] [BUG] Rancher GKE Cluster Creation Fails with Shared VPC Subnetworks
This is a backport issue for https://github.com/rancher/dashboard/issues/15432, automatically created via [GitHub Actions workflow](https://github.com/rancher/dashboard/actions/runs/19677073406) initiated by @gaktive

Original issue body:

JIRA: SURE-10594

### **Issue Description:**
When creating a GKE cluster in a Shared VPC setup, Rancher attempts to reference the subnetwork using only its short name (e.g., gcp-non-prod-us-east4). GCP rejects this with a 404 Not Found, because in Shared VPCs subnetworks belong to the host project and must be referenced using the fully qualified path:

### **Env:** 
Rancher: 2.12.0
local cluster: Helm, 
Rke2 version: 1.31

****Steps to Reproduce:****

- Set up a GKE cluster creation via Rancher using a Shared VPC subnetwork.

- Apply the cluster config with only the short subnetwork name.

- Observe the failure with a 404 error from GCP.

****Expected Behavior:****
Rancher should detect when the subnetwork is in a Shared VPC and automatically resolve or expand the short name to the fully qualified subnetwork resource path.

**Workaround:**
Manually update the cluster config YAML to include the fully qualified subnetwork path before applying.

**Additional Information:**

`time="2025-08-04T19:45:48Z" level=error msg="Error recording gkecc [ (id: )] failure message: Operation cannot be fulfilled on gkeclusterconfigs.gke.cattle.io \"c-n4l99\": the object has been modified; please apply your changes to the latest version and try again, original error: googleapi: Error 404: Not found: project \"logics-2-0-nonprod\" does not have a subnetwork named \"gcp-non-prod-us-east4\" in region \"us-east4\".\nDetails:\n[\n  {\n    \"@type\": \"type.googleapis.com/google.rpc.RequestInfo\",\n    \"requestId\": \"0x48e0f3fcc65a172c\"\n  }\n]\n, notFound" `

### PR DESCRIPTION
**Pull request by momesgin**
**Backport of PR https://github.com/rancher/dashboard/pull/15769**

### Summary
Fixes #16041 

### Occurred changes and/or fixed issues

We now will send the full path for `sunbetwork` instead of the short formatted version.

### Technical notes summary

- Updated `formatSubnetworkOptions` in `shell/components/google/util/formatter.ts` to return the full path for the name
- Updated `shell/machine-config/google.vue` to use the label instead of name for consistency between GKE and GCE forms
- Unit tests

### Areas or cases that should be tested

Go to **GKE** and **GCE** cluster creation pages and check:
- we're still displaying the same short format for the name of a subnetwork
- we're sending the full path format in the payload of the network request

### Areas which could experience regressions

The above should cover the main regression possibiities, just also make sure the cluster gets created successfully.

### Screenshot/Video

GKE before:
image

GKE after:
image

GCE before:
image

GCE after:
image

The subnetwork dropdown:
Screenshot 2025-10-28 at 2 15 13 PM
Screenshot 2025-10-28 at 2 14 29 PM
Screenshot 2025-10-28 at 2 12 41 PM
Screenshot 2025-10-28 at 2 13 45 PM

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes
- [x] The PR has been reviewed in terms of Accessibility
- [x] The PR has considered, and if applicable tested with, the three Global Roles `Admin`, `Standard User` and `User Base`

### CODE REVIEW

File: shell/components/google/util/formatter.ts [hunk 1]
```diff
@@ -67,10 +67,13 @@ export function formatSubnetworkOptions(t: Translation, network: string, subnetw
   }
 
   const labeled: GKESubnetworkOption[] = out.map((sn: GKESubnetwork) => {
-    const name = sn.name ? sn.name : (sn.subnetwork || '').split('/').pop();
+    const shortName = sn.name ? sn.name : (sn.subnetwork || '').split('/').pop();
+    const fullName = sn.subnetwork || sn.selfLink || shortName;
```
Comment (eva-vashkevich) [inline shell/components/google/util/formatter.ts:71]: are we sure both sn.subnetwork and  sn.selfLink are okay? have we tested with both?

Comment (momesgin) [reply shell/components/google/util/formatter.ts:71]: could you explain a bit more? is this something that we should've checked in 2.13?

Comment (eva-vashkevich) [reply shell/components/google/util/formatter.ts:71]: I might be just ignorant, but I am not convinced sn.subnetwork and sn.slefLink are interchangeable?

Comment (momesgin) [reply shell/components/google/util/formatter.ts:71]: you're definately more knowledgeable than me on this, how can I test this?

Comment (eva-vashkevich) [reply shell/components/google/util/formatter.ts:71]: I don't think sn.subnetwork ever exists?

Comment (eva-vashkevich) [reply shell/components/google/util/formatter.ts:71]: @mantis-toboggan-md I think you were the first to add sn.subnetwork as a name (https://github.com/rancher/dashboard/pull/14694/files#diff-214cc722ead9ea3d6cb41a9911f99338c7fb74ea423e7b21069b2ed9c129de03) . do you know if it's ever there?
I don't think it should be a first choice at least

Comment (mantis-toboggan-md) [reply shell/components/google/util/formatter.ts:71]: this was probably originally supposed to fall back to `sn.network` not `sn.subnetwork`, a mistake on my part. Either way selfLink should be the first choice. I'm not sure it would ever be undefined and require a fallback but sn.network is the subnet's network's selfLink

Comment (momesgin) [reply shell/components/google/util/formatter.ts:71]: I had to update some unit tests to pass after this change:

```
    const shortName = sn.name ? sn.name : (sn.network || '').split('/').pop();
    const fullName = sn.selfLink || sn.network || shortName;
```

Now the question is, should we create a new issue for this and merge it to the master branch first and then backport to 2.12.5? or address it here and forwardport to master later?

Comment (momesgin) [reply shell/components/google/util/formatter.ts:71]: To make things more organized I've created [an issue](https://github.com/rancher/dashboard/issues/16052) for it and raised a [separate PR](https://github.com/rancher/dashboard/pull/16053).

Comment (mantis-toboggan-md) [reply shell/components/google/util/formatter.ts:71]: I was wrong. `sn.subnetwork` is defined when the user has selected a shared vpc, in which case, `sn.selfLink` is not defined. Sorry to everyone involved.

**Review by mantis-toboggan-md — APPROVED** [review]

File: shell/components/google/util/formatter.ts (hunk 1 above)
Comment (momesgin) [reply shell/components/google/util/formatter.ts:71]: no worries at all, I think the unit tests you've written before was very helpful to catch this, the failing tests made me confident to separate this.
