### PR TITLE
Fix cluster count when there are Harvester clusters

### LINKED ISSUE #15971: Show the correct Cluster and Harvester Cluster counts in the resource menu
- We split prov clusters into two
  - Cluster Management --> Clusters
    - Shows all except harvester clusters
    - The count shown in the resource menu shows ALL clusters, which is incorrect
  - Virtualization Management (harvester) --> Clusters
    - Shows all harvester clusters
    - The count shown in the resource menu does not exist
- Counts come from the `counts` resources which doesn't allow filtering
- https://github.com/rancher/rancher/issues/34905 was created but not likely to succeed
- We might be able to work around this in the UI
  - Allow resource menu's to use an alternative to the `count` object
  - For vai on world
    - piggyback on top level menu cluster requests which already exclude harvester clusters
    - this doesn't hit the store, but can expose the counts
    - need to ensure this works when there are pinned clusters as well (multiple requests)
  - For vai off world
    - we can do the calculation locally, triggered on count change to avoid churn
  - This must be peformant, we cannot execute the function on render

### PR DESCRIPTION
**Pull request by nwmac**
### Summary
Fixes #15971

### Occurred changes and/or fixed issues

This PR fixes an issue with the cluster count display when Harvester clusters are present. It introduces a "Saved Counts" mechanism to the dashboard store, allowing specific resource counts to be stored and retrieved separately from the generic store counts.

Changes:

- Added savedCounts to the state, along with a setSavedCount mutation and getSavedCount getter.
- Updated findAll and findPage actions to accept a saveCountAs parameter, which persists the response count to savedCounts.
- Updated PaginationWrapper to support passing saveCountAs to the underlying request.
- Introduced SAVED_COUNTS.K8S_CLUSTERS constant.
- Updated TopLevelMenu helper to save the CAPI.RANCHER_CLUSTER count as SAVED_COUNTS.K8S_CLUSTERS during fetch.
- Configured CAPI.RANCHER_CLUSTER in manager.js to use a custom.countGetter, which prioritizes the saved K8s cluster count.
- Updated Home Page (home.vue) to display the saved K8s cluster count in the badge.
- Updated Type component (Type.vue) to support custom.countGetter.

This ensures that the displayed cluster count accurately reflects the number of clusters returned by the pagination request (which filters correctly), resolving discrepancies that may arise from the generic resource counts when Harvester clusters are involved.

### Areas or cases that should be tested

Check that with a Harvester cluster registered, that the count in the side bar and on the home screen now show the count of clusters without Harvester, as described in screenshots below.

### Screenshot/Video

I have 4 k8s clusters and 1 Harvester cluster:

Before:

Home page incorrectly has a count of 5, but only 4 clusters in the table:

image

After:

image

Before:

Cluster Management list incorrectly has a count of 5, but only 4 clusters in the table:

image

After:

image

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes
- [x] The PR has been reviewed in terms of Accessibility
- [x] The PR has considered, and if applicable tested with, the three Global Roles `Admin`, `Standard User` and `User Base`

### CODE REVIEW

File: shell/pages/home.vue [hunk 1]
```diff
@@ -256,8 +256,14 @@ export default defineComponent({
...
     altClusterList() {
       return this.tooManyClusters && !this.altClusterListDisabled;
-    }
+    },
 
+    clusterCountDisplay() {
+      // If we have the cluster count from the store, use that instead
+      const savedCount = this.$store.getters['management/getSavedCount'](SAVED_COUNTS.K8S_CLUSTERS);
+
+      return !!savedCount ? savedCount : this.clusterCount;
```
Comment (richard-cox) [inline shell/pages/home.vue]: Think this should be something like `typeof savedCount !== 'undefined' ? savedCount : this.clusterCount`.

That might cover the world of standard-users who only have access to 1 harvester cluster. Bit of an edge case though.

File: shell/components/nav/TopLevelMenu.helper.ts [hunk 2]
```diff
@@ -216,7 +216,8 @@ export class TopLevelMenuHelperPagination extends BaseTopLevelMenuHelper impleme
           context: 'side-bar',
         }
       },
-      formatResponse: { classify: true }
+      formatResponse: { classify: true },
+      saveCountAs:    SAVED_COUNTS.K8S_CLUSTERS
```
Comment (richard-cox) [inline shell/components/nav/TopLevelMenu.helper.ts]: this fetches unpinned clusters, rather than all clusters. so creates this bug

Image

Image

generally i think we probably don't need the plumbing that supports it either 
in ActionFindPageArgs and pagination-wrapper. The former normally works on fetching a reduced amount and the latter fetches resources that don't hit the store. Up to you on those parts through.

Comment (richard-cox) [reply shell/components/nav/TopLevelMenu.helper.ts]: This does mean the requests to fetch clusters in the home page clusters list and the request to fetch cluster management cluster list clusters need the saveCountAs flag somehow

Comment (richard-cox) [reply shell/components/nav/TopLevelMenu.helper.ts]: For the side nav we do call findPage with filters 

```
filter: metadata.labels[provider.cattle.io]!=harvester
filter: status.provider!=harvester
```

Which is constructed via `paginationFilterClusters`

That one also handles the scenario where the local cluster is hidden (setting `hide-local-cluster`)

File: shell/pages/home.vue (hunk 1 above)
Comment (nwmac) [reply shell/pages/home.vue]: Done

**Review by richard-cox — DISMISSED** [review]

File: shell/components/nav/TopLevelMenu.helper.ts (hunk 2 above)
Comment (richard-cox) [reply shell/components/nav/TopLevelMenu.helper.ts]: Resolved via https://github.com/rancher/dashboard/pull/16499/commits/727bfd15ea76a9cd5a1bc06beaa646e331e02ca5
