### PR TITLE
Initial migration of Vue3 for compatible fixes

### LINKED ISSUE #10854: Initial migration of Vue3 for compatible fixes
# Description

As an effort to slim out the current [Vue3 migration configuration PR](https://github.com/rancher/dashboard/pull/9171/commits), isolate compatible changes.

## Context

Several fixes are required after updating the libraries, but many may be already adopted in the current state for reasons which may vary from:
- Existing deprecated flag and compatibility
- Missing flag for linters in newer TS versions
- Stricter markup requirements with currently equal outcome

### PR DESCRIPTION
**Pull request by cnotv**
### Summary
Fixes #10854

As mentioned in the issue, this is an effort to get rid of some commits present in the [migration PR](https://github.com/rancher/dashboard/pull/9171) 

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: pkg/aks/util/validators.ts [hunk 1]
```diff
@@ -5,7 +5,7 @@
  */
 
 import { get } from '@shell/utils/object';
-import { LoadBalancerSku, OutboundType } from 'types';
+import { LoadBalancerSku, OutboundType } from '../types/index';
```
Comment (codyrancher) [inline pkg/aks/util/validators.ts:8]: This should probably be switched to `@pkg/aks/types`

File: shell/assets/styles/global/_columns.scss [hunk 2]
```diff
@@ -1,6 +1,6 @@
 @use "sass:math";
 
-@import "~shell/assets/styles/base/functions";
```
Comment (codyrancher) [inline shell/assets/styles/global/_columns.scss:3]: What does this do? 

From what I read it was to prevent additional css files from being generated but I think we inline all of our css.

File: shell/edit/workload/__tests__/Upgrading.test.ts [hunk 3]
```diff
@@ -22,7 +22,7 @@ describe('component: Upgrading', () => {
     input.setValue(newValue);
     input.trigger('blur');
 
-    expect(wrapper.props('value')[key]).toBe(newValue);
+    expect(wrapper.props('value')?.[key]).toBe(newValue);
```
Comment (codyrancher) [inline shell/edit/workload/__tests__/Upgrading.test.ts:25]: Was this intentional? Should we know if the value is present in tests?

I might be missing something there.

**Review by codyrancher — APPROVED** [review]
Just a few questions. Feel free to push, I was just curious about some of it.

**Comment by richard-cox** [comment]
There's some changes to an extension here, can these be tracked somewhere? We can then advise internal/external extension owners to do the same

File: shell/assets/styles/global/_columns.scss (hunk 2 above)
Comment (cnotv) [reply shell/assets/styles/global/_columns.scss:3]: To be fair I forgot what was the initial error since the picked commit is 3 months old 😅 
There was an issue importing though, so I made it standard.

File: shell/edit/workload/__tests__/Upgrading.test.ts (hunk 3 above)
Comment (cnotv) [reply shell/edit/workload/__tests__/Upgrading.test.ts:25]: It was just to do not break the test while doing the migration and get non-formal errors.
It will fail anyway.

**Comment by cnotv** [comment]
> There's some changes to an extension here, can these be tracked somewhere? We can then advise internal/external extension owners to do the same

Sure thing, but what should be the topic? These are errors generated from a higher and stricter version of TS, so the author will have to fix many more of these afterward. The same is true for the rest of the code. I tried to check if can be automated something, but TS usually requires too much refactoring and is better manual.

**Review by codyrancher — APPROVED** [review]

**Comment by richard-cox** [comment]
> > There's some changes to an extension here, can these be tracked somewhere? We can then advise internal/external extension owners to do the same
> 
> Sure thing, but what should be the topic? These are errors generated from a higher and stricter version of TS, so the author will have to fix many more of these afterward. The same is true for the rest of the code. I tried to check if can be automated something, but TS usually requires too much refactoring and is better manual.

Maybe something generic stating that we now required TS version X and some common update changes may be... x,y,z. A lot of extension code comes from boilerplate stuff we auto-generate or provide via examples in docs, so a bit of hand holding will ease their pain.

**Comment by cnotv** [comment]
> > > There's some changes to an extension here, can these be tracked somewhere? We can then advise internal/external extension owners to do the same
> > 
> > 
> > Sure thing, but what should be the topic? These are errors generated from a higher and stricter version of TS, so the author will have to fix many more of these afterward. The same is true for the rest of the code. I tried to check if can be automated something, but TS usually requires too much refactoring and is better manual.
> 
> Maybe something generic stating that we now required TS version X and some common updates may be... x,y,z. A lot of extension code comes from boilerplate stuff we auto-generate or provide via examples in docs, so a bit of hand holding will ease their pain.

We are going to update all the libraries and dependencies with the scripts, so they do not have to change anything.
The major changes are way too diverse and are published in the TS documentation.
I have no way to foresee our boilerplate possible issues, plus this goes against the principle of using a type check. If I have to do it manually, what's the sense of it? 😅

**Comment by richard-cox** [comment]
> We are going to update all the libraries and dependencies with the scripts, so they do not have to change anything. The major changes are way too diverse and are published in the TS documentation. I have no way to foresee our boilerplate possible issues, plus this goes against the principle of using a type check. If I have to do it manually, what's the sense of it? 😅

If we're supplying a script to extension developers that will make the changes in this PR then no problem. 

If not, this PR contains changes to extensions that they may also have to make, and we can document to make their lives easier.

For example
- "Implementations of IClusterProvisioner can now get `Component` as `import type { Component } from 'vue';`"
- "Import paths should be complete, starting with `@pkg`"
- etc

We won't need everything, but just parts we know about and have done ourselves for our extensions
