### PR TITLE
Parse custom resource quotas as a flat list for editing Namespaces

### LINKED ISSUE #16798: [BUG] Extended quotas are not being setup correctly
**Rancher Server Setup**
- Rancher version:
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

**Describe the bug**

The quota namespace handler is spinning:

```
2026/02/27 11:18:43 [ERROR] error syncing 'test-ns-1': handler namespace-auth: json: cannot unmarshal string into Go struct field ResourceQuotaLimit.limit.extended of type map[string]string, handler resourceQuotaSyncController: json: cannot unmarshal string into Go struct field ResourceQuotaLimit.limit.extended of type map[string]string, requeuing
```

The Project spec has the correct settings

```yaml
spec:
  clusterName: local
  containerDefaultResourceLimit:
    limitsCpu: 20m
    limitsMemory: 20Mi
    requestsCpu: 1m
    requestsMemory: 1Mi
  displayName: testing
  namespaceDefaultResourceQuota:
    limit:
      extended:
        requests.nvidia.com/gpu: "2"
      limitsCpu: 2000m
      limitsMemory: 500Mi
      requestsStorage: 1Gi
  resourceQuota:
    limit:
      extended:
        requests.nvidia.com/gpu: "4"
      limitsCpu: 2000m
      limitsMemory: 2000Mi
      requestsStorage: 2Gi
    usedLimit: {}
```

But the NS quota is corrupted:

```yaml
metadata:
  annotations:
    field.cattle.io/containerDefaultResourceLimit: '{"limitsCpu":"20m","limitsMemory":"20Mi","requestsCpu":"1m","requestsMemory":"1Mi"}'
    field.cattle.io/description: testing 1
    field.cattle.io/projectId: local:p-7nszb
    field.cattle.io/resourceQuota: '{"limit":{"extended":"NaN","limitsCpu":"2000m","limitsMemory":"500Mi","requestsStorage":"1024Mi"}}'
```

**To Reproduce**

1. Navigate to Local Cluster Explorer => Cluster => Projects/Namespaces
2. Create a new project with a mix of predefined and custom resource quotas (mirror the yaml above for an example).
3. Click on "Create Namespace" for the newly created resource quota
4. Give the namespace a valid name and open the browser developer tools to monitor network requests
5. Click "Create"

**Result**

When rendering the Namespace Create/Edit form, the Resource Quotas tab is missing all custom quotas defined during project creation.

When Creating/Editing a resource quota, the request payload contains `"extended": "NaN"` in the collection of resource quotas for `metadata.annotations.field.cattle.io/resourceQuota`.

**Expected Result**

When rendering the Namespace Create/Edit form, all Resource Quotas created during Project creation should be displayed in the Resource Quotas tab.

When Creating/Editing a resource quota, the request payload should contain a fully-formed collection of resource quotas for `metadata.annotations.field.cattle.io/resourceQuota`.

**Screenshots**

Missing Custom Quotas in the Namespace Form:

Image

**Additional context**

Example of a malformed annotation:

```
      "field.cattle.io/resourceQuota": "{\"limit\":{\"extended\":\"NaN\",\"limitsCpu\":\"0m\",\"limitsMemory\":\"500Mi\",\"requestsStorage\":\"1024Mi\"}}",
```

Example of a well-formed annotation:

```
      "field.cattle.io/resourceQuota": "{\"limit\":{\"extended\":{\"requests.nvidia.com/gpu\":\"4\"},\"limitsCpu\":\"0m\",\"limitsMemory\":\"500Mi\",\"requestsStorage\":\"24Mi\"}}"
```

### PR DESCRIPTION
**Pull request by rak-phillip**
### Summary
This parses custom resource quotas as a flat list so that any values under the "extended" key read by the namespace edit form.

Fixes #16798

### Occurred changes and/or fixed issues

- Parse extended resource quotas for namespace form
- Add a display value for extended types
- Unit test the new namespace resource quota behavior

### Technical notes summary

This is very similar to the original approach taken in #16550, where we would flatten all of the properties under extended to produce a collection of keys prefixed with `extended.`. I think that this approach is safe here because this form does not deal with ArrayList.vue and we are not adding/removing resource quotas for the namespace form.

### Areas or cases that should be tested

See issue for more details: 

- Create/Edit namespace for project that contains custom resource quotas
   - Namespace form should render all resource quotas
   - Network request on save should contain all resource quotas

### Areas which could experience regressions

Pay attention to the functions that parse to and from flat lists. If there's an error in the logic, we could fail to render/save the form properly.

### Screenshot/Video

image

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes
- [x] The PR has been reviewed in terms of Accessibility
- [x] The PR has considered, and if applicable tested with, the three Global Roles `Admin`, `Standard User` and `User Base`

### CODE REVIEW

File: shell/components/form/ResourceQuota/Namespace.vue [hunk 1]
```diff
@@ -57,14 +57,35 @@ export default {
         .filter((type) => !this.types.includes(type.value) || type.value === currentType);
     },
     update(key, value) {
-      const resourceQuota = {
-        limit: {
-          ...this.value.resourceQuota.limit,
-          [key]: value
+      this.value['resourceQuota'] = { limit: this.limitsFromFlatList(key, value) };
```
Comment (codyrancher) [inline shell/components/form/ResourceQuota/Namespace.vue:60]: I don't think this is actually a problem and it was already present but I figured I'd bring it up just in case I'm missing something.

If resourceQuota ever had a properties outside of `limit` we would clobber it here by creating a new object and assigning it to resourceQuota.

Comment (rak-phillip) [reply shell/components/form/ResourceQuota/Namespace.vue:60]: The main difference here is how we populate limits, otherwise this should be the same behavior as before:

https://github.com/rancher/dashboard/blob/7ac7bd6075666b8e1f1a8b314908093b09c39c0c/shell/components/form/ResourceQuota/Namespace.vue#L59-L68
