### PR TITLE
Fix styles for `ResourceCancelModal`

### LINKED ISSUE #10648: 'Back to form' dialog styling is broken
Go to install a Helm Chart (e.g. Epinio) - make a change in the YAML. Click to go back to 'Edit as Form' and the dialog that is shown looks terrible:

image

### PR DESCRIPTION
**Pull request by rak-phillip**
### Summary
This updates the styles for `ResourceCancelModal.vue` so that the modal will render as it did before #10591 merged. 

Fixes #10648

### Occurred changes and/or fixed issues

- Use `customClass` prop for `app-modal`
- Remove `v--modal-box` styles - a quick review reveals that these styles weren't being applied to the original modal either, so they are not needed
- Keep styles `.header`, `.body`, and `.footer`

### Areas or cases that should be tested

This can be tested as a part of any "Edit as YAML" form. For example:

1. Navigate to Local Cluster => Storage => ConfigMaps
2. Click on "Create"
3. Click on "Edit as YAML"
4. Click on "Back to Form"

Observe the design of the modal, it should match the original design from v2.8.x

#### New

back-to-form-new

#### Original (v2.8.0)

back-to-form-org

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: shell/components/ResourceCancelModal.vue [hunk 1]
```diff
@@ -99,32 +99,27 @@ export default {
     margin: 0 10px;
   }
 
-  .v--modal-box {
```
Comment (cnotv) [inline shell/components/ResourceCancelModal.vue:102]: I see more `v--modal-box` around, should we be worried?

**Review by cnotv — APPROVED** [review]
Sorry to have been missing this on my radar 😓 

LGTM

File: shell/components/ResourceCancelModal.vue (hunk 1 above)
Comment (rak-phillip) [reply shell/components/ResourceCancelModal.vue:102]: The final two instances are associated with `shell/components/PromptModal.vue` (thoroughly tested and used throughout Dashboard) & `shell/dialog/RotateCertificatesDialog.vue` (uses `PromptModal`, the associated `rotate-modal` class appears to be unused). 

I removed both of those instances, because they were really unused.

**Review by cnotv — APPROVED** [review]
LGTM
