### PR TITLE
Fix target namespace for charts

### LINKED ISSUE #16368: v0.24.3 Turtles installation failing on Rancher 2.12-head version
### What steps did you take and what happened?

**Turtles**: v0.24.3, **Rancher**: v2.12-head (v2.12-f312cd39400f5ef81d3695b14c7dd8c2859f0c08-head)

Installation of Turtles v0.24.3 which is meant for Rancher 2.12 versions is failing on head version. Its using incorrect namespace _cattle-turtles-system_ for installation.

```
helm install --labels=catalog.cattle.io/cluster-repo-name=turtles-chart --namespace=cattle-turtles-system --timeout=10m0s --values=/home/shell/helm/values-rancher-turtles-0.24.3.yaml --version=0.24.3 --wait=true rancher-turtles /home/shell/helm/rancher-turtles-0.24.3.tgz
Error: INSTALLATION FAILED: failed pre-install: warning: Hook pre-install rancher-turtles/templates/pre-install-job.yaml failed: 1 error occurred:
	* namespaces "rancher-turtles-system" not found
```

Image

### What did you expect to happen?

Installation to work on released as well as dev versions.

### How to reproduce it?

_No response_

### Rancher Turtles version

_No response_

### Anything else you would like to add?

Its working on released versions.

Image

### Label(s) to be applied

/kind bug

### PR DESCRIPTION
**Pull request by momesgin**
### Summary
Fixes #16368 

### Occurred changes and/or fixed issues
- Fixed an issue where the chart installation/upgrade process relied on the chart's latest version target namespace instead of the target namespace defined in the specifically selected version.
- This ensures that when installing a specific version of a chart that has a different target namespace than the latest version, the correct namespace is used for creation or existing app detection.

### Technical notes summary
- Refactored `fetchChart` in `shell/mixins/chart.js` to fetch the specific version information **before** determining if the app is already installed.
- Updated the logic to prioritize `version.annotations['catalog.cattle.io/namespace']` and `version.annotations['catalog.cattle.io/release-name']` over `chart.targetNamespace` and `chart.targetName`.
- Updated `shell/pages/c/_cluster/apps/charts/install.vue` to set `this.forceNamespace` and `this.value.metadata.name` based on the selected version's annotations.
- Added unit tests in `shell/pages/c/_cluster/apps/charts/__tests__/install.test.ts` and `shell/mixins/__tests__/chart.test.ts` to verify the namespace resolution logic.

### Areas or cases that should be tested
1.  **Add the Repository:**
    *   Go to **Apps & Marketplace** -> **Repositories**.
    *   Click **Create**.
    *   Target: `https://rancher.github.io/turtles`
    *   Click **Create**.

2.  **Test Older Version (0.24.3):**
    *   Go to **Apps & Marketplace** -> **Charts**.
    *   Find **Rancher Turtles**.
    *   Click on the chart card.
    *   In the **Chart Versions** sidebar, select **0.24.3**.
    *   Click **Install**.
    *   Proceed through the wizard steps and click **Install** to start the process.
    *   **Verify:** If the installation starts and opens the terminal window, check the executed command. It **MUST** include:
        `--namespace=rancher-turtles-system`

3.  **Test Latest Version:**
    *   Go back to **Apps & Marketplace** -> **Charts** -> **Rancher Turtles**.
    *   Select the **latest** version 
    *   Click **Install** (or Upgrade if you managed to install the previous one).
    *   Proceed to the installation execution.
    *   **Verify:** Check the executed command in the terminal window. It **MUST** include:
        `--namespace=cattle-turtles-system`

Note: The actual success of the installation does not matter for this test; we are verifying that the UI targets the correct namespace for each version.

### Areas which could experience regressions

- Since the order of operations in `fetchChart` changed (fetching version before checking for existing app), verify that the dashboard still correctly identifies when an app is already installed versus a new install, especially for charts without fixed namespaces.
- Test installing a standard chart (no fixed namespace) to ensure no regressions.
- Test upgrading an existing app

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes
- [x] The PR has been reviewed in terms of Accessibility
- [x] The PR has considered, and if applicable tested with, the three Global Roles `Admin`, `Standard User` and `User Base`

### CODE REVIEW

File: shell/pages/c/_cluster/apps/charts/install.vue [hunk 1]
```diff
@@ -166,10 +166,10 @@ export default {
     } else if (this.$route.query[FROM_CLUSTER] === _FLAGGED) {
       /* For Fleet, use the fleet-default namespace. */
       this.forceNamespace = DEFAULT_WORKSPACE;
-    } else if ( this.chart?.targetNamespace ) {
+    } else if ( this.version?.annotations?.[CATALOG_ANNOTATIONS.NAMESPACE] ) {
       /* If a target namespace is defined in the chart,
       set the target namespace as default. */
-      this.forceNamespace = this.chart.targetNamespace;
+      this.forceNamespace = this.version.annotations[CATALOG_ANNOTATIONS.NAMESPACE];
```
Comment (richard-cox) [inline shell/pages/c/_cluster/apps/charts/install.vue:172]: Comment only. 

I thought we'd need to run through this all again if we can't link a chart to the app and user has to select. When that happens though we refresh the page and come back around to this code.

Comment (momesgin) [reply shell/pages/c/_cluster/apps/charts/install.vue:172]: I need to dig deeper on this.

I've created a tech dept [issue](https://github.com/rancher/dashboard/issues/16521) to address all the references to charts targetNamespace and targetName.
