### PR TITLE
Ensure we keep the same cached list and previous entries when SSP pages update

### LINKED ISSUE #15847: Pod list selection is lost after pods are updated
SURE-10901

**Setup**
- Rancher version: v2.12.0

**Describe the bug**
When selecting a few pods in the Rancher UI --> Workloads --> Pods and the Status of a Pod changes (for example to Running, Terminating,...) the selection resets and the user has to do it again.

Rancher 2.12.2 --> Selection resets when for example i scale a deployment
Rancher 2.10. --> Selection does not reset (The View does not refresh aswell)

I have tried with Server-Side Pagination on/off for the 2.10 since we enabled it by default in 2.12

**To Reproduce**
Spin Up Rancher 2.12
Select a few pods
Delete one, or scale a deployment up. Literally any change to the pods status works

**Result**
Status changes of Pods should reset my selection

**Expected Result**
Status changes of Pods should not reset my selection

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by richard-cox**
### Summary
Fixes #15847

### Occurred changes and/or fixed issues
- when a SSP enable page receives an update the entries in the store (list and map) get updated
- the map is just a key:value collection and was updated in place
  - new entries added, existing ones updated, old ones removed
- the list, which is an ordered array representing the page, was emptied and repopulated with the new page
  - this meant anything that _referenced_ the old entries were disconnected from their new matching entries in the list
  - this broke places like sortable table selection that relied on object reference checks

### Areas or cases that should be tested

- Deployments List - Selected Row Changes
  - Tab A - Deployments list - select a deployment
  - Tab B - scale up/down the deployment
  - Tab A - Row should remain selected, the deployment column's ready count should update
- Deployments List - Selected Row is removed
  - Tab A - Deployments list - select two deployment
  - Tab B - delete one of the deployments
  - Tab A - deleted deployment's row should be removed, the selected count should drop by one
- Deployments List - Row is added
  - Tab A - Select a deployment with name starting with something other than A. There are other deployments below that row
  - Tab B - create a deployment with name starting with A
  - Tab A - The originally selected row remains selected (but not highlighted)

### Areas which could experience regressions
- This is an impactful change given it affects all paginated calls (tables, drop downs with pagination, anything else that uses the advanced filtering like label selector requests, etc)
- Table
  - Covered in core test cases
- Drop Down
  - Installing `Logging` app
  - Create some opaque secrets in a namespace (values do not matter)
  - Logging --> Output --> Create
  - Select namespace with secrets in 
  - `Output` tab `Access` dropdowns should show secrets
- Label Selector example
  - similar set of tests as the deployments list, however the pods list in the deployment detail page

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes
- [x] The PR has been reviewed in terms of Accessibility
- [x] The PR has considered, and if applicable tested with, the three Global Roles `Admin`, `Standard User` and `User Base`

### CODE REVIEW

File: shell/plugins/dashboard-store/mutations.js [hunk 1]
```diff
@@ -515,8 +515,29 @@ export default {
...
+
+    // Create a map of the current references in cache.list
+    const currentPageMap = new Map(cache.list.map((i) => [i[keyField], i]));
+
+    // Create an array containing the new page, but using the same object for resources that exist in old and new page
+    const newPage = proxies.map((p) => {
+      const existing = currentPageMap.get(p[keyField]);
+
+      if (existing) {
+        replaceResource(existing, p, ctx.getters);
```
Comment (codyrancher) [inline shell/plugins/dashboard-store/mutations.js:531]: I don't think there's a functionality concern but do you care that it looks like we will call replaceResource twice on each resource since we also do it below in the map section?

I know they're different containers but both containers should be holding a reference to the same underlying object.

Comment (richard-cox) [reply shell/plugins/dashboard-store/mutations.js:531]: Good point!

When a resource is new the same `proxy` object reference is added to both list and map. So in theory we only need to call replaceResource once. Would need a bit of investigating to confirm, and the performance reward is slim (given we're only working on pages of limited size). Are there objections to doing this in a later release / PR?

Comment (codyrancher) [reply shell/plugins/dashboard-store/mutations.js:531]: Fine with me

Comment (richard-cox) [reply shell/plugins/dashboard-store/mutations.js:531]: Grand, created https://github.com/rancher/dashboard/issues/16325
