### PR TITLE
Fix textual descriptions for cluster appearance in multiple places

### LINKED ISSUE #12807: a11y: Fix textual descriptions for cluster appearance in multiple places
a11y Issues: 138, 139, 144

**Issue 138 - Textual description missing for interactive image**

The textual description is not specified for the interactive images that resulted in screen reader users finding it difficulty to understand the purpose of the interactive images.

Occurrences:

Cluster Appearance
- "Information" icon associated with "Use custom badge" checkbox

DaemonSet: Create
- "Information" icon associated with Pull Secrets input field) 

Repository: Create 
- "Information" icon associated with "Key" label)

Users Retention Settings
- "Information" icon associated with "Inactivity period" and "User retention process schedule input field" input fields
- "Warning" icon present in input field)

Import Extension Catalog
- "Information" icon associated with "Image Pull Secrets" text

Banners
- "Information" icon associated with "Show Login Consent as a modal dialog" checkbox

Example:

image

Remediation:

Provide hidden textual description as "Information - Use custom badge" within <i> element. Position the text off-screen via CSS.

Alternatively, Apply the following changes:
• Provide role="img" for <i> element containing mentioned informative image.
• Provide textual description such as "Information" using "aria-label" attribute.

**Issue 139 - No textual description provided for SVG element**

The SVG image lacks textual description that resulted in screen reader users unable to access the information conveyed through the image.

Occurs: Main Content, Images in SIDE NAVIGATION and RANCHER HEADER sections

image

Add textual description of the image by using the <title> element within <svg> element. Ensure that the textual description is descriptive of image's purpose.

**Issue 144 - Additional content available on hover not hoverable and persistent**

Additional content that becomes available when users hover over with a mouse on the image does not stay persistent. 
Moreover, when low vision users try to move their mouse on the additional content in order to read it, the content disappears resulting in users with low vision found it difficult to access the additional content.

Occurrences:

Cluster Appearance
- Overwrites the default cluster name abbreviation. (which gets available when users hover on "Information" icon associated with "Use custom badge" checkbox)

Repository: Create 
- Paste lines of Key=Value or... (which gets available on activating "Add Label and "Add Annotation" buttons > hover on "Information" icon associated with "Key" label)

Users Retention Settings
- User duration units... and The user retention process... (which gets available on activating checkboxes such as "Disable user accounts after..." and "Delete user accounts after..." checkboxes > hover on "Information" icon associated with "Inactivity period" and "User retention process schedule input field" input fields)
- User retention process... (which gets available on activating checkboxes such as "Disable user accounts after..." and "Delete user accounts after..." checkboxes > type in "User retention process schedule" input field > hover on "Warning" icon present in input field)

Cluster Dashboard
- 10/29/2024 21:33:16 (which gets available on hovering Created: 12 days ago text)
- Customize Appearance (which gets available on hovering Cluster Tools interactive image)

Import YAML
- "end of the stream or a document…" (which gets available on hovering "Error" icon)
      
Import Extension Catalog
- Must be of Type 'kubernetes.io/dockercfg' or 'kubernetes.io/dockerconfigjson' (which gets available when users hover on "Information" icon associated with "Image Pull Secrets" label)

Banners
- Show a modal dialog on the login screen that must be accepted by a user before they can login (which gets available when users hover on "Information" icon associated with "Show Login Consent as a modal dialog" checkbox)

Home Links
- Paste lines of key=value or key:value into any key field for easy bulk entry (which gets available when users hover on "Information" icon associated with "Display Text" checkbox)

DaemonSet: Create
- Must be of Type `kubernetes.io/dockercfg` or `kubernetes.io/dockerconfigjson` (which gets available when users hover on "Information" icon associated with "Pull Secrets " label)

Example:

image

Remediation:

Modify the scripts associated with the additional content to ensure that it remains visible until user decides to dismiss the additional content.

### PR DESCRIPTION
**Pull request by aalves08**
### Summary
Fixes #12807 

### Occurred changes and/or fixed issues

- created `v-stripped-aria-label` directive so that we can re-use tooltip texts as aria-label's while stripping out HTML tags 
- add missing textual descriptions for cluster appearance in multiple places
- enable key tooltip containers to reveal their tooltips with keyboard navigation

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: shell/directives/strip-aria-label.js [hunk 1]
```diff
@@ -0,0 +1,16 @@
+export default {
```
Comment (richard-cox) [inline shell/directives/strip-aria-label.js:1]: shouldn't this be called `clean-aria-labels` and use the same process at clean-tooltips?

Comment (aalves08) [reply shell/directives/strip-aria-label.js:1]: we could call it `clean-aria-labels` but it's different from `clean-tooltips` for sure since tooltips may accept HTML, which is sanitized first, whereas the aria-labels one is for stripping the HTML tags (we don't want HTML on aria-labels), hence the name

File: shell/assets/translations/en-us.yaml [hunk 2]
```diff
@@ -2627,6 +2630,7 @@ glance:
   secretsTable: Full secrets list
 
 clusterBadge:
+  badgeAppearance: Cluster bagde Appearance
```
Comment (richard-cox) [inline shell/assets/translations/en-us.yaml:2633]:
```suggestion
  badgeAppearance: Cluster Badge Appearance
```

File: shell/components/ClusterBadge.vue [hunk 3]
```diff
@@ -23,6 +23,7 @@ export default {
     :style="{ backgroundColor: cluster.badge.color, color: cluster.badge.textColor }"
     class="cluster-badge"
     :class="{'cluster-badge-border': showBorders}"
+    :aria-label="t('clusterBadge.badgeAppearance')"
```
Comment (richard-cox) [inline shell/components/ClusterBadge.vue:26]: `Cluster Badge Appearance` doesn't quite describe what this is. It should probably be something like `Cluster comment: <actual text>`

File: shell/components/ClusterIconMenu.vue [hunk 4]
```diff
@@ -76,6 +76,7 @@ export default {
         style="enable-background:new 0 0 100 100;"
         xml:space="preserve"
       >
+        <title>{{ t('nav.ariaLabel.clusterIcon') }}</title>
```
Comment (richard-cox) [inline shell/components/ClusterIconMenu.vue:79]: Feels like this one should contain something about it being the icon for the local cluster

File: shell/components/ClusterIconMenu.vue [hunk 5]
```diff
@@ -106,10 +107,12 @@ export default {
     <i
       v-if="!routeCombo && cluster.pinned"
       class="icon icon-pin cluster-pin-icon"
+      :alt="t('nav.ariaLabel.pinCluster')"
```
Comment (richard-cox) [inline shell/components/ClusterIconMenu.vue:110]: this one should have some reference to the cluster name

File: shell/components/ClusterProviderIcon.vue [hunk 6]
```diff
@@ -37,7 +37,19 @@ export default {
...
+      version="1.1" 
+      id="Layer_1" 
+      xmlns="http://www.w3.org/2000/svg" 
+      xmlns:xlink="http://www.w3.org/1999/xlink" 
+      x="0px" 
+      y="0px" 
+      viewBox="0 0 100 100" 
+      style="enable-background:new 0 0 100 100;" 
+      xml:space="preserve">
+      <title>{{ t('nav.ariaLabel.clusterProvIcon') }}</title>
```
Comment (richard-cox) [inline shell/components/ClusterProviderIcon.vue:52]: Needs some cluster context

File: shell/components/ClusterProviderIcon.vue [hunk 7]
```diff
@@ -60,6 +72,7 @@ export default {
       v-else-if="cluster.providerNavLogo"
       class="cluster-os-logo"
       :src="cluster.providerNavLogo"
+      :alt="t('nav.ariaLabel.clusterProvIcon')"
```
Comment (richard-cox) [inline shell/components/ClusterProviderIcon.vue:75]: Needs some cluster context

File: shell/components/ClusterBadge.vue (hunk 3 above)
Comment (richard-cox) [reply shell/components/ClusterBadge.vue:26]: actually, this one contains text. will screen readers use the aria-label as a prefix for the text within the element?

File: shell/edit/workload/index.vue [hunk 8]
```diff
@@ -259,11 +259,14 @@ export default {
               </div>
               <div class="spacer" />
               <div>
+                zzz
```
Comment (richard-cox) [inline shell/edit/workload/index.vue:262]: debug

File: shell/directives/strip-aria-label.js (hunk 1 above)
Comment (richard-cox) [reply shell/directives/strip-aria-label.js:1]: ah, got it now.

that should be covered in a comment or update the name to be something like `strip-html-aria-label`

**Review by richard-cox — CHANGES_REQUESTED** [review]

File: shell/components/ClusterBadge.vue (hunk 3 above)
Comment (aalves08) [reply shell/components/ClusterBadge.vue:26]: Probably (tbh, idk how screen readers will behave on this matter), but I definitely bet on having a complete `aria-label` completely address a11y.

I'm going with your `Cluster comment: <actual text>` approach. I had confused this component with the button one in cluster explorer main page. Thanks

File: shell/components/ClusterIconMenu.vue (hunk 4 above)
Comment (aalves08) [reply shell/components/ClusterIconMenu.vue:79]: True! I thought that we could have more icons on clusters, but I've just double-checked we can't. updated the string and key

File: shell/components/ClusterIconMenu.vue (hunk 5 above)
Comment (aalves08) [reply shell/components/ClusterIconMenu.vue:110]: fixed

File: shell/directives/strip-aria-label.js (hunk 1 above)
Comment (aalves08) [reply shell/directives/strip-aria-label.js:1]: Updated the name of the file and added comment to file directive

File: shell/components/ClusterIconMenu.vue [hunk 9]
```diff
@@ -106,10 +107,12 @@ export default {
     <i
       v-if="!routeCombo && cluster.pinned"
       class="icon icon-pin cluster-pin-icon"
+      :alt="t('nav.ariaLabel.pinCluster', { cluster: 'Local' })"
```
Comment (richard-cox) [inline shell/components/ClusterIconMenu.vue:110]: this is in a different if block to above, and could show either local or other clusters, so should have the actual cluster name

**Review by richard-cox — CHANGES_REQUESTED** [review]
One comment, otherwise looking good. Might be worth @rak-phillip giving it a quick eyeball as well

File: shell/components/ClusterIconMenu.vue (hunk 9 above)
Comment (aalves08) [reply shell/components/ClusterIconMenu.vue]: You are right... I confused the usage with other "cluster" components. This one may be used by a cluster different than local. Fixed

**Review by richard-cox — APPROVED** [review]
Looks good, but final approval should come from @rak-phillip

**Review by rak-phillip — APPROVED** [review]
LGTM
