### PR TITLE
Fix deprecated charts not being returned from store

### LINKED ISSUE #15144: Deprecated charts do not show correct data, or can be installed
**Setup**
- Rancher version: v2.13.0 (dev of), probably before as well

**Describe the bug**
- Step 1 of the wizard to install a deprecated chart is always disabled
- Additionally, maybe connected, no versions are shown on the chart detail page
  - is this because we hide the section if there's no versions, or other metadata?
  - is it a bug?

**To Reproduce**
- Nav to apps --> charts
- filter by deprecated
- click on istio
- click on install

**Result**
- The next button is always disabled
- There's no chart details in the header
- clicking cancel gives error, as there's no this.chart

**Expected Result**
- able to install, see chart details in header, cancel works

**Additional context**
- my guess is we're filtering out the deprecated charts and the wizard isn't correctly reporting it. 
- we must be doing something slightly similar on the detail page HOWEVER that does show most of the chart data

### PR DESCRIPTION
**Pull request by momesgin**
### Summary
Fixes #15144 

### Occurred changes and/or fixed issues

`showDeprecated` flag was added to the store getter `calatog/chart` when the checkbox "Show deprecated apps" was added to the UI in 2.9 in order to show/hide deprecated charts. The url query parameter(`?deprecated` or `?deprecated=true`) was missing in a couple of places such as when we get the versions from the store or when we go to the install/upgrade page.

### Technical notes summary

- Added missing deprecated parameter to `'catalog/version'` and `install` method
- Unit tests

### Areas or cases that should be tested

Make sure you can install deprecated charts
### Areas which could experience regressions

Check Explorer => Cluster tools page, you should not see a deprecated chart by default like `Istio`, but by manually adding `deprecated=true` to the url you should be able to see it
### Screenshot/Video

https://github.com/user-attachments/assets/edb38efc-c680-4c3c-8fb3-9e1cedf8686c

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes
- [x] The PR has been reviewed in terms of Accessibility

### CODE REVIEW

File: shell/store/catalog.js [hunk 1]
```diff
@@ -114,7 +114,7 @@ export const getters = {
 
   chart(state, getters) {
     return ({
-      key, repoType, repoName, chartName, includeHidden, showDeprecated, multiple
```
Comment (richard-cox) [inline shell/store/catalog.js]: this is a bit dangerous given we're flipping the functionality for all usages of this getter. if we didn't care about extensions i'd say we should go for it, but maybe we avoid just in case we break anyone.

it's probably best to keep the showDeprecated arg and ensure when chart is called we correctly make use of it. 

i had a quick look at references to `catalog/chart` and it's a mixed bag

- shell/components/InstallHelmCharts.vue - showDeprecated: true
- shell/config/router/navigation-guards/install-redirect.js - showDeprecated: true
- shell/edit/provisioning.cattle.io.cluster/index.vue - showDeprecated: true
- shell/mixins/chart.js - showDeprecated: true
- shell/models/catalog.cattle.io.app.js - tricky, some places yes, some places no. maybe this aligns with showHidden?
- shell/utils/uiplugins.ts - showDeprecated: false

File: shell/store/__tests__/catalog.test.ts [hunk 2]
```diff
@@ -296,4 +296,35 @@ describe('catalog', () => {
       expect(result).toHaveLength(0);
     });
   });
+
+  describe('getters', () => {
+    describe('chart', () => {
+      it('should return the correct chart', () => {
```
Comment (richard-cox) [inline shell/store/__tests__/catalog.test.ts]: this test is nice to have, but it doesn't validate the issue (charts that are deprecated should be returned)

File: shell/store/catalog.js (hunk 1 above)
Comment (momesgin) [reply shell/store/catalog.js]: @richard-cox thanks! I mistakenly assumed that before adding `showDeprecated` to the getter `'catalog/chart'` there was no `deprecated` argument passed to it, but actually we were always sending `false`:

https://github.com/rancher/dashboard/commit/fb2c9e5dbc50bf5202ca1420d0b5b534ecfd918a#diff-31b0043fb6852fd3650396c7d7fbe3b5ae4ba1fe3a4293fadb00a712ac53684cL119

which makes me think if passing `true` can have a side-effect for this use case?
- shell/edit/provisioning.cattle.io.cluster/index.vue

The use case in `shell/models/catalog.cattle.io.app.js` needs more investigation. I think for the other true cases we should be fine though.

Update:
I found the root cause of the issue to be not using `showDeprecated` flag in `'catalog/version'` getter:
https://github.com/rancher/dashboard/blob/master/shell/mixins/chart.js#L347
and also not passing it as a query in `install` method:
https://github.com/rancher/dashboard/blob/master/shell/pages/c/_cluster/apps/charts/chart.vue#L150

I think the safest fix would be just passing the missing `showDeprecated` flags

File: shell/store/__tests__/catalog.test.ts (hunk 2 above)
Comment (richard-cox) [reply shell/store/__tests__/catalog.test.ts]: the replacement is also nice to have (it tests the change in the PR), however it still doesn't test the actual problem from the issue

the issue revolves around the UI requesting a chart that is deprecated and NOT getting it back from the catalog store. so the flow we need to test is
1. the catalog store has a chart that is deprecated
1. the ui calls `versions` with the deprecated flag
1. the ui receives the chart that is deprecated back

This then covers all sorts of possible regressions (for instance we pass in the correct deprecated flag however the function is changed to ignore it)

**Review by richard-cox — CHANGES_REQUESTED** [review]
see inline comment
