### PR TITLE
fix issue with dependency on @pkg/harvester on shell

### LINKED ISSUE #8008: harvester-manager missing in extension build
**Setup**
- Rancher version: 2.7.2-rc1
- Browser type & version:
safari
**Describe the bug**

I try to follow https://rancher.github.io/dashboard/plugins/introduction to build a simple extension.  Hit on some issues, I try to find walk around for some of them, as I described in https://github.com/rancher/dashboard/issues/7964 

However, this one I have no clue how to fix. my extension failed to build because of missing  @/pkg/harvester-manager/config/harvester-manager

**To Reproduce**

- Start a a container with node:17, mount dashboard repo into it as a volume
- Start a local verdaccio with hint from shell/scripts/test-plugin-build.sh
- Configure the container to use registry http://localhost:4873 
- Run `yarn build:lib'
- Run `yarn publish:lib'
- Run `yarn publish-shell'
- https://rancher.github.io/dashboard/plugins/introduction to create a test extension name helloworld
- when run `yarn dev`  it throws errors like below
**Result**
```
 ERROR  Failed to compile with 2 errors                                                                     friendly-errors 21:29:41

These dependencies were not found:                                                                          friendly-errors 21:29:41
                                                                                                            friendly-errors 21:29:41
* @/pkg/harvester-manager/config/harvester-manager in ./node_modules/cache-loader/dist/cjs.js??ref--6-0!./node_modules/thread-loader/dist/cjs.js??ref--6-1!./node_modules/babel-loader/lib??ref--6-2!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@rancher/shell/edit/provisioning.cattle.io.cluster/import.vue?vue&type=script&lang=js&
* vue-virtual-scroll-list in ./node_modules/cache-loader/dist/cjs.js??ref--6-0!./node_modules/thread-loader/dist/cjs.js??ref--6-1!./node_modules/babel-loader/lib??ref--6-2!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@rancher/shell/components/nav/WindowManager/ContainerLogs.vue?vue&type=script&lang=js&
                                                                                                            friendly-errors 21:29:41
To install them, you can run: npm install --save @/pkg/harvester-manager/config/harvester-manager vue-virtual-scroll-list
ℹ Waiting for file changes                                                                                                  21:29:41
ℹ Memory usage: 1.1 GB (RSS: 1.77 GB)                                                                                       21:29:41
ℹ Listening on: https://172.17.0.2:8005/  

```
**Expected Result**

The simple extension should build and run

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by aalves08**
Fixes #8008 

- fix issue with dependency on `@pkg/harvester` on shell
- fix console warning
- add` vue-virtual-scroll-list` as a dependency of shell

**Screenshots**
Screenshot 2023-02-09 at 13 58 39
Screenshot 2023-02-09 at 14 07 39

### CODE REVIEW

**Review by nwmac — COMMENTED** [review]
@aalves08 Can you look into why the plugin check gate (https://github.com/rancher/dashboard/blob/master/.github/workflows/check-plugins.yaml) didn't pick this up? The PR that brought this in should have failed that gate.

**Comment by richard-cox** [comment]
This is another work around just like https://github.com/rancher/dashboard/pull/7211#discussion_r1098821673.

Do we know why the import fails?

**Comment by nwmac** [comment]
So, aside from rancher-components, code in shell should NOT reference any code in pkg - since that code is not included when we publish shell - so in the use case where we use shell as a package, it will fail.

I think the fix here makes sense to me

File: pkg/harvester-manager/machine-config/harvester.vue [hunk 1]
```diff
@@ -729,7 +729,7 @@ export default {
         <transition-group>
           <div
             v-for="(disk, i) in disks"
-            :key="i"
+            :key="disk"
```
Comment (mantis-toboggan-md) [inline pkg/harvester-manager/machine-config/harvester.vue:732]: This causes a different console warning (avoid using non-primitive values for keys) because `disk` is an object. I think you can use `${disk.bootOrder}${i}`

**Review by mantis-toboggan-md — CHANGES_REQUESTED** [review]

File: pkg/harvester-manager/machine-config/harvester.vue (hunk 1 above)
Comment (aalves08) [reply pkg/harvester-manager/machine-config/harvester.vue]: Fixed

**Review by mantis-toboggan-md — DISMISSED** [review]

**Review by mantis-toboggan-md — APPROVED** [review]

**Review by nwmac — APPROVED** [review]
