### PR TITLE
fix keyboard nav on login screen

### LINKED ISSUE #12775: a11y: Fix keyboard navigation, role, aria-label and focus display issues on the login screen
a11y Issues: 49, 55, 43, 53

Fix keyboard navigation and focus issues on the logins screen:

image

image

The locale menu should use the new Menu component.

**Issue 43**

The role and state is not defined for mentioned drop-down resulting in screen reader users are not able to understand the interactive elements functionality.

image

**Issue 53**

A focus indicator is not visually available as user tabs through mentioned checkbox using a keyboard resulting in users with learning and mobility impairments as well as those with low vision not being able to easily find out which element currently has the focus.

Login 
Main content
- Remember Username (unselected checkbox)

Homepage 
- Main Content 
- Logo image
- Cluster management" link
- Continuous Delivery
- Virtualization Management
- User and Authentication
and so on. 

Preferences
Main Content 
- Take me to the home page radio button
- Take me to the area I last visited radio button
- Take me to cluster: radio button 
- Enable "View in API"  checkbox 
and so on.

Account and API Keys
Main Content 
-  Checkboxes present inside the table
- Back button 

Create API Key
Main Content 
- 90  days - Maximum allowed radio button 
- Custom radio button 

Cluster Dashboard
Main Content 
- Cluster Tools 

Search
Main Content
- Admission
- MutatingWebhookConfigurations
- ValidatingAdmissionPolicies
- ValidatingAdmissionPolicyBindings
- ValidatingWebhookConfigurations 
and so on. 

Cluster Appearance
Main Content 
- Use custom badge, Show cluster comment, Badge background color checkboxes
- Transparent (available after selecting Badge background color) 

Projects/Namespaces
Main Content 
- Name, default, user-2rgrp and so on checkboxes

Create Namespace:
- Enforce
- Audit
- Warn

Charts
Main Content
- Show deprecated apps checkbox
- All, Rancher, Partners and RKE2 (that becomes available when user activate "All" dropdown list)

Charts: Kubecost (2.4.1)
Main content
- Show more / Show less

Cluster Management - Create
- RKE1 RKE2/3s switch

Cluster Drivers
- Alibaba ACK
- Amazon EKS
- Azure AKS
- Baidu CCE and so on

Pod Security Admission: Create
-Usernames, RuntimeClasses and Namespaces checkboxes 

Repository: Create
Main Content 
- http(s) URL to an index generated by Helm, Git repository containing Helm chart or cluster template definitions and OCI Repository radio buttons
- Remove buttons (which gets available after activating  Add Label and  Add Annotation button) 
- Skip TLS Verifications and Insecure Plain Http  (which gets available after activating OCI Repository Experimental radio buttons)

Git Repo - Add Repository
Main Content 
- Enable Self-Healing and Always Keep Resources checkboxes.
- Remove buttons (which gets available after activating  Add Path button) 

Users Retention Settings
Main Content 
- Disable user accounts after an inactivity period (duration since last login) and Delete user accounts after an inactivity period (duration since last login) checkboxes.
- Toggle button associated with Run the user retention process in DRY mode (no changes will be applied).

User: Create
Main Content 
- User, Show/hide and Release Notes links
- Ask user to change their password on next login, Generate a random password, Administrator, Restricted Administrator, Standard User and so on checkboxes. 

Add Extensions repositories
Main Content 
- Add Partners Extensions Repository checkbox. 

Global Settings
Main Content 
- Show Banner in Header, Show Banner in Footer, Show Consent Banner on Login Screen, Show Login Consent as a modal dialog, Show custom login error, Bold, Italic and Underline checkboxes 
- Left, Center and Right radio buttons. 
- Text Color and Background Color container                 
      
Branding
Main Content 
- Use a Custom Logo, Use a Custom Banner, Use a Custom Background, Use a Custom Favicon, Use a Custom Color and Use a Custom Link Color checkboxes.

Home Links
Main Content 
- Remove Button (available after activating Add Link button)
-  Show checkboxes 

About 
Main Content 
- Home Link 

image

^^ NOTE: The list goes beyond the login page - all need to be taking into account

### PR DESCRIPTION
**Pull request by aalves08**
### Summary
Fixes #12775

### Occurred changes and/or fixed issues

- Fix keyboard navigation on `login` screen
- checkbox is now visibly focusable
- add `role="button"` to `AsyncButton`
- `Password` component is now tabbable
- refactor `LocaleSelector` component to work with keyboard navigation (`login` mode only)

### Areas or cases that should be tested

- Go to the login screen and browse the page with the tab key
- use `enter` or `space` key to trigger UI elements on the page

### Screenshot/Video

https://github.com/user-attachments/assets/86a838b0-ba86-404c-b330-c725b95a793e

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

**Review by rak-phillip — COMMENTED** [review]
Keyboard navigation is definitely improved, but I'm noting a lot of missing behavior that would satisfy keyboard interactions for the menubar pattern[^1]. Some notable elements that don't align with the APG:

- When a menu opens, or when a menubar receives focus, keyboard focus is placed on the first item
- Tab and Shift + Tab do not move focus among the items in the menu
- Arrow Navigation and Escape behavior are missing

We can discuss more on how we would like to approach these instances, but I suspect that we will replace one-off implementations like these with a standardized component once we address #12771. 

[^1]: https://www.w3.org/WAI/ARIA/apg/patterns/menubar/

File: shell/components/LocaleSelector.vue [hunk 1]
```diff
@@ -50,13 +65,28 @@ export default {
...
           skidding="12"
-          :triggers="['click']"
+          :triggers="[]"
+          :autoHide="false"
+          :flip="false"
+          :container="false"
+          @focus.capture="openLocaleSelector"
         >
           <a
             data-testid="locale-selector"
```
[the remark this answers is not in the document]
Comment (aalves08) [reply shell/components/LocaleSelector.vue:92]: The outermost `div` inside the `mode="login"` `div` has the role `menu` and all it's menu items inside have the role `menuitem`.

File: pkg/rancher-components/src/components/Form/Checkbox/Checkbox.vue [hunk 2]
```diff
@@ -227,14 +235,14 @@ export default defineComponent({
...
         @click.stop.prevent
       >
       <span
         class="checkbox-custom"
         :class="{indeterminate: indeterminate}"
-        :tabindex="isDisabled ? -1 : 0"
+        :tabindex="-1"
         :aria-label="label"
         :aria-checked="!!value"
         role="checkbox"
```
[the remark this answers is not in the document]
Comment (nwmac) [reply pkg/rancher-components/src/components/Form/Checkbox/Checkbox.vue:248]: The animation is dreadful and should be removed

File: pkg/rancher-components/src/components/Form/Checkbox/Checkbox.vue [hunk 3]
```diff
@@ -114,6 +114,14 @@ export default defineComponent({
       type:    Boolean,
       default: false
     },
+
+    /**
+     * Tab index for proper keyboard nav control
+     */
+    tabbingIndex: {
```
[the remark this answers is not in the document]
Comment (nwmac) [reply pkg/rancher-components/src/components/Form/Checkbox/Checkbox.vue:121]: .. and we aren't setting this anyway in our use of `Checkbox` on the login page, which it feels like we should, so that it is explicit.

**Comment by aalves08** [comment]
@nwmac going to resolve all of the PR comments that you had around `tabbingIndex` and `tabindex`. They will all be cleaned on the next PR commit.

File: pkg/rancher-components/src/components/Form/Checkbox/Checkbox.vue [hunk 4]
```diff
@@ -227,14 +235,14 @@ export default defineComponent({
...
-        :tabindex="-1"
+        :tab-index="tabbingIndex"
         :name="id"
         @click.stop.prevent
       >
       <span
         class="checkbox-custom"
         :class="{indeterminate: indeterminate}"
-        :tabindex="isDisabled ? -1 : 0"
+        :tabindex="-1"
```
[the remark this answers is not in the document]
Comment (aalves08) [reply pkg/rancher-components/src/components/Form/Checkbox/Checkbox.vue:245]: Fixed the the next commit

File: shell/components/LocaleSelector.vue (hunk 1 above)
[the remark this answers is not in the document]
Comment (rak-phillip) [reply shell/components/LocaleSelector.vue:92]: We had an OOB discussion and decided that a lot of these patterns should be fixed with #12771. It's not worth the effort to duplicate these efforts at this time.

**Review by rak-phillip — COMMENTED** [review]
This is looking good. We want to clean up the unused props and I think this will be good to merge.

**Comment by aalves08** [comment]
@rak-phillip removed the `tabbingIndex `. Good spot. Thanks

File: shell/components/LocaleSelector.vue [hunk 5]
```diff
@@ -12,6 +12,14 @@ export default {
       type:    String,
       default: ''
     },
+    tabbingIndex: {
+      type:    Number,
+      default: null,
+    },
```
Comment (rak-phillip) [inline shell/components/LocaleSelector.vue:18]: One more unused instance of `tabbingIndex` that can be removed.

Comment (aalves08) [reply shell/components/LocaleSelector.vue]: Don't know how I missed that. It's the last one lingering, I've made sure of that 😛 Fixed. Thanks

**Comment by aalves08** [comment]
@rak-phillip fixed and ready for final review 🤞

File: shell/components/AsyncButton.vue [hunk 6]
```diff
@@ -275,6 +275,7 @@ export default defineComponent({
 <template>
   <button
     ref="btn"
+    role="button"
```
Comment (nwmac) [inline shell/components/AsyncButton.vue:278]: This seems unrelated to this PR.

File: shell/components/form/Password.vue [hunk 7]
```diff
@@ -127,17 +133,14 @@ export default {
...
             href="#"
-            @click.prevent.stop="reveal = false"
-          >{{ t('action.hide') }}</a>
-          <a
-            v-else
-            tabindex="-1"
-            href="#"
-            @click.prevent.stop="reveal=true"
-          >{{ t('action.show') }}</a>
+            tabindex="0"
```
Comment (nwmac) [inline shell/components/form/Password.vue:137]: I think this should have `role=button` as this is a link being used as a button.

File: shell/components/LocaleSelector.vue [hunk 8]
```diff
@@ -50,13 +61,28 @@ export default {
...
+        role="menu"
+        :aria-label="t('locale.menu')"
+        class="locale-login-container"
+        tabindex="0"
+        @click="openLocaleSelector"
+        @blur.capture="closeLocaleSelector"
+        @keyup.enter="openLocaleSelector"
+        @keyup.space="openLocaleSelector"
+      >
         <v-dropdown
```
Comment (nwmac) [inline shell/components/LocaleSelector.vue:75]: I guess the keyboard behaviour for the menu will be fixed when we wire in a standard menu component, as Phil notes. Tab should not move focus between menu items - the up/down arrow keys should do that - but we can tackle that =in the standard menu component. We will need to make sure we wire it in here.

**Review by nwmac — CHANGES_REQUESTED** [review]

File: shell/components/LocaleSelector.vue (hunk 8 above)
Comment (aalves08) [reply shell/components/LocaleSelector.vue:75]: Me and @rak-phillip agreed that he would work on his new menu component and will replace all instances on the code afterwards.

The menu is now browsable with the `tab` key despite not being optimal. It's a definite improvement but not the final solution.

**Review by nwmac — APPROVED** [review]

**Review by rak-phillip — APPROVED** [review]
