### PR TITLE
Side nav visual bugs

### LINKED ISSUE #9659: New Side Nav Visual Bugs
**Setup**
- Rancher version: pre-2.8.0

**Describe the bug**
Following on from https://github.com/rancher/dashboard/pull/9582

- General
  - Menu items outside of groups should be left aligned with group names
    - these previously had icons which meant they kind of aligned with the group names. now there's no icons they're not aligned
    - image
  - Best seen in Cluster Management.
    - Items at top with no group should not have a bottom margin (margin wise they should be treated the same as closed groups) 
      - image
      - note the gap betweens drivers and rke1 config, which is not between rke1 config and advanced
    - Group labels are not vertically centrally aligned. This is best seen on the Node Templates page and the `RKE1 Configuration` group is closed
      - image
  - Best seen in Cluster Explorer.
    -  The backgound for open groups should not include the bottom margin
      - image
      - note the light grey area under the hovered over `Events` entry
  - All menu items are background highlighted for 
    - Users & Authentication
    - Global Settings
    - Global Configuration (requires FF `legacy` enabled)
    - Cluster Management top level groups
    - Continues Delivery - dashboard, git repos, clusters and cluster groups
    - image
- Cluster Explorer
  - Custom nav links aren't the same size as other links
      - image
      - Note - these are shown by creating `ui.cattle.io.navlink` resources in the cluster. note that when adding a `group name` the menu item is different to those with out it
  
Question
- What's the plan to connect the namespace icon to the namespace filter?

Discussion
- The highlight colours (current group & current menu item) are quite bold in dark mode. We might need to consider toning them down
  - image
- We might also need to tone down the colour of current menu item in light mode
  - image

### PR DESCRIPTION
**Pull request by bisht-richa**
### Summary
Fixes #9659

Fixed New Side Nav Visual Bugs

### Screenshot/Video

Screenshot 2023-09-11 at 10 01 15

============
Screenshot 2023-09-11 at 10 01 30

============
Screenshot 2023-09-11 at 10 01 36

============
Screenshot 2023-09-11 at 10 05 26

### CODE REVIEW

File: shell/components/nav/Group.vue [hunk 1]
```diff
@@ -425,9 +419,13 @@ export default {
...
+
+    &.root {
+      background: transparent;
+      A {
+        padding-left: 14px;
+      }
+    }
   }
 
-  // .bg-yellow {
```
Comment (richard-cox) [inline shell/components/nav/Group.vue:430]: This PR CI is passing and I'd really like to get it in, so will approve. The next PR you make though, can you sneak in the removal of this comment?

**Review by richard-cox — APPROVED** [review]

File: shell/components/nav/Group.vue (hunk 1 above)
Comment (bisht-richa) [reply shell/components/nav/Group.vue:430]: I will do that
