### PR TITLE
Ensure fetch is not called when navigating backwards

### LINKED ISSUE #11931: Exception thrown when leaving Chart detail page
**Setup**
- Rancher version: dev of 2.10.0

**Describe the bug**
- When leaving the detail page for a Chart an exception is thrown
- Looks like some of the chart details are removed which trigger a chart look up using undefined input which throws an exception
- Feels like this shouldn't be triggered given the change of page

**To Reproduce**
- Navigate to Cluster Explorer --> Apps --> Charts --> click on any chart --> Charts

**Result**
image

**Expected Result**
The deliverable for this is in two parts
- understand why this happens, what changed with vue3 and does it impact anything else?
- given above ensure no exception is thrown

### PR DESCRIPTION
**Pull request by jordojordo**
### Summary
Fixes #11931

The issue was caused due to a watch on the `$route.query` object, when that changed we would call `$fetch` a second time before leaving the page.

### Occurred changes and/or fixed issues

Added a condition to check for an empty query object before calling `$fetch`

### Technical notes summary

When navigating backwards (from `apps/charts/chart` to `apps/charts`) the query object is empty, the watch is still used when the route contains the query, e.g. when selecting a different version from the Readme view.

### Areas or cases that should be tested

- Navigate to `apps/charts`
- Select a chart
- Ensure the version select still works
- Navigate back to the charts page
- Ensure no errors are logged in the console

### Screenshot/Video

https://github.com/user-attachments/assets/abac7e37-fdb2-4765-a79b-faa113fc3be4

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: shell/pages/c/_cluster/apps/charts/chart.vue [hunk 1]
```diff
@@ -115,7 +115,9 @@ export default {
 
   watch: {
     '$route.query'(neu, old) {
-      if ( !isEqual(neu, old) ) {
+      // If the query changes, refetch the chart
+      // When going back to app list, the query is empty and we don't want to refetch
+      if ( !isEqual(neu, old) && Object.keys(neu).length > 0 ) {
```
Comment (momesgin) [inline shell/pages/c/_cluster/apps/charts/chart.vue:120]: I was wondering if we should update the same logic in `shell/pages/c/_cluster/apps/charts/install.vue` as well?

**Review by momesgin — APPROVED** [review]
