### PR TITLE
Keywords on chart detail page

### LINKED ISSUE #15073: [Apps & Marketplace] - Keywords on the right panel has broken commas on the chart detail page
**Setup**
- Rancher version:
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**

**To Reproduce**

Go to Explore => Apps => Search for CloudCasa => Click on the Card => Check "Keywords" section on the right panel

**Result**

Image

**Expected Result**

Image

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by momesgin**
### Summary
Fixes #15073 

### Occurred changes and/or fixed issues

- Fixed broken commas
- Fixed the bottom spacing
- Fixed dashed border color in dark mode

### Screenshot/Video

image

The dashed border now has the right color in dark mode:

image

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes
- [x] The PR has been reviewed in terms of Accessibility

### CODE REVIEW

File: shell/pages/c/_cluster/apps/charts/chart.vue [hunk 1]
```diff
@@ -677,10 +681,17 @@ export default {
...
-              margin-right: 8px;
+            .keyword-item {
+              display: inline-block;
+              white-space: nowrap;
+            }
+
+            span {
+              margin-right: 4px;
+              margin-left: -2px;
             }
```
Comment (codyrancher) [inline shell/pages/c/_cluster/apps/charts/chart.vue]: I think we want to move this styling into the .keyword-item selector. With it being here it gets applied to the both the keyword-item and the span that contains the comma.

File: shell/pages/c/_cluster/apps/charts/chart.vue [hunk 2]
```diff
@@ -677,10 +681,17 @@ export default {
...
-            a {
-              margin-right: 8px;
+            .keyword-item {
+              display: inline-block;
+              white-space: nowrap;
+            }
+
+            span {
+              margin-right: 4px;
+              margin-left: -2px;
```
Comment (codyrancher) [inline shell/pages/c/_cluster/apps/charts/chart.vue]: This appears to be shifting the keywords so they're not aligned with the title 

image

I think we'd want to get rid of this and adjust the margin-right. My suspicion is that this was needed to compensate for the margin-right getting applied to both spans.

File: shell/pages/c/_cluster/apps/charts/chart.vue [hunk 3]
```diff
@@ -492,16 +492,20 @@ export default {
...
             >
-              {{ keyword }}
+              <router-link
+                v-clean-tooltip="t('catalog.chart.info.keywordsTooltip')"
+                :to="{ name: 'c-cluster-apps-charts', query: { [SEARCH_QUERY]: keyword } }"
+                data-testid="chart-keyword-link"
+              >
+                {{ keyword }}
+              </router-link>
               <span v-if="version.keywords.length > 1 && i !== version.keywords.length - 1">,</span>
```
Comment (codyrancher) [inline shell/pages/c/_cluster/apps/charts/chart.vue:507]: I don't know if you'd want to do this but I figured I'd just mention it in case it would be helpful.

If you didn't want the comma to be wrapped in a span you could replace the `span` with `template`. It just came to mind when I noticed the span styling was getting applied to two elements even though I thought the intention was to only apply it to one.

i.e.:
`<template v-if="version.keywords.length > 1 && i !== version.keywords.length - 1">,</template>`

File: shell/pages/c/_cluster/apps/charts/chart.vue (hunk 2 above)
Comment (momesgin) [reply shell/pages/c/_cluster/apps/charts/chart.vue]: nice catch!

File: shell/pages/c/_cluster/apps/charts/chart.vue (hunk 3 above)
Comment (momesgin) [reply shell/pages/c/_cluster/apps/charts/chart.vue:507]: The intention was to style the comma, and I needed the span to target the comma, but I didn't notice that I was applying it to another span tag as well.

File: shell/pages/c/_cluster/apps/charts/chart.vue [hunk 4]
```diff
@@ -675,12 +679,18 @@ export default {
         }
 
         &--keywords{
-          word-break: break-word;
```
Comment (momesgin) [inline shell/pages/c/_cluster/apps/charts/chart.vue:678]: I realized that I don't need this anymore after I added `white-space: nowrap;` to `.keyword-item`
