### PR TITLE
Error handling for contentLibrary, tag and network fields

### LINKED ISSUE #10460: [BUG] hostsystem error  for cluster provisioned with vsphere provider
**Rancher Server Setup**
- Rancher version: 2.8.2
- Installation option (Docker install/Helm Chart): Helm 
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2 3-node cluster v1.26.11+rke2r1 
- Proxy/Cert Details: Ingress with private CA

**Information about the Cluster**
- Kubernetes version: RKE2 v1.26.11+rke2r1 
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Rancher provisioned cluster with vsphere provider (provisioned with Rancher v2.7)

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
  - If custom, define the set of permissions:

**Describe the bug**

After upgrading to v2.8.2, when I edit my clusters provisioned with Rancher and the vSphere provider, I see the following error for every pool Machine Pool I have in the cluster.

```
pool1: The provided value for hostsystem was not found in the list of expected values. This can happen with clusters provisioned outside of Rancher or when options for the provider have changed. 
```

The host field is empty. Because according to the documentation: *Specific host to create VM on (leave blank for standalone ESXi or for cluster with DRS)*. So, I think is a false error.

**To Reproduce**
Edit one cluster that was previously provisioned with the vsphere provisioner of Rancher and the host field was left blank.

**Result**

**Expected Result**
No error

**Screenshots**
imagen
imagen

**Additional context**

### PR DESCRIPTION
**Pull request by momesgin**
### Summary
Fixes #10460 

### Technical notes summary

`contentLibrary` was added to the list of the fields that should be exempt from displaying errors when their value is `null` or `""`. Also found `network` and `tag` to be special cases where they're falsy

### Areas or cases that should be tested

Provisioning vSphere Clusters

### Areas which could experience regressions

Provisioning vSphere Clusters

### Screenshot/Video

Screenshot 2024-03-11 at 4 46 37 PM
Screenshot 2024-03-11 at 4 48 07 PM

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: shell/machine-config/vmwarevsphere.vue [hunk 1]
```diff
@@ -655,9 +656,12 @@ export default {
...
         const value = isArray ? [] : content[0]?.value;
-        // null and "" are valid values for hostsystem and folder
-        const isNullOrEmpty = ['folder', 'hostsystem'].includes(key) && (this.value[key] === null || this.value[key] === '');
-        const shouldHandleError = [_EDIT, _VIEW].includes(this.mode) && !isNullOrEmpty && !this.poolCreateMode;
+        const isNullOrEmpty = NULLABLE_EMPTY_FIELDS.includes(key) && (this.value[key] === null || this.value[key] === '');
+        const shouldHandleError =
+          [_EDIT, _VIEW].includes(this.mode) && // error messages should only be displayed in Edit or View mode
+          !this.poolCreateMode && // almost identical to Create mode
+          !isNullOrEmpty && // null and empty string are valid values for some fields e.g. contentLibrary, folder and hostsystem
+          !isArray; // this flag is used for network and tag fields, and should not diplay error for them
```
Comment (rak-phillip) [inline shell/machine-config/vmwarevsphere.vue:664]: Typo in the comment 🙂

```suggestion
          !isArray; // this flag is used for network and tag fields, and should not display error for them
```

**Review by rak-phillip — COMMENTED** [review]
Looks good, just noticed a a typo in the comment for `!isArray`

**Review by rak-phillip — APPROVED** [review]
