### PR TITLE
Server-side Pagination: Fix project/namespace filter bug

### LINKED ISSUE #14347: Server-side Pagination: Changing project/namespace filter has no affect
**Setup**
- Rancher version: v2.12

**Describe the bug**
- with ssp enabled changing the ns filter does not kick off a request

**To Reproduce**
- Enable Vai + SSP
- Navigate to cluster --> Workloads --> Pods
- Flick between `Only System Namespaces` and `Only User Namespaces`

**Result**
- the rows in the pods list do not change

**Expected Result**
- the rows in the pods list reflects the filter (should be a number of system ones, some in user given system)

### PR DESCRIPTION
**Pull request by richard-cox**
### Summary
Fixes #14347

### Occurred changes and/or fixed issues
Filtering resources via project/namespace did not cause list to change
  - Changes mostly in the mixin
  - Streamline changes to namespaces and list pagination control  to share more code, and changes to one doesn't overwrite the other

### Areas or cases that should be tested
- Enable Vai --> enable SSP --> refresh --> go to list of any namespaced resource --> change the ns filter --> list should update given filter

### Areas which could experience regressions
- upstream/downstream filtering by project, namespace, users, system

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: shell/plugins/steve/steve-pagination-utils.ts [hunk 1]
```diff
@@ -304,16 +362,28 @@ class StevePaginationUtils extends NamespaceProjectFilters {
     let filters: PaginationParamFilter[] = [];
 
     if (!showDynamicRancherNamespaces || productHidesSystemNamespaces) {
-      // We need to hide dynamic namespaces ('c-', 'p-', etc) OR system namespaces
-      filters = this.handlePrefAndSettingFilter(allNamespaces, showDynamicRancherNamespaces, productHidesSystemNamespaces);
+      // We need to hide dynamic namespaces ('c-', 'user-', etc) OR system namespaces
```
Comment (richard-cox) [inline shell/plugins/steve/steve-pagination-utils.ts:365]: reserved namesaces. not dynamic, obscure

Comment (richard-cox) [reply shell/plugins/steve/steve-pagination-utils.ts:365]: also in description of setting. referenced in docs?

File: shell/plugins/steve/steve-pagination-utils.ts [hunk 2]
```diff
@@ -25,19 +25,63 @@ import { PaginationSettingsStore } from '@shell/types/resources/settings';
...
+      return false;
+    }
+
+    // Is this a upstream namespace for a downstream cluster?
+    if (ns.id.startsWith('local-p')) {
+      return true;
+    }
+
+    // Is this the upstream namespace for the `Default` project
+    if (getProject(`local/${ ns.id }`)?.metadata.labels[DEFAULT_PROJECT] === 'true') {
```
Comment (richard-cox) [inline shell/plugins/steve/steve-pagination-utils.ts:50]: this shouldn't be needed!

**Review by nwmac — APPROVED** [review]
