### PR TITLE
Preventing the re-render of cloud credentials when validation takes place

### LINKED ISSUE #13802: Cloud Creds: Secret input loses focus as footer button is enabled
**Setup**
- Rancher version: v2.11
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**
When creating/editing a cloud credential, the Secret/Access Token input field loses focus as the Create/Save button is enabled. Workaround is to refocus and continue typing secret. 
Order does matter - secret/access token needs to be filled last to reproduce this issue. 

**To Reproduce**
1. go to Cluster Management => Cloud Credentials => Create => Amazon
2. fill out form (secret last)
3. notice secret input loses focus as Create button is enabled

**Result**
Secret/Access Token input field loses focus as the Create/Save button is enabled.

**Expected Result**
Secret/Access Token input field does not lose focus as the Create/Save button is enabled.

**Screenshots**

https://github.com/user-attachments/assets/11b92bbb-0090-42f6-bc48-8c962c3d12e6

**Additional context**
Discovered while testing: https://github.com/rancher/dashboard/issues/13590

### PR DESCRIPTION
**Pull request by codyrancher**
### Summary
Fixes #13802

### Technical notes summary
This one is frustrating, it's absolutely not obvious what the root problem is. I found a fix through trial and error to narrow the change down.

For some reason if you visit the page after selecting the subtype if you then make the form valid it causes an event/state change to propagate all the to the root of the app and forces a re-render. 

The issue stopped once I removed the wrapping element but that broke other aspects because inherrited attributes were overwriting expected values for props. I then narrowed this down to `done-params` being present ultimately fixed the behavior.

Looking at all references to `done-params` doesn't explain the fix. And just adding other attributes in it's place doesn't either.

### Areas or cases that should be tested
Cloud credentials which have validation. Azure, AWS, and S3 Compatible all had this issue when I tested.

### Areas which could experience regressions
Cloud credentials in general, creating and editing.

### Screenshot/Video
https://github.com/user-attachments/assets/a2c6f178-97ac-42a7-809c-6dbf0fe35b0f

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: shell/edit/cloudcredential.vue [hunk 1]
```diff
@@ -272,47 +274,46 @@ export default {
 </script>
 
 <template>
-  <form class="filled-height">
```
Comment (codyrancher) [inline shell/edit/cloudcredential.vue:275]: Removing this to be consistent with all other uses of CruResource. I can put this back in if we'd like. It doesn't affect the footer which was the original purpose.

File: shell/edit/cloudcredential.vue [hunk 2]
```diff
@@ -272,47 +274,46 @@ export default {
...
-    <Loading v-if="$fetchState.pending" />
-    <CruResource
-      v-else
+  <Loading v-if="$fetchState.pending" />
+  <CruResource
+    v-else
+    :done-params="$attrs['done-params'] /* Without this, changes to the validationPassed prop end up propagating all the way to the root of the app and force a re-render when the input becomes valid. I haven't found a reasonable explanation for why this happens. */"
```
Comment (codyrancher) [inline shell/edit/cloudcredential.vue:280]: The actual fix

**Comment by codyrancher** [comment]
@rak-phillip I don't call this a proper fix but given the amount of time I've spent on this already and the given severity I thought it was appropriate to go with this change. If you're not comfortable with this fix let me know and maybe we can figure something else out.

File: shell/edit/cloudcredential.vue (hunk 2 above)
Comment (rak-phillip) [reply shell/edit/cloudcredential.vue:280]: Would it be appropriate to do `v-bind="$attrs"` instead? It's hard to tell, but it seems like all the fallthrough attributes are intended for this node.

If not, I think that it would be more clear if we created a `doneParams` prop for this component. This way, we could have a more explicit contract for this component instead of relying on implicit attributes.

File: shell/edit/cloudcredential.vue (hunk 1 above)
Comment (rak-phillip) [reply shell/edit/cloudcredential.vue:275]: I'm fine with keeping this out, the extra form tag appeared to be a little redundant in the dom tree.

**Review by rak-phillip — COMMENTED** [review]
Tested the fix and it behaves as expected. I only have a few comments about data binding for `cloudcredential.vue`

File: shell/edit/cloudcredential.vue (hunk 2 above)
Comment (rak-phillip) [reply shell/edit/cloudcredential.vue:280]: we had an out of band discussion and decided to keep the implementation as it is in this PR. There's too many conflicts and edge cases that complicate making a change.

**Review by rak-phillip — APPROVED** [review]
LGTM

**Comment by codyrancher** [comment]
Updated based on our conversation.

**Review by rak-phillip — APPROVED** [review]
