### PR TITLE
aks networking validation fixes and user-defined-routing fixes

### LINKED ISSUE #12985: AKS - fix networking validation
**Describe the bug**
Following on from https://github.com/rancher/aks-operator/issues/750 the AKS Networking section needs some validation fixes:

 Image

1. Box name where users are selecting LoadBalancer or User Defined Routing needs to be called Outbound Type, currently is DNS Prefix
2. When User Defined Routing is selected then Virtual Network has to be provided, it can't be empty
3. When User Defined Routing is selected then Network Plugin Azure CNI has to be selected

### PR DESCRIPTION
**Pull request by mantis-toboggan-md**
### Summary
Fixes #12985

### Occurred changes and/or fixed issues
This PR has some small fixes to the AKS networking section:
- fixed the label on the outboundType input
- fixed the LoadbalancerSKU validator always returning an error when User Defined Routing is selected
- marked virtual network as required when User Defined Routing is selected
- automatically switch to the azure network plugin when User Defined Routing is selected

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes
- [x] The PR has been reviewed in terms of Accessibility

### CODE REVIEW

File: pkg/aks/components/Config.vue [hunk 1]
```diff
@@ -715,6 +729,22 @@ export default defineComponent({
         this.config['logAnalyticsWorkspaceGroup'] = null;
         this.config['logAnalyticsWorkspaceName'] = null;
       }
+    },
+
+    isUserDefinedRouting(neu: boolean) {
```
Comment (codyrancher) [inline pkg/aks/components/Config.vue:734]: It feels like there's an opportunity in the future to improve the validation interface. What a pain to make this conditional.

File: pkg/aks/components/Config.vue [hunk 2]
```diff
@@ -255,6 +250,7 @@ export default defineComponent({
         locationRequired:        requiredInCluster(this, 'aks.location.label', 'config.location'),
         resourceGroupRequired:   requiredInCluster(this, 'aks.clusterResourceGroup.label', 'config.resourceGroup'),
         dnsPrefixRequired:       requiredInCluster(this, 'aks.dnsPrefix.label', 'config.dnsPrefix'),
+        virtualNetworkRequired:  requiredInCluster(this, 'aks.virtualNetwork.label', 'config.virtualNetwork'),
```
Comment (codyrancher) [inline pkg/aks/components/Config.vue:253]: Below this line `ipv4WithOrWithoutCidr` is being passed 3 arguments even though the method only expects one argument.

It's not a part of this pr. and I can't comment on it in github so feel free to ignore but I figured I'd mention it since I saw it while browsing the code.

**Review by codyrancher — APPROVED** [review]

File: pkg/aks/components/Config.vue (hunk 2 above)
Comment (mantis-toboggan-md) [reply pkg/aks/components/Config.vue:253]: Thanks for catching that, removed them for tidiness

File: pkg/aks/components/Config.vue (hunk 1 above)
Comment (mantis-toboggan-md) [reply pkg/aks/components/Config.vue:734]: Yeah, using the form validation mixin gets hacky the instant you deviate from validating a single field on the component's value property - hopefully we can replace that mixin soon(tm) https://github.com/rancher/dashboard/issues/13937

**Review by codyrancher — APPROVED** [review]
