### PR TITLE
Fix failure to fetch workload resources in monitoring chart install

### LINKED ISSUE #11536: Server-side Pagination: Monitoring: Network errors are thrown when the user navigates to Monitoring chart
**Setup**
- Rancher version: v2.9-13494c6a541d408b00e78415d18128f642f295d0-head
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**
Network errors are thrown when the user navigates to the second step in installing the Monitoring chart when vai enabled.

**To Reproduce**
1. go to Global settings > feature flags > enable `ui-sql-cache`
2. go to Global settings > performance > enable `Server-sdie Pagination'
3. go to cluster dash
4. click Tools
5. click Install for Monitoring chart
6. click Next
7. notice 422 errors thrown (GET /batch.jobs, /batch.cronjobs, /apps.statefulsets, /app.replicasets, /apps.deployments, /apps.daemonsets)

Error: 
{
 "type": "error",
    "links": {},
    "code": "InvalidBodyContent",
    "message": "column is invalid [metadata.fields.1]: supplied column is invalid",
    "status": 422
}

**Result**
422 errors thrown

**Expected Result**
No errors thrown

**Screenshots**
https://github.com/user-attachments/assets/7f5f9c66-8a65-40b3-8f25-5048c2c0fae9

**Additional context**

### LINKED ISSUE #11539: Server-side Pagination: Monitoring: ‘storage class name’ options missing from Prometheus/Grafana tabs when Vai enabled
**Setup**
- Rancher version: v2.9-dd23578d3e3499f54d80c4ed88cc52c44ee69539-head
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**
The 'storage class name’ options are missing from the Prometheus/Grafana tabs when Vai is enabled. Note: The options appear after Monitoring chart is installed.

**To Reproduce**
1. go to Global settings > feature flags > enable ui-sql-cache
2. go to Global settings > performance > enable `Server-sdie Pagination'
4. go to cluster dash 
5. click Storage
6. click StorageClasses > create one
7. click Apps
8. select Monitoring chart
9. click install > Next
10. click Prometheus tab > select persistent storage > notice ‘storage class name’ options missing
11. click Grafana tab > enable with pvc template > notice ‘storage class name’ options missing
12. click Grafana tab > enable with statefulset template > notice ‘storage class name’ options missing

**Result**
The 'storage class name’ options are missing from the Prometheus/Grafana tabs when Vai enabled.

**Expected Result**
The 'storage class name’ options are available in the Prometheus/Grafana tabs when Vai enabled.

**Screenshots**

https://github.com/user-attachments/assets/151d0779-2403-4c0c-9aae-5b0a4cf3de67

**Additional context**

### LINKED ISSUE #11540: Server-side Pagination: Monitoring: ‘enable with existing pvc’ option missing from Grafana tab when Vai enabled
**Setup**
- Rancher version: v2.9-dd23578d3e3499f54d80c4ed88cc52c44ee69539-head
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**
The ‘enable with existing pvc’ option missing from the Grafana tab when Vai is enabled. Note: The options appear after Monitoring chart is installed.

**To Reproduce**
1. go to Global settings > feature flags > enable ui-sql-cache
2. go to Global settings > performance > enable `Server-sdie Pagination'
4. go to cluster dash 
5. click Storage
6. click PersisentVolumeClaims > create one
7. click Apps
8. select Monitoring chart
9. click Install > Next
10. click Grafana tab
11. under Grafana Storage, notice 'enable with existing pvc' option is missing

**Result**
The ‘enable with existing pvc’ option missing from the Grafana tab when Vai is enabled.

**Expected Result**
The ‘enable with existing pvc’ option is available in the Grafana tab when Vai is enabled.

**Screenshots**

https://github.com/user-attachments/assets/160073e6-c461-4fb1-981c-a93b506db7fe

**Additional context**

### LINKED ISSUE #14445: SSP: Error thrown when navigating to Service detail page
**Setup**
- Rancher version: v2.12
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**
An error is thrown when navigating to the Service detail page when SSP is enabled.

`fetch.client.js:76 Error in fetch(): Error: labelSelector must not be empty when using findLabelSelector (avoid fetching all resources)`

**To Reproduce**
1. Enable SSP
2. Go to local cluster 
3. Go to Services Discovery> Services
4. Go to a Service detail page

**Result**
Error thrown.
**Expected Result**
No errors.

**Screenshots**

https://github.com/user-attachments/assets/b9ff9aee-5ae9-420b-83d8-48deb3a16922

**Additional context**
Discovered while testing https://github.com/rancher/dashboard/issues/13043

### LINKED ISSUE #14446: SSP: Error thrown when using search filter on Services list page
**Setup**
- Rancher version: v2.12
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**
An error is thrown when using the search filter on the Services list page when SSP is enabled.

`{
    "type": "error",
    "links": {},
    "code": "InvalidBodyContent",
    "message": "column is invalid [targetPort]: supplied column is invalid",
    "status": 422
}`

**To Reproduce**
1. Enable SSP
2. Go to local cluster 
3. Go to Services Discovery> Services
4. Type anything in filter search box
5. 

**Result**
Error thrown.
**Expected Result**
No errors.

**Screenshots**

Image

**Additional context**
Discovered while testing https://github.com/rancher/dashboard/issues/13043

### PR DESCRIPTION
**Pull request by richard-cox**
### Summary
Fixes #11536
Fixes #11539
Fixes #11540

Also
Fixes #14446
Fixes #14445

### Occurred changes and/or fixed issues
- Fields in install monitoring wizard were empty (#11536, #11539, #11540)
  - exception caused by missing backend indexed fields
  - exception meant a number of input options were not populated
  - these fields have now been indexed, so no code changes required to fix (just comments tidied up)
- Review sorting/filtering on other fields that depended on backend indexing or bug fixes 
  - some are fine (removed comments associated with them)
  - some are still not (created new issues and updated comments)
- Fix sorting storage classes by `default` column
- Fixed issue when searching `services`, ensure column using local property targetPort are not used when searching server side (#14446)
- Can now sort on service type
- Can now view service detail page for services without selectors without seeing error in console (#14445)

### Areas or cases that should be tested
All with vai on

- Install monitoring chart (should be fine)
- Services list - search by any text should result in the correct rows displayed (no errors)
- Services list - sorting by type should work
- Service detail page for `kubernetes` service - no error in console
- Storage Class - sorting on default class should work

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: shell/config/product/explorer.js [hunk 1]
```diff
@@ -305,8 +305,11 @@ export function init(store) {
     [
       STEVE_STATE_COL,
       STEVE_NAME_COL,
-      STEVE_NAMESPACE_COL,
-      TARGET_PORT,
+      STEVE_NAMESPACE_COL, {
+        ...TARGET_PORT,
+        sort:   false,
+        search: false,
```
Comment (richard-cox) [inline shell/config/product/explorer.js:311]: Fix sorting storage classes by default column

File: shell/config/product/explorer.js [hunk 2]
```diff
@@ -315,8 +318,8 @@ export function init(store) {
       },
       {
         ...SPEC_TYPE,
-        sort:   false, // ['spec.type', 'spec.clusterIP'] Pending API support  (blocked https://github.com/rancher/rancher/issues/48473 (index fields)
-        search: 'spec.type',
+        sort:   ['spec.type'],
```
Comment (richard-cox) [inline shell/config/product/explorer.js:321]: Can now sort on service type

File: shell/config/product/explorer.js [hunk 3]
```diff
@@ -496,8 +499,8 @@ export function init(store) {
       },
       {
         ...STORAGE_CLASS_DEFAULT,
-        sort:   false, // [`metadata.annotations[${ STORAGE.DEFAULT_STORAGE_CLASS }]`], // Pending API Support - https://github.com/rancher/rancher/issues/48453
-        search: false, // [`metadata.annotations[${ STORAGE.DEFAULT_STORAGE_CLASS }]`], // Pending API Support - https://github.com/rancher/rancher/issues/48453
+        sort:   [`metadata.annotations[${ STORAGE.DEFAULT_STORAGE_CLASS }]`],
```
Comment (richard-cox) [inline shell/config/product/explorer.js:502]: Fix filtering/sorting storage classes by default column

File: shell/models/service.js [hunk 4]
```diff
@@ -138,6 +138,11 @@ export default class Service extends SteveModel {
   }
 
   async fetchPods() {
+    if (!this.podRelationship) {
+      // If empty or not present, the service is assumed to have an external process managing its endpoints
```
Comment (codyrancher) [inline shell/models/service.js:142]: Is this assumption documented anywhere? I tried to look it up and I found some mentions of it but didn't see anything official.

Comment (richard-cox) [reply shell/models/service.js:142]: I grabbed it from the reference docs https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.32/#servicespec-v1-core. It's not well indexed by google though


selector object
Route service traffic to pods with label keys and values matching this selector. If empty or not present, the service is assumed to have an external process managing its endpoints, which Kubernetes will not modify. Only applies to types ClusterIP, NodePort, and LoadBalancer. Ignored if type is ExternalName. More info: https://kubernetes.io/docs/concepts/services-networking/service/

Comment (codyrancher) [reply shell/models/service.js:142]: Thanks!
