### PR TITLE
fix issue with Resources Select in globalRoles edit/create interface

### LINKED ISSUE #9209: Bug in selecting resources in Global Roles interface
**Setup**
- Rancher version: 2.7-head
- Rancher UI Extensions:
- Browser type & version: Chrome

**Describe the bug**
Selecting the `resource` called `apps` in the category `catalog.cattle.io` causes the input to become in a weird state which renders it unusable/unselectable in Global Roles creation

**To Reproduce**
- Go to Users & Authentication - Roles - Global Roles - Create
- Select the `resource` called `apps` in the category `catalog.cattle.io`

**Result**
Select input becomes unusable/unselectable

**Expected Result**
Select input should work correctly

**Screenshots**
Screenshot 2023-06-26 at 15 45 00

### PR DESCRIPTION
**Pull request by aalves08**
Fixes #9209 

- Fix issue with Select `resources` in GlobalRoles edit/create view where selecting an item with duplicate labels caused the Select to become unusable
- update `getOptionKey` in `Select` component to match the same code as in `LabeledSelect` (since it's the same usage of `v-select`, don't understand the particularity of the code before, also given the fact that `LabeledSelect` works fine)
- Remove `option-key` and `option-label` from the only place where the usage of the component `Select` had it defined in Dashboard, since it's the default for components that use `v-select`

Notes:
- Both Kubewarden and Elemental don't make use of `Select` component - checked it
- Cannot fix the `Select` pointing to `apps` in `project.cattle.io`, since both have the exact same label. In this case, it's not relevant because what the `value` uses for `resource` is just the string `app`. The `API Groups` value (which also come from this select) works as expected.

**Screenshots**
Screenshot 2023-06-26 at 15 44 47

### CODE REVIEW

File: shell/components/form/Select.vue [hunk 1]
```diff
@@ -135,8 +135,8 @@ export default {
       return true;
     },
     getOptionKey(opt) {
-      if (opt?.optionKey) {
-        return get(opt, opt.optionKey);
+      if (this.optionKey) {
```
Comment (richard-cox) [inline shell/components/form/Select.vue:138]: Can this still be gated on `opt` (as well as this.optionKey)? it was specifically checked for here https://github.com/rancher/dashboard/pull/7562/files#diff-75439429eb24f054e1624b15d5efd59dc38fe8e8224cb067d26d5f335712830fR138

**Review by richard-cox — CHANGES_REQUESTED** [review]
Had some fun with `option-key="optionKey"` (intentional string, rather than var) and confusing v-select `opt` with roledetailedit select's `options`. Only one minor safety like request, otherwise tested and looks good

**Comment by richard-cox** [comment]
@aalves08 GH is showing this PR in a weird state (it's stating review required, when a review has been given). Just in case it isn't showing up in your filters, its ready for tweaking

File: shell/components/form/Select.vue (hunk 1 above)
Comment (aalves08) [reply shell/components/form/Select.vue:138]: It cannot be after `if (this.optionKey)`, otherwise we will get the same error. I can put under the `else` condition. I am not sure this should be used, to be fair, as it's fundamentally different from the `LabeledSelect`, which is very similar to this component.
https://github.com/rancher/dashboard/blob/master/shell/components/form/LabeledSelect.vue#L216-L222

Nevertheless, I've added it as a fallback.

**Comment by aalves08** [comment]
@richard-cox true... I took you out as a reviewer and added you back and the state got corrected. I could ask for a re-review, so you should receive a notification.

File: shell/components/form/Select.vue (hunk 1 above)
Comment (richard-cox) [reply shell/components/form/Select.vue:138]: Basically trying to catch the case where `opt` is undefined and the if block is skipped as before. Code as is would go into the block and return `undefined`.

Updating to `if (opt && this.optionKey)` should cover it

**Review by richard-cox — CHANGES_REQUESTED** [review]

**Review by richard-cox — APPROVED** [review]
Did a bit of deep dive into `getOptionKey`. made a tweak, added lots of comments to help others understand the madness of opt.optionKey. More detail in commit message

If that looks good feel free to merge

**Comment by richard-cox** [comment]
@aalves08 Does this one need QA? I noticed the connected issue isn't marked with dev complete and hasn't gone through QA
