### PR TITLE
Custom chart UIs show PSP switch on Kubernetes v1.25

### LINKED ISSUE #8434: Custom chart UIs show PSP switch on Kubernetes v1.25
**Setup**
- Rancher version: Rancher v2.7.2-rc5
- Browser type & version: Microsoft Edge v111.0.1661.41 (Official build) (arm64)

**Describe the bug**

When installing charts on a Kubernetes v1.25.6 cluster, the custom chart UIs still show the **Enable PodSecurityPolicies** checkbox, even though it is not possible to have PSPs in this version of Kubernetes and above.

**To Reproduce**

1. Create an RKE downstream cluster with Kubernetes v1.25.
2. Go to **Explore Cluster** and select the newly created v1.25 cluster.
3. In **Apps**/**Charts**, select one of the following charts:
    * Alerting Drivers
    * Epinio
    * Istio
    * Logging
    * Longhorn
    * Monitoring
    * NeuVector
    * OPA Gatekeeper
    * Prometheus Federator
5. Click **Install**.
6. Select any project then click **Next**.
7. Notice that the second page of configuration shows the **Enable Pod Security Policies** checkbox.

**Result**
A user can still select the checkbox to install PodSecurityPolicies even though these are not supported in Kubernetes v1.25 anymore.

**Expected Result**

A user cannot choose to install PSPs from the UI when the cluster is Kubernetes v1.25.

### PR DESCRIPTION
**Pull request by cnotv**
### Summary
Fixes #8434

### Occurred changes and/or fixed issues
PSP checkbox to be displayed if K8S < 1.25 or PSP is already enabled.
This is applied for the charts:
- OPA Gatekeeper
- Istio
- Logging
- Monitoring
- Rancher Backup
- Alerting
- Epinio
- Longhorn
- NeuVector
- Prometheus Federator

### Technical notes summary
- Moved markup within the component to avoid empty spaces
- Allowed to pass title for areas which require one
- Passed cluster object to parse version
- Extended tests
- Created helper to get ignored questions with variables matching the path of the current cluster (ignore logic already existed) for same condition
- Added tests to the helper, created separately due high complexity of the component (2500+ lines)

### Areas or cases that should be tested
All the charts above for clusters with K3/RKE2 and K8S < v1.25 or >= 1.25 and PSP disabled/enabled

### Areas which could experience regressions
Same as above.

#### Custom charts

PSP checkbox present in all the charts for 1.24 and not 1.25

https://user-images.githubusercontent.com/5009481/227222888-c7e4e624-3a73-4af3-95c3-87e716d5f8e5.mp4

Proof of Cluster update (with error in the navigation 🤔 )

https://user-images.githubusercontent.com/5009481/227243291-86042c2e-0b8e-4917-b365-da42a900a45b.mp4

Disabling PSP but with an error in the server response

https://user-images.githubusercontent.com/5009481/227243277-c9369f63-9a5e-460b-91c1-4a22d30b84ed.mp4

#### Standard charts (question.yaml)

PSP checkbox present in the charts for 1.24 and not 1.25

https://user-images.githubusercontent.com/5009481/227595029-4f15e81e-92f0-4f09-a96c-81de8057c1eb.mp4

Disabling PSP but with an error in the server response

https://user-images.githubusercontent.com/5009481/227595125-055229b4-22a1-4be8-b604-98d5e6467e6a.mp4

### CODE REVIEW

**Comment by cnotv** [comment]
@mantis-toboggan-md I have added the logic, tests, description and videos also for the standard charts.

File: shell/components/ChartPsp.vue [hunk 1]
```diff
@@ -14,24 +14,71 @@ export default {
...
   },
-  computed: { ...mapGetters({ t: 'i18n/t' }) }
+  computed: {
+    ...mapGetters({ t: 'i18n/t' }),
+
+    /**
+     * Display checkbox only if contains PSP or K8S version is less than 1.25
+     */
+    hasCheckbox() {
+      const clusterVersion = this.cluster?.metadata?.annotations?.['management.cattle.io/current-cluster-controllers-version'] || '';
```
Comment (mantis-toboggan-md) [inline shell/components/ChartPsp.vue:58]: This looks like a new way of getting the k8s version. Could the mgmt cluster `kubernetesVersion` getter be used here? eg const `clusterVersion = cluster.kubernetesVersion`

**Review by mantis-toboggan-md — CHANGES_REQUESTED** [review]
The functionality of the pr looks good, I just had a question about how the current kubernetes version is determined

**Review by mantis-toboggan-md — APPROVED** [review]
LGTM
