### PR TITLE
GKE - allow initial node count to be 0

### LINKED ISSUE #11844: GKE: Validation required for Min/Max NodeCount
**Setup**
Rancher - v2.9-ac80dbd08dd92b65627b36e8658c87ea661c1baf-head
Dashboard - release-2.9 https://github.com/rancher/dashboard/commit/e7910502ec96bab1d8e67cc20af872a755a8a01c

**Describe the bug**
On GKE portal, 0 Min NodeCount & 1000 Max NodeCount is allowed. 
On Rancher UI, the MinCount needs to be allowed and MaxCount needs to be validated.

**Screenshots**

GKE:
MinCount: 
image

MaxCount:
image

Rancher:

MinCount: 
image

MaxCount:
image

### PR DESCRIPTION
**Pull request by mantis-toboggan-md**
### Summary
Fixes #11844 

### Occurred changes and/or fixed issues
This PR updates the GKE provisioning form to validate that node pools' initial node count is >=0 and <=1000

### Technical notes summary
I moved the validator to a utility file so I could write a couple unit tests. Also fixed a couple issues related to vue3 migration that prevented the form from working.

### Areas or cases that should be tested
Create a GKE cluster - node pools' initial node count should be validated to be >=0 and <=1000

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: pkg/gke/components/GKENodePool.vue [hunk 1]
```diff
@@ -464,7 +464,7 @@ export default defineComponent({
           :mode="mode"
           :value="preemptible"
           :disabled="!isNew"
-          @input="$emit('update:preemptible', $event)"
+          @update:value="$emit('update:preemptible', $event)"
```
Comment (mantis-toboggan-md) [inline pkg/gke/components/GKENodePool.vue:467]: Somehow, this component didn't get this vue3 update to input event syntax. I searched the codebase and didn't find any other components with the same problem.

File: pkg/gke/components/CruGKE.vue [hunk 2]
```diff
@@ -686,7 +674,7 @@ export default defineComponent({
     @error="e=>errors=e"
     @finish="save"
   >
-    <template>
+    <div>
```
Comment (mantis-toboggan-md) [inline pkg/gke/components/CruGKE.vue:677]: This change is also due to vue3.

**Review by momesgin — APPROVED** [review]
