### PR TITLE
Unpin rancher version in e2e tests, update tests following vai on by default

### LINKED ISSUE #14585: Unpin rancher version used in e2e tests
- https://github.com/rancher/dashboard/pull/14564
- Bug in head causing rancher crash during explorer2 and vai suites when looking at workload types

### PR DESCRIPTION
**Pull request by richard-cox**
~Blocked on https://github.com/rancher/rancher/issues/48691~
~Blocked on https://github.com/rancher/rancher/issues/50637 (causes chart tests to fail)~
Worked around https://github.com/rancher/rancher/issues/50823

### Summary
Fixes https://github.com/rancher/dashboard/issues/14495
Fixes #14585

### Occurred changes and/or fixed issues
- Unpin rancher version in e2e tests,
  - Reset rancher version tests run on to head
- Fixes after kube bump to 1.33
  - 1.33 uses buggy containerd 2.0
  - our spammy (create 26 resources, test, delete containing ns) workloads tests were causing kube to crash with OOM
  - fixes
    - we now take more pauses when creating and
    - wait for ns to be deleted before continuing 
    - set a much less aggressive cron schedule when testing cronjobs
    - use a smaller container image
- Update tests following vai on by default
  - Given Vai on by default, fix tests
    - Ensure that vai on query params are dynamically applied given vai ff
    - Remove workload list specific tests 
    - Change tests that use the workload list to other resource lists
    - Remove tests that dabble with the workload health drop down
    - Ensure fixed areas with vai on (like now visible list groups) don't break tests
  - Flip `vai` test suite from testing with vai on... to testing with vai off
- also
  - we now save rancher docker logs as test artefacts  (on test failure)
  - fix script that replicates and runs gate-like commands in local env
  - improve flaky tests (compliance + kontainer)

### Areas or cases that should be tested
N/A

### Areas which could experience regressions
N/A

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes
- [x] The PR has been reviewed in terms of Accessibility

### CODE REVIEW

File: cypress/support/commands/rancher-api-commands.ts [hunk 1]
```diff
@@ -1168,3 +1169,12 @@ Cypress.Commands.add('createService', (namespace: string, name: string, options:
     return resp.body.metadata.name;
   });
 });
+
+/**
+ * Supplement the provided path for a collection of steve resources with default steve query params
```
Comment (richard-cox) [inline cypress/support/commands/rancher-api-commands.ts]: not a collection anymore. better description. when would this be used

File: cypress/e2e/tests/setup/rancher-setup.spec.ts [hunk 2]
```diff
@@ -96,7 +97,7 @@ describe('Rancher setup', { tags: ['@adminUserSetup', '@standardUserSetup', '@se
     });
   });
 
-  it('Create standard user', () => {
+  it('Initialise State', () => {
```
Comment (richard-cox) [inline cypress/e2e/tests/setup/rancher-setup.spec.ts]: revert

File: cypress/e2e/tests/priority/vai-setup.spec.ts [hunk 3]
```diff
@@ -4,21 +4,21 @@ import { FeatureFlagsPagePo } from '@/cypress/e2e/po/pages/global-settings/featu
```
Comment (richard-cox) [inline cypress/e2e/tests/priority/vai-setup.spec.ts:4]: rename file

Comment (richard-cox) [reply cypress/e2e/tests/priority/vai-setup.spec.ts:4]: comment

File: cypress/e2e/tests/pages/explorer/policy/network-policy.spec.ts [hunk 4]
```diff
@@ -97,8 +97,16 @@ describe('NetworkPolicies', { testIsolation: 'off', tags: ['@explorer', '@adminU
...
     networkPolicyPage.waitForPage();
+    cy.isVaiCacheEnabled().then((isVaiCacheEnabled) => {
+      const chain = isVaiCacheEnabled ? cy.intercept('GET', '/v1/networking.k8s.io.networkpolicies?*') : cy.wrap(true);
+
+      chain.as('listRequest');
+    });
+
     networkPolicyPage.searchForNetworkPolicy(networkPolicyName);
     networkPolicyPage.waitForPage(`q=${ networkPolicyName }`);
+    cy.wait('@listRequest');
```
Comment (richard-cox) [inline cypress/e2e/tests/pages/explorer/policy/network-policy.spec.ts]: comment why this is needed. non-vai, vai world

File: cypress/e2e/tests/accessibility/shell.spec.ts [hunk 5]
```diff
@@ -352,29 +351,12 @@ describe('Shell a11y testing', { tags: ['@adminUser', '@accessibility'] }, () =>
...
-        });
-
         it('Deployments page', () => {
           const deploymentsListPage = new WorkloadsDeploymentsListPagePo();
 
           deploymentsListPage.goTo();
           deploymentsListPage.waitForPage();
           deploymentsListPage.sortableTable().checkLoadingIndicatorNotVisible();
-          // expand the health scale up/down control
-          deploymentsListPage.sortableTable().getTableCell(1, 10).click();
```
Comment (richard-cox) [inline cypress/e2e/tests/accessibility/shell.spec.ts:381]: make alex and phil aware that workloads page/list has been removed. let a11y company aware

File: cypress/e2e/tests/navigation/side-nav/product-side-nav.spec.ts [hunk 6]
```diff
@@ -108,20 +109,20 @@ describe('Side navigation: Cluster ', { tags: ['@navigation', '@adminUser'] }, (
 
   it('Clicking on the tab header should navigate', () => {
     const productNavPo = new ProductNavPo();
-    const group = productNavPo.groups().eq(1); // First group is 'Workloads'
+    const group = productNavPo.groups().eq(0); // first group is 'Cluster'
 
     // Select and expand current top-level group
     group.click();
-    const workloads = new WorkloadPagePo();
+    const homepage = new ClusterDashboardPagePo('local');
```
Comment (richard-cox) [inline cypress/e2e/tests/navigation/side-nav/product-side-nav.spec.ts]: homePAge --> clusterDashboard

File: cypress/e2e/po/pages/explorer/api-services.po.ts [hunk 7]
```diff
@@ -15,7 +15,7 @@ export class APIServicesPagePo extends PagePo {
   }
 
   waitForRequests() {
-    APIServicesPagePo.goToAndWaitForGet(this.goTo.bind(this), ['/v1/apiregistration.k8s.io.apiservices?exclude=metadata.managedFields']);
+    APIServicesPagePo.goToAndWaitForGet(this.goTo.bind(this), [`/v1/apiregistration.k8s.io.apiservices?*`]);
```
Comment (richard-cox) [inline cypress/e2e/po/pages/explorer/api-services.po.ts:18]: note for future - these changes are now vai on / off agnostic (there are different params for both)

File: cypress/e2e/tests/pages/explorer/dashboard/certificates.spec.ts [hunk 8]
```diff
@@ -65,7 +65,7 @@ describe('Certificates', { testIsolation: 'off', tags: ['@explorer', '@adminUser
   });
 
   it("show correct 'expired' states", () => {
-    cy.intercept('GET', '/v1/secrets?*', (req) => {
+    cy.intercept('GET', /^\/v1\/secrets\?[\S]+$/, (req) => {
```
Comment (richard-cox) [inline cypress/e2e/tests/pages/explorer/dashboard/certificates.spec.ts:68]: cypress wildcards won't work if the query param has a `~`, instead used regex

**Review by nwmac — DISMISSED** [review]
