### PR TITLE
Changed navlink page and improved error handling for FileImageUpload

### LINKED ISSUE #5184: Provide user feedback for image file upload
**Detailed Description**

Provide user feedback for image file upload when used within the form:

- **Weight**, user is not informed
- **Format**, we may restrict the upload, but the user is not informed
- **Proportions**, images may not be square, nor we crop them
- **Limitations**, in some cases we set `20000` in others `200000`, while server triggers EOT error

Issue: on image limitation, no feedback is provided and the image is not added

**Context**

While uploading images, we do not provide these information, nor any feedback related to server communication.

#### Navlinks

- Path: `/c/local/explorer/ui.cattle.io.navlink/create#group`
- How to reach:
  - Search for resource `navlink`
  - Create new resource
- Custom component adopted: `FileImageSelector`

Screenshot from 2022-02-22 17-56-14

#### Global Settings> Branding > Logo

- Path: `/c/local/settings/brand`
- How to reach:
  - Open global settings
  - Navigate to Branding
  - Scroll to Logo settings
  - Enable "Use a custom logo"
  
Screenshot from 2022-02-22 17-58-04

### LINKED ISSUE #9348: "Create" buttons should be disabled when required fields are not filled on Navlinks page
**Setup**
- Rancher version: v2.7.5-rc5
- Browser type & version: Chrome 14.0.5735.198

**Describe the bug**
"Create" button should be disabled when required fields are empty

**To Reproduce**
Path: /c/local/explorer/ui.cattle.io.navlink/create#group
How to reach:
Search for resource navlink
Create new resource
Leave all fields empty

**Result**
"Create" button is enabled

**Expected Result**
"Create" button should be disabled

### PR DESCRIPTION
**Pull request by eva-vashkevich**
### Summary
Fixes #9348
Fixes #5184 

Changed "Navlinks" page from tabular to regular page, added validation to it and error message on file upload. Changed FileSelector to FileImageSelector on "Branding" page.

### Occurred changes and/or fixed issues
For Branding page:
- Changed all occurrences of FileSelector to FileImageSelector
For Navlinks page:
- Disabled  "Create" button if required fields are not filled in
- Removed tabs
- Added error on file upload
For FileSelector:
- Added type validation if expected type is image

### Technical notes summary
Added MIME byte checking to validate that uploaded file is an image (https://mimesniff.spec.whatwg.org/#matching-an-image-type-pattern) 

### Areas or cases that should be tested
Used Chrome for local testing.
Open "Local" -> "NavLinks" -> "Create"
- Tabs should be removed
- "Create" button should be disabled
- Validate that filling in required fields enables "Create" button
- Switch to the different link type and validate that filling in new required fields also enables the button
- "Group Image" subsection is added.
- Appropriate error should be displayed if image is too big or has wrong type.

Open "Global settings" -> "Branding"
- Try uploading custom "logo" and "favicon" and make sure appropriate error is displayed if file is too big or has incorrect format

### Areas which could experience regressions
FIleSelector required additional testing to make sure it is still working for non-image case

### CODE REVIEW

File: shell/components/form/FileSelector.vue [hunk 1]
```diff
@@ -63,7 +77,13 @@ export default {
     accept: {
       type:    String,
       default: '*'
-    }
+    },
+
+    fileType: {
```
Comment (mantis-toboggan-md) [inline shell/components/form/FileSelector.vue:82]: This can be covered using the existing `accept` prop to restrict which file types can be selected for upload:  https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#limiting_accepted_file_types. I would add an accept prop to the `FileImageSelector` component that defaults to allowing all images: 
```
 accept: {
    type:    String,
    default: 'image/*'
  }
```

Then pass through more specific restrictions in the navlinks component: 
```
   <FileImageSelector
     v-model="value.spec.iconSrc"
     :read-as-data-url="true"
     :mode="mode"
     :label="t('navLink.tabs.groupImage.iconSrc.label')"
     accept="image/jpeg,image/png,image/svg+xml"
     @error="setImageError"
     @input="setIcon"
   />

**Review by mantis-toboggan-md — CHANGES_REQUESTED** [review]

**Review by mantis-toboggan-md — APPROVED** [review]
lgtm
