### PR TITLE
Fix initialisation of `ui-brand` setting

### LINKED ISSUE #9270: Initialisation of `ui-brand` setting fails
**Setup**
- Rancher version: 2.7.q3 pre-release
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**
- Green branding should be applied when the rancher-csp-adapter app is installed (https://github.com/rancher/csp-adapter)
- Branding is applied to a setting ui-branding
- In the initial case when ui-branding has not been set it won't ever get set, regardless of app found

**To Reproduce**
- Ensure /v3/settings/ui-brand does not exist
- Hack in an install of csp-adpater chart
  - From a shell env in the local cluster
    ```
    helm repo add rancher-charts https://charts.rancher.io
    helm install rancher-csp-adapter rancher-charts/rancher-csp-adapter --set aws.enabled=true --set aws.accountNumber=1234 --set aws.roleName=abc
    ```

**Result**
- Once the app is installed the branding will remain blue, even over refresh
**Expected Result**
- The branding should turn green

**Screenshots**

**Additional context**
- Uninstalling the app should return the branding back to blue
- Installing the app again will not result in green branding (expected)
- Deleting the ui-brand setting can be done via /v3/settings/ui-brand

### PR DESCRIPTION
**Pull request by richard-cox**
### Summary
Fixes #9270

### Occurred changes and/or fixed issues
- Green branding should be applied when the `rancher-csp-adapter` app is installed (https://github.com/rancher/csp-adapter)
- This was not happening, fix is to ensure the reactive parts fire correctly again
- I'm not sure when this came in, possibly 2.7.5

### Technical notes summary
- ui-brand setting comes from the existence of a helm app
- this was broken for the initial case
  -  cause by a computed property not re-running given change after `fetch`
- fixing this reactivity exposed some other scenarios where we need to be safe
  - for instance when logged out, or in the process thereof

> Also fixed the position of the `Logging Out...` text. Previously this was at the top of the page, it's now in the centre

To Test in Dev
- Update `return this.apps.find((a) => a.metadata.name === 'rancher-csp-adapter');`  to look for any chart, for example  `traefik`

To Test in Deployed
```
helm repo add rancher-charts https://charts.rancher.io
helm install rancher-csp-adapter rancher-charts/rancher-csp-adapter --set aws.enabled=true --set aws.accountNumber=1234 --set aws.roleName=abc
```

### Areas or cases that should be tested
- Systems where the `rancher-csp-adapter` app is installed (and ui-branding goes green)
- Systems where the `rancher-csp-adapter` app has been uninstalled (and ui-branding returns to blue)

### CODE REVIEW

File: shell/mixins/brand.js [hunk 1]
```diff
@@ -23,13 +24,19 @@ export default {
...
     } catch (e) {}
+
+    // Setting this up front will remove `computed` churn, and we only care that we've initialised them
+    this.haveAppsAndSettings = !!this.apps && !!this.globalSettings;
   },
 
   data() {
-    return { apps: [], globalSettings: [] };
+    return {
+      apps: null, globalSettings: null, haveAppsAndSettings: null
```
Comment (guangyee) [inline shell/mixins/brand.js:34]: this is different from https://github.com/rancher/dashboard/pull/9092/files#diff-556137f68d06f23031944f124827daa23f6f1cb5c7c6fe4ade07260010874f9eR35 so I presume this is what we want?

File: shell/mixins/brand.js [hunk 2]
```diff
@@ -61,7 +68,23 @@ export default {
...
+      // Note! these used to be `findBy(this.app)` however for that case we lost reactivity on the collection
+      // (computed fires before fetch, fetch happens and update apps, computed would not fire again - even with vue.set)
+      // So use `.find` here instead
+      return this.apps.find((a) => a.metadata.name === 'rancher-csp-adapter');
+    },
+
+    canCalcCspAdapter() {
+      // We need to take consider the loggedIn state, as the brand mixin is used in the logout page where we can be in a mixed state
+      // (things in store but user has no auth to make changes)
+      return this.loggedIn && this.haveAppsAndSettings;
```
Comment (guangyee) [inline shell/mixins/brand.js:87]: this block is also different from https://github.com/rancher/dashboard/pull/9092/files#diff-556137f68d06f23031944f124827daa23f6f1cb5c7c6fe4ade07260010874f9eR70-R80

**Review by aalves08 — CHANGES_REQUESTED** [review]
So, codewise, nothing stands out and installing + removing the `rancher-csp-adapter` app applies and removes the branding correctly (it's reactive).

I have found a problem with the login though... If you logout, then immediately do a login, we get this white-screen error (check screenshots). It's the same issue, either with the `rancher-csp-adapter` app installed or not (check header for branding on screenshots).

It looks like an easy fix:
`if (brandSetting.value !== '')` vs `if (brandSetting?.value !== '')`

Screenshot 2023-07-06 at 15 12 34
Screenshot 2023-07-06 at 15 13 33

**Comment by guangyee** [comment]
I also ran into the blank screen issue on my FF browser. Interestingly, the problem is not reproducible on my Chrome browser.

File: shell/mixins/brand.js (hunk 1 above)
Comment (richard-cox) [reply shell/mixins/brand.js:34]: Covered in comment in original PR. These changes will go in to and supersede any tweaks in there.

Comment (richard-cox) [reply shell/mixins/brand.js:34]: As per https://github.com/rancher/dashboard/pull/9269#discussion_r1261050249

File: shell/mixins/brand.js (hunk 2 above)
Comment (richard-cox) [reply shell/mixins/brand.js:87]: As per https://github.com/rancher/dashboard/pull/9269#discussion_r1261050249
