### PR TITLE
Resolve issues with workload pod storage

### LINKED ISSUE #11787: Case 4 Workload Pod Storage components
## Steps to reproduce

- Navigate to Cluster Explorer --> Workloads --> Deployments
- Click on Create
- Select the `Pod` tab --> `Storage` vertical tab

## Additional info

- Fails to render component containing form for selected storage type
- shell/edit/workload/storage/index.vue volumeTypeOptions
- image

### PR DESCRIPTION
**Pull request by rak-phillip**
### Summary
This resolves several issues associated with the Pod Storage tab under when creating new deployments:

- `ButtonDropdown.vue` now renders a label
- `ButtonDropdown.vue` now renders a list volumes
- Selecting a volume now renders the associated form in `ArrayListGrouped.vue`

Fixes #11787

### Technical notes summary

Several issues are resolved in this PR:

- Updates the slot syntax to be more consistent with `CruResource.vue`. This should help with accurately rendering slot content when we iterate over component slots.
- `v-select` now makes use of `modelValue`/`update:modelValue` for two-way data binding. This is consistent with the Vue3 migration guide.
- This approach uses the spread operator to create a new array instead of using push. It appears that using push on a nested property of a reactive object was not triggering Vue's reactivity in this instance, while creating a new array does the job.
- Add missing `value` prop in `ArrayListGrouped.vue`
- Normalize `customVolumeTypes` paths for storage `ButtonDropdown`

### Areas or cases that should be tested

- Storage
- ButtonDropdown
- ArrayList
- ArrayListGrouped

### Areas which could experience regressions

- Storage
- ButtonDropdown
- ArrayList
- ArrayListGrouped

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

**Review by richard-cox — APPROVED** [review]
Functionally looks good. Code changes too, though @codyrancher should have the last say on vue3 specifics.

I tested setting one of the volumes in a container however that failed (which is might be related to case 5&6 from epic https://github.com/rancher/dashboard/issues/11773)

File: shell/components/ButtonDropdown.vue [hunk 1]
```diff
@@ -211,14 +211,15 @@ export default {
...
+      #[slot]="scope"
       :key="slot"
-      v-slot:[slot]="scope"
     >
-      <slot
-        v-if="slot !== 'selected-option'"
-        :name="slot"
-        v-bind="scope"
-      />
+      <template v-if="slot !== 'selected-option' && typeof $slots[slot] === 'function'">
```
Comment (codyrancher) [inline shell/components/ButtonDropdown.vue:217]: Just for my own info, what other values would `typeof $slots[slot]` produce other than a function. Does it just differentiate between plain elements and components?

**Review by codyrancher — APPROVED** [review]
LGTM

File: shell/components/ButtonDropdown.vue (hunk 1 above)
Comment (rak-phillip) [reply shell/components/ButtonDropdown.vue:217]: When working on a demonstration, I couldn't get this to evaluate to anything other than `function` and the migration guide docs support this[^1]. 

When I was working on aedd3348035cebaeeea57832e5947f780511fdcd, I recall encountering instances of `undefined`/`string`. This could have been added in error while testing - I will review these cases and follow up in another PR if this line is not needed.

[^1]: https://v3-migration.vuejs.org/breaking-changes/slots-unification.html
