### PR TITLE
[App Card] - Fix truncation and extra icons

### LINKED ISSUE #16860: Long repo names are not truncated
**Setup**
- Rancher version:
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**

Long repo names used to get truncated to only occupy one line of text but now they break the cards.

**To Reproduce**

Create a repo with a very long name then go to Apps > Charts page

**Result**

**Expected Result**

**Screenshots**

Image

**Additional context**

### LINKED ISSUE #16861: Extra category icons on chart card
**Setup**
- Rancher version:
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**

We used to display only one category icon for multiple categories on chart cards, but now we display an icon for every category.

**To Reproduce**

Go to Apps > Charts page and find a card with multiple categories (try filtering the results by Infrastructure from the side filter panel)

**Result**

**Expected Result**

**Screenshots**

Image

**Additional context**

### PR DESCRIPTION
**Pull request by momesgin**
### Summary
Fixes #16860 
Fixes #16861 

### Occurred changes and/or fixed issues

Updated the CSS styling to fix the truncation issue with the labels, and restructured the template to fix displaying an icon for each label.

### Areas or cases that should be tested

As described on each issue's description.

### Areas which could experience regressions

- Make sure the screen reader functions as before.
- Make sure clicking on each item works as before.

### Screenshot/Video

Before:
image

After:
image

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes
- [x] The PR has been reviewed in terms of Accessibility
- [x] The PR has considered, and if applicable tested with, the three Global Roles `Admin`, `Standard User` and `User Base`

### CODE REVIEW

File: shell/pages/c/_cluster/apps/charts/AppChartCardFooter.vue [hunk 1]
```diff
@@ -47,27 +52,20 @@ function onClickItem(type: string, label: string) {
...
-              />
-            </template>
-            {{ label }}
-            <span v-if="footerItem.labels.length > 1 && j !== footerItem.labels.length - 1">, </span>
+            <span class="app-chart-card-footer-button-label">{{ label }}</span>
           </rc-button>
+          <span
+            v-if="footerItem.labels.length > 1 && j !== footerItem.labels.length - 1"
+            class="app-chart-card-footer-item-separator"
+          >,&nbsp;</span>
```
Comment (rak-phillip) [inline shell/pages/c/_cluster/apps/charts/AppChartCardFooter.vue]: Avoid using `&nbsp;` to control layout. Defer to CSS to control the layout instead.

File: shell/pages/c/_cluster/apps/charts/AppChartCardFooter.vue [hunk 2]
```diff
@@ -47,27 +52,20 @@ function onClickItem(type: string, label: string) {
...
         </rc-item-card-action>
         <span
           v-else
           v-clean-tooltip="footerItem.labelTooltip"
           class="app-chart-card-footer-item-text"
           data-testid="app-chart-card-footer-item-text"
         >
-          {{ label }}
-          <span v-if="footerItem.labels.length > 1 && j !== footerItem.labels.length - 1">, </span>
+          {{ label }}<span v-if="footerItem.labels.length > 1 && j !== footerItem.labels.length - 1">,&nbsp;</span>
```
Comment (rak-phillip) [inline shell/pages/c/_cluster/apps/charts/AppChartCardFooter.vue]: Same here, avoid using `&nbsp;` to control layout.

File: shell/pages/c/_cluster/apps/charts/AppChartCardFooter.vue [hunk 3]
```diff
@@ -31,13 +31,18 @@ function onClickItem(type: string, label: string) {
       class="app-chart-card-footer-item"
       data-testid="app-chart-card-footer-item"
     >
+      <i
+        v-if="footerItem.icon"
+        v-clean-tooltip="t(footerItem.iconTooltip?.key)"
+        :class="['icon', 'app-chart-card-footer-item-icon', footerItem.icon]"
+      />
```
Comment (rak-phillip) [inline shell/pages/c/_cluster/apps/charts/AppChartCardFooter.vue]: nit: We will want to start using the `RcIcon` component so that we will have a more structured way of working with icons moving forward.

Comment (momesgin) [reply shell/pages/c/_cluster/apps/charts/AppChartCardFooter.vue]: this was kinda a rabbit hole lol but I managed to limit the scope to only the use cases of `AppChartCardFooter.vue`.
