### PR TITLE
Replace the done param fix and changed how we render the credential dynamic components

### LINKED ISSUE #13802: Cloud Creds: Secret input loses focus as footer button is enabled
**Setup**
- Rancher version: v2.11
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**
When creating/editing a cloud credential, the Secret/Access Token input field loses focus as the Create/Save button is enabled. Workaround is to refocus and continue typing secret. 
Order does matter - secret/access token needs to be filled last to reproduce this issue. 

**To Reproduce**
1. go to Cluster Management => Cloud Credentials => Create => Amazon
2. fill out form (secret last)
3. notice secret input loses focus as Create button is enabled

**Result**
Secret/Access Token input field loses focus as the Create/Save button is enabled.

**Expected Result**
Secret/Access Token input field does not lose focus as the Create/Save button is enabled.

**Screenshots**

https://github.com/user-attachments/assets/11b92bbb-0090-42f6-bc48-8c962c3d12e6

**Additional context**
Discovered while testing: https://github.com/rancher/dashboard/issues/13590

### PR DESCRIPTION
**Pull request by codyrancher**
### Summary

Fixes #13802

### Occurred changes and/or fixed issues
I reverted the `done-param` changes, I still have no idea why those functioned. 

I was able to trace what was causing the re-renders further and it seems to be caused by re-computing the component that we wanted to render even if that component didn't change. We now manually compute these values which prevents the re-render from occurring when the form input becomes valid.

### Areas or cases that should be tested
Cloud credentials create pages, hosted providers create credentials  section, node provisioned cluster create credentials section.

### Areas which could experience regressions
Anywhere with creating/selecting credentials.

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: shell/edit/cloudcredential.vue [hunk 1]
```diff
@@ -112,14 +119,6 @@ export default {
       return this.value?.provider;
     },
 
-    cloudComponent() {
```
Comment (codyrancher) [inline shell/edit/cloudcredential.vue:115]: I'm moving the components from computed properties to data properties that need to be manually assigned.

It looks as though the re-render was being caused when these properties got recomputed even if the resulting value didn't change.

File: shell/edit/cloudcredential.vue [hunk 2]
```diff
@@ -80,20 +80,27 @@ export default {
...
+      cloudComponent:                null
     };
   },
 
   watch: {
     'value._name'(newValue) {
       this.nameRequiredValidation = newValue?.length > 0;
+    },
+
+    driverName() {
```
Comment (codyrancher) [inline shell/edit/cloudcredential.vue:102]: Driver name isn't always available by the time data/fetch are invoked so I needed to add a watcher.

File: shell/edit/cloudcredential.vue (hunk 1 above)
Comment (rak-phillip) [reply shell/edit/cloudcredential.vue:115]: This is a great observation, I hadn't considered that there might be an issue with the design of this computed prop. 

This piqued my interest, so I decided to investigate what would happen if we adhered to the principle of "keep computed props as simple as possible" to see if this affects the outcome - it appears that it does. 

I decided to split the getters out into individual computed properties and the issue appears to be resolved with this approach as well:

```javascript
    hasCustomCloudCredentialComponent() {
      const driverName = this.driverName;

      return this.$store.getters['type-map/hasCustomCloudCredentialComponent'](driverName);
    },

    cloudCredentialComponent() {
      const driverName = this.driverName;

      return this.$store.getters['type-map/importCloudCredential'](driverName);
    },

    genericCloudCredentialComponent() {
      return this.$store.getters['type-map/importCloudCredential']('generic');
    },

    cloudComponent() {
      if (this.hasCustomCloudCredentialComponent) {
        return this.cloudCredentialComponent;
      }

      return this.genericCloudCredentialComponent;
    },
```

This style of access in more in-line with how vuex getters are typically accessed in a Vue component. My current hypothesis is that our style of accessing getters can produce scenarios that invalidate a computed prop's cache.

Comment (codyrancher) [reply shell/edit/cloudcredential.vue:115]: I'll switch it over to this.

File: shell/edit/cloudcredential.vue [hunk 3]
```diff
@@ -80,20 +80,27 @@ export default {
...
   },
 
   data() {
     return {
       credCustomComponentValidation: false,
       nameRequiredValidation:        false,
       nodeDrivers:                   null,
-      kontainerDrivers:              null
+      kontainerDrivers:              null,
+      cloudComponent:                null
```
Comment (rak-phillip) [inline shell/edit/cloudcredential.vue:93]: Storing `cloudComponent` in data produces the following warning:

```
[Vue warn]: Vue received a Component that was made a reactive object. This can lead to unnecessary performance overhead and should be avoided by marking the component with `markRaw` or using `shallowRef` instead of `ref`. 
Component that was made reactive:  
Object { name: "AsyncComponentWrapper", __asyncLoader: load(), __asyncHydrate: __asyncHydrate(el, instance, hydrate), __asyncResolved: Getter, setup: setup()
 }
 
  at <CruResource key=1 mode="create" validation-passed=false  ... > 
  at <CruCloudCredential key=4 ref="comp" value= 
Object { type: "cloudcredential", __clone: true, metadata: {…}, _name: "", annotations: {…}, amazonec2credentialConfig: {}, _type: "provisioning.cattle.io/cloud-credential", … }
  ... > 
  at <AsyncComponentWrapper key=4 ref="comp" value= 
Object { type: "cloudcredential", __clone: true, metadata: {…}, _name: "", annotations: {…}, amazonec2credentialConfig: {}, _type: "provisioning.cattle.io/cloud-credential", … }
  ... > 
  at <Index resource-override="cloudcredential" parent-route-override="c-cluster-manager-cloudCredential" class="outlet" > 
  at <CloudCredentialCreate class="outlet" onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< 
Proxy { <target>: {…}, <handler>: {…} }
 > > 
  at <RouterView key="/c/_/manager/cloudCredential/create" class="outlet" > 
  at <Default onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< 
Proxy { <target>: {…}, <handler>: {…} }
 > > 
  at <RouterView> 
  at <App>
``

This can be resolved via `toRaw` or `shallowRef` when assigning a value to `cloudComponent`.

**Review by rak-phillip — CHANGES_REQUESTED** [review]
LGTM - this behaves much more reliably than before. We just need to resolve the new warning as a result of storing components in data.

File: shell/edit/cloudcredential.vue (hunk 3 above)
Comment (codyrancher) [reply shell/edit/cloudcredential.vue]: I should've caught that. I was just looking at another instance of this last week.
