### PR TITLE
fix form fields missing label associations

### LINKED ISSUE #12804: a11y: Form fields are missing label associations
a11y Issue: 58

The form fields below do not have labels explicitly associated to them. The "for" attribute is missing in labels of the form fields resulting in screen reader users unable to understand the purpose of the form field.

Login 
- Username input field
- Password input field

Change Password 
- Current Password input field
- New Password input field
- Confirm Password input field

Create API Key
- Description input field

Cluster Appearance
- Icon Text 
- Custom comment 

Pod Security Admission: Create
- Name input field
- Description input field

Repository: Create
- Name input field
- Description input field
- Index URL (available after selecting "http(s) URL to an index generated by Helm" radio button)
- Git Repo URL (available after selecting "Git repository containing Helm chart or cluster template definitions" radio button)
- OCI Repository Host URL (available after selecting "OCI Repository Experimental" radio button)
- Min Wait Time (in Seconds), Max Wait Time (in Seconds) and Max Number of Retries  spin input fields (available after selecting "OCI Repository Experimental" radio button)

Git Repo - Add Repository
- Name input field
- Description input field
- Repository URL input field
- Branch Name input field
- Service Account Name and Target Namespace input fields (which gets available on activating "Next" button)

User: Create
- Username input field
- Display name input field
- Description input field
- New password input field
- Confirm password input field

Users Retention Settings
- Inactivity period, User retention process schedule and Default last login (ms) input fields input fields (available on activating Disable user accounts after an inactivity period (duration since last login) and Delete user accounts after an inactivity period (duration since last login) checkboxes)

Import Extension Catalog
- Catalog Image Reference

Banners
- Accept button text
-  text to display

Branding
- Private Label input field 

**Example:**

image

**Remediation:**

Use ‘for’ and ‘id’ attributes to associate labels with their respective form fields. Ensure that the value of ‘for’ attribute of the label exactly matches the value of ‘id’ attribute of the form field.

### PR DESCRIPTION
**Pull request by aalves08**
### Summary
Fixes #12804 

### Occurred changes and/or fixed issues

- fix form fields missing label associations

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: pkg/rancher-components/src/components/Form/LabeledInput/LabeledInput.vue [hunk 1]
```diff
@@ -330,7 +331,10 @@ export default defineComponent({
     }"
   >
     <slot name="label">
-      <label v-if="hasLabel">
+      <label
+        v-if="hasLabel"
+        :for="labelForIdentifier"
```
Comment (rak-phillip) [inline pkg/rancher-components/src/components/Form/LabeledInput/LabeledInput.vue:336]: If an id is provided for labeled input, then the `for` identifier will not match the provided id.

File: pkg/rancher-components/src/components/Form/LabeledInput/LabeledInput.vue [hunk 2]
```diff
@@ -137,8 +137,9 @@ export default defineComponent({
 
   data() {
     return {
-      updated:          false,
-      validationErrors: '',
+      updated:            false,
+      validationErrors:   '',
+      labelForIdentifier: `labeled-input-for-id-${ generateRandomAlphaString(12) }`
```
Comment (rak-phillip) [inline pkg/rancher-components/src/components/Form/LabeledInput/LabeledInput.vue:142]: nitpick: we could probably drop name this `inputId` to reduce how verbose the identifier is:

```suggestion
      inputId: `input-${ generateRandomAlphaString(12) }`
```

File: pkg/rancher-components/src/components/Form/LabeledInput/LabeledInput.vue (hunk 1 above)
Comment (rak-phillip) [reply pkg/rancher-components/src/components/Form/LabeledInput/LabeledInput.vue:336]: We can check if `id` has been provided as an attribute on the `mounted()` hook; use that to update the data prop that makes the `for` connection:

```js
  mounted() {
    const { id = null } = this.$attrs;

    if (id) {
      this.inputId = id;
    }
  },
```

File: pkg/rancher-components/src/components/Form/LabeledInput/LabeledInput.vue [hunk 3]
```diff
@@ -349,6 +353,7 @@ export default defineComponent({
     <slot name="field">
       <TextAreaAutoGrow
         v-if="type === 'multiline' || type === 'multiline-password'"
+        :id="hasLabel ? labelForIdentifier : ''"
```
Comment (rak-phillip) [inline pkg/rancher-components/src/components/Form/LabeledInput/LabeledInput.vue:356]: Each instance of `labelForIdentifier` needs to be replaced if we're going to use `inputId` for the data prop.

File: pkg/rancher-components/src/components/Form/LabeledInput/LabeledInput.vue (hunk 1 above)
Comment (aalves08) [reply pkg/rancher-components/src/components/Form/LabeledInput/LabeledInput.vue]: That's a great idea! So simple... 🤦  Implemented

I also noticed that `labelForIdentifier` wasn't connected to anything 🤷 🤷 🤷  🤦 

Everything corrected and up for review. Thank you very much for your review mate... 🙇

File: pkg/rancher-components/src/components/Form/LabeledInput/LabeledInput.vue (hunk 3 above)
Comment (aalves08) [reply pkg/rancher-components/src/components/Form/LabeledInput/LabeledInput.vue]: fixed

**Review by rak-phillip — APPROVED** [review]
LGTM
