### PR TITLE
fix issue with squashed custom box in Checkbox

### LINKED ISSUE #10000: When installing the Windows GMSA chart, the two `Credential Spec` buttons are not sized the same
**Setup**
- Rancher version: `v2.7.7`
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**

When installing the `Windows gMSA` chart in a downstream RKE2 custom cluster, you see the following screen right before installation:

image

The second button, when compared to the first, looks condensed and odd. It should be an exact match to the first button for consistency.

**To Reproduce**

1. As a standard user, provision a downstream RKE2 custom cluster (I had 3 etcd, 1 cp, 2 Linux workers, 4 Windows workers).
2. Navigate to cluster explorer > cluster > Apps > Repositories.
3. Add the `https://github.com/rancher/Rancher-Plugin-gMSA` repo with the `main` branch.
4. Attempt to install the `Windows gMSA` branch; note that the buttons do not match at the end of chart installation.

**Result**
The buttons mismatch prior to installing the `Windows GMSA` chart.

**Expected Result**

The buttons should not mismatch prior to installing the `Windows GMSA` chart.

### PR DESCRIPTION
**Pull request by aalves08**
fix issue with squashed custom box in Checkbox + add tests + sneaky fix for prop as computed

### Summary
Fixes #10000 

### Occurred changes and/or fixed issues

- fix issue with squashed custom box in Checkbox 
- add tests 
- sneaky fix for prop as computed

### Areas or cases that should be tested

- Follow repro steps in #10000 and make sure box is not squashed and is always 14px x 14px

### Screenshot/Video

Screenshot 2024-02-15 at 09 38 01

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: pkg/rancher-components/src/components/Form/Checkbox/Checkbox.vue [hunk 1]
```diff
@@ -319,12 +319,13 @@ $fontColor: var(--input-label);
   }
 
  .checkbox-custom {
-    height: 14px;
-    width: 14px;
+    height: 14px !important;
```
Comment (nwmac) [inline pkg/rancher-components/src/components/Form/Checkbox/Checkbox.vue:322]: Do we have to use `!important` ? This is generally bad practice

Comment (aalves08) [reply pkg/rancher-components/src/components/Form/Checkbox/Checkbox.vue:322]: I caught a breakpoint (shrink window) where the box was 13x13px somehow... I just enforced it by doing the `!important` so that it never breaks it's form.

Comment (aalves08) [reply pkg/rancher-components/src/components/Form/Checkbox/Checkbox.vue]: Can't repro it... Spent 10min scaling the window again and again... Removed the `!important`

**Review by eva-vashkevich — COMMENTED** [review]
Thank you

**Review by nwmac — APPROVED** [review]
