### PR TITLE
Hide filtered items in KeyValue

### LINKED ISSUE #13470: Cannot remove annotations on imported or local k3s and rke2 clusters
**Setup**
- Rancher version: `head` (2.11)
- Rancher UI Extensions:
- Browser type & version: Firefox 135.0.1
Image

**Describe the bug**

Cannot remove annotations after adding them on imported k3s and rke2 clusters.

Found when testing https://github.com/rancher/dashboard/issues/9476

**To Reproduce**

Can be reproduced with either local cluster or an imported cluster. Steps for local cluster:
1. Setup rancher on k3s or rke2
2. Edit local cluster config
3. Add an annotation with a key and value
4. Try to remove the annotation using the "Remove" button on the right, either before or after saving

**Result**
Cannot remove the annotation.

Note that there is a workaround by removing the text inside of the annotation, then clicking the remove button.

**Expected Result**

Annotation should be removed without having to clear the text first.

**Screenshots**

https://github.com/user-attachments/assets/4e77dde5-5d0a-4340-ad59-486657ccbddd

**Additional context**

If there are multiple "empty" annotations, then clicking one remove button will remove all of them. This is a separate issue, and I do not view that bit as a bug personally. I am calling it out here because it can feel a bit weird and lead to a degraded UX -- for example, if I know I want to add 5 annotations, then accidentally click the button 6 times, then try to remove one empty field, it will remove all of them and I'll have to click the button 5 times on my second attempt.

Note that in frustration, when I clicked 4 or 5 times in quick succession on the Remove button, I was able to remove an annotation.

### PR DESCRIPTION
**Pull request by momesgin**
### Summary
Fixes #13470 , #13471 

### Technical notes summary

The filtering toggle in `KeyValue.vue` has never worked properly. There were two sources of truth in there, first `filteredRows` which was filtering items that are a system label, passed as `protectedKeys` prop, and the second was `this.rows` which includes the whole items. When rendering, the component was using `filteredRows` but when adding or removing items, `this.rows` was being mutated by using the index of items in `filteredRows`.

You can see this issue by going to Explorer => Projects/Namespaces => Edit Config => Check Pod Security Admission Tab => enable any of the items there => Check Labels & Annotations Tab => Add a label using "Z" for its key and label => Try to Remove

Because there's no unique property in a label to rely on, you need to either create a temporary local id/index to track, or hide the filtered items without removing them from the list. I implemented the hiding approach since this component has many functionalities relied on the index which makes it tricky to update all the places, specially when it supports both arrays and objects, and also it's been vastly used throughout the app that makes it hard to test for the possible regressions. I've tested the performance of the component with 1000 items and didn't notice any slowness, though it's not the most accurate testing.

### Areas or cases that should be tested

What's been mentioned on the issues, and also the case mentioned above
### Screenshot/Video

https://github.com/user-attachments/assets/14dae5b7-3458-4485-a442-5314f1707d97

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: shell/components/form/KeyValue.vue [hunk 1]
```diff
@@ -665,11 +659,14 @@ export default {
...
       <template
-        v-for="(row,i) in filteredRows"
+        v-for="(row,i) in rows"
         v-else
         :key="i"
       >
-        <div class="rowgroup">
+        <div
+          class="rowgroup"
+          :class="{'hidden': isProtected(row.key) && !toggleFilter}"
```
Comment (codyrancher) [inline shell/components/form/KeyValue.vue:668]: We could replace the `hidden` class with the `hide` class. I figure we might as well use the global style since it exists.

https://github.com/rancher/dashboard/blob/master/shell/assets/styles/base/_helpers.scss#L134

**Review by codyrancher — CHANGES_REQUESTED** [review]
Other than the class it lgtm

**Comment by richard-cox** [comment]
Would this obsolete https://github.com/rancher/dashboard/pull/11125, and solve it's issue https://github.com/rancher/dashboard/issues/11115?

**Comment by momesgin** [comment]
> Would this obsolete #11125, and solve it's issue #11115?

@richard-cox no, different components(`Rule.vue` and `RulePath.vue`) are used there, not `KeyValue.vue`

**Review by codyrancher — APPROVED** [review]
