### PR TITLE
Charts/Apps sorting and header items

### LINKED ISSUE #14246: [Apps & Marketplace] - Search Bar
**Screenshot**

Image

### LINKED ISSUE #14247: [Apps & Marketplace] - Sorting dropdown and the total number of apps
- Sorting dropdown
- Display the total number of apps
- Display "Clear All Filters" when a filter is applied

**Screenshot**

Image

### LINKED ISSUE #14248: [Apps & Marketplace] - Empty State
**Screenshot**

Image

### LINKED ISSUE #14572: Fleet: Dashboard: Ellipsis and warning icons are pushed outside the card container
**Setup**
- Rancher version: v2.12
- Rancher UI Extensions:
- Browser type & version: Any

**Describe the bug**
In the Dashboard, when a GitRepo or HelmOp AppBundle has a long name, the ellipsis menu and warning icon are pushed outside the card container.

**To Reproduce**

1. Go to Fleet > Dashboard
2. Create a GitRepo or HelmOp AppBundle with a long name (e.g., test-tar-default-workspace)
3. View the item in the Fleet Dashboard page

**Result**
The warning icon and ellipsis menu are pushed outside the visible card container.

**Expected Result**
Warning icon and ellipsis menu should remain within the bounds of the card container.

**Screenshots**

Image

**Additional context**

### PR DESCRIPTION
**Pull request by momesgin**
### Summary
Fixes #14246 
Fixes #14247
Fixes #14572 
Fixes #14248 

### Occurred changes and/or fixed issues

- Message for total number of the charts
- Reset all filters
- Sorting dropdown
- Updated refresh all repos button

### Screenshot/Video

image

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes
- [x] The PR has been reviewed in terms of Accessibility

### CODE REVIEW

File: shell/store/catalog.js [hunk 1]
```diff
@@ -536,6 +536,7 @@ function addChart(ctx, map, chart, repo) {
       chartNameDisplay: chart.annotations?.[CATALOG_ANNOTATIONS.DISPLAY_NAME] || chart.name,
       chartDescription: chart.description,
       featured:         chart.annotations?.[CATALOG_ANNOTATIONS.FEATURED],
+      featuredNumber:   chart.annotations?.[CATALOG_ANNOTATIONS.FEATURED] ? Number(chart.annotations?.[CATALOG_ANNOTATIONS.FEATURED]) : Number.MAX_SAFE_INTEGER,
```
Comment (richard-cox) [inline shell/store/catalog.js]:
```suggestion
      featuredIndex:   chart.annotations?.[CATALOG_ANNOTATIONS.FEATURED] ? Number(chart.annotations?.[CATALOG_ANNOTATIONS.FEATURED]) : Number.MAX_SAFE_INTEGER,
```
`featuredIndex` would give more understanding of what this represents. i might have suggested featuredNumber, if so apologies for churn

File: shell/store/catalog.js [hunk 2]
```diff
@@ -565,6 +566,12 @@ function addChart(ctx, map, chart, repo) {
   }
 
   obj.versions.push(chart);
+
+  if (obj.durationSinceRelease) {
```
Comment (richard-cox) [inline shell/store/catalog.js]: this could be simpler expressed as just `if (!obj... --> obj.dur =` and also avoids possible future bugs if other functionality is added below

File: shell/store/catalog.js [hunk 3]
```diff
@@ -700,5 +708,17 @@ export function filterAndArrangeCharts(charts, {
     return true;
   });
 
+  if (sort === 'featured') {
```
Comment (richard-cox) [inline shell/store/catalog.js]: `featured` --> `recommended` (since we're also prioritising certified repos)

File: shell/pages/c/_cluster/apps/charts/index.vue [hunk 4]
```diff
@@ -262,6 +270,18 @@ export default {
 
     clusterId() {
       return this.$store.getters['clusterId'];
+    },
+
+    noFiltersApplied() {
+      return Object.values(this.internalFilters).every((arr) => arr.length === 0) && !this.searchQuery;
+    },
+
+    totalMessage() {
```
Comment (richard-cox) [inline shell/pages/c/_cluster/apps/charts/index.vue:282]: this will update before the results of the filter are shown

- no filter - `253 charts in total`
- click on a filter - `253 charts matching your criteria.`
- list updated - `21 charts matching your criteria.`

the number should be aligned with what we're showing. i'm guessing this is rendering lag

File: shell/pages/c/_cluster/apps/charts/index.vue [hunk 5]
```diff
@@ -57,20 +67,11 @@ export default {
...
-      },
-      internalFilters: { // in order to update the filter checkboxes smoothly
-        repos:      [],
-        categories: [],
-        statuses:   [],
-        tags:       []
-      },
-      installedApps: [],
-      statusOptions: [
+      filters:              createInitialFilters(),
```
Comment (richard-cox) [inline shell/pages/c/_cluster/apps/charts/index.vue:70]: we initialise filters and internalFilters with two different instances of a filter object, however in `resetAllFilters` we create one instance and that reference is set to both. feels like the latter should also have separate objects as well?

File: shell/pages/c/_cluster/apps/charts/index.vue [hunk 6]
```diff
@@ -100,7 +101,13 @@ export default {
           }
         }
       ],
-      appCardsCache: {},
+      appCardsCache:      {},
+      selectedSortOption: 'featured',
+      sortOptions:        [
+        { value: 'featured', label: this.t('catalog.charts.sortBy.recommended') },
```
Comment (richard-cox) [inline shell/pages/c/_cluster/apps/charts/index.vue]: think these values are used often enough (repeatedly in here and referenced also in the catalog store) to be an enum somewhere (probably in shell/types)

**Review by richard-cox — CHANGES_REQUESTED** [review]
- UX: We don't have a way to flip the order of the sort. For example if i wanted to find charts beginning with `y` i'd need to scroll pass them all. This is not too bad at the moment, but if we bring in pagination it will be important (user would need to page through to get to last page)
  - At window width of 1920 rows now only contain two cards, should they contain 3?
  - General page issues. If there’s no catch all dashboard issue for this page i’ll create a new issue
    - `+ Add new` link opens in new window instead of the current one
    - `noCharts: 'There are no charts available, have you added any repos or set filters?'` we should know if there are any repos or filters are show a customised message
    - `tooltip: Experimental - using this filter is not yet 100% accurate. Proceed with caution.`
      - i don't think we can ever get to a point where installed or upgradable filters are 100% accurate. This one needs tweaking.
      - Suggestion
        - Experimental - Charts installed outside of Rancher may not be accurately filtered

**Comment by momesgin** [comment]
> UX: We don't have a way to flip the order of the sort.

I agree, it would be nice to have the option for the opposite sort orders, it can be easy to do if we just rely on one sorting factor, for example for alphabetical order(`chartNameDisplay`):

```
  if (sort === 'name-ascending') { // our current sorting
    return sortBy(out, ['chartNameDisplay', 'featuredNumber', 'certifiedSort', 'repoName']);
  }
  
  if (sort === 'name-descending') {
    return sortBy(out, ['chartNameDisplay'], true);
  }
```

> * At window width of 1920 rows now only contain two cards, should they contain 3?

It's because of the minimum width of `420px`, changing it to `410px` can solve the problem, here's how the cards would look like in their minimum width:


image



>   * `+ Add new` link opens in new window instead of the current one

It's by design, I personally prefer new tab though

>   * `tooltip: Experimental - using this filter is not yet 100% accurate. Proceed with caution.`
>     
>     * i don't think we can ever get to a point where installed or upgradable filters are 100% accurate. This one needs tweaking.
>     * Suggestion
>       
>       * Experimental - Charts installed outside of Rancher may not be accurately filtered

I also received feedback from Neil when I demoed the page to him, he suggested these:

`Installation status can not be determined with 100% accuracy`
`Upgradeable status can not be determined with 100% accuracy`

>   * `noCharts: 'There are no charts available, have you added any repos or set filters?'` we should know if there are any repos or filters are show a customised message

@oboc-sts your thoughts on all the above points?

btw we have a separate issue for the empty state, and I've almost finished the work for it.

File: shell/store/catalog.js (hunk 1 above)
Comment (momesgin) [reply shell/store/catalog.js]: no worries at all, done

File: shell/store/catalog.js (hunk 2 above)
Comment (momesgin) [reply shell/store/catalog.js]: good point, thanks. Done

**Comment by oboc-sts** [comment]
@momesgin my replies below - I hope I haven't missed anything.

**Sorting**:
The initial specs mention the following sorting criteria:
- "Recommended" - default option, places the "featured" charts first;
- "Last updated" -  most recently updated charts first;
- "Chart name" - alphabetically, A → Z.

I agree we might need to consider a reverse alphabetical order.
Let's change the last criteria to "Chart name, A → Z" and add another criteria to the list: "Chart name, Z → A".

The complete list of sorting criteria will now look like this:
- "Recommended" - default option, places the "featured" charts first;
- "Last updated" -  most recently updated charts first;
- "Chart name,  A → Z" - alphabetical order, A → Z;
- "Chart name,  Z → A" - reverse alphabetical order, Z → A.

**Cards min-width**
By design, they should've fit 3 in a row for that resolution. The implementation might differ though. Anyway, I see it looks ok with 410. We can even try 400px and see how it goes.

**Add new**
I don't usually like forcing a particular behaviour on the user but, in this case, the "open in new tab" behaviour was intended to prevent the user from loosing his filters, sorting and whatever else he might have set on the chart catalogue by switching to a new page, especially when the 2 pages are tightly correlated - you add a new repo and you want to refresh the catalogue to see the new charts in. 

At least this ^ was the initial thought behind the decision. Now I'm having second thoughts :) I mean, if you really care about preserving your current state of the catalogue, you'd open that link in a new tab yourself.

I think the answer to this question will also provide us with the answer to this dilemma:  if I click the back button of the browser after hitting the "add new" link, am I being taken to the catalogue page in the state that I left it in or in its initial state (no filters, no search, default sorting)? If the answer is the latter option, we have to go with the new tab. Otherwise, keep the target in the same tab.

The point I'm trying to make is this: are we, as a system, forgiving enough and allow the user to make mistakes and recover from them or not? If not... then we have to try and prevent these mistakes from taking place.

**Empty state**
The empty state @richard-cox was mentioning is the old one. I don't believe we have these issues with the new empty state.

**Experimental tooltips**
@richard-cox 's suggestion looks better indeed. Let's go with it: "Experimental - Charts installed outside of Rancher may not be accurately filtered"

**Comment by richard-cox** [comment]
**Sorting**

> "Recommended" - default option, places the "featured" charts first;
> "Last updated" - most recently updated charts first;
> "Chart name, A → Z" - alphabetical order, A → Z;
> "Chart name, Z → A" - reverse alphabetical order, Z → A.

This is the way.

**Cards min-width**

> By design, they should've fit 3 in a row for that resolution. The implementation might differ though. Anyway, I see it looks ok with 410. We can even try 400px and see how it goes.

This is also the way.

**Add new**

If we started afresh i think i would be in favour of a new tab, but atm i think the only button clicks that take users away from the current tab are for external sites. So doing this by default is a bit jarring.

> if I click the back button of the browser after hitting the "add new" link, am I being taken to the catalogue page in the state that I left it in or in its initial state (no filters, no search, default sorting)

It should load the same url which now has all the filter params and they should be applied. @momesgin can you confirm?

The click should be based on an anchor, so users have the option to 'open in new tab' (something i wish we had everywhere). @momesgin can you also confirm? 

If both above is true we should then be alright to default to current tab

**Empty state**
Different issue, gotcha

**Experimental tooltips**
Neil's trumped me on this

```
Installation status can not be determined with 100% accuracy
Upgradeable status can not be determined with 100% accuracy
```

**Comment by oboc-sts** [comment]
@richard-cox I feel Neil's suggestions, whilst accurate, are a bit too vague. We can go with his suggestions or yours, but between the 2, I'd choose yours.

As for the new tab - totally agree. Let's wait for @momesgin 's confirmations.

**Comment by momesgin** [comment]
@richard-cox all the comments should be addressed now, sorry for the delay

btw I also merged my changes for the empty state

File: shell/config/types.js [hunk 7]
```diff
@@ -134,6 +134,14 @@ export const CATALOG = {
   REPO:         'catalog.cattle.io.repo',
 };
 
+// Charts/Apps
+export const SORT_OPTIONS = {
```
Comment (richard-cox) [inline shell/config/types.js]:
```suggestion
export const CATALOG_SORT_OPTIONS = {
```

File: shell/assets/translations/en-us.yaml [hunk 8]
```diff
@@ -1059,15 +1058,19 @@ catalog:
...
     versionWindowsIncompatible: Linux only version
     header: Charts
-    featuredCharts: Featured Charts
-    noCharts: 'There are no charts available, have you added any repos or set filters?'
+    noCharts:
+      title: No charts to show
+      messagePart1: <b>Tips:</b> undo the last filter you applied or
+      messagePart2: clear all filters
+      messagePart3: ', and ensure you have the right <a tabindex="0" href={repositoriesUrl} target="_blank" rel="noopener noreferrer nofollow">repositories</a> in place.'
+      messagePart4: 'Want to learn more about Helm Charts and Apps? Read our <a tabindex="0" href="{docsBase}/how-to-guides/new-user-guides/helm-charts-in-rancher" target="_blank" class="secondary-text-link">documentation <i class="icon icon-external-link"></i></a>.'
```
Comment (richard-cox) [inline shell/assets/translations/en-us.yaml:1075]:
```suggestion
      messagePart4: 'Want to learn more about Helm Charts and Apps? Read our <a tabindex="0" href="{docsBase}/how-to-guides/new-user-guides/helm-charts-in-rancher" class="secondary-text-link">documentation <i class="icon icon-external-link"></i></a>.'
```

File: shell/assets/translations/en-us.yaml [hunk 9]
```diff
@@ -1059,15 +1058,19 @@ catalog:
     windowsIncompatible: Linux only
     versionWindowsIncompatible: Linux only version
     header: Charts
-    featuredCharts: Featured Charts
-    noCharts: 'There are no charts available, have you added any repos or set filters?'
+    noCharts:
+      title: No charts to show
+      messagePart1: <b>Tips:</b> undo the last filter you applied or
```
Comment (richard-cox) [inline shell/assets/translations/en-us.yaml:1072]: we need to avoid concatenating l10n sentences given grammar can be different

**Review by richard-cox — CHANGES_REQUESTED** [review]
- the linked issues in the description all need to be prefixed with `Fixes` for gh to automatically link them to the PR
- when this merges it needs to be via `Squash Merge`

### Performance
We might still have a problem here, but maybe we get it out and iterate.

Going from a refresh on the installed apps list to the charts page (with the bitnami repo + 254 total charts) it takes a couple of seconds to render the page. It looks like the majority of the cpu churn is simple related to taking the vue components and rendering them.

image

if we get feedback that this is too long we need to implement pagination to reduce the number of cards rendered

File: shell/assets/translations/en-us.yaml (hunk 8 above)
Comment (momesgin) [reply shell/assets/translations/en-us.yaml:1075]: you sure about this? I think all our doc links open in a new tab

Comment (richard-cox) [reply shell/assets/translations/en-us.yaml:1075]: ah, sorry, it's the repo link above

File: shell/assets/translations/en-us.yaml (hunk 9 above)
Comment (momesgin) [reply shell/assets/translations/en-us.yaml:1072]: I started a conversation earlier on our slack channel about this. We need a click event listener on "clear all filters" part of the translation, and we can't simply assign event handlers with the current translation implementation. Also if we just use a url for resetting filters(e.g. `/c/local/apps/charts`) the page will be refreshed which is a bad ux. I've created [an issue](https://github.com/rancher/dashboard/issues/14532) to add the support for these cases in our translations.

File: shell/assets/translations/en-us.yaml (hunk 8 above)
Comment (momesgin) [reply shell/assets/translations/en-us.yaml:1075]: no worries, my bad, I forgot about the repo link case

File: shell/assets/translations/en-us.yaml (hunk 9 above)
Comment (richard-cox) [reply shell/assets/translations/en-us.yaml:1072]: think we need a simpler solution of just supporting router-link. i had a go and it gets into the dom but no functionality. comment added to issue

File: cypress/e2e/tests/pages/explorer2/workloads/pods.spec.ts [hunk 10]
```diff
@@ -424,6 +424,7 @@ describe('Pods', { testIsolation: 'off', tags: ['@explorer2', '@adminUser'] }, (
 
     // testing https://github.com/rancher/dashboard/issues/14071
     it('should remove the correct environment variable from the workload form', () => {
+      cy.viewport(1280, 720);
```
Comment (richard-cox) [inline cypress/e2e/tests/pages/explorer2/workloads/pods.spec.ts:427]: this doesn't need to be here, but given date it can slip in

**Review by richard-cox — APPROVED** [review]
When this merges it needs to be via Squash Merge

File: cypress/e2e/tests/pages/explorer2/workloads/pods.spec.ts (hunk 10 above)
Comment (momesgin) [reply cypress/e2e/tests/pages/explorer2/workloads/pods.spec.ts:427]: this was added to fix an e2e test unrelated to my work(`workloads/pods`), I have an [open PR](https://github.com/rancher/dashboard/pull/14596) for setting the minimum viewport resolution in our e2e tests, once this gets merged I'll remove this part on that PR.
