### PR TITLE
SCC Offline registration status does not update on complete

### LINKED ISSUE #14813: SCC Offline registration status does not update on complete
# Description

After completing the offline registration process, the displayed value does not update.

## Context

In the online process the registration is handled in this way:
- Create namespace (if missing)
- Delete existing secret
- Create new secret
- Poll registration with a specific condition, till same hash of secret is found

For the offline process the secret is kept and just updated. Therefore the registration is kept as well, but with a status of `In Progress`. As consequence the polled logic is not working for this case, as the resource to compare to is the old registration and not the secret, the value is the condition state and not the label.

https://github.com/user-attachments/assets/89db02af-d062-4975-a474-65582680742d

### PR DESCRIPTION
**Pull request by cnotv**
### Summary
Fixes #14813

### Occurred changes and/or fixed issues

Fixed registration to be updated.

### Technical notes summary

- Added unit tests for offline registration
- Ensured secret to be loaded also in registering offline third step

### Screenshot/Video

https://github.com/user-attachments/assets/4a825d7e-7cb5-4084-8df8-a592381e91ca

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes
- [x] The PR has been reviewed in terms of Accessibility

### CODE REVIEW

File: pkg/rancher-prime/pages/registration.composable.ts [hunk 1]
```diff
@@ -312,7 +314,7 @@ export const usePrimeRegistration = (storeArg?: Store<any>) => {
     const isError = lastCondition.type === 'RegistrationActivated' && lastCondition.status === 'False';
     const isError2 = lastCondition.type === 'Failure' && lastCondition.status === 'True';
     const isCompleteOnline = mode === 'online' && lastCondition.type === 'Done' && lastCondition.status === 'True';
-    const isCompleteOffline = mode === 'offline' && lastCondition.type === 'OfflineActivationDone' && lastCondition.status === 'True';
+    const isCompleteOffline = mode === 'offline' && registration.status?.conditions.length > 3 && lastCondition.type === 'OfflineActivationDone' && lastCondition.status === 'True';
```
Comment (rak-phillip) [inline pkg/rancher-prime/pages/registration.composable.ts]: What is the significance of 3 in `registration.status?.conditions.length > 3`? This seems like a magic number to me.

Comment (cnotv) [reply pkg/rancher-prime/pages/registration.composable.ts]: I do not have another parameter to distinguish the registration status if not based on the amount of conditions already generated.
The only way to make it work is this number.

Comment (cnotv) [reply pkg/rancher-prime/pages/registration.composable.ts]: @mallardduck What do you think about this?

Comment (cnotv) [reply pkg/rancher-prime/pages/registration.composable.ts]: Nvm we could check the last condition to be `OfflineRequestReady`

Comment (mallardduck) [reply pkg/rancher-prime/pages/registration.composable.ts]: I did fix the bug you reported about the cert condition too. So now that would be the condition to check being true (along with other signals) to know it's completed.
