### PR TITLE
Automation preventdefault on press enter

### LINKED ISSUE #8817: Automation: Pressing Enter in textarea elements not working
Based on work done in https://github.com/rancher/dashboard/issues/8550, let's write an automated test to ensure the Enter works in text areas. @torchiaf can offer guidance.

To reproduce:
- Go to local -> Storage -> ConfigMaps
- Create a new ConfigMap
- Add a new entry in Data form
- Select value field and press Enter

Expected behaviour:
A new line is added to the value.

### PR DESCRIPTION
**Pull request by bisht-richa**
### Summary
Fixes #8817

Automation:  should prevent default events on keypress Enter if the `preventEnterSubmit` property is false

### CODE REVIEW

File: shell/components/CruResource.vue [hunk 1]
```diff
@@ -412,6 +412,7 @@ export default {
     </p>
     <form
       :is="(isView? 'div' : 'form')"
+      id="cru-form"
```
Comment (torchiaf) [inline shell/components/CruResource.vue:415]: Please, use instead `data-testid` to identify DOM elements for testing.

File: shell/components/__tests__/CruResource.test.ts [hunk 2]
```diff
@@ -66,4 +66,67 @@ describe('component: CruResource', () => {
...
+            'current_store/all':       jest.fn(),
+            'i18n/t':                  jest.fn(),
+            'i18n/exists':             jest.fn(),
+          }
+        },
+        $route:  { query: { AS: _YAML } },
+        $router: { applyQuery: jest.fn() },
+      }
+    });
+    const element = wrapper.find('#cru-form');
```
Comment (torchiaf) [inline shell/components/__tests__/CruResource.test.ts:93]: Change this after you define `data-testid` as attribute, see previous comment:
```
wrapper.find('[data-testid="cru-form"]');
```

**Review by torchiaf — CHANGES_REQUESTED** [review]
Just a small hint about using of `data-testid`, otherwise LG.

**Review by torchiaf — APPROVED** [review]
LGTM
