### PR TITLE
Re-enable vai support for side nav and home page cluster lists

### LINKED ISSUE #14493: SSP: Side Nav clusters lists do not update correctly
**Setup**
- Rancher version: v2.12.0 (dev of)

**Describe the bug**
- To Update

**To Reproduce**
- To Update

**Result**
- To Update

**Expected Result**
- To Update

### LINKED ISSUE #15569: SSP: Integrate SSP with cluster side bar
- The main applicable side bar contains two lists of clusters
  - Pinned
  - Unpinned
- Avoid fetching all resources of each type to support these lists by utilised server-side pagination requests
- This change came a while ago, however hit some bumps on the way
  - most recently https://github.com/rancher/dashboard/issues/14493, can be tested together with it
- This is a dedicated issue to ensure QA happens in the milestone that the feature is enabled for

Test cases 
All the below with vai on and off

- Clusters covering both pinned and unpinned never exceed 10
  - when there are more clusters we show the count at top and see all link at bottom
- Harvester clusters are not included
  - Empty/un-connected cluster is fine --> Virtualization --> Harvester Clusters --> Import Existing --> shouldn't show in side bar
- Local cluster is not included when setting is on
  - global settings --> settings --> `hide-local-cluster` enabled
- clusters can be pinned and unpinned
  - note - these won't automatically update in other tabs, which is also how it worked before
- Multi-tab reactivity via https://github.com/rancher/dashboard/pull/15262 `Areas or cases that should be tested`
  - ignore initial instructs to change code, not applicable given code changes associated with this issue

### PR DESCRIPTION
**Pull request by richard-cox**
### Summary
Fixes #14493
Fixes #15569

### Occurred changes and/or fixed issues
- ~Use vai cache for side nav and home page clusters lists~
  - Disabled given current lack of support for sorting by state, provider and kube version
- Fix issues related to automatic updates of resources that have multiple watchers/listeners 

#### State
- Pre-vai / traditional watch world
  - store 1:1 subscribe 1:1 one socket 1:M watches 1:1 resource
  - a single watch could be
    - all of a resource type
    - resource types in a namespace
    - resource types applicable to a labelSelector
    - one singe resource type
  - a single watch could also be of mode resource.changes (no resource.change containing data, only resource.changes on resource/s change)
- Pre-this PR - code
  - store 1:1 subscribe 1:1 one socket 1:M watches --> 0:1 resource + 0:M listeners (that piggy back on a resource watch and trigger something else in code)
  - as per above, however a watch can cover
    - naught or one single watch as before
    - AND / OR
    - naught or many listeners who follow the watch and trigger something else in code given the message type
- Pre-this PR - Issues
  - Troubled watches
    - the side nav has `mode=resource.changes` cluster watches
    - the home page has `mode=resource.changes` cluster watches
    - the cluster management list has _no mode_ cluster watch
  - so multiple watches on the same type can be running
  - issues occur when
    - some watches are incompatible with others and can cause the cache would become corrupted
      - watching all of resource + no mode set VS watching all of a resource + mode set
      - watching all of a resource for a SSP list VS watching a single resource outside of the page
    - code was added to deal with this, but was buggy
    - compatibility issues includes
      - cache would become corrupted (socket updates added to cache when the cache represented a single SSP page)
      - re-watching a resource after socket dies/stop happens would look at the cache for a revision and watch from there. that revision would be incompatible with the state of listeners

#### Core fixes
- no longer do crazy things up-front to unwatch incompatible watches, instead prevent edge cases where this becomes an issue
- when a socket restarts and the normal watch looks at it's own cache for a revision to watch from, let it. if there are listeners it's own resources could be out of date, so always trigger as 'change' to get latest.
- subscribe watch keys now include `mode`, allows for concurrent mode and no mode watches

#### Refactors
- Pull out the socket watch listener stuff into it's own file outside of the subscribe file
  - keeps it's own logic separate
  - tracks listeners and callbacks
  - tracks if a listener is associated with a normal watch (a watch kicked off by the vanilla watches, not a watch kicked off by a listener request)
- Remove sideNavCache
  - introduced to cache the clusters shown in the side nav such that when the user goes from one layout to another (and the side nav is re-rendered) there's no visual blip. now the do this via a singletone service within the same file. this also means we don't stop watching --> start watching when users transition between layouts

#### Alternatives Considered
1. shell/utils/pagination-wrapper.ts uses own shell/plugins/steve/subscribe.js instance
   - each wrapper would use it's own subscription instance, with own socket
   - no cross over, or incompatible watches
   - subscription handles stuff like reconnecting socket, reconnect watches, resyncing watches, etc
   - Issues
     - subscription is heavily mixed with the dashboard store. would need an abstraction layer (all store references in subscription)
    - this would create a lot more sockets + watches
2. shell/utils/pagination-wrapper.ts uses own shell/utils/socket.js
   - as per above, but avoids the massive abstraction layer
   - issues
     -  would need to handle reconnect watches, resyncing watches, etc
     - lots more sockets + watches
3. request we can make duplicate watches using a unique id
   - when watching we send a unique id, which means we can have duplicate watches on the same resource + mode + etc
   - it should be easy than to avoid conflicts given data in the id (side-nav-cluster:transient --> don't pollute state, just trigger listeners)
   - issues
     - not quite sure this would work, just pushing problem around (TBD)
4. on watch --> unwatch incompatible
   - no dangling, incompatible watches running
   - issues
     - initial approach, the code for this got real complicated real quick 

### Areas or cases that should be tested

in shell/plugins/steve/steve-pagination-utils.ts uncomment lines in PAGINATION_SETTINGS_STORE_DEFAULTS
```
          // { resource: CAPI.RANCHER_CLUSTER, context: ['home', 'side-bar'] },
          // { resource: MANAGEMENT.CLUSTER, context: ['side-bar'] },
```

- Tab 1 Switch between clusters --> Pods list. Tab 2 create new pod. Tab 1 should show new pod
- Tab 1 Switch between clusters --> Pods list --> Pod . Tab 2 kick off change to pod. Tab 1 should show changes
- Tab 1 Nav to home page and refresh. Tab 2 create a new custom cluster. Tab 1 should show new cluster in cluster list AND in side nav
- Tab 1 Nav to home page and refresh. Tab 2 delete a cluster. Tab 1 should not show cluster list OR in side nav
- Tab 1 Nav to home page and refresh --> nav to cluster management / clusters list. Tab 2 create new custom cluster. Tab 1 should show new cluster in list AND side nav
- Tab 1 Nav to home page and refresh --> nav to cluster management / clusters list / cluster. Tab 2 kick off change to cluster. Tab 1 should show changes
- Tab 1 Nav to cluster management / clusters list / cluster and refresh. Nav to clusters list. Tab 2 create new custom cluster. Tab 1 should show new cluster in list AND side nav
- Tab 1 Nav to cluster management / clusters list and refresh . Tab 2 create a custom cluster. Tab 1 should show cluster in list AND in side nav
- Tab 1 Nav to home page and refresh. Tab 2 create/edit the cluster badge of a cluster. Tab 1 should show change to cluster badge
- Tab 1 Nav to cluster management / clusters list and refresh . Tab 2 create/edit the cluster badge of a cluster. Tab 1 should show change to cluster badge

> !! Cluster pinned state does not cause the side nav cluster lists to re-ender, this is not a regression (state is held in `userpreferences`, which are not watchable)

### Areas which could experience regressions
- everything that relies on automatic updates to resources

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes
- [x] The PR has been reviewed in terms of Accessibility

### CODE REVIEW

File: shell/plugins/steve/resourceWatcher.js [hunk 1]
```diff
@@ -40,10 +40,10 @@ export const WATCH_STATUSES = {
  * Create a unique key for a specific resource watch's params
  */
 export const keyForSubscribe = ({
-  resourceType, type, namespace, id, selector
+  resourceType, type, namespace, id, selector, mode
```
Comment (richard-cox) [inline shell/plugins/steve/resourceWatcher.js:43]: subscribe watch keys now include `mode`, allows for concurrent mode and no mode watches

File: shell/components/nav/TopLevelMenu.helper.ts [hunk 2]
```diff
@@ -139,12 +139,6 @@ export abstract class BaseTopLevelMenuHelper {
     this.$store = $store;
 
     this.hasProvCluster = this.$store.getters[`management/schemaFor`](CAPI.RANCHER_CLUSTER);
-
-    // Reduce flicker when component is recreated on a different layout
-    const { clustersPinned = [], clustersOthers = [] } = this.$store.getters['sideNavCache'] || {};
```
Comment (richard-cox) [inline shell/components/nav/TopLevelMenu.helper.ts:144]: sideNavCache was introduced to cache the clusters shown in the side nav such that when the user goes from one layout to another (and the side nav is re-rendered) there's no visual blip. now the do this via a singletone service within the same file. this also means we don't stop watching --> start watching when users transition between layouts

File: shell/plugins/steve/subscribe.js [hunk 3]
```diff
@@ -560,10 +556,6 @@ const sharedActions = {
       return;
     }
 
-    if (!stop) {
-      dispatch('unwatchIncompatible', messageMeta);
```
Comment (richard-cox) [inline shell/plugins/steve/subscribe.js:566]: This was the root of a lot of problems. At first i expanded from just checking if the mode was different to doing all sorts of weird stuff with if there was a standard watch / listeners... then had to try to fold in the abort stuff from resource.start was well. Was a rabbit hole. Switched to a forgiving model that protected the cache at the point it needed to, primarily prevent resource.change data going to the store if it represents a page (see resource.change handler)

File: shell/components/nav/TopLevelMenu.helper.ts [hunk 4]
```diff
@@ -157,16 +151,12 @@ export abstract class BaseTopLevelMenuHelper {
       iconColor:       mgmtCluster.iconColor,
       isLocal:         mgmtCluster.isLocal,
       pinned:          mgmtCluster.pinned,
-      description:     provCluster?.description || mgmtCluster.description,
+      description:     provCluster?.description || mgmtCluster.description, // If description is the only thing we care about, don't bother watching...
```
Comment (richard-cox) [inline shell/components/nav/TopLevelMenu.helper.ts]: there's probably components that will use the prov cluster.

they need to look at helper cache and not store

File: shell/plugins/steve/index.js [hunk 5]
```diff
@@ -17,16 +19,22 @@ export function SteveFactory(namespace, baseUrl) {
     state() {
       return {
```
Comment (richard-cox) [inline shell/plugins/steve/index.js:20]: tech debt item, add raw to unwatchables

File: shell/plugins/steve/subscribe.js [hunk 6]
```diff
@@ -450,34 +435,34 @@ const sharedActions = {
...
-        callbacks: { }
-      };
-      listeners[event].push(listener);
-    }
+    const hasStandardWatch = ctx.getters.listenerManager.hasStandardWatch({ params });
 
-    if (!listener.callbacks[id]) {
-      listener.callbacks[id] = callback;
-      ctx.dispatch('watch', params);
+    if (!hasStandardWatch) {
```
Comment (richard-cox) [inline shell/plugins/steve/subscribe.js:463]: comment, nothing to piggy back on

**Comment by richard-cox** [comment]
re-run tests to check for flakyness

File: shell/plugins/subscribe-events.ts [hunk 7]
```diff
@@ -0,0 +1,211 @@
...
+        // no point setting a non-existent watch as not started
+        return;
+      }
+      watch = this.initialiseWatch({ params });
+    }
+
+    watch.hasStandardWatch = standardWatch;
+
+    // is watch empty, if so get rid of the entry
+    if (!watch.hasStandardWatch && watch.listeners.length === 0) {
```
Comment (richard-cox) [inline shell/plugins/subscribe-events.ts:110]: confirm

File: shell/plugins/steve/index.js (hunk 5 above)
Comment (richard-cox) [reply shell/plugins/steve/index.js:20]: https://github.com/rancher/dashboard/issues/15443

File: shell/plugins/subscribe-events.ts (hunk 7 above)
Comment (richard-cox) [reply shell/plugins/subscribe-events.ts:110]: updated method name to something more inline with others that work hasStandardWatch, and updated comment

File: shell/plugins/steve/subscribe.js (hunk 3 above)
Comment (richard-cox) [reply shell/plugins/steve/subscribe.js:566]: This is just a note, no changes required

File: shell/components/nav/TopLevelMenu.helper.ts (hunk 4 above)
Comment (richard-cox) [reply shell/components/nav/TopLevelMenu.helper.ts]: removed incorrect comment

File: shell/plugins/steve/subscribe.js (hunk 6 above)
Comment (richard-cox) [reply shell/plugins/steve/subscribe.js:463]: updated comments to be clearer

**Comment by richard-cox** [comment]
@nwmac I've made the updates following the review from a few weeks back (addressed comments from above). These were just comments (code) and i've renamed one function

**Review by nwmac — APPROVED** [review]

**Review by nwmac — APPROVED** [review]
