### PR TITLE
Custom login error messages - #5427

### LINKED ISSUE #5401: Add support for Custom Login Failed Message
Internal reference: SURE-4232

Add a new banner 'Login Failed Banner'.

When set, this should be shown on the login screen:

image

### PR DESCRIPTION
**Pull request by Shavindra**
### Summary

Fixes #5401 - Add support for Custom Login Failed Message 

### Technical notes summary
1. Updated the `pages/c/_cluster/settings/banners.vue` section to have extra 2 fields to disable / enable show custom login error message.
2. Created `components/form/NotificationSettings.vue` which include checkbox and input field.
3. Original error message still shown 
4. The `loginError` field is added to `ui-banners` field in the settings and new settings are saved in there.

### Areas or cases that should be tested
1. Navigate to Global settings > Brands > Scroll to bottom
5. Select the checkbox to show the message and type in the message in the text box below
6. Logout or open an incognito tag. Type in wrong user/password
    1. it should show the error message
7. Un check the checkbox > apply 
    1. Refresh the login page and try again. 
    2. It should not display the message
8. check the checkbox and remove the message (empty) > apply
    1. Refresh the login page and try again. 
    2. It should not display the message

https://user-images.githubusercontent.com/1387263/161841807-fdd1324b-24bc-4287-8a00-769d27e55c68.mov

### CODE REVIEW

File: pages/auth/login.vue [hunk 1]
```diff
@@ -149,9 +150,14 @@ export default {
       return this.err;
     },
 
+    errorToDisplay() {
+      return this.customLoginError?.showMessage && this.customLoginError?.message && this.errorMessage ? `${ this.customLoginError.message } \n ${ this.errorMessage }` : this.errorMessage ? this.errorMessage : '';
```
Comment (catherineluse) [inline pages/auth/login.vue:154]: I found this long ternary statement hard to read. To me it would be easier to understand if it was something like this:

```js
if (this.customLoginError?.showMessage && this.customLoginError?.message && this.errorMessage) {
  return `${ this.customLoginError.message } \n ${ this.errorMessage }`;
}

if (this.errorMessage) {
  return this.errorMessage;
}

return '';
```

File: pages/auth/login.vue [hunk 2]
```diff
@@ -160,6 +166,13 @@ export default {
     });
   },
 
+  async fetch() {
+    const { value } = await this.$store.dispatch('management/find', { type: MANAGEMENT.SETTING, id: SETTING.BANNERS });
+
+    console.log(value);
```
Comment (catherineluse) [inline pages/auth/login.vue:172]: should the console log be removed?

**Review by catherineluse — CHANGES_REQUESTED** [review]
When I tested the PR locally, I saw that the custom error was still showing even when the checkbox for the setting was unchecked.
Screen Shot 2022-04-05 at 4 25 37 PM
Screen Shot 2022-04-05 at 4 25 05 PM

The error shouldn't show in that case. Should the text input be cleared when you uncheck the box?

File: pages/auth/login.vue (hunk 2 above)
Comment (catherineluse) [reply pages/auth/login.vue:172]: looks like drone is complaining about it

> /drone/src/pages/auth/login.vue
>   172:5  warning  Unexpected console statement  no-console
> 
> /drone/src/pages/c/_cluster/settings/notifications.vue
>   50:5  warning  The "BannerSettings" component has been registered but not used  vue/no-unused-components

File: assets/translations/en-us.yaml [hunk 3]
```diff
@@ -6522,7 +6523,13 @@ branding:
     tip: You can override the link color used throughout the UI with a custom color of your choice.
     useCustom: Use a Custom Link Color
     example: Link Example
-
+notifications:
+  header: Custom notifications
+  menuLabel: 'Custom Notifications'
+  loginError:
+    header: Custom error messages
```
Comment (catherineluse) [inline assets/translations/en-us.yaml:6530]: can this be capitalized? `Custom Error Messages`

**Review by catherineluse — APPROVED** [review]
LGTM
