### PR TITLE
[9614] Seccomp Profile added to POD and Container page of all Worklods | Pod Name Validation fixed

### LINKED ISSUE #9614: Create Pod from UI is missing seccompprofile settings
**Setup**
- Rancher version: 2.7.5
- Rancher UI Extensions: none
- Browser type & version: chrome

**Describe the bug**

Create Pod UI does not have option for specifing seccompprofile which is required with PSA.

### PR DESCRIPTION
**Pull request by marcelofukumoto**
### Summary
Fixes #9614

- Added Seccomp Profile to the POD (create/edit) and Container (create/edit) Security Context
  - It contains 4 options
    - None, RuntimeDefault, Localhost, Unconfined
    - Some ref: https://kubernetes.io/docs/reference/node/seccomp/
      - Localhost has a second Input called Localhost Profile which is the Path of the file used
      - The new input requires a value (validation)
        - Added the (!) showing error for the Tab and the Security Context on the lsit
  - As default for POD the option selected is RuntimeDefault
  - As default for Container the option select is None
  - Those options are added to all Workloads
  - Pods cannot edit it (error)
    - But other workloads, they can
- Fixed a validation for the NAME of the POD [BUG-9614-1]
  - The validation for the "Create" button to be enabled was not considering NAME
- Fixed a bug where the YAML file got the config lost if changes the security context [BUG-9614-2]
- Merged the Security from Pod and Container, adding a conditional if container or pod.
- Change accessibility only for security context
  - Added focus on list click
  - Added some new texts for label
  - Fieldset added to the page

### Occurred changes and/or fixed issues

https://github.com/rancher/dashboard/issues/9614
- pkg/rancher-components/src/components/Form/Checkbox/Checkbox.vue - [ACCESSIBILITY] Added some focus for Checkbox and styles as well
- pkg/rancher-components/src/components/LabeledTooltip/LabeledTooltip.vue - [ACCESSIBILITY] Added Tooltip text to the Tooltip
- shell/assets/styles/base/_typography.scss - [ACCESSIBILITY] Changed Typography to use H3 style for Legend, so we can use Fieldset
- shell/assets/translations/en-us.yaml - Added new texts for the SeccompProfile fields, Added texts for accessibility, title for capabilities
- shell/components/form/LabeledSelect.vue - [ACCESSIBILITY] Added for the Value to be added to accessibility
- shell/components/form/SeccompProfile.vue - New component create to be reused on the Pod and Container pages to represent the SeccompProfile option
- shell/components/form/Security.vue - Changed UI to accept container and pod changes, changed Yes/No Radio to Checkbox
-  shell/components/form/__tests__/LabeledSelect.test.ts - Test changed because of the label
- shell/components/form/__tests__/SeccompProfile.test.js - Added test for the new component
- shell/components/form/__tests__/Security.test.ts - Refactored to have more detailed tests
- shell/edit/workload/__tests__/index.test.ts - Removed podFsGroup, not using anymore on the new structure
- shell/edit/workload/index.vue - Security Context of the pod
- shell/edit/workload/mixins/workload.js - Logic of the workload, added validation logics for the new Seccomp fields
- shell/models/pod.js - Added the missing custom validation for the name on the pod model [BUG-9614-1]

### Technical notes summary

- The Update of the security context of the pod happens at the shell/edit/workload/mixins/workload.js for the podFsGroup. I could use the same place to update the changes on the SeccompProfile, but I decided to pass the podTemplateSpec directly to the Pod
- I made sure that the YAML file is not rewritten when changing security context for containers (pod seems ok) [BUG-9614-2]

### Areas or cases that should be tested

- All workloads CREATE for POD and CONTAINERS
- All workloads EDIT for POD and CONTAINER
- Test cases on the PDF 
[Issue 9614 - 2.pdf](https://github.com/user-attachments/files/23778091/Issue.9614.-.2.pdf)

### Areas which could experience regressions

- Create and Edit for POD and CONTAINER were edited
- Since there was many changes to the page structure, Security Context needs to be texted throughly

### Screenshot/Video

- Test results on the PDF
[Issue 9614 - 2.pdf](https://github.com/user-attachments/files/23778091/Issue.9614.-.2.pdf)
[Issue 9614 - 2 - UI Check.pdf](https://github.com/user-attachments/files/23778346/Issue.9614.-.2.-.UI.Check.pdf)

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes
- [x] The PR has been reviewed in terms of Accessibility
- [x] The PR has considered, and if applicable tested with, the three Global Roles `Admin`, `Standard User` and `User Base`

### CODE REVIEW

File: shell/edit/workload/mixins/workload.js [hunk 1]
```diff
@@ -276,23 +282,48 @@ export default {
...
-      podFsGroup:                 podTemplateSpec.securityContext?.fsGroup,
       savePvcHookName:            'savePvcHook',
       tabWeightMap:               TAB_WEIGHT_MAP,
-      fvFormRuleSets:             [],
-      fvReportedValidationPaths:  ['spec'],
-      isNamespaceNew:             false,
-      idKey:                      ID_KEY
+      fvFormRuleSets:             [{
+        path:           'podTemplateSpec.securityContext.seccompProfile.localhostProfile',
+        rules:          [''],
```
Comment (richard-cox) [inline shell/edit/workload/mixins/workload.js:291]: haven't dived into code, but if there's no rules isn't this a no-op?

File: shell/edit/workload/mixins/workload.js [hunk 2]
```diff
@@ -276,23 +282,48 @@ export default {
...
     ...mapGetters(['currentCluster']),
+    seccompProfileTypes() {
+      return [
+        {
+          value: 'None',
+          label: 'None'
+        },
+        {
+          value: 'RuntimeDefault',
+          label: 'RuntimeDefault - inherit the default seccomp profile'
```
Comment (richard-cox) [inline shell/edit/workload/mixins/workload.js]: this and the labels below need localising with `this.t('<path in localisation file>')`

File: shell/edit/workload/mixins/workload.js [hunk 3]
```diff
@@ -276,23 +282,48 @@ export default {
...
+          label: 'Localhost - define a custom seccomp profile'
+        }, {
+          value: 'Unconfined',
+          label: 'Unconfined - no seccomp profile'
+        }];
+    },
+
     tabErrors() {
-      return { general: this.fvGetPathErrors(['image'])?.length > 0 };
+      const tabErrors = { podSecurityContext: this.fvGetPathErrors(['podTemplateSpec.securityContext.seccompProfile.localhostProfile'])?.length > 0 };
```
Comment (richard-cox) [inline shell/edit/workload/mixins/workload.js:323]: how come the `image` has been removed (not needed?) and `localHostProfile` added? i would have though it's both or neither?

File: shell/edit/workload/mixins/workload.js (hunk 1 above)
Comment (richard-cox) [reply shell/edit/workload/mixins/workload.js:291]: i see where this is now loaded - 'podTemplateSpec.securityContext.seccompProfile.type' watcher.

That one sets the `fvFormRuleSets[0]` as the secompProfile one. Would be worth adding a comment here stating that it has to be in that first position in the array

File: shell/models/pod.js [hunk 4]
```diff
@@ -46,6 +46,20 @@ export default class Pod extends WorkloadService {
...
   }
 
+  get customValidationRules() {
+    const out = [
+      {
+        nullable:       false,
+        path:           'metadata.name',
+        required:       true,
+        translationKey: 'generic.name',
+        type:           'subDomain',
```
Comment (richard-cox) [inline shell/models/pod.js:56]: out of interest, what does this do / mean?

Comment (richard-cox) [inline shell/models/pod.js]: out of interest, what does this do / mean?

File: shell/components/form/Security.vue [hunk 5]
```diff
@@ -60,31 +62,43 @@ export default {
         return {};
       }
     },
-    mode: { type: String, default: 'edit' }
+    formType:            { type: String, default: 'container' },
+    mode:                { type: String, default: 'edit' },
```
Comment (richard-cox) [inline shell/components/form/Security.vue]:
```suggestion
    mode:                { type: String, default: _EDIT },
```

With `import { _EDIT } from '@shell/config/query-params';`

File: shell/components/form/Security.vue [hunk 6]
```diff
@@ -122,124 +149,201 @@ export default {
...
-            :label="t('workload.container.security.allowPrivilegeEscalation.label')"
-            :disabled="privileged"
-            :options="[false,true]"
-            :labels="[t('workload.container.security.allowPrivilegeEscalation.false'), t('workload.container.security.allowPrivilegeEscalation.true')]"
+        </fieldset>
+      </div>
+    </div>
+  </div>
+  <div
+    v-if="formType === 'container'"
```
Comment (richard-cox) [inline shell/components/form/Security.vue]: Think it's worth bringing `'container'` out as a `const` somewhere. 

There's 7 references in components and 8 in unit tests

We don't have the best pattern for locations for this kind of stuff, so i would say an `export` in this component.

File: shell/components/form/Security.vue [hunk 7]
```diff
@@ -122,124 +149,201 @@ export default {
...
+  >
+    <div
+      class="row"
+    >
+      <div class="col span-6">
+        <fieldset>
```
Comment (richard-cox) [inline shell/components/form/Security.vue:193]: I think @mantis-toboggan-md  is doing some work on the new form work which will be used an example for all new (and at some point existing) forms.

If we go with the fieldset + legend  pattern it would be good to also do it there. If we're not sure can you bring up in the next demo session?

File: shell/edit/workload/mixins/workload.js (hunk 3 above)
Comment (marcelofukumoto) [reply shell/edit/workload/mixins/workload.js:323]: It moved to the allContainers() at line 433.
Before the validation of the "image" was only applying to the "current" container showing, there was only ONE validation for it, and so it was bugged.
The correct is to apply the validation of the "image" for each container separately, so here it has been removed and added to the containers" validation.

File: shell/models/pod.js (hunk 4 above)
Comment (marcelofukumoto) [reply shell/models/pod.js:56]: This is the one that validates the NAME on the POD level of the pod.
same you can find on the shell/models/workload.js.
Since models/workload and models/pod are independent and both coming from WorkloadService. Than it is needed to add on both. It could be added directly on WorkloadService, but I thought would be better to only change on the models/pod for this issue.

**Comment by marcelofukumoto** [comment]
Changed applied as requested:
shell/assets/translations/en-us.yaml - Added localisation text
shell/components/form/Security.vue - Added _EDIT and new const FORM_TYPES created
shell/components/form/__tests__/Security.test.ts - Fixed test to use FORM_TYPES (this one since they are tests, I think would make sense to keep them as string
shell/edit/workload/index.vue - Changed to use FORM_TYPES
shell/edit/workload/mixins/workload.js - Added comments for the fvFormRulesets[0] to explain the details of implementation and changed the localisation

---

Merged master to fix conflict

File: shell/edit/workload/mixins/workload.js (hunk 1 above)
Comment (marcelofukumoto) [reply shell/edit/workload/mixins/workload.js:291]: Right, it was just to keep a default no "rules" and to fix the INDEX 0 as the position for the path. Added a comment to explain it better. I think maybe not the best solution but I used how it was implemented already. I think it should be on the models or somewhere else, but since it should have validation improvements, I thought was the safest bet.
Thank you for the comment! And fixed.

File: shell/edit/workload/mixins/workload.js (hunk 2 above)
Comment (marcelofukumoto) [reply shell/edit/workload/mixins/workload.js]: Right!! Thank you for noticing! Fixed.

File: shell/components/form/Security.vue (hunk 5 above)
Comment (marcelofukumoto) [reply shell/components/form/Security.vue]: Changed! Thank you for the suggestion!

File: shell/components/form/Security.vue (hunk 6 above)
Comment (marcelofukumoto) [reply shell/components/form/Security.vue]: Right. I added a FORM_TYPES on this file. Thanks for the suggestion!

File: shell/components/form/Security.vue (hunk 7 above)
Comment (marcelofukumoto) [reply shell/components/form/Security.vue:193]: That seems like a good idea to share about it and why we should use fieldset + legends.
Instead of demo session, maybe we can have a meeting between us(me, you and @mantis-toboggan-md) first and discuss about it. Than after we got agreement or direction we can share on the demo.

Comment (richard-cox) [reply shell/components/form/Security.vue:193]: Ok, we can shortcut and start a slack discussion in our team channel? I think it should be easy to get consensus there. Should be straight forward if Alex and myself are onboard

File: shell/models/pod.js (hunk 4 above)
Comment (richard-cox) [reply shell/models/pod.js:56]: ah, sorry, i mean specifically the `type: subDomain`. I had a better look through code and it might relate to the validator in shell/utils/validators/formRules/index.ts? It's a weird one to use, but given it's a copy from workload lets stick with it

File: shell/utils/validators/formRules/index.ts [hunk 8]
```diff
@@ -270,6 +270,8 @@ export default function(
 
   const containerImage: Validator = (val: any) => !val?.image ? t('workload.validation.containerImage', { name: val.name }) : undefined;
 
+  const localhostProfile: Validator = (val: any) => (val?.securityContext?.seccompProfile?.type === 'Localhost' && !val?.securityContext.seccompProfile?.localhostProfile && !val?.securityContext?.privileged) ? t('workload.validation.containerImage', { name: val.name }) : undefined;
```
Comment (richard-cox) [inline shell/utils/validators/formRules/index.ts]: another thing i missed, the translation points to the container image validation error rather than localHostProfile one

File: shell/edit/workload/mixins/workload.js (hunk 3 above)
Comment (richard-cox) [reply shell/edit/workload/mixins/workload.js:323]: Gotcha.

Missed this the first time around, generally we should avoid adding properties to the resource we will eventually save (that `container.error` object). Normally they would get persisted when the object is saved, but i think kube now sends a warning back. These are a bit different though

1. There's already an error object, so the issue exists already
1. The only way to produce the bug is to setup the form such that the errors exist --> edit as yaml --> save. This isn't something we would expect to happen often

Given above lets keep as is for the moment

Comment (richard-cox) [reply shell/edit/workload/mixins/workload.js:323]: image

There's the _init as well (not changed by this PR), which in theory i think we strip before sending. Not sure

File: shell/utils/validators/formRules/index.ts (hunk 8 above)
Comment (marcelofukumoto) [reply shell/utils/validators/formRules/index.ts]: Oh! Thank you for finding this. I tried to see how I missed the wrong message. But it seems this text is not used on the UI because the button is usually disabled so you can't really see the message. I could check debugging the error message.
Fixed!

File: shell/edit/workload/mixins/workload.js (hunk 3 above)
Comment (marcelofukumoto) [reply shell/edit/workload/mixins/workload.js:323]: Thanks! Interesting to know. I just followed the same way that the Container Image was being done.
So to use the "spec" to control the UI is never a good idea. I think that happens on the computed "allContainers" which means that if we just use an UI Helper for the errors instead of using the "spec" would fix this problem.

As you said, it is already an issue now. Let's discuss, would be great to have an "issue" to track this one. But I think with the form changes, maybe the logic will disappear as well.
