### PR TITLE
Fix for cronjobs can not be created

### LINKED ISSUE #5479: Cannot deploy a Cron Job workload
**On 2.6-head commit id: `c2d8e32`**
- Deploy a cronjob workload - cron - * * * * *
- Save changes made
- Error on UI: `Cannot read properties of undefined (reading '0')`
- Error in console

```
impl.js:182 CreateEditView mixin failed to save:  TypeError: Cannot read properties of undefined (reading '0')
    at f.saveWorkload (index.vue:581:1)
    at child-hook.js:37:34
    at d (runtime.js:45:40)
    at Generator._invoke (runtime.js:274:22)
    at Generator.O.forEach.t.<computed> [as next] (runtime.js:97:21)
    at r (asyncToGenerator.js:3:20)
    at l (asyncToGenerator.js:25:9)
```

### PR DESCRIPTION
**Pull request by nwmac**
Fixes #5479 

The NVIDIA GPU changes did not take into account workloads where the containers property is undefined.

### CODE REVIEW

File: edit/workload/index.vue [hunk 1]
```diff
@@ -578,30 +578,32 @@ export default {
...
-      if (nvidiaGpuLimit > 0) {
-        containerResources.requests = containerResources.requests || {};
-        containerResources.requests[GPU_KEY] = nvidiaGpuLimit;
-      }
-
-      if (!this.nvidiaIsValid(nvidiaGpuLimit) ) {
-        try {
-          delete containerResources.requests[GPU_KEY];
-          delete containerResources.limits[GPU_KEY];
+      if (template.spec.containers && template.spec.containers[0]) {
```
Comment (richard-cox) [inline edit/workload/index.vue:581]: This could just be `template.spec.containers?.[0]`, but it achieves the same result

**Review by richard-cox — APPROVED** [review]
