### PR TITLE
[FIX] Added error handling when driver activation fails

### LINKED ISSUE #9183: Node Driver page does not handle errors
SURE-9632

**Setup**
- Rancher version: v2.7 head
- Rancher UI Extensions: n/a
- Browser type & version: chrome 114

**Describe the bug**

When disabling/enabling a Node Driver if the API returns a 400/500 it does not display the error nor update the UI in anyway, which is confusing.

**To Reproduce**

Apply https://github.com/rancher/webhook/pull/250 to the webhook, then try and disable a node driver _after_ creating a cluster that uses one of the node drivers. Nothing will happen in the UI after clicking disable.

**Result**
Nothing happens when the request is denied.

**Expected Result**

A notification is shown with the error so the user knows what happened in the background when trying to disable/enable the driver. 

**Screenshots**

image

**Additional context**

path: `/dashboard/c/_/manager/pages/rke-drivers`

This was found when developing https://github.com/rancher/rancher/issues/41128, when adding the webhook which can deny an update on the `NodeDriver` resources

### PR DESCRIPTION
**Pull request by eva-vashkevich**
### Summary
Fixes #9183 

Added growls to activate requests

### Areas or cases that should be tested

For both node (not covered by E2E tests) and cluster drivers verify that if activate, deactivate, activate in bulk, and deactivate requests fail, appropriate error is displayed.

### Areas which could experience regressions

None

### Screenshot/Video

https://github.com/user-attachments/assets/a28142b3-9dc8-499a-a883-1531dcd213c5

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: shell/models/nodedriver.js [hunk 1]
```diff
@@ -78,19 +78,19 @@ export default class NodeDriver extends Driver {
 
   activate() {
     return this.$dispatch('rancher/request', {
-      url:    `v3/nodeDrivers/${ escape(this.id) }?action=activate`,
+      url:    `v3/nodeDrivers11/${ escape(this.id) }?action=activate`,
```
Comment (rak-phillip) [inline shell/models/nodedriver.js:81]: What is the meaning of `11` in the endpoint?

Comment (eva-vashkevich) [reply shell/models/nodedriver.js:81]: I've missed it, thank you for catching. this is how I was testing that error handling works...

**Review by rak-phillip — APPROVED** [review]
LGTM
