### PR TITLE
AKS: fix node labels and errors when saving the cluster fails immediately

### LINKED ISSUE #10952: [v2.9] AKS: Labels/Taints not visible for Nodepool
**Setup**
Rancher version: `v2.9-6d87a11ea46b7571646d7c3d7af704584c39fd62-head`
Browser type & version: Chrome latest

**Describe the bug**
AKS (Vue UI): Labels/Taints not visible for Nodepool 

**To Reproduce**
- Provision AKS cluster from Rancher UI
- For Nodepool, add labels/taints while provisioning
- Wait for Cluster to become Active

API payload sent:
```
    "nodePools": [
      {
        "availabilityZones": [
          "1",
          "2",
          "3"
        ],
        "count": 1,
        "enableAutoScaling": false,
        "maxPods": 110,
        "maxSurge": "1",
        "mode": "System",
        "name": "agentpool",
        "nodeLabels": {
          
        },
        "nodeTaints": [
          "k1=v1:PreferNoSchedule"
        ],
        "orchestratorVersion": "",
        "osDiskSizeGB": 128,
        "osDiskType": "Managed",
        "osType": "Linux",
        "vmSize": "Standard_DS2_v2",
        "labels": {
          "k2": "v2"
        }
      }
    ],
```

**Screenshots**
After cluster is provisioned:
image

**Expected Result**
Labels/Taints for Nodepool must be visible on UI

### LINKED ISSUE #11084: AKS - can't update some input fields if the save request fails
**Describe the bug**

**To Reproduce**
1. Attempt to provision an AKS cluster with a configuration that will fail (eg, try to re-use the name of an existing cluster)
2. After hitting save, attempt to change the cluster name.
**Result**
The cluster name input can't be edited: the input is immediately re-populated with the old value. The same appears to be true of the description and cluster resource group inputs. The node inputs also become disabled.

**Expected Result**
When creating a new AKS cluster, if the save action fails, the entire form should be editable. 

**Screenshots**
(in this video, I am mashing backspace)

https://github.com/rancher/dashboard/assets/42977925/00029ef1-f8b0-4427-83c0-2cbc5e85c8b0

**Additional context**

### PR DESCRIPTION
**Pull request by mantis-toboggan-md**
### Summary
Fixes #10952 
Fixes #11084 

### Occurred changes and/or fixed issues
This PR fixes an issue with node labels not being saved - the wrong key was used it should be `nodeLabels`, see `<rancher url>v3/schemas/aksNodePool`. This PR also corrects an issue with the form when saving throws an error ( see the issue for an example misconfiguration - many incorrect cluster configurations either throw inline form validation errors before saving or show up after saving when the user is taken back to the cluster list view)

### Technical notes summary
The problem in #11084 appears to be related to the before save hook removing ui-only fields from AKS node pools. With the `__validation` property missing, some form validators start throwing errors; this sends the whole form out of whack (eg cluster name no longer being editable. idk). I realized as well that the ui-only fields need to be preserved so that when editing a provisioned cluster to add new node pools, the UI keeps track of which pools are new and keeps all their input fields editable.

### Areas or cases that should be tested
1. Create a cluster with node labels defined and verify that they're saved
2. Edit the cluster; verify that the previously-configured labels are shown, and that labels can be added and removed.

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: pkg/aks/components/CruAks.vue [hunk 1]
```diff
@@ -983,17 +983,6 @@ export default defineComponent({
       }
     },
 
-    // these fields are used purely in UI, to track individual nodepool components
-    cleanPoolsForSave(): void {
```
Comment (momesgin) [inline pkg/aks/components/CruAks.vue:987]: if this is not needed anymore, I think we should be able to remove its usage here:
https://github.com/rancher/dashboard/blob/7c53e5fcc5b00e7aacdd4e1627f2e5a45a9ae815/pkg/aks/components/CruAks.vue#L302

Comment (mantis-toboggan-md) [reply pkg/aks/components/CruAks.vue:987]: You're right. Interesting that that didn't throw errors.

**Review by momesgin — APPROVED** [review]
lgtm
