### PR TITLE
Fix Legacy / Project group

### LINKED ISSUE #10595: Legacy/Project sub-nav is broken when you select a project
Enable the legacy feature flag.

Open the 'Legacy' side nav item:

image

Select a project in the filter at the top - the Nav collapses - if you expand if again, 'Project' is no longer shown :

image

It is supposed to show, along with the sub-nav for legacy projects.

This is a regression.

We should add test automation - these are embedded pages, but we should be able to check that the side navigation is correctly shown.

### PR DESCRIPTION
**Pull request by richard-cox**
### Summary
Fixes #10595

### Occurred changes and/or fixed issues
- fixed scenario exposed by the project virtual type where call to allTypes ruled out all virt / spoofed types if basic mode has an invalid entry (!groupForBasicType)
- however also removed the project virtual type. the nav item comes from `Project` group specified in `basicTypes` call)
- fixed a few things around the project group
  - add label for project group
  - explicitly set project group root of app
- fixed display of namespace icon for a menu item if there are no counts

Also
- fixed some TS errors in test
- fixed typos in tests

### Areas or cases that should be tested
- Contains e2e test that navigates to legacy --> project --> config maps

### Areas which could experience regressions
- virtual / spoof side nav menu items, like those in Global Settings

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: shell/components/nav/Type.vue [hunk 1]
```diff
@@ -179,9 +179,12 @@ export default {
         />
         <i
           v-if="namespaceIcon"
-          class="icon icon-namespace namespaced"
+          class="icon icon-namespace"
         />
-        {{ count }}
+        <span
+          v-if="showCount"
+          :class="{'namespaced': namespaceIcon}"
```
Comment (richard-cox) [inline shell/components/nav/Type.vue:186]: .namespaced should only show if both count and ns visible

**Review by nwmac — APPROVED** [review]
LGTM
