### PR TITLE
Handle resources that cannot be watched

### LINKED ISSUE #10668: Steve socket is spammed on fresh visit to node detail page
**Setup**
- Rancher version: v2.9-head

**Describe the bug**
- Rancher now returns a `resource.error` message when watching an individual resource over websocket
  - See https://github.com/rancher/rancher/issues/41809
  - Previously it failed to return an `resource.error` of `too old` which would result in socket spam
- That revealed a scenario where the ui itself caused the spamming
  - See https://github.com/rancher/dashboard/issues/10540
  - Handle the way we get revisions when watching
- That also revealed another bug, which this issue is about
  - The `resource.error` message is now returned when we try to watch a resource we should not
    - For instance the `metrics.k8s.io.nodemetrics` resource used in the node detail page
    - The `resource.error` though isn't one we let stick, so we just try to `resource.start` / watch again... which results in the same resource.error, repeat ad nauseam  
  - Impact
    - This happens on navigate to the node detail page, as opposed to only when refreshing on the detail page
    - The spam does not stop by going from the detail page to the list page. Going from the node detail page where we watch an individual node metric to the node list where we watch all node metrics should behave the same as things like pod ... but it doesn't. Pods will stop the individual watch and start a watch for all. 
    - This applies to all resources that we can't watch (no schema watch verb, about 8 out of 182 in a DS rke2 cluster)

**To Reproduce**
- Bring up a rancher instance at or newer than [793118](https://github.com/rancher/rancher/commit/793118fc730d915f06d0cd2593509b67273c34e6) (7th March)
- Ensure that the metrics server is running
  - keep things simple, test in local cluster
  - log in
  - go to `<rancher url>/v1/schemas/metrics.k8s.io.nodemetrics`
  - if this returns, great, you're set
     - if not enable / install metrics server, ensure the url above is reachable
     - check with distro on how to do this, otherwise run `apply` command from https://github.com/kubernetes-sigs/metrics-server
- Navigate to the node list
- Bring up dev tools
- Navigate to a node's detail page

**Result**
- View the `messages` sent over the cluster socket repeat the resource.start, resource.stop / resource.error, resource.start cycle

**Expected Result**
- We should not attempt to watch resources the user cannot watch

**Screenshots**
image

### PR DESCRIPTION
**Pull request by richard-cox**
### Summary
Fixes #10668

### Occurred changes and/or fixed issues
- some resources cannot be watched over web socket
  - examples metrics.k8s.io.podmetrics, metrics.k8s.io.nodemetrics, componentstatus
- change 1
  - when these are watched the BE now sends an error... which we ignore and try to watch again
  - change 1 is to handle the error so that we don't immediately try to re-watch
- change 2
  - avoid this scenario entirely though by not watching resources that do not have the `warch` verb
  - because of this change 1 can only be tested by changing code
- ~change 3~
  - ~in addition fixed two watch related issues highlighted when navigated / refreshing on list or detail page and navigating to detail or list page.~
    - ~Switching from a detail page with a watch on a specific resource to the list page where we watch all resources did not unwatch on the specific one~
    - ~Switching to a detail page of a resource that's already in the store should ensure we're watching it~
  - backed out, risky and not related to the bug. see description https://github.com/rancher/dashboard/pull/10669/commits/754e15b77c06a3e4d60aa9d4e3af8332e23a33bd

### Technical notes summary
- i've checked a fairly vanilla ds rke2 cluster and there's only about 8 out of 182 resources that cannot be watched
- these can be determined for the lack of `watch` verb in their schema

### Areas or cases that should be tested
- node detail page node resource graphs change correctly
- there's minimal messages in the clusters web socket

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: shell/plugins/dashboard-store/actions.js [hunk 1]
```diff
@@ -428,6 +428,25 @@ export default {
       out = getters.byId(type, id);
 
       if ( out ) {
+        if ( opt.watch !== false ) {
```
Comment (richard-cox) [inline shell/plugins/dashboard-store/actions.js:431]: do we do lots of find's on resources where we;re already watching

File: shell/plugins/steve/subscribe.js [hunk 2]
```diff
@@ -828,10 +837,11 @@ const defaultActions = {
       selector:  msg.selector
     };
 
+    // Are we switching between watches on the same type that only cover a subtype of them? If so unwatch the existing one
     state.started.filter((entry) => {
       if (
         entry.type === newWatch.type &&
-        entry.namespace !== newWatch.namespace
+        (entry.namespace !== newWatch.namespace || entry.id !== newWatch.id || entry.selector !== newWatch.selector)
```
Comment (richard-cox) [inline shell/plugins/steve/subscribe.js:844]: review with above comment & selector

**Review by nwmac — APPROVED** [review]
LGTM
