### PR TITLE
Extensions: Don't show version when installing

### LINKED ISSUE #7239: Incorrect version show when installing an extension
UI always shows the latest version - if you select another version, while installing, the latest version is always shown instead of the version that you selected.

### PR DESCRIPTION
**Pull request by nwmac**
Fixes #7239

A couple of updates:

- Don't show version number when installing - we don't know the version until install has completed
- Allow the user not to uninstall the plugin CRD

### CODE REVIEW

File: shell/pages/c/_cluster/uiplugins/RemoveUIPlugins.vue [hunk 1]
```diff
@@ -21,13 +22,23 @@ export default {
 
       this.defaultRepo = repos.find(r => r.name === UI_PLUGINS_REPO_NAME && r.spec.gitRepo === UI_PLUGINS_REPO_URL);
     }
+
+    if (this.$store.getters['management/schemaFor'](UI_PLUGIN)) {
+      const plugins = await this.$store.dispatch('management/findAll', { type: UI_PLUGIN });
+
+      // Are there any plugins installed?
+      this.hasPluginsInstalled = (plugins || {}).length > 0;
```
Comment (richard-cox) [inline shell/pages/c/_cluster/uiplugins/RemoveUIPlugins.vue:30]: {} ==> []

**Review by richard-cox — CHANGES_REQUESTED** [review]

**Review by richard-cox — APPROVED** [review]
