### PR TITLE
fix(LinkName): add node schema checking

### LINKED ISSUE #9445: User without permission to view resource page returns Cannot read properties of null
**Setup**
- Rancher version: v2.7.5
- Browser type & version: Chrome

**Describe the bug**

When the project member user accesses the host information on the pod list page，the explorer page wont load and returns `Cannot read properties of null (reading 'parentNameOverride')`

**To Reproduce**

Cluster in local or downstream cluster:
1. Create user user1 and set it as project member role.
2. Log in to user1 and create deployment, waiting for deployment Active.
3. navigate to the pod list, and click node name.

**Result**

The page wont load and returns a blank page with `Cannot read properties of null (reading 'parentNameOverride')`

**Expected Result**

Expected the page to load without errors

**Screenshots**

image

image

**Additional context**

Console Errors:

### PR DESCRIPTION
**Pull request by ly5156**
### Summary
Fixes #9445

1. If the user is not authorized to access the node, display plain text

### CODE REVIEW

File: shell/components/formatter/LinkName.vue [hunk 1]
```diff
@@ -41,15 +42,29 @@ export default {
       };
 
       return { name, params };
+    },
+
+    hasPermission() {
+      if (this.type === NODE_TYPE) {
```
Comment (richard-cox) [inline shell/components/formatter/LinkName.vue:48]: Think we can make this generic. In `shell/middleware/authenticated` there's an `invalidResource` function which is used to determine if a schema for a type exists

```
  // Note - don't use the current products store... because products can override stores for resources with `typeStoreMap`
  const inStore = store.getters['currentStore'](resource);
  // There's a chance we're in an extension's product who's store could be anything, so confirm schemaFor exists
  const schemaFor = store.getters[`${ inStore }/schemaFor`];

  // In order to check a resource is valid we need these
  if (!inStore || !schemaFor) {
    return false;
  }

  // Resource is valid if a schema exists for it (standard resource, spoofed resource) or it's a virtual resource
  const validResource = schemaFor(resource) || store.getters['type-map/isVirtual'](resource);

  if (validResource) {
    return false;
  }
```

That part can be made into a function, lets go with canViewResource in `shell/utils/auth.js`, and used there and in this file.

There are other checks we can do to determine if the resource is available (like if the schema collection and resource links provide a way for the user to fetch it) but just checking the schema is there is ok for now

**Review by richard-cox — CHANGES_REQUESTED** [review]

File: shell/components/formatter/LinkName.vue (hunk 1 above)
Comment (ly5156) [reply shell/components/formatter/LinkName.vue]: Thanks for the review, I've changed the code

**Review by richard-cox — DISMISSED** [review]
I've wired in the helper to the auth flow to handle missing resources there. @aalves08 can you give this a quick check?

Edit: I also rebased with master to get the latest e2e updates

File: shell/middleware/authenticated.js [hunk 2]
```diff
@@ -15,6 +15,7 @@ import dynamicPluginLoader from '@shell/pkg/dynamic-plugin-loader';
 import { AFTER_LOGIN_ROUTE, WORKSPACE } from '@shell/store/prefs';
 import { BACK_TO } from '@shell/config/local-storage';
 import { NAME as FLEET_NAME } from '@shell/config/product/fleet.js';
+import { canViewResource } from 'utils/auth';
```
Comment (aalves08) [inline shell/middleware/authenticated.js]: could you update this to `import { canViewResource } from '@shell/utils/auth';` so that we consistently call the alias `shell` on all imports?

**Review by aalves08 — APPROVED** [review]
I've seen you fixed the `@shell` import, so testing-wise and code-wise, lgtm!
