### PR TITLE
Fix removing array type values in machine pool configs

### LINKED ISSUE #10693: vSphere - Network, Tags and Parameters can be added but not removed
**Setup**
- Rancher version: 2.7-head, 2.8-head & 2.9-head

**Describe the bug**

When provisioning a vSphere cluster you can successfully add network, tags and parameters but you can't remove them afterwards.

**Screenshots**

https://github.com/rancher/dashboard/assets/135728925/d041cc7f-022f-4327-98e6-fda7cde2aff3

### PR DESCRIPTION
**Pull request by momesgin**
### Summary
Fixes #10693 

In `rke2.vue`, before saving the new changes made to the machine pools configuration we run `syncMachineConfigWithLatest` function, it gets the latest(last saved) config from the BE, then uses Lodash `merge` function to update it with the current changes made by the user. The problem is that if the user removes an item from an array type config value(e.g. network in vSphere), it will never work due to the default behaviour of Lodash `merge` function. Example:

```
const lastSavedConfigFromBE = { a: ["test"] };
const currentConfigByUser = { a: [] };

merge(lastSavedConfigFromBE, currentConfigByUser) // { a: ["test"] }
```

A new helper function `customMerge` is created to address the issue by correctly replacing the old array values with the new values during the merge process.

### Areas or cases that should be tested

This change is not limited to vSphere's machine pool config, any array type values for any provider's machine pool config will be affected. I haven't found any examples so far, but I believe the removing issue exists for any provider's array type value in their machine pool config, and this PR should fix them too.

### Areas which could experience regressions

Same as above.

### Screenshot/Video

https://github.com/rancher/dashboard/assets/135728925/35beeba1-5198-4010-8b02-3c1f9d3717f1

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

**Review by codyrancher — APPROVED** [review]
I have a feeling that we're going to want to change the functionality of `syncMachineConfigWithLatest` and just replace the metadata instead of merging.

With that said, let's see how this works in practice.

File: shell/utils/custom-merge.ts [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+ *
+ * const lastSavedConfigFromBE = { a: ["test"] };
+ * const currentConfigByUser = { a: [] };
+ * merge(lastSavedConfigFromBE, currentConfigByUser); // returns { a: ["test"] }; but we expect { a: [] };
+ *
+ * More info: https://github.com/lodash/lodash/issues/1313
+ *
+ * This helper function addresses the issue by always replacing the old array with the new array during the merge process.
+ */
+export function customMerge(obj1 = {}, obj2 = {}): Object {
```
Comment (richard-cox) [inline shell/utils/custom-merge.ts:19]: I'm not sure of the possible usages outside of shell/edit/provisioning.cattle.io.cluster, can this live there and be titled something like poolConfigMerge?

Otherwise it probably needs to be generic and go into `utils/obect`

File: shell/utils/custom-merge.ts [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+  return mergeWith(obj1, obj2, (obj1Value, obj2Value) => {
+    if (Array.isArray(obj1Value) && Array.isArray(obj2Value)) {
+      return obj2Value;
```
Comment (richard-cox) [inline shell/utils/custom-merge.ts:22]: This would lose any values in array 1, which i think is the blocker for it to be truly 
 generic merge

**Review by richard-cox — CHANGES_REQUESTED** [review]

File: shell/utils/custom-merge.ts (hunk 2 above)
Comment (momesgin) [reply shell/utils/custom-merge.ts:22]: How about making this specific to vSphere clusters only? my initial intention was to address potential issues across all providers, but based on your feedback and the fact that we don't have enough test coverage for all the scenarios yet, it might be better to restrict this helper function to vSphere clusters

Comment (richard-cox) [reply shell/utils/custom-merge.ts:22]: Sounds good! That would resolve both comments

**Review by richard-cox — APPROVED** [review]
I haven't validated by vsphere creds yet, but general edit of non-vsphere looks good. If you've validated the issue is resolved then lets get this in.

**Comment by momesgin** [comment]
> I haven't validated by vsphere creds yet, but general edit of non-vsphere looks good. If you've validated the issue is resolved then lets get this in.

I just tested it and it works as expected
