### PR TITLE
Remove custom chart steps feature

### LINKED ISSUE #11898: Vue3: Additional install/upgrade chart steps fail to load
**Setup**
- Rancher version: dev if 2.10

**Describe the bug**
- Charts that have built-in install experiences can contain conditional additional steps
- these are defined as vue components in `shell/chart/<chart name/steps`
- this is a process brought in with https://github.com/rancher/dashboard/pull/3101, however the actual steps have been removed (v1 monitoring no longer supported)
- whilst testing https://github.com/rancher/dashboard/issues/11773 found out the underlying process is broken 

> Note 1: **broken feature isn't currently being used**
> Note 2: I tagged this with vue3, but haven't confirmed working in vue2

**To Reproduce**
- Add the following to a new file at `shell/chart/monitoring/steps/my-step.vue`
  - ```
    <script>
    export default {
      label:      'generic.add',
      subtext:    'generic.back',
      weight:     100,
      components: {},
      data() {
        return {};
      },
      mounted() {
        this.$emit('update', {
          loading: false,
          ready:   true,
          hidden:  false,
        });
      },
    };
    </script>
    <template>
      <div>
        Hello World
      </div>
    </template>
    ```
- Run the dashboard
- Nav to Apps --> Charts --> Monitoring --> Install
 
**Result**

```
fetch.client.js:75 Error in fetch(): TypeError: customStep.component is not a function
    at Proxy.loadChartStep (install.vue:934:1)
    at install.vue:929:1
    at Array.map (<anonymous>)
    at Proxy.loadChartSteps (install.vue:929:1)
    at async Proxy.fetch (install.vue:269:1)
    at async Proxy.$_fetch (fetch.client.js:72:1)
```


**Expected Result**
- Additional step show in install chart wizard

**Additional context**
- see `shell/store/catalog.js `chartSteps`, `shell/pages/c/_cluster/apps/charts/install.vue` `loadChartSteps`

### PR DESCRIPTION
**Pull request by rak-phillip**
### Summary
This removes the ability to add custom steps while installing charts. 

Several issues with this feature were uncovered while reviewing #12010. Most notably, custom steps would fail to render if specific top-level variables (`label`, `subtext`) weren't defined. Since this feature does not appear to be in active use, we decided to remove it at this point.

Fixes #11898 

### Occurred changes and/or fixed issues

- Remove the ability to add custom chart steps
- Add `markRaw` to dynamically rendered component to prevent Vue from warning about adding reactivity to components that don't need it

### Areas or cases that should be tested

- Installing charts

### Areas which could experience regressions

- Installing charts

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: shell/pages/c/_cluster/apps/charts/install.vue [hunk 1]
```diff
@@ -922,33 +906,6 @@ export default {
       }
     },
 
-    async loadChartSteps() {
-      const component = this.version?.annotations?.[CATALOG_ANNOTATIONS.COMPONENT];
-
-      if ( component ) {
-        const steps = await this.$store.getters['catalog/chartSteps'](component);
```
Comment (rak-phillip) [inline shell/pages/c/_cluster/apps/charts/install.vue:929]: We can also consider removing `chartSteps()` from `shell/store/catalog.js`

**Review by mantis-toboggan-md — DISMISSED** [review]
LGTM

**Review by mantis-toboggan-md — APPROVED** [review]
