### PR TITLE
Fixed httpget options not showing up

### LINKED ISSUE #12383: Workloads: Creation: row of inputs not rendered for HttpGet
**Setup**
- Rancher version: 2.10
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**
Input fields not rendering for HttpGet hookoption component.

**To Reproduce**
1. go to workload creation page
2. under container tab, scroll down to Lifecycle Hooks
3. under 'PostStart' or 'PreStop', click 'Create HTTP request'

**Result**
Screenshot 2024-10-28 at 11 16 11 AM

**Expected Result**
Screenshot 2024-10-28 at 11 17 30 AM

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by eva-vashkevich**
### Summary
Fixes #12383 

Fixed httpget fileds not rendering when creating a workload.

### Occurred changes and/or fixed issues

Removed inner template tag since it looks like it was redundant.

### Technical notes summary

Inner template and its content was treated by Vue as an HTML template element as described in
https://vuejs.org/api/built-in-special-elements#template , so it wasn't rendered.

### Areas or cases that should be tested

Workloads -> Deployments -> General ->Lifecycle Hooks
For both PodStart and PodStop if "Create HTTP request" is selected, HttpGet configuration should be visible, editable and if saved, it should be respected. 
Same applies to editing existing configuration

### Areas which could experience regressions

Just workloads should be affected

### Screenshot/Video

Screenshot 2024-10-28 at 3 35 53 PM

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

File: shell/components/form/HookOption.vue [hunk 1]
```diff
@@ -150,35 +150,33 @@ export default {
...
-            :options="schemeOptions"
-            :mode="mode"
-          />
-        </template>
+        <LabeledInput
+          v-model:value="value.httpGet.host"
+          :label="t('workload.container.lifecycleHook.httpGet.host.label')"
+          :placeholder="t('workload.container.lifecycleHook.httpGet.host.placeholder')"
+          :mode="mode"
+        />
```
Comment (rak-phillip) [inline shell/components/form/HookOption.vue:158]: We discussed this OOB, but we may need to add `@update:value="update"` to each instance of `LabeledInput` that was previously wrapped by the template in order to avoid regressions. It needs to be confirmed if `update` was ever invoked when editing any of these instances of `LabeledInput` before doing so.

Comment (eva-vashkevich) [reply shell/components/form/HookOption.vue]: I don't think it makes a difference in this case, but I've added @update:value="update" for consistency.

**Comment by eva-vashkevich** [comment]
The second commit was needed to fix LifecycleHooks not listening to the value update, which caused the following bug:
if you select PostStart -> Create HTTP request, populate some values and then switch to "None", the resulting value is broken and leads to create error.

**Comment by nwmac** [comment]
@aalves08 Adding you as a reviewer if you have time before NA wakes up

**Review by rak-phillip — APPROVED** [review]
LGTM
