### PR TITLE
Fixing the autoscroll feature for container logs

### LINKED ISSUE #13545: Difficult to stop logs from scrolling
**Setup**
- Rancher version: v2.10.3

**Describe the bug**
- When viewing the logs of a chatty pod the user should be able to scroll up (either by mouse wheel or manually using scroll bar) to see earlier entries. The `Follow` button should then become enabled and any new log entries should not impact the visible log lines. If the user wants to see those and keep the new log lines visible they could scroll back to the bottom or press the Follow button
- However... this often does not work
  - scrolling up using mouse wheel often just returns the user to the bottom of the logs showing the new log lines
  - the same goes for scroll bar
- Sometimes this does work, i'm guessing it's a timing issue with when the log line comes in

**To Reproduce**
- Deploy a pod with a chatty log (there must be some good examples out there in docker hub)
- Worklods --> Pods --> View log

**Result**
- as per description

**Expected Result**
- as per description

**Additional context**
- Setting this as a high priority, as it's a large application developer use case

### PR DESCRIPTION
**Pull request by codyrancher**
### Summary
fixes #13545

### Occurred changes and/or fixed issues
- Scrolling or clicking in the log container stops following; Follow button resumes it
- Auto-scroll no longer fights user input
- Fixed `[Vue warn]: Invalid prop: type check failed for prop "height"` on ContainerLogs

### Technical notes summary

- **Recursive scroll loop**: `vue3-virtual-scroll-list`'s `scrollToBottom()` spawns a recursive 3ms `setTimeout` that never terminates while the user is scrolling away. Replaced with a one-shot `scrollToOffset(getScrollSize())`.
- **`isFollowing` state**: Moved from a debounced `@scroll` handler (100ms stale window) to `@wheel.passive`/`@mousedown` listeners on the native `logs-container` div. The VirtualList component doesn't forward native events so listeners had to go on the parent element.
- **Watcher performance**: No longer using a watcher to update the scroll position, we now just update the scroll position when we add more lines.
- **`height` prop**: Declared `required: Number` in `ContainerLogs` but never used — removed.

### Areas or cases that should be tested
- Open a chatty pod's logs — container should auto-scroll to bottom
- Scroll with mouse wheel — auto-scroll stop
- Click inside the log container — auto-scroll stops
- Click Follow — jumps to bottom, auto-scroll resumes
- Open multiple log windows and confirm scroll state is independent per window
- `[Vue warn]: Invalid prop: type check failed for prop "height"` no longer in the console.

### Areas which could experience regressions
- ContainerLogs.vue

### Notes
You can make a chatty pod with
```
apiVersion: v1
kind: Pod
metadata:
  name: log-generator
  namespace: default
  labels:
    app: log-generator
spec:
  containers:
    - name: log-generator
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - |
          i=0
          while true; do
            echo "$(date +%Y-%m-%dT%H:%M:%SZ) [INFO] Log entry $i - Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore."
            i=$((i+1))
            sleep 0.01
          done
  restartPolicy: Never
```

And a less chatty pod to help verify the edge cases:

```
apiVersion: v1
kind: Pod
metadata:
  name: log-generator-slow
  namespace: default
  labels:
    app: log-generator-slow
spec:
  containers:
    - name: log-generator-slow
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - |
          i=0; while true; do echo "$(date -u +%Y-%m-%dT%H:%M:%S.%3NZ) level=info msg=\"Log entry number $i from log-generator-slow pod. request_id=$(cat /proc/sys/kernel/random/uuid 2>/dev/null || echo $RANDOM) status=200 duration_ms=$((RANDOM % 500)) method=GET path=/api/v1/resource/$((RANDOM % 1000))\""; i=$((i + 1)); sleep 1; done
  restartPolicy: Never

```

### Screenshot/Video

https://github.com/user-attachments/assets/a22fa072-f203-4d28-841f-c78c3f1d6a3a

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes
- [x] The PR has been reviewed in terms of Accessibility
- [x] The PR has considered, and if applicable tested with, the three Global Roles `Admin`, `Standard User` and `User Base`

### CODE REVIEW

File: shell/components/Window/ContainerLogs.vue [hunk 1]
```diff
@@ -110,12 +109,6 @@ export default {
       required: true,
     },
 
-    // The height of the window
-    height: {
-      type:     Number,
-      required: true,
-    },
-
```
Comment (codyrancher) [inline shell/components/Window/ContainerLogs.vue:118]: This wasn't referenced in the code and was causing console warnings

File: shell/components/Window/ContainerLogs.vue [hunk 2]
```diff
@@ -290,18 +282,6 @@ export default {
...
-    lines: {
-      handler() {
-        if (this.isFollowing) {
-          this.$nextTick(() => {
-            this.follow();
-          });
-        }
-      },
-      deep: true
-    }
```
Comment (codyrancher) [inline shell/components/Window/ContainerLogs.vue:303]: We now just do the scrolling after we add lines instead of adding a watcher. It improved performance.

File: shell/components/Window/ContainerLogs.vue [hunk 3]
```diff
@@ -537,9 +515,8 @@ export default {
     follow() {
       const virtualList = this.$refs.virtualList;
 
-      if (virtualList) {
-        virtualList.scrollToBottom();
```
Comment (codyrancher) [inline shell/components/Window/ContainerLogs.vue:541]: scrollToBottom has an interval that can't be cancelled and just continuously scrolls once called.

File: shell/components/Window/ContainerLogs.vue [hunk 4]
```diff
@@ -607,7 +584,7 @@ export default {
             :aria-label="t('wm.containerLogs.follow')"
             :aria-disabled="isFollowing"
             :disabled="isFollowing"
-            @click="follow"
+            @click="startFollowing"
```
[the remark this answers is not in the document]
Comment (codyrancher) [reply shell/components/Window/ContainerLogs.vue:617]: Fixed, but added the follow to the startFollowing() method instead of inlining it.

File: shell/components/Window/ContainerLogs.vue [hunk 5]
```diff
@@ -451,22 +431,20 @@ export default {
...
+    stopFollowing() {
+      this.isFollowing = false;
+    },
 
-        this.isFollowing = distanceFromBottom <= this.scrollThreshold;
-      }
-    }, 100),
+    startFollowing() {
+      this.isFollowing = true;
+    },
```
[the remark this answers is not in the document]
Comment (codyrancher) [reply shell/components/Window/ContainerLogs.vue:477]: I ended up addressing this one too. I don't particularly like this UI interaction but since it was originally there and called for in the original issue I put it back in.

**Comment by momesgin** [comment]
not sure if this is caused by your last commit or I missed it in my original review, but using the scrollbar handle to scroll up doesn't stop following:

https://github.com/user-attachments/assets/2a308118-9b0c-49f8-90c3-00d068ab99da

**Review by momesgin — APPROVED** [review]
